### PR TITLE
Add Arabic language to frontend

### PR DESCRIPTION
**Pull request by KhaledEmad7**
## Proposed change

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks. As this is our first RTL lang in the UI I wasn’t sure if the UI would need other adjustments. Did you find it still legible, usable etc?

**Review by shamoon — APPROVED** [review]
Thank you for the PR. We'll merge this for now, there's been some issue with the arabic translation file Im trying to sort out but it does look like the UI is largely translated and if there are significant RTL issues we can iron them out.

**Comment by KhaledEmad7** [comment]
Yes, the UI is fine but there are still some missing changes needed to be done in the translation, I have made another PR for that hope it helps.

**Comment by KhaledEmad7** [comment]
The only change that can improve UX is making the front-end right aligned instead of left; however, the translation doesn't need any changes.

**Comment by tooomm** [comment]
@KhaledEmad7 Have a look at #2302 and give it a try. :)

**Pull request merged**
