### PR TITLE
Feature: Reduce classifier memory usage somewhat during training

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

A few slight changes to how the classifier training works.

- Document modification time + auto matching primary key hash is used to decide if the model should be retrained
- Content is pre-processed one document at a time instead of all held in memory
- Format number bumped
- Testing and a few tweaks to the testing

Testing against my own random document assortment, it is a decrease in usage of around 10MB of memory with around 700 documents.  With more documents or larger documents, this would likely see more savings.

At this point, memory allocation is almost fully within `.fit` or `.fit_transform` or imports.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by jonaswinkler** [comment]
I'll give this a spin on my instance this weekend

**Review by henrywintif — APPROVED** [review]
Looks good. In the future, its worth thinking about storing predictions distinctly from manually entered tags, and also storing negative tags when a user removes a tag so we can track false positives and negatives. That's out of scope for this PR though

**Comment by jonaswinkler** [comment]
Everything works as expected!

Except one thing, which was supported before.

* Don't change any documents, but instead set the matching algorithm of a tag/correspondent/type to auto that is already associated with documents.

Then the model won't be updated. (Should we care about this situation?)

If yes, the solution would be simple:

Store a set of IDs for storage paths, tags, types and correspondents with matching=auto in the model too and compare these when train() is called.

**Comment by stumpylog** [comment]
Storing a potentially large set of IDs into the pickle file doesn't seem like the best solution to me.  Those values would also need to be read out and stored in memory.  I'm actually leaning towards returning to the hashing, but only for the AUTO type ids.

The big change here is keeping the processed document contents for all documents out of memory.  The hashing shouldn't be very large.

**Comment by jonaswinkler** [comment]
Oh... I might have communicated this wrongly. You don't need to store the correspondent / tag / type ID for every document, just a *set* of correspondent / tag / type IDs that have AUTO as the matching algorithm, so that you'll notice when this set changes (AUTO enabled or disabled somewhere).

This works either way, so I'll leave it up to you to change or keep it.

**Review by jonaswinkler — APPROVED** [review]

**Pull request merged**
