### PR TITLE
Chore: Extend the live service utility for handling 503 errors

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

I'd written two of these utilities to handle HTTP errors when using Gotenberg/Tika in the CI test runs.  This combines them into a single place for usage.  It will probably fail right away, but it seemed to be more stable in my numerous re-runs.

The best change is probably the skipping if the calls all failed with HTTP 503 errors.  We don't really care if the server died in our tests.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain): - Code cleanup

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — APPROVED** [review]
Worth a shot! This is the last bugaboo in our ci but yea seems random and is rarely relevant.

**Comment by shamoon** [comment]
I dont get why this didnt work?

**Comment by stumpylog** [comment]
I do.  The errors are chained, so the actual raised error is a `ParseError` from an `httpx.xyzError`.  I'll need to do some tweaking

**Comment by stumpylog** [comment]
8 runs without a failure.  Naturally, it will fail immediately in `dev`.  In some hacked up testing, it does properly handle a ParseError from an HTTPStatusError and the status code

**Pull request merged**
