### PR TITLE
Bump Helm Chart version to trigger release

### PR DESCRIPTION
**Pull request by alexander-bauer**
## Proposed change

Bump the Helm Chart version to trigger a release.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain): Helm chart adjustment to force the initial release

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by alexander-bauer** [comment]
@shamoon  and @stumpylog since y'all were the reviewers on the initial PR #1947, would you mind taking a quick look at this to bump the chart version, and therefore trigger a release?

**Comment by shamoon** [comment]
Cool let's do it

**Comment by shamoon** [comment]
Except doesn’t it only run on `tag`?
😑

**Comment by alexander-bauer** [comment]
Shoot. It does. Doh.

I think what I'll need to do is adjust the action to run on any commit to the main branch, and then bump the version again. Another PR incoming 🤦

**Pull request merged**
