### PR TITLE
Bump the Helm Chart version (and fix CI, hopefully)

### PR DESCRIPTION
**Pull request by alexander-bauer**
## Proposed change

Bump the Helm Chart version to trigger a release. (Again.) See #2118 and #1947.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain): Helm chart adjustment to force the initial release

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by alexander-bauer** [comment]
@shamoon Here's the new attempt; I think this one will work. The first commit adjusts the CI action to run on every commit to the main branch, (which is a no-op for commits that do not alter the `Chart.yaml` version -- the docs for the action suggest to do it that way), and the second commit bumps the chart version.

**Review by shamoon — APPROVED** [review]
Ok yea, I would be good with this even though it runs on every push to main (i.e. not always a true release), since it does seem to make sure something has changed before packaging a new version.

But again I will defer to ci team before merging.

**Comment by tooomm** [comment]
Why don't we test this on a separate repo to understand how it works?

**Comment by shamoon** [comment]
Thats fine (the repo can easily be cloned to test) but I do think this will work, I just didnt want to alter the ci workflow without consulting others.

**Review by stumpylog — APPROVED** [review]

**Comment by alexander-bauer** [comment]
I'm working this on my fork, and having some unexpected trouble. I'm going to mark this a WIP until I figure things out.

**Comment by shamoon** [comment]
Any updates here? Thoughts I had:

- Somehow store before & restore after the index.yaml on documentation deploy
- Always run the chart-releaser action after doc deployment assuming releaser action doesnt overwrite the entire branch like mkdocs does (i guess somehow have to force releaser to re-publish that file)

**Comment by shamoon** [comment]
@alexander-bauer how's it going?

If we don't have a resolution here soon I'd like to propose reverting the previous PR.

**Comment by alexander-bauer** [comment]
Hi @shamoon, my apologies, it's been a busy season. I've actually been thinking about how to handle this alongside the mkdocs job, and I'm thinking that a separate Helm chart repository is probably the way to go. I'm still of the mind that in-repository charts are still ideal, but making the chart releaser and mkdocs behave together probably outweighs the potential difficulties of using a separate repository.

Along those lines, I think what we should do is this:
1. Close this PR, and revert the prior one.
2. Open a new repository with essentially just the contents of the original PR.

After that's up and working, we can open a new PR in this repository updating docs to reference the new chart location.

**Comment by shamoon** [comment]
Great, thanks!

**Pull request closed without merging**
