### PR TITLE
Feature: Implement custom fields for documents

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

With the combined work between us, this implements custom fields which can be attached to documents.  Only certain datatypes are supported, but it should fit most cases people could use it for.

Implements #141, one of the older requests.  Can also do #422 via URLs, #3112, #1917 and probably many others.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
What a mountain of work—enjoyed working on it with ya mate!

One thing you made me think of: the comment above made me realize something about the URL field: I think it should have a button to actually open the URL, that'd be a cool little feature and make it more useful, I think. I can get to that later.

**Comment by shamoon** [comment]
Ok, added that, updated translation strings.

In general this PR has a good chunk of UI changes I'm happy with in the end. Excited to have this feature in the release 👏

Screenshot 2023-11-04 at 8 18 35 PM
Screenshot 2023-11-04 at 8 14 35 PM
Screenshot 2023-11-04 at 8 14 50 PM

**Comment by stumpylog** [comment]
I need to look into why codecov hasn't commented.  Probably a setting to tweak from that one which stopped the extra runs.  The coverage for this branch looks good though.

**Comment by shamoon** [comment]
Yea probably that change, https://app.codecov.io/github/paperless-ngx/paperless-ngx/pull/4502

I can do a little better for the frontend tho 💪

**Review by shamoon — APPROVED** [review]
🚀

**Comment by stumpylog** [comment]
No reason I can think of to not merge this.  Looks good from the latest image.  The addition of the link clinking is great.

**Comment by nimodius** [comment]
A very wonderful feature, everyone are looking for to the new version of this software. Thank you @stumpylog !!

**Comment by w41ru5** [comment]
Thank you so much for your work here! I have been wanting this feature for some time and I really appreciate the time everyone put into making it happen.

**Comment by PN3UMA** [comment]
This isn't showing up for me yet. I'm on the latest (1.17.4). Am I missing something?

**Comment by shamoon** [comment]
Yes, you missed that it hasn't been released yet =) Theres a beta for 2.0 right now

**Comment by PN3UMA** [comment]
> Yes, you missed that it hasn't been released yet =) Theres a beta for 2.0 right now

How embarrassing. Well, I'll find the beta and check it out. Thank you.

**Comment by Instafails** [comment]
Would it be possible to display the additional fields in the document overview as well? So in the following overview: 
182-130-max


As an example of where I would find this function helpful: For invoices, you could create the invoice amount as an additional field and would see the invoice amount directly in the overview in the document search.

**Comment by shamoon** [comment]
Please make a FR. Commenting on a merged PR isnt the best way to raise something like that.

**Comment by ppacher** [comment]
It's so awesome this finally landed! I just upgraded to 2.0.0-beta-rc1 and was wondering if it's possible to search for custom fields using the /document?query= endpoint. I wasn't able to find something about it in api.md.
Is this supported?

**Comment by vincemue** [comment]
thanks, I just started with Paperless 3 days ago and didnt expect such a nice feature so soon.
Is it already possible to define which custom field to always show?

**Comment by andresledo** [comment]
I really liked this function, but I think it can be improved based on the functions of another document manager called Docuware. In this one it allows the following:

Assign that the field is always visible when a document type is selected. 
Allow to search for a document by the customized field. 
Show the document's custom fields in the document list. 
Fill automatically with machine learning, for example, in the case of an invoice from the same supplier, the total is always in the same position or with a literal "total" or similar. 
When having the cursor inside the custom field and selecting text inside the pdf viewer it is automatically copied to the field.

**Comment by epe** [comment]
> I really liked this function, but I think it can be improved based on the functions of another document manager called Docuware. In this one it allows the following:
> 
> Assign that the field is always visible when a document type is selected. Allow to search for a document by the customized field. Show the document's custom fields in the document list. Fill automatically with machine learning, for example, in the case of an invoice from the same supplier, the total is always in the same position or with a literal "total" or similar. When having the cursor inside the custom field and selecting text inside the pdf viewer it is automatically copied to the field.

I certainly agree on the Document type or tag. - in the custom fields there should be a setting of Tags/Document types where this custom field is automatically presented or maybe even make it required?

**Comment by willyp713** [comment]
> > I really liked this function, but I think it can be improved based on the functions of another document manager called Docuware. In this one it allows the following:
> > Assign that the field is always visible when a document type is selected. Allow to search for a document by the customized field. Show the document's custom fields in the document list. Fill automatically with machine learning, for example, in the case of an invoice from the same supplier, the total is always in the same position or with a literal "total" or similar. When having the cursor inside the custom field and selecting text inside the pdf viewer it is automatically copied to the field.
> 
> I certainly agree on the Document type or tag. - in the custom fields there should be a setting of Tags/Document types where this custom field is automatically presented or maybe even make it required?

Agreed. It's wonderful that I can add "Invoice Number" as a custom field, but it would be even better if it automatically attached to any "Invoice" document type!

**Comment by sparklesam** [comment]
Possible to use custom fields as filename placeholders in the future, I can see it would be very useful like for accounting purposes for custom field like invoice number or amount?

**Comment by JiroMusik** [comment]
I really love that custom fields, just what I needed and I would love to see that auto fill for these fields either by algorithmus or regex
Thumbs up for your work so far

**Pull request merged**
