### PR TITLE
Fix: ensure CSRF-Token on Index view

### LINKED ISSUE #4991: [BUG] No csrftoken cookie when authenticating with Remote-User headre
### Description

Hi,

I am using a setup of paperless where it is presented in an iframe on my custom platform to manage different home applications.  All applications accessible on the same host/domain. Paperless is accessed through a reverse proxy which sets the Remote-User header to a value extracted from a authenticated JWT.

However, I am not able to PUT any changes to the documents when authenticating like this, because the CSRF token is not set.

In the same setup, but without the Remote-User header, i.e. logging in the normal way, the `csrftoken` is available even in the iframe.

Are there any options to fix this?

### Steps to reproduce

Tried to reproduce it with a simple setup. 

### Webserver logs

```bash
[2023-12-15 21:43:42,309] [WARNING] [django.request] Forbidden: /api/hassio_ingress/sbI4PGZexNJ_Fl09iiQUQe5bPucj3EKVkkL-37oa34E/api/documents/228/
```

### Browser logs

```bash
{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":403,"statusText":"OK","url":"https://home.anpingen.de/api/hassio_ingress/sbI4PGZexNJ_Fl09iiQUQe5bPucj3EKVkkL-37oa34E/api/documents/228/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://home.anpingen.de/api/hassio_ingress/sbI4PGZexNJ_Fl09iiQUQe5bPucj3EKVkkL-37oa34E/api/documents/228/: 403 OK","error":{"detail":"CSRF Failed: CSRF cookie not set."}}
```

### Paperless-ngx version

2.1.2

### Host OS

Linux x86_64

### Installation method

Docker - official image

### Browser

Edge

### Configuration changes

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by baflo**
## Proposed change

Fixes an issue that does not set the CSRF-Token when using `PAPERLESS_ENABLE_HTTP_REMOTE_USER=true`.

The issue can be reproduced by just using the [Docker Compose instructions](https://docs.paperless-ngx.com/setup/#docker_hub) and setting `PAPERLESS_ENABLE_HTTP_REMOTE_USER=true` in `docker-compose.env`. After setup, use [ModHeader](https://chromewebstore.google.com/detail/empty-title/idgpnmonknjnojddfkpgkljpfnnfcklj?pli=1) to set the `REMOTE_USER` header to any username. Try to create anything or upload a document; you'll get an error that the CSRF token is missing.

> EDIT: This PR includes setup for local Docker testing, so you can easily reproduce the error.

By adding `ensure_csrf_token` to the route providing the frontend, the token is always set.

Closes #4992

## Type of change

- [x] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — CHANGES_REQUESTED** [review]
Ah, thanks for digging into it, apologies if I was wrong about the initial issue. It's odd to me no one has brought this up before since this all has been the case for literally years. Anyway, this makes sense looking at it and I dont imagine there are any big side-effects to the change.

Re: changes: this will fail lint (see the PR template) and please revert the changes to the compose files

**Comment by shamoon** [comment]
In other words, I still dont understand what is different about your setup that makes this relevant, many users (myself included) use `PAPERLESS_ENABLE_HTTP_REMOTE_USER` without issue (for years). I have to wonder if its your RP

**Comment by baflo** [comment]
No worries :)
I fixed the mentioned points

**Comment by shamoon** [comment]
Thank you. One last thing if you can rebase this on the latest dev branch to allow merge

**Comment by baflo** [comment]
Updated to latest dev

**Review by stumpylog — APPROVED** [review]

**Comment by stumpylog** [comment]
Looks like one other PR went into `dev`, so one more rebase would be great if you can.

**Comment by shamoon** [comment]
Should be ok, other commit was fully frontend. Thanks again

**Pull request merged**
