### PR TITLE
Fixes the Docker image tags

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

This pull request fixes the Docker metadata action for image tagging.  With these changes, the image tags look like:

```
  ghcr.io/stumpylog/paperless-ngx:1.6.3
  ghcr.io/stumpylog/paperless-ngx:ngx-1.6.3
  ghcr.io/stumpylog/paperless-ngx:latest
```

for a Git tag named `ngx-1.6.3` or `ghcr.io/paperless-ngx/paperless-ngx:feature-fix-docker-tags` for a branch created in this repo.

However, I'd like to get a feel for what people think about using semvar.  The action we user [directly supports semvar tags](https://github.com/docker/metadata-action#typesemver) for managing the final image tags.  I think if we wanted to change up how we create tags a little bit, this could be a benefit to the users.

For example, if we tag releases as either `v1.6.1` or `1.6.1`, the action can create a `1.6.1` tag, as well as an updated `1.6` tag.  That would allow a user to use either a specific version by using `:1.6.1` or a certain series set, getting any bugfixes with `:1.6`.  The action also manages `:latest`, so it would update from `1.6.1` to `1.7.0` if a user used that.

For betas, we'd need to include that in the tag name to be clear it is a beta.  So a branch `1.6.1-beta` is created, then tagged as `1.6.1-beta0`, `1.6.1-beta1`, etc as fixes are made to the branch.  These each get a new image tag created and pushed.  These could also be something like `1.6.1rc2`.

So this would remove the `ngx-` or `beta-` portion from tags both in Git and GHCR.  But it would allow us to defer some of the work of managing image tags to an action.  Maybe this was something already discussed, but with the change in how we create tags in the action, I thought I'd bring it up.

@paperless-ngx/ci-cd

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks for sorting this out, Im excited to get the new build process off the ground!

I agree using 'proper' server would be nice e.g. vX.X.X. We inherited the `ngx-X.X.X` from -ng and the last time I thought about this (I admit not very deeply) it seemed like a potential lot of work for little benefit, but that was before this new process. My only worry about is it will be tricky to make sure we catch it in all places eg. the docs, etc but I agree it would probably be good once it was done!

Just to clarify, this PR doesnt depend on that at all right? Cause it LGTM =)

**Review by shamoon — APPROVED** [review]

**Comment by stumpylog** [comment]
That's correct, this doesn't depend on semver at all.  Basically branches and tags are named how they are, while a branch/tag matching ngx-x.y.z will also make an image tag x.y.z

**Comment by shamoon** [comment]
Ok well lets merge this since it fixes the current process (hopefully) and then we can discuss the above further if theres interest.

**Comment by stumpylog** [comment]
I think this is going to break again, but this time, it's not our fault.  Looks like https://www.piwheels.org/ has gone down during the building.  Sigh.

**Comment by shamoon** [comment]
Lol. Well if it’s just re-running once it’s back that’s a pretty easy fix :)

https://downforeveryoneorjustme.com/piwheels.org

**Comment by shamoon** [comment]
awww snap! https://github.com/paperless-ngx/paperless-ngx/runs/5804226086?check_suite_focus=true
36 minutes 😎

👏👏👏

(I cant actually test at the moment)

@schnuffle

**Pull request merged**
