### PR TITLE
Chore: Initial refactor of consume task

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

This makes the consume_file task know much less about the inner working of things like barcodes and collation, by implementing a plugin like system, with a defined structure of calls and data flow between the task and things it calls.  This is just the initial work, the Consumer will be next, but so many things rely on the behavior of `try_consume_file` that made the diff way too large.

The benefits:

- Defined way to request the task exits, rather than needing to know what a return means
- Single connection for websocket data, which is always flushed and closed at the end
- One time creation of a temporary directory, which will be cleaned up
- Eventual easier integration of new features to consume, such as password removal or decryption (maybe even allow from the 

Despite my best efforts, git insisted files were deleted when they were just moved.

Closes #(issue or discussion)

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [x] Other. Please explain: Refactoring for new features

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — COMMENTED** [review]
Thanks for this stumpy, seems like a lot of work already but way more organized in the end.

In terms of a code review:
- As far as I can tell, not that much code has changed so not sure how much it needs? Im also just not the most able to comment python code-wise, as you know
- I can definitely give the image a spin but since all the tests pass Im not really expecting to find much

So yea, just not sure if youre looking for more than a "LGTM" since thats mostly what I'll be able to offer

**Comment by stumpylog** [comment]
Mostly yeah, any extra testing you can do.  The tests do pass, but I also updated them, so they would.  Hopefully it does make it a little bit cleaner in the end, and easier to add more modifiers to the consume flow in the end

**Review by shamoon — APPROVED** [review]
Thanks again stumpy, I tested a bit with a fresh install, asn, splitting, workflows and didnt have any issues. Again, no real comment on code changes here other than to say "LGTM"

**Comment by stumpylog** [comment]
I decided keeping the file history intact was important, so I did some squashing and fixing to allow tracking the change still

**Pull request merged**
