### PR TITLE
Feature: Allows filtering email by the TO value(s) as well

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

This change allows a user to add a filter for the TO value into an email rule.  I can see this being useful for shared inboxes where there may be many TO addresses routed to a single location.  The actual TO searching is handled by iamp_tools, as with the other searching.

I took a stab at the frontend portion.  No doubt poorly.

Fixes #950

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — APPROVED** [review]
Ha frontend looks great! (I did update the translation strings =)

Good feature in general, in trying to test this out a bit a couple things (not problems):

- At first I tried testing with my gmail using my regular email as the TO value and sending an email to mygmail+randomstring@domain.com (which google supports), interestingly this didn't filter out the messages as I would expect (logs below for reference). Wonder if the that is just a quirk of gmail (probably), not so surprising since emails are still going to the regular email of course
    - Using nouser@domain.com correctly ignores the emails and using my address does pick them up, so it clearly works. 
- Just checking, overall is this matching the entire TO of an email (in other words doe it have to be an email)? It looks like yes and if so perhaps we should validate the field? But wasn't sure

```
[2023-03-12 01:51:54,597] [DEBUG] [paperless_mail] Rule gmail.Gmail Rule: Selecting folder INBOX
[2023-03-12 01:51:54,693] [DEBUG] [paperless_mail] Rule gmail.Gmail Rule: Searching folder with criteria (SINCE 10-Feb-2023 SUBJECT "[paperless]" TO "user@domain.com")
[2023-03-12 01:51:55,658] [DEBUG] [paperless_mail] Rule gmail.Gmail Rule: Processing mail [paperless] Test 1 from email@domain.com with 1 attachment(s)
[2023-03-12 01:51:55,669] [INFO] [paperless_mail] Rule gmail.Gmail Rule: Consuming attachment 1-s2.0-S0002870310007295-main.pdf from mail [paperless] Test 1 from email@domain.com
[2023-03-12 01:51:55,684] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[fe0ffa9f-a97c-47b9-8182-01e2d8a390c4] received
[2023-03-12 01:51:55,811] [DEBUG] [paperless_mail] Rule gmail.Gmail Rule: Processing mail [paperless] Test 2 from from email@domain.com with 1 attachment(s)
[2023-03-12 01:51:55,815] [INFO] [paperless_mail] Rule gmail.Gmail Rule: Consuming attachment 1-s2.0-S0140673611603103-main.pdf from mail [paperless] Test 2 from from email@domain.com
```

**Comment by shamoon** [comment]
(sorry I created a merge conflict with the other one, fixed but needed to force-push)

**Comment by stumpylog** [comment]
- If something is stripping out the + portion, it must be somewhere in `imap_tools`.  I'm not sure what processing it may do.  I'll look, just to be sure, since that is a little unexpected to me as well
- The actual value ends up in an IMAP command called SEARCH.  Based on this [RFC section](https://www.rfc-editor.org/rfc/rfc3501#section-6.4.4) the TO is simply looking for the given string inside the message TO field.  So it doesn't need to be an email address that I can tell.

**Comment by shamoon** [comment]
> * The actual value ends up in an IMAP command called SEARCH.  Based on this [RFC section](https://www.rfc-editor.org/rfc/rfc3501#section-6.4.4) the TO is simply looking for the given string inside the message TO field.  So it doesn't need to be an email address that I can tell.

Oh cool, that's probably more useful, I think TO often contains a name too, right e.g. `John Doe <user@example.com>`? Makes it more useful for filtering 👍.

**Comment by stumpylog** [comment]
I couldn't reproduce the `+` disapparing.  With my own GMail account:
```
Searching folder with criteria (SINCE 20-Feb-2023 UNSEEN TO "me+fork@gmail.com")
```
So the + portion remained, which I would expect.

I also tested it out with searching via just name, and that also returned (a lot) of messages.  So no email requirement confirmed.

I did find a bug (thanks celery for making dates strings).  i'll fix it or let the pickle PR sort it.

**Comment by shamoon** [comment]
Sorry I didn’t explain clearly I used “email@domain.com” in my filter and sent the email to email+something@domain.com. I don’t think it’s a bug here, more that I would guess that gmail still treats this email like it’s addressed to email@domain.com so my filter still picked up the email (I thought it would filter it out)

In your example, above did it correctly find emails you sent to me+fork? Again just curious, don’t think it’s a bug here

**Comment by stumpylog** [comment]
Oh, gotcha.  Yeah, both filtering to by that email and by name have me results that made sense

**Pull request merged**
