### PR TITLE
Chore: Raise Gotenberg container version

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

Gotenberg released 7.10, which deprecated the two settings for choosing the PDF/A output.  For the moment, my client library sends the old option and the new option, which should result in an equivalent PDF/A output on either 7.9 or 7.10.  

Once v8 is out and seems well tested, we'll need to upgrade the library and version again.  Users will have to upgrade to v8 at that point, or else they won't actually get PDF/A (or maybe a crash)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — APPROVED** [review]
Oh man, glad you caught this, thanks. Basically another breaking change? This job is getting harder. Dont know what we'd do without you!

**Comment by stumpylog** [comment]
It's not a breaking change (yet), but it will be when Gotenberg v8 comes out.  At that point, the 2 old form fields will stop working.  Either that means an error or returning not PDF/A (I'm not sure which).  

When I update gotenberg-client for that, we'll have to figure out how to be really clear users need to be on v8.  But I plan to not do that until v8 is out for a while

**Comment by shamoon** [comment]
Yea, gotcha. Cool, is it worth / in our realm to add warning(s) now?

**Comment by stumpylog** [comment]
I did think about how to start adding some warning. But Gotenberg doesn't provide a route to get the version running.  So I could add a blanket warning of "if using Gotenberg, then warn to consider upgrading"

**Comment by shamoon** [comment]
I defer to you. I guess the other thing is people aren't going to upgrade unless they change their compose (in ours at least we specify a version) so none of those 'watchtower WTF' kinda moments.

**Comment by stumpylog** [comment]
I think I'll put something in the release page and edit the changelog to suggest updating to 7.10.  Then when v8 eventually, maybe mark it as notable and put in the warning

**Pull request merged**
