### PR TITLE
Enhancement: include current filename placeholder in workflows

### PR DESCRIPTION
**Pull request by Lu-Fi**
In some cases it is desirable that the title corresponds to the file name. If, for example, variables are used in the macro storage path, a new definition is not always possible. It should therefore be possible to use the current file name in a workflow.

Closes #(issue or discussion)

Add {filename} to the allowed possible variables in a workflow

- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by vamagnus** [comment]
This would close my FR [#8194](https://github.com/paperless-ngx/paperless-ngx/discussions/8194). Not directly but will do the job!

**Comment by shamoon** [comment]
Im not really sure it does close that FR, but I suppose you're the one who opened it. At best it indirectly does though, since I would guess most people dont actually want their title to have all the same restrictions as a file name (ya know, spaces, etc).

We do generally ask that outside PRs target a feature request discussion, but this is also a small change so Im fine with it as long as there are no objections from other maintainers.

**Comment by vamagnus** [comment]
Yeah, I guess what I meant to say was that it would meet my needs by indirectly doing the job, rather than closing the FR. This FR could still offer additional flexibility, so I’d expect it to remain open.

**Comment by Lu-Fi** [comment]
anything i have to do here ? Or still wait .....

**Review by shamoon — APPROVED** [review]

**Pull request merged**
