### PR TITLE
Elaborate on retagger for open documents

### PR DESCRIPTION
**Pull request by darkmattercoder**
## Proposed change

If the retagger changes tags, correspondents or doc types for documents which are currently being edited, the changes will appear in the document overview as if they had been applied.

However, in the actual editing view, they are only displayed as suggestions, as long as the document is not saved again.

The pull request clarifies that in the docs.

See the following two screenshots as a reference

overview

edit

Fixes # (issue)

## Type of change

- [X] Other (please explain): documentation

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [~] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [~] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [~] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
```
check docstring is first.............................(no files to check)Skipped
check json...........................................(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
check toml...........................................(no files to check)Skipped
check that executables have shebangs.................(no files to check)Skipped
fix end of files.........................................................Passed
mixed line ending........................................................Passed
trim trailing whitespace.................................................Passed
check for case conflicts.................................................Passed
detect private key.......................................................Passed
prettier.................................................................Passed
ruff.................................................(no files to check)Skipped
black................................................(no files to check)Skipped
Hadolint.............................................(no files to check)Skipped
beautysh.............................................(no files to check)Skipped
shellcheck...........................................(no files to check)Skipped
```
- [x] I have made corresponding changes to the documentation as needed.
- [~] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
This is not true, you need to close the document and reopen it.

**Comment by darkmattercoder** [comment]
well, shoultn't that then be mentioned? Does not hurt to have that in the docs. I am open to rewording. It took me three days to understand the behaviour. Which was frustrating. I think a note how open documents and the retagger interfer, cannot hurt, can it?

**Comment by shamoon** [comment]
Maybe? I suppose having worked on the project for a long time I dont have a good sense for what is or isnt apparent to new users, but that said I dont think anyone has ever mentioned this before so I dont really know how much of point of confusion it is. Mostly though, I dont think it's that common. There's also the fact that when this happens the "discard, save", etc buttons are active, which I think might tip off users.

But the bigger thing is that this is true for _any_ situation where a document gets edited outside of the browser window. I.e. if you have a document open and then open it in e.g. another browser and make a change the same thing happens. In other words, Im not sure if this one note really covers the behavior.

Im really not trying to be difficult or pedantic over a small change, just pointing out some things...

**Comment by shamoon** [comment]
There isnt a way for the command to know a doc is open unfortunately, and yea not sure that kinda thing would be worth it

**Pull request closed without merging**
