### PR TITLE
Enhancement: support disabling regular login

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Doesnt seem allauth provides any 'core' way to do this.

Screenshot 2024-02-18 at 9 37 53 PM

Closes #5813
https://github.com/paperless-ngx/paperless-ngx/pull/5190#issuecomment-1938433928

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by tribut** [comment]
This seems to just hide the login form, but not disable the ability to login using a non-sso username/password. In that case, the description should reflect that ("'regular' login can be hidden" instead of "... disabled").
Unless of course there is some django magic that disables login without the form present :)

**Comment by shamoon** [comment]
This PR doesnt alter the flow at all. It just removes the login form and thus the ability for a user to signin with built-in Paperless-ngx credentials.

Your question is a distinct change in my mind, though I see the use in it, this is much simpler.

**Comment by tribut** [comment]
> Oh hey!

Hey :)

> I think it functionally does disable it due to CSRF.

CSRF tokens only protect against cross-origin attacks. The attacker in this scenario isn't covered, because they can just use the token from the SSO form.

Try this:

- Using devtools, copy the HTML for the normal login form to a text editor
- Set `PAPERLESS_DISABLE_REGULAR_LOGIN=True`, reload the page
- Replace the `csrfmiddlewaretoken` in your editor with the one from the SSO-only login page
- Paste everything into the new page
- Login normally (works)

**Comment by shamoon** [comment]
I’m not sure what the above proves? A user who has access to creating a new html page on the server does not seem like the “target” user of disabling login. They could also just change the environment var too, so what?

**Comment by shamoon** [comment]
Oh I see you’re saying just in the browser. I guess I see your point, assuming this “attacker” both knows the form field names (that are no longer visible) and… has a valid login?

Still, is that really a problem?

**Comment by shamoon** [comment]
I've taken a look at https://github.com/pennersr/django-allauth/issues/345 and added a small change here. As far as I can tell, this is the "correct" way to do this, welcome any other thoughts about an alternative.

And if folks are not happy with this Im happy to close it, frankly the PR is not for my own needs.

**Comment by tribut** [comment]
Thanks for taking the time. Unfortunately, in my tests this does not disable the login, only signups.

I've taken the liberty and replaced it with code that apparently does. I'm not very familiar with allauth, but given that upstream [checks for malicious login attempts in `pre_authenticate`](https://github.com/pennersr/django-allauth/blob/079872ab5564fa73a73bbf36af990a29dea1ac3c/allauth/account/adapter.py#L658-L665) this seemed like a good fit and I've verified it as described in my previous comment. The error message is not shown to the user (because in `login.html` we only check for `form.error` and then show the generic username/password message), but the only user who would see that is an attacker anyway.

A bit of explanation of why I think this is important: I've seen many instances of SSO-enabled services with default or weak credentials. Someone sets up the app with a throwaway account, enables SSO and then "disables" the normal login. That's why I think we should clearly communicate whether we disable or merely hide the login.

Again, thank you!

**Review by tribut — APPROVED** [review]

**Comment by oeiber** [comment]
> This PR doesnt alter the flow at all. It just removes the login form and thus the ability for a user to signin with built-in Paperless-ngx credentials.
> 
> Your question is a distinct change in my mind, though I see the use in it. This is much simpler.

Please consider there's also a django login page (/admin/login), which should also be disabled.

**Comment by shamoon** [comment]
> Please consider there's also a django login page (/admin/login), which should also be disabled.

As noted, we wont be disabling that.

**Pull request merged**
