### PR TITLE
Add stale.yml

### PR DESCRIPTION
**Pull request by shamoon**

### CODE REVIEW

**Comment by yschroeder** [comment]
I would suggest to use a different label to mark stale issues. Wontfix sounds rouge and like we made a conscious decision. Maybe use stale as label instead?

Also I would like it to not close issues that we have acknowledged somehow. If someone reports a bug and we acknowledge it but can't manage to fix within 30 days, the bot should not handle it, right?

**Comment by shamoon** [comment]
I changed the label, fair enough. Commenting etc. prevents closure, also can add a label like 'pinned' (or we could add more)

**Review by qcasey — APPROVED** [review]

**Comment by shamoon** [comment]
Why is this requiring 2 reviews? From me =)

**Comment by qcasey** [comment]
I think the main branch had 2 reviews required, I'm not sure that's totally necessary.

**Pull request merged**
