### PR TITLE
Chore: change dark mode to use Bootstrap's color modes

### PR DESCRIPTION
**Pull request by lkster**
## Proposed change

I'm working on custom theme for paperless and needed to refactor this anyway so maybe it would be actually worth to add.

Currently paperless has it's own mechanism to set specific theme. Bootstrap 5.3 implemented color modes functionality which is then used for dark mode. Since paperless uses Bootstrap, it'd be good to actually utilize this functionality for dark mode.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain): refactor

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Can I ask what the real advantage is here, besides being more bootstrap-y? For the most part I see almost no difference except brighter borders (which I dont think we should change) and some visual bugs (see below), and its not like this reduces our codebase or anything (does it)?

Screenshot 2023-09-12 at 2 59 09 PM

And curious what you had in mind with a 'theme'?

**Comment by shamoon** [comment]
Edit: I fixed the couple small things I noticed. In general Im OK with this but yea, curious about what the perceived advantage is & you theme idea

**Comment by ThaFog** [comment]
With only this there's barely any advantage other than utilizing bs feature. However there should be after bigger theming refactor (eg. sticking more to bootstrap's variables) so I'd treat it as some step towards it. This is at least a starting point for me. As I said, I felt like it's good to PR this here as I've done this anyway. Next work I guess will be more related to refactoring and changing theme. 

About the theme itself - in general I try to unify look of every app I have on my personal homeserver wherever this is possible. My styling is also based on bootstrap which you can find here: https://bootstrap.lukester.app/ . So in the end the transition should be easier + if you like it in the end, I'd be happy to share it.

Btw. sorry for these borders, I was testing it on fresh instance

**Comment by shamoon** [comment]
Yea, so this also broke the 'live' application of toggling "use system settings". I've simplified things, I think we really only need 3 cases: "use system settings" = "auto" otherwise dark or light.

Let me know if you have any issues, Im ok to merge this (a lot of work to arrive back where things are currently =), if you have larger ideas about themeing please open a discussion or find us in the chat.

**Comment by ThaFog** [comment]
Huh sorry once again for that, I see it was indeed quick testing on my side. Anyway sure I can show you everything when I'm done so we'll be able to discuss the final direction if it turns out to be going into official repo

**Review by shamoon — APPROVED** [review]

**Pull request merged**
