### PR TITLE
Consumer: set `date added` from timestamp of source file

### PR DESCRIPTION
**Pull request by chrisblech**
see: https://github.com/paperless-ngx/paperless-ngx/discussions/3463

## Proposed change

When the new setting `PAPERLESS_CONSUMER_MTIME_AS_DATE_ADDED` is set to `true`,
consumer will set `date added` of new documents to the modification timestamp of the source file.

see: https://github.com/paperless-ngx/paperless-ngx/discussions/3463

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [X] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [X] If applicable, I have tested my code for new features & regressions.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [X] I have made corresponding changes to the documentation as needed.
- [X] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks, this would need testing to be added.

Only other thing is whether this is something other folks want or more of a one-off, I see you just opened the FR so nothing to glean from that yet. In general I see it as quite particular to your situation, which by the way could be done via post-consume script...

**Comment by shamoon** [comment]
Ah, sorry about that I may be wrong about doing that with a post-consume script but I still am concerned about the generalizability of this

**Comment by stumpylog** [comment]
I've got a couple of issues with the change:

- It introduces another configuration variable with what feels like a narrow use case
- The added field isn't really meant to be changed.  it's the date/time the document was added to paperless.  Setting the document's creation date (as #3466 helps fix) seems more correct

Using the API might be more correct anyway, given there is an existing script already.  I think it would be pretty easy to integrate there

**Comment by shamoon** [comment]
Thank you again, we'll close this for now but can always re-address if needed.

**Pull request closed without merging**
