### PR TITLE
Feature LDAP Auth

### PR DESCRIPTION
**Pull request by Timoms**

### CODE REVIEW

**Comment by Nicarim** [comment]
I'm not sure if paperless should be concerned in supporting different authorization methods. Providing support to trusting reverse proxy's headers (Proxy Auth) would provide plenty of support for different providers like

- https://github.com/greenpau/caddy-security/blob/main/README.md
- https://github.com/thomseddon/traefik-forward-auth

Which provides support to plenty of methods, and doesn't clutter the code for paperless. 
My point is that it's hard to test this feature as is and ensure it's quality, security and that it works when user models will be worked on. It's far easier to just offload it, and trust the external provider to provide this, and keep paperless as lean as possible in that field. Meaning we just support basic authorization method, autologin for fully trusted environment and trusting auth headers for every other auth (OAuth, OIDC, SAML, LDAP)

**Comment by yschroeder** [comment]
Adding this feature was/is heavily debated in our Matrix chat.

Some points I distilled from the chat:

Pros:
* Direct LDAP support is easier to set up (than a reverse proxy, see below)
* Allows to use advanced features like groups or mail addresses (later, currently paperless can't benefit)

Cons:
* Increased maintenance effort (test LDAP auth regularly)
* Already possible via a reverse proxy and `PAPERLESS_ENABLE_HTTP_REMOTE_USER` (if you can run both services on the same host)

**Comment by alexander-bauer** [comment]
I wonder if there's a place for something like OAuth2 integration rather than direct LDAP, to support "enterprise" solutions like some folks have at home, while minimizing the burden of authentication flow on us.

I think Django and Flask share an OAuth2 library implementation that doesn't require terribly much participation from the targeted app.

**Comment by mweimerskirch** [comment]
> * Direct LDAP support is easier to set up (than a reverse proxy, see below)

Maybe it would be possible to provide an alternative docker compose example that comes pre-configured with an authentication server (something like Authelia or Keycloak) and a reverse proxy (like Nginx). This way, it would be almost as easy to set up as with the "standard" authentication.

Additional benefits (depending on the authentication server that's used):

- Additional authentication methods (not just LDAP)
- Two factor authentication

Cons:

- Probably breaks app support.

I'm not completely opposed to integrating LDAP support directly though.

**Comment by alexander-bauer** [comment]
Oops, my last comment was on mobile and I didn't realize this was a complete pull request - I thought it was just a feature req; my mistake!

I had a brief peek through the code, and it looks good to me. It'd be great to add CI tests for it, though.

**Review by alexander-bauer — COMMENTED** [review]
Looks good to me, minus that I don't see any CI tests to ensure that LDAP auth actually works. I'd love at least another set of eyes, and ideally someone who can test.

**Review by alexander-bauer — APPROVED** [review]

**Comment by yschroeder** [comment]
I have the feeling that we should not introduce login methods overall, as we have a working solution via a reverse proxy. Instead, I'd like to focus on the actual document management not user management. Adding LDAP would result in the next person adding e.g. Oauth2 and sooner or later we end up with a login system that can also handle documents...

Instead all of them can use the reverse proxy route. It is even documented in the setup section how to set up a reverse proxy for this.

**Comment by yschroeder** [comment]
Apart from my previous comment I'd also really like to see CI tests for this.

But I think we have to fight feature creep...

**Comment by alexander-bauer** [comment]
That's a very good point @yschroeder. What does user management look like through a reverse proxy right now? Is everybody authenticated as `paperless` with the trusted rproxy, or does it create users automatically in the DB?

**Review by alexander-bauer — APPROVED** [review]
(Whitespace changes look good - still pending discussion about whether additional auth methods are wise.)

**Comment by yschroeder** [comment]
@alexander-bauer I don't know how it works exactly. The user name is passed via the `Remote-User` header from the proxy to paperless so I assume it creates a database entry for the user.

Maybe @Nicarim can enlighten us. He uses paperless with a reverse proxy AFAIK.

**Comment by yschroeder** [comment]
I looked through the django documentation and it seems that a user is created automatically.

https://docs.djangoproject.com/en/4.0/ref/contrib/auth/#django.contrib.auth.backends.RemoteUserBackend

**Comment by mweimerskirch** [comment]
> What does user management look like through a reverse proxy right now? Is everybody authenticated as `paperless` with the trusted rproxy, or does it create users automatically in the DB?

The proxy handles authentication AND authorization. In the case of LDAP for example, your user might authenticate, but you might not be in the right LDAP group, so you might not be authorized to access the resource behind the reverse proxy.

If both authentication and authorization passed, the reverse proxy forwards your request, but adds a "Remote-user" header that has the authenticated username as a value.

If the PAPERLESS_ENABLE_HTTP_REMOTE_USER is set, it will then trust this header and automatically create the user in the database. Using the administration interface in Paperless, you can then make additional changes, like set a firstname, lastname, etc. or set permissions (although Paperless currently doesn't really use them yet if I remember correctly).

**Comment by Nicarim** [comment]
I was able to setup LDAP authorization and authentication using `caddy-security` and `caddy` through `Remote-User` header.
Basically it just works once you figure out how to map the fields from LDAP onto the proxy, and from proxy to django. 

Here is the config (Caddyfile) I used to test this. It's obviously setup for development version of paperless, but for production it's even simpler since you don't have to match the rules like I did (just auth for authentication prompt, and single /* for the paperless traffic).
```
{
	http_port 8080
	https_port 8443
	debug

	order authenticate before respond

	security {
		authentication portal myportal {
			crypto default token lifetime 3600
			crypto key sign-verify "test"
			backends {
				ldap_backend {
					method ldap
					realm localhost
					servers {
						ldap://127.0.0.1:389 posix_groups
					}
					attributes {
						name cn
						surname sn
						username cn
						member_of memberOf
						email	mail
					}
					username "cn=admin,dc=example,dc=org"
					password "admin"
					search_base_dn "dc=example,dc=org"
					search_filter "(&(|(uid=%s)(cn=%s))(objectclass=person))"
					groups {
						"ou=groupper,dc=example,dc=org" admin
					}
				}
			}
		}
		authorization policy mypolicy {
      set auth url /auth/
      crypto key verify "test"
      inject header Remote-User from sub
      allow roles admin
    }
	}
}

localhost:8080 {
	route /auth/* {
		authenticate * with myportal
	}
	route /api* {
		authorize with mypolicy
		reverse_proxy http://localhost:8000
	}
	route /admin* {
		authorize with mypolicy
		reverse_proxy http://localhost:8000
	}
	route /static* {
		authorize with mypolicy
		reverse_proxy http://localhost:8000
	}
	route /accounts* {
		authorize with mypolicy
		reverse_proxy http://localhost:8000
	}
	route {
		authorize with mypolicy
		reverse_proxy http://localhost:4200
	}
}
```

**Comment by alexander-bauer** [comment]
Given the availability and relative ease of the authenticating proxy approach, I think I'm in favor of not adding LDAP logic to the Paperless core.

We should definitely make sure that an example authenticating proxy configuration is available in our docs, though.

**Comment by yschroeder** [comment]
> We should definitely make sure that an example authenticating proxy configuration is available in our docs, though.

Agree. Wee already have a section on configuring nginx:
https://paperless-ngx.readthedocs.io/en/latest/setup.html#using-nginx-as-a-reverse-proxy

Maybe it would fit nicely somewhere there.

**Comment by Timoms** [comment]
> Given the availability and relative ease of the authenticating proxy approach, I think I'm in favor of not adding LDAP logic to the Paperless core.
> 
> We should definitely make sure that an example authenticating proxy configuration is available in our docs, though.

Still not sure about that. 
We talked about maintenance - and thats a good point. But offloading the management part to the user (or maybe even company) will reduce the "easy to install" possibility imo. 

When looking at my network or the company one: We install an application and add direct ldap support. Its easy. See GitLab for example. We just dropped "apt install gitlab-ce" and configured the ldap connector and everything worked out of the box. No need of additional proxies with auth.  
I never worked with auth proxies because every popular application has direct ldap support.

One thing I could agree with is rewriting the code to support e.g. OID / oAuth providers. That way we could "remove" the direct ldap connector while still providing a direct user auth (even with usernames, firstname, lastname and other claims - which does not apply to the simple "remote user header").

What do you guys think?

**Comment by Timoms** [comment]
I am currently working on SAML2 as a replacement for LDAP - keep this PR up I'll link it later if the SAML PR is ready.

**Comment by dani** [comment]
The reason I've hacked the direct LDAP auth support is because I also use the paperless Android app, which auth directly against the API (and does not support http basic auth or any "fancy" auth method). So my reverse proxy protects paperless web interface through an SSO system (Lemonldap::NG actually), with an exception for /api and /fetch which are unprotected by the reverse proxy, so the mobile app can auth.

**Comment by aroberts** [comment]
@Timoms - any reason to drop this in favor of SAML? I don't currently run a SAML provider, but of course I have LDAP backing my environment. I have the same issue as @dani - I can get the web functionality I want using remote user headers from my reverse proxy, but I need some kind of solution for the API. I would prefer not to add a SAML dependency to my environment if possible.

**Comment by sevmonster** [comment]
> e.g., why SAML vs OIDC?

That's the problem with implementing a specific auth backend, there are multuple methods and they all have their benefits, camps of followers, and implementation details/headaches. I agree with everyone else that it is more beneficial to focus development time on making the core experience better and leave setting up SSO and other functionality to the tools that are designed to do it. If anything, a better user provisioning experience would be beneficial, e.g. to fill out more user details in the environment to carry over into Paperless, such as email.

I am currently using authentik + nginx and things work fine. The [authentik documentation for Paperless-ng](https://goauthentik.io/integrations/services/paperless-ng/) works for -ngx.

**Comment by aroberts** [comment]
> I agree with everyone else that it is more beneficial to focus development time on making the core experience better and leave setting up SSO and other functionality to the tools that are designed to do it. 

I’m with you here, right up until app-based SSO support is required to support major features (e.g., native clients that auth via the API). Reverse proxy is ALWAYS my first choice for auth, but it’s not always workable. In that case, I’m in favor of the app supporting the simplest external auth story possible to make the features (nearly always client apps) work, which is usually ldap. 

> I am currently using authentik + nginx and things work fine. 

To be clear, I have no objection to SAML support being added in general - I am not a maintainer, and will not bear any of the pain, but if this is my only path to client support, I’ll need to find a self hostable saml project, and then maintain that in my stack. 

Full transparency, I’ll be running the app itself behind a reverse proxy, and only using a “native” auth solution (i.e. ldap/saml/oidc) to make clients work. 

Meanwhile, what appears to be a fully functioning LDAP impl is sitting right here, and the only thing keeping me from using it is the knowledge that it’s not realistic for me to continuously backmerge the ongoing development into this branch, since I’m not connected to this code base in any way. 

I just reread your post and realized that you’re advocating for none of this merging- which is ok but then the clients need to support some kind of browser-login-based auth rather than auth via api.

**Comment by sevmonster** [comment]
> I am not a maintainer, and will not bear any of the pain

Same, just passing by and throwing my hat into the ring.

> I just reread your post and realized that you’re advocating for none of this merging- which is ok but then the clients need to support some kind of browser-login-based auth rather than auth via api.

No, I was talking specifically about more in-depth authentication methods like SAML, OAuth2, OIDC, CAS2, etc... This LDAP implementation does not appear have a lot of implementation or maintenance cost and augments the existing login method. Implementing even one of those alternative methods (not LDAP) without a third-party library would, I imagine, be a lot of technical debt and would require API and client changes to be any more useful than the current Remote-User setup. (And if security is an issue with the current system, have the reverse proxy provide a static header that the requesting client never sees, so that even if the client provides a Remote-User etc header, it won't do anything without that extra header.)

I have not done much with Paperless yet but it seems there are API keys with Tokens, is that correct? Wouldn't it be easier to expose that to the user (rather than have it be in the admin page) and have any API logins use that token instead? I may not be understanding how this works since I am new to the platform.

**Comment by shamoon** [comment]
Im not clear if this is being worked on any more, its been quite some time so Im closing to keep things tidy. If OP or anyone else is interested perhaps there should be more discussion. As noted, there's still a lot of debate about integrating this into the core.

**Comment by DoctorOgg** [comment]
it sure would be nice to have LDAP support, I look forward to it!

**Pull request closed without merging**
