### PR TITLE
Enhancement: Support image rotation

### PR DESCRIPTION
**Pull request by martintan**
## Proposed change

This PR updates the document actions "rotate" option, to be enabled for image types (jpg, png, gif, tiff, bmp, webp). I wanted to add this functionality as myself and others who use paperless have mentioned rotating images as a nice to have. There is also a [discussion](https://github.com/paperless-ngx/paperless-ngx/discussions/6309) about this functionality

image

rotated:

image

I tested the change by uploading all image types (jpg, png, gif, tiff, bmp, webp) and rotated each of them. I made additional changes to rotate logic according to some issues I found with specific image types:
- for tiff, I found that we need to pass `dpi` when saving image or else it will be saved with DPI of 1 and cause this error: [OCRmyPDF fails due to passing image_dpi of 1](https://github.com/paperless-ngx/paperless-ngx/issues/4636)
- sometimes, depending on the file, Pillow cannot detect the DPI (I observed this for one `sample.png`), so it must not be passed when saving. BMP, GIF, WEBP will never have DPI.

I've also updated tests for bulk edit to test rotating all image types, and test error when rotating a non PDF or non image.

Closes #(issue or discussion)
[Disable Rotating if document isnt a PDF](https://github.com/paperless-ngx/paperless-ngx/discussions/6309)

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
I cannot find an open FR with decent community support to allow rotation of images.  Is there one?

**Comment by martintan** [comment]
@stumpylog 

This [discussion](https://github.com/paperless-ngx/paperless-ngx/issues/59) about the original rotate feature has a lot of comments where some of them mention rotating images, with several upvotes (but it's from 2023)

> [vbMatthew](https://github.com/vbMatthew)
> [on Oct 3, 2023](https://github.com/paperless-ngx/paperless-ngx/discussions/396#discussioncomment-7176628)
> Simply having a feature to rotate the image and redo OCR for a single document would be great. I love this software, but the inability to rotate a document after it's been scanned really gets in the way of this being the perfect solution for our home document management.
> 
> I'm a software developer, though I work mostly in .NET. However, I'm willing to put some time in to adding a manual rotate feature if anyone wants to give me some pointers or a good place to start.

> [FunctionDJ](https://github.com/FunctionDJ)
> [on Feb 3, 2023](https://github.com/paperless-ngx/paperless-ngx/discussions/396#discussioncomment-4853535)
> Is there any current tool that allows cropping/rotating/merging of images into a PDF for free that also supports WebP for good compression? I have no idea if WebP can be embedded into PDF.

**Comment by stumpylog** [comment]
That's still not a voted on feature request.  I'll let the other maintainer chime in as well, but we ask feature PR to target feature requests with community support.  Implementing something just one or a few people want merely adds to the maintenance burden.

**Comment by shamoon** [comment]
I do have to agree here, it’s the same litmus test we apply to all (non-tiny) outside PRs. In fact, the lack of votes on that one would suggest there isn’t much interest, although that may be because of the title.

I hate to discourage a contribution but if you’d like to open a feature request and there really is support for this we’d of course be happy to readdress. In the meantime we’ll close this.

If you’re interested in other work you can always browse existing FRs. Thanks for your interest in the project.

**Pull request closed without merging**
