### PR TITLE
add default_group from ENV

### PR DESCRIPTION
**Pull request by IamTaoChen**
## Proposed change

Fixes # (issue)

## Type of change
When user login, it would try to get default_group from ENV(DEFAULT_GROUP, split by ','). Then if default_group exists, it will add user to these groups.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks for the PR.

Im not sure how I feel about this, can you explain the use case a little more? The group can be explicitly set on a user via the UI, so this seems redundant and also like it will get used only one time which makes a new ENV feel like overkill?

**Comment by TaoChan1005** [comment]
> Thanks for the PR.
> 
> Im not sure how I feel about this, can you explain the use case a little more? The group can be explicitly set on a user via the UI, so this seems redundant and also like it will get used only one time which makes a new ENV feel like overkill?

Beacuse I use SSO to sigup user. we want to have a 'everyone' group which can be easy to give them some permissions

**Comment by shamoon** [comment]
Ah, ok. Would you mind explaining a bit more what your setup is with SSO, etc?

**Comment by TaoChan1005** [comment]
> Ah, ok. Would you mind explaining a bit more what your setup is with SSO, etc?

I use CAS as my IDP, apache2(use cas auth) reverse proxy and set REMOTE_USER_USER to auth.

**Comment by shamoon** [comment]
Thanks. IIRC django does not provision new users (at the moment), so I’m still not sure I understand the true value of this. If you have to manually create new users you could just add them to the group then?

Welcome other thoughts if I’m missing something

**Comment by hendrik1120** [comment]
Django does create new users, they just aren't assigned to any group. Since the oidc pr has been stuck for months, this is the only workaround.

**Comment by shamoon** [comment]
> Django does create new users

Youre right =) I wrote the original RemoteUser backend class and I didnt remember that being the case, but its been a while! I also couldn't find a clear answer in the Django docs.

Yea so I can see how this is sort of a band-aid without the oidc feature, I would be OK with it in this case unless others have issues.

Besides fixing the linting this would also need test coverage, too. Thanks.

**Review by shamoon — CHANGES_REQUESTED** [review]
Please address linting and add test coverage, thanks

**Comment by shamoon** [comment]
Please reopen if/when you are able to address the above. Thanks for the PR

**Pull request closed without merging**
