### PR TITLE
[Beta] Paperless-ngx v1.7.0 Release Candidate 1

### PR DESCRIPTION
**Pull request by shamoon**
Hello everyone, and welcome to our latest `beta` release! :tada: 

With so many new features / bug fixes / languages / documentation updates since the last release, we felt it warranted beta testing. We have just pushed a [release candidate](https://github.com/paperless-ngx/paperless-ngx/releases/tag/ngx-1.7.0-rc1) for the upcoming 1.7.0 version. This is an all-call for beta testing. If you have the time, we would really appreciate your input.

@paperless-ngx/backend @paperless-ngx/frontend  @paperless-ngx/ci-cd @paperless-ngx/issues @paperless-ngx/test 

## Beta Testing

A new docker container has been built at `ghcr.io/paperless-ngx/paperless-ngx:beta`. A release zip can be found in the [github pre-release](https://github.com/paperless-ngx/paperless-ngx/releases/tag/ngx-1.7.0-rc1) or the [latest CI build](https://github.com/paperless-ngx/paperless-ngx/actions?query=branch%3Abeta).

Please test this beta as best you can and report any bugs by [opening a new issue here](https://github.com/paperless-ngx/paperless-ngx/issues/new?assignees=&labels=bug&milestone=v1.7.0&template=bug-report.yml&title=[BUG]+v1.7.0+RC1+Bug). See the [changelog](https://github.com/paperless-ngx/paperless-ngx/blob/beta/docs/changelog.rst) and [closed PRs](https://github.com/paperless-ngx/paperless-ngx/pulls?q=is%3Apr+milestone%3Av1.7.0+is%3Aclosed), especially ones labeled non-trival, to guide your tests.

Please remember to [make a backup](https://paperless-ngx.readthedocs.io/en/latest/administration.html#making-backups) if you will be running this over a production installation.

Once you have tested thoroughly for a few days and have not found any [more] issues please approve this PR. We generally aim for **about 5 tested approvals** before this is merged. This is not simply a code review, we prefer hands-on production experience with this beta. The beta will be open for at least 5 days.

Some additional notes:

* The `beta` container is updated as commits are made, see the [actions tab](https://github.com/paperless-ngx/paperless-ngx/actions?query=branch%3Abeta) for progress.
* If bugs are found release candidates will be pushed as necessary.

## Found Issues + Fixes So Far

- [x] #696, #698 --> #700, #704, #715
- [x] #703 --> #723
- [x] #707 --> #713
- [x] #708 --> #717
- [x] #730 --> #737
- [x] https://github.com/paperless-ngx/paperless-ngx/pull/717#issuecomment-1100758310 --> #745
- [x] https://github.com/paperless-ngx/paperless-ngx/issues/763 --> #765
- [x] #771 --> #772

# Thank you

If you're reading this, **thank you** for being a part of paperless-ngx! While we are proud to continue to publish new releases, we are even prouder of the collaborative process that makes it possible. Thanks to each and every person who has contributed so far 🙏

### CODE REVIEW

**Comment by shamoon** [comment]
Seems like bug reports (that are specific to 1.7.0-rc1) have died down. I havent noticed any show-stopping bugs so seems good to me.

If others have had a chance to test this version and are good with it please **approve** this PR. Thanks all!

**Review by stumpylog — DISMISSED** [review]
I threw all my documents at the beta image, no issues I noticed.  Lets go for it.

**Comment by shamoon** [comment]
Sorry merging that last css PR dismissed your review stumpy. Thanks!

**Review by stumpylog — APPROVED** [review]

**Review by qcasey — APPROVED** [review]
Yep, I've been running it for over a week without issue.

**Review by bauerj — APPROVED** [review]
Seems to work fine here!

**Comment by smseidl** [comment]
### Congrats to all
I wanted to drop a thank you to everyone who helped with getting 1.7 released!  This is a big step forward for this group (imo) to start adding significant features on top of the forked version of Paperless-NG.  I can't wait to see what 1.8 brings.

**Pull request merged**
