### PR TITLE
Chore: Upgrade channels to v4

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

With the release of [channels](https://github.com/django/channels) v4, the dependence on a whole server is now gone.  This PR upgrades to v4, with no apparent changes needed, and remove a bucket of dependencies that came in from daphne.

Note that daphne does still exist for develop, as the websocket testing relies on it

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain) - dependency management

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — APPROVED** [review]
Not sure if this is intentionally a draft but I didn't notice any issues in testing out the docker image. Thanks for sorting this out

**Comment by stumpylog** [comment]
Still working on it a little bit.  pipenv really wants to add some things back and I don't get why yet

**Comment by stumpylog** [comment]
Alright, it should be all good now.  I'll check it out again tomorrow, but at least earlier consuming all the test samples seemed all good

**Comment by shamoon** [comment]
Cool, yea pulling again works OK for me 👍

**Pull request merged**
