### PR TITLE
[Docs] Fix 2 small typos

### PR DESCRIPTION
**Pull request by tooomm**
## Proposed change

Fixing small typos in the documentation.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (typos in docs)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by qcasey — DISMISSED** [review]
Thank you!

**Comment by tooomm** [comment]
The `around a lot` part feels still a bit weird and unclear. But I'm not certain how the feature works exactly and which wording fits it best. 🙈

**Comment by qcasey** [comment]
We could probably remove `around a lot` if it only adds confusion. _Since this command moves your documents,_ is clearer and still accurate.

**Comment by tooomm** [comment]
>*Since this command moves your documents*, is clearer and still accurate.

Simple and on point, I like that 👍

**Review by qcasey — APPROVED** [review]
Thanks again :smiley:

**Review by shamoon — APPROVED** [review]

**Pull request merged**
