### PR TITLE
Chore: Includes OCRMyPdf logging into the log file

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

Closes #(issue or discussion)

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — APPROVED** [review]
Oh interesting thanks, got a sample? I wonder if this will help make it apparent to people where OCR happens...

(probably not)

**Comment by stumpylog** [comment]
It's already been included in the console, so `docker logs` for example.  It would look like this:
```
[2024-02-28 10:00:01,842] [INFO] [ocrmypdf._pipelines.ocr] Start processing 2 pages concurrently
[2024-02-28 10:00:01,844] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2024-02-28 10:00:01,845] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2024-02-28 10:00:01,860] [INFO] [ocrmypdf._pipelines.ocr] Postprocessing...
[2024-02-28 10:00:02,099] [ERROR] [ocrmypdf._exec.ghostscript] GPL Ghostscript 10.02.1 (2023-11-01)
Copyright (C) 2023 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Processing pages 1 through 2.
Page 1
Page 2

The following errors were encountered at least once while processing this file:
	stream inherited a resource

   
[2024-02-28 10:00:02,100] [ERROR] [ocrmypdf._exec.ghostscript]  This file had errors that were repaired or ignored.
   
[2024-02-28 10:00:02,100] [ERROR] [ocrmypdf._exec.ghostscript]  The file was produced by: 
   
[2024-02-28 10:00:02,101] [ERROR] [ocrmypdf._exec.ghostscript]  >>>> KUBRA Data Transfer Ltd. via ABCpdf <<<<
   
[2024-02-28 10:00:02,101] [ERROR] [ocrmypdf._exec.ghostscript]  Please notify the author of the software that produced this
   
[2024-02-28 10:00:02,101] [ERROR] [ocrmypdf._exec.ghostscript]  file that it does not conform to Adobe's published PDF
   
[2024-02-28 10:00:02,102] [ERROR] [ocrmypdf._exec.ghostscript]  specification.
```

The formatting isn't amazing, tends to just dump output from the subprocess I think

**Comment by shamoon** [comment]
Cool thanks, do you think it should be debug level? (or maybe Im misunderstanding that parameter)

**Comment by shamoon** [comment]
Oh yea I think im misunderstanding, as is it will only show if the user has DEBUG level (not the default INFO)? Thats what I meant

**Comment by stumpylog** [comment]
Ah, no that just controls the level which will be included in the file.  So anything at INFO or lower from ocrmypdf will be included in the file.  The log already includes DEBUG and lower from paperless

**Comment by shamoon** [comment]
Ah gotcha, thanks

**Pull request merged**
