### PR TITLE
Bugfix: Handle RTL languages better

### LINKED ISSUE #1163: [BUG] RTL Import is reversed
### Description

When importing an RTL (arabic) document, the content is reversed. 

I.e, if it is the following:
 إعادة اصدار لوحة المركبة
Paperless imports it as:
ﺔﺒﻛﺮﻤﻟﺍ ﺔﺣﻮﻟ ﺭﺍﺪﺻﺍ ﺓﺩﺎﻋﺇ

I believe this could potentially be related to the following issue from the original paperless-ng repo: https://github.com/jonaswinkler/paperless-ng/pull/627

### Steps to reproduce

1. Import an RTL (Arabic in my case) document
2. Check the content within Paperless
3. Will be reversed

### Webserver logs

_No response_

### Paperless-ngx version

1.7.1

### Host OS

Unraid 6.10.3

### Installation method

Docker

### Browser

_No response_

### Configuration changes

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

For a digitally born PDF, the text is extracted using `pdfminer.six`.  Unfortunately, they have a long open issue about supporting RTL languages.  Fortunately, Tesseract via OCRMyPDF handles RTL languages.

So, with this PR, if the detected language for text extracted via `pdfminer.six` is an RTL (or at least the common ones), the processing will force OCR of the document, which produces a sidecar file with the content, formatted correctly.

Original Document:
image
 1.9.1 Content:
image
This branch:
image

The OCR isn't amazing, but at least to me, it's pretty clear the ordering is fixed.

Fixes #1163

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
This is great! @OmarWazzan perhaps youre able / interested to test this out a bit?

**Comment by OmarWazzan** [comment]
Hi @shamoon!

Happy to help, unfortunately I’m on a work trip for another week or two. Can test it when I’m back

**Comment by OmarWazzan** [comment]
Hi @shamoon!

I'm back and able to test. What would be the best way to do so?

**Comment by stumpylog** [comment]
I created a sample `docker-compose.yml` here: https://gist.github.com/stumpylog/0b66002be64e87da3f3419525fac3ff8

It does assume just a Linux installation, not Portainer, Synology, etc.  It's a few steps, but if you're will to test it out, here's the steps I would do:

1. Drop that into a bare folder
2. create the folders `redis-data`, `data` and `media`.  
3. adjust `PAPERLESS_OCR_LANGUAGE` as well, I left those commented out, but there
4. start with `docker-compose up`
5. Once started, it will be available at port 8180, ie `http://localhost:8180`
6. Test it out with lots of RTL docs
7. When finished `Ctrl+C` to stop the containers
8. Feel free to remove them and the network

**Comment by shamoon** [comment]
@OmarWazzan any luck?

**Comment by shamoon** [comment]
@OmarWazzan any luck?

**Comment by OmarWazzan** [comment]
Hi @shamoon, unfortunately had a thing pop up and have not been able to get to it yet.

I run my instance on unraid LSIO container, so need to spin up a VM to get it running

**Comment by shamoon** [comment]
No worries thanks 🙏

**Review by shamoon — APPROVED** [review]
I see no harm in going for it with this. We will get more feedback after a release and shouldn't affect much else other than the relevant cases

**Pull request merged**
