### PR TITLE
Feature: Management command to redo OCR

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

This PR adds a new management command to allow users to redo OCR of documents, for example with a newer versions of packages or to try and fix a failed OCR.  It accepts a list of primary document keys (similar to the thumbnails command).  I've tested that it runs without issue and the content can be updated.

### TODO
 - [ ] unit testing of the command.
 - [ ] documentation

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by sukisoft** [comment]
Thanks for adding this!!

Since the redo-ocr feature is somewhat highly wanted, i was wondering, if it would be possible and could be done with a quick win, to add this to the gui. Somehting like a new group of buttons called "Actions" when selected 1-n documents. 

image

**Comment by shamoon** [comment]
> Since the redo-ocr feature is somewhat highly wanted, i was wondering, if it would be possible and could be done with a quick win, to add this to the gui. 

Ha, “quick”! Though not super complicated there is a bit more to it :), but I was planning to take care of that once I have some time.

nice work @stumpylog !

**Comment by shamoon** [comment]
@stumpylog take a look at those last commits, if youre 100% not happy with them feel free to squash them back to previous and remove them, otherwise please modify as you see fit of course. I extracted your redo logic to tasks.py and added it as a method to bulk edit and changed the UI a bit so now you can choose that option and it is distributed as an `async_task`. What do you think?

Screen Shot 2022-06-22 at 5 49 36 AM

**Comment by sukisoft** [comment]
Awesome. Pretty much exactly what i had in mind. Maybe this could be extended in the future to list more management commands. 

Code-wise i'm not the guy to judge this, but i'd hope it fits. I'd really love to see this in the next release.

**Review by bauerj — APPROVED** [review]
Wow, that's a great feature!

Code-wise I can only review the backend code but that looks excellent. Good job!

**Pull request merged**
