### PR TITLE
Feature: global search, keyboard shortcuts / hotkey support

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Been working on and playing with this for a while and I kinda love it. Welcome any feedback ofc.

This PR:

- Replaces the upper search (which is currently just like a shortcut to advanced search) with a **Global** search that searches all docs, tags, etc
    - Hybrid search: first searches by title (db, fast) but also adds in advanced search results (e.g. using the index) for docs if not enough results are found
        - Advanced search can be disabled
    - Moved the search suggestions to the advanced search field, where I think it shoulda been all along
- Adds hotkey shortcut keys for some things (its extremely easy to add more in the future with this)
    - `Shift ?` opens the help dialog

Video (all keyboard):

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/9481728c-1b10-47b2-9660-3fd82375376a

Screenshot 2024-04-19 at 10 38 56 AM
Screenshot 2024-04-19 at 10 43 48 AM

Obviously this is mostly frontend, as far as the backend part I looked into different ways to search across models and this actually seemed the best. Of course, welcome any thoughts on that part in parcticular

Closes #240 but mostly I just think its way better than the current thing

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by nimodius** [comment]
WOw I very much like the look of this, excited to try it. Thank you paperless team for all the amazing work!!

**Comment by shamoon** [comment]
One update here: I realized the current iteration could lose access to running an advanced search in the way the current thing does, so I've added an 'Advanced search &rarr;' button that shows if:

1. Advanced search is disabled (so no advanced search results are shown) OR
2. Advanced search is enabled and the number of documents returned is the limit i.e. theres a possibility for more results.

See screenshots.

Potentially more results (same if advanced search disabled):
Screenshot 2024-04-28 at 9 46 01 AM


Only 1 result and advanced already enabled (no button):
Screenshot 2024-04-28 at 10 10 11 AM

**Review by stumpylog — APPROVED** [review]
Hard to test all the changes, but what I managed to seems to be working

**Comment by reinob** [comment]
I just updated to 2.8.1 (THANKS!), and have noticed that in the global search the text is black and the background dark green. Like in the screenshots above, except that the text is black (see screenshot).

global_search

Is this configurable somewhere?
(I'm using Firefox 125.0.3, and have currently nothing else to test it with).

**Comment by shamoon** [comment]
#6602

**Comment by denilsonsa** [comment]
Problem: the `Ctrl + →` and `Ctrl + ←` hotkeys are taking over the built-in behavior when editing text inside a text box.

How to reproduce:

1. Search for documents, or open a view.
2. Edit one.
3. Focus on one of the many text fields.
4. Use `Ctrl + →` and `Ctrl + ←` to quickly move the cursor between words.

BUG: It doesn't work anymore, instead the document navigation shortcut is triggered.

I suggest picking a different shortcut, or disabling shortcuts when a text field is focused. (In fact, most other shortcuts are already disabled anyway.)

**Comment by shamoon** [comment]
Please dont comment on a merged PR, you can open discussion(s), thanks

**Pull request merged**
