### PR TITLE
Fix: ghostscript rendering error doesnt trigger frontend failure message

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

I think this is just cause it needs to raise a `ParseError`. Currently it just never completes. I made the message a bit more explicit. Could instead link to https://docs.paperless-ngx.com/troubleshooting/#consumption-fails-with-ghostscript-pdfa-rendering-failed but that's quite long =)

Screenshot 2023-08-31 at 12 40 40 AM

Currently just gets stuck:
Screenshot 2023-08-30 at 8 23 54 PM

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
In `try_consume_file`, we should probably catch and handle other non-`ParseError` and report status before cleaning up on those.

Around here:
https://github.com/paperless-ngx/paperless-ngx/blob/407a119b9a47b72a5d404809190dc94ef808b35d/src/documents/consumer.py#L452-L460

**Comment by shamoon** [comment]
Do you think it needs to be a separate catch or can we just catch everything in that one? I wasn't honestly really sure why it was limited to just `ParseError`

**Comment by stumpylog** [comment]
The only thing I can think of is that ParseError's come from us, so something we kind of know about, while anything else we just didn't handle it, so it's more unexpected.  But then I think there's some places inside parsers which catch just bare `Exception` anyway, so that doesn't really hold anymore.

So I think catching everything here seems alright

**Comment by shamoon** [comment]
Hopefully not over-complicating this but I separated them out, left the commits so easy to go back if you prefer the one exception, but like you said I was distinguishing between "expected-ish" (ParseError) and unexpected (everything else). And tried to include coverage.

**Comment by shamoon** [comment]
Sorry, confusing the relevant blocks

**Review by stumpylog — APPROVED** [review]
Nice, thanks for all the testing.  Completely missed just mocking out the original error, all I thought of was sample files.

**Pull request merged**
