### PR TITLE
Feature: Save pending tasks for frontend

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

`django-celery-results` doesn't create or update a model for pending tasks, which means they're also not visible for users in the frontend until execution actually begins.  But celery provides lots of [signals](https://docs.celeryq.dev/en/stable/userguide/signals.html).  So with this PR, the signals for before publishing, before execution and after execution are connected.  These updates disconnect us from `django-celery-results` instead updating `PaperlessTask` as needed.

image

I've tested this with multiple workers on sqlite, which _can_ lock up if enough task workers exist and the user tries to do UI changes to the db as well.  But that was 4+ workers and a few hundred documents.  With postgres, I never saw any sort of database locked errors.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
@shamoon I broke the frontend display of the name.  The equivalent in the model and hopefully the API response is `task_file_name`.

**Comment by stumpylog** [comment]
Curious, that migration error is probably from 1026 instead of 1027, since that's the only one touching a field named `created`.  Is your virtual environment up to date?  I find https://code.djangoproject.com/ticket/33899 which should be fixed at this point.

`WorkerLostError` looks more complicated indeed.  I haven't seen it in a build image.

**Comment by shamoon** [comment]
Yea it was 1026 which agreed, I thought we sorted out. Its ok, I'll keep an eye out for that one.

**Review by shamoon — APPROVED** [review]
Ha, funny we circled all the way back to signals, I agree this is better for the end-user with things feeling more immediate.

**Comment by shamoon** [comment]
Ps. just to confirm, I too wasn't seeing this with the Docker builds (even on macOS)
Screen Shot 2022-10-17 at 2 25 36 PM
Screen Shot 2022-10-17 at 2 26 29 PM

**Pull request merged**
