### PR TITLE
Align CI checks with pre-commit (mostly)

### PR DESCRIPTION
**Pull request by stumpylog**
This pull request re-works the Github Actions so we can double check at least some of the formatting and checks for both backend and frontend code, plus some checks against documentation for pushes and pull requests.

Best [viewed in the graph form](https://github.com/stumpylog/paperless-ngx/actions/runs/1978360726), the following checks now run:
* Backend Code Checks
  * reorder-python-imports
  * yesqa
  * add-trailing-comma
  * black
  * flake8
* Frontend Code Checks
  * prettier (over JS, TS and MD files)

Additionally, the dependencies were updated a bit between the jobs so backend things block backend, etc.

Finally, I was able to tweak, modify and add some configuration files so there less duplication between `.pre-commit-config.yaml`, `ci.yml`, `.prettierrc` and `setup.cfg` settings.  There's still some, but it's more configured in a single location now.

### CODE REVIEW

**Comment by shamoon** [comment]
Awesome! Frontend part looks fine to me, appreciate that you kept our prettier settings. I will let @paperless-ngx/ci-cd  review.

Thanks as always for all the work @stumpylog

**Comment by stumpylog** [comment]
Oh, I should mention the testing of this.

Please ignore the terrible spelling in the [frontend check test](https://github.com/stumpylog/paperless-ngx/runs/5530560614?check_suite_focus=true) and the [backend check test](https://github.com/stumpylog/paperless-ngx/runs/5530040777?check_suite_focus=true)

**Comment by shamoon** [comment]
> Oh, I should mention the testing of this.

I wonder if it’s an inconsistency between pre-commit and this somehow, one would hope not but I don’t think those md/ts files have actually changed since the #276  . I can take a look

**Comment by stumpylog** [comment]
Sorry, that wasn't clear.  I'm still working on Monday's coffee.  I broke a file or 2 deliberately in each area so I could see if the check caught it and what the output looked like.

**Comment by shamoon** [comment]
> Sorry, that wasn't clear. I'm still working on Monday's coffee. I broke a file or 2 deliberately in each area so I could see if the check caught it and what the output looked like.

Aha, now I get it. Then cool, it works :)

**Review by qcasey — APPROVED** [review]
This is really well done, thank you!

**Comment by qcasey** [comment]
Could someone please run prettier on `dev` real quick:

https://github.com/paperless-ngx/paperless-ngx/runs/5599339302?check_suite_focus=true

**Comment by shamoon** [comment]
> Could someone please run prettier on `dev` real quick:
> 
> https://github.com/paperless-ngx/paperless-ngx/runs/5599339302?check_suite_focus=true

I will take care of this later today

**Comment by stumpylog** [comment]
Thanks @shamoon.  I'm just on a phone for a days.

**Comment by shamoon** [comment]
All set in https://github.com/paperless-ngx/paperless-ngx/commit/ff4538612ed3e042b5e1b194ac33ecb87a7c2129

**Pull request merged**
