### PR TITLE
Fix: missing tooltip translation & filter editor wrapping

### LINKED ISSUE #1299: [BUG] Input field too small
### Description

With 1.8.0 (great work btw.!) the input field for "title & content" is way too small, see:

Bildschirmfoto 2022-07-29 um 12 06 36

Or can I just hide the storage path button? I don't need this.

### Steps to reproduce

Upgrade from 1.7 to 1.8.

### Webserver logs

_No response_

### Paperless-ngx version

1.8.0

### Host OS

gentoo x86_64

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

_No response_

### Other

_No response_

### LINKED ISSUE #1300: Missing translation
### Description

The translation string is missing for the **hover title** in the lower left corner when hovering over "Suggest an idea".

For e.g. when you switch to German it looks like this:
Unbenannt

The title gets set in line 192 at the end `title="Suggest an idea"`
https://github.com/paperless-ngx/paperless-ngx/blob/main/src-ui/src/app/components/app-frame/app-frame.component.html#L192

Please add the possibility to translate this string too.
Thank you :)

### Steps to reproduce

Hover over the "Suggest an idea" button in the lower left corner on the paperless website

### Webserver logs

_No response_

### Paperless-ngx version

1.8.0

### Host OS

Ubuntu

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

This small PR addresses two (unrelated) issues reported in 1.8.0, the first a missing translation string and the second the fact that the filter editor text field can become too short on certain screen sizes. Regarding the second issue, fix was to increase the breakpoint at which everything goes to one line from 1200 --> 1400 px (e.g. at user's screen size things will now be on two lines). Screenshot below is new minimum width to illustrate, its still small but acceptable I think.

Screen Shot 2022-07-29 at 2 42 02 PM

Fixes #1299
Fixes #1300

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] ~~I have made corresponding changes to the documentation as needed.~~
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by tooomm** [comment]
Looking at your screenshot, it's still small indeed. Probably even smaller for other languages...

On mobile, it switches to icon-only filter buttons at one point. Maybe that's a reasonable solution for smaller desktop/laptop/tablet screens as well?

**Comment by qcasey** [comment]
> Looking at your screenshot, it's still small indeed. Probably even smaller for other languages...

This is true, unfortunately this PR doesn't fix for other languages (try German). The longer titles of the other items push the field small once again.

localhost_8000_settings

**Comment by shamoon** [comment]
Hmm, actually should be OK in German, that’s where I tested it. But I will double-check.

We discussed this a bit in the original Storage paths PR, it was always going to be a trade-off. The “fix” (barring a more sig UI change is just pushing the limit at which we keep things on two lines (eg currently 1200, PR goes to 1400, could go further…) but yea, it’s a compromise.

But I will double-check this a bit later

**Comment by shamoon** [comment]
Yea I think this is the best compromise, thanks. Here's a screenshot around 1450px on German and English with newest changes:

Screen Shot 2022-07-31 at 8 23 24 PM
Screen Shot 2022-07-31 at 8 25 54 PM

**Review by qcasey — APPROVED** [review]
Awesome, thanks for the fix

**Pull request merged**
