### PR TITLE
Fix: limit asn integer size

### LINKED ISSUE #2496: [BUG] Archive serial number is parsed as int during index creation causing overflow issues
### Description

I have a document where I put 9364061719 as archive serial number field and everything saved properly. Recently I was trying to update my paperless-ngx to a newer version but updating search index failed with:

ValueError: Numeric field value 9364061719 out of range [-2147483648, 2147483647]

This also happens if I just run "document_index rebuild" on the same build (1.8.0) but I can also reproduce it in "latest".

### Steps to reproduce

1. Create a document
2. Set archive serial number to a large number like 9364061719 
3. Run document_index rebuild script or try to upgrade.

### Webserver logs

```bash
Traceback (most recent call last):
  File "/app/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/app/paperless/src/documents/management/commands/document_index.py", line 23, in handle
    index_reindex(progress_bar_disable=options["no_progress_bar"])
  File "/app/paperless/src/documents/tasks.py", line 48, in index_reindex
    index.update_document(writer, document)
  File "/app/paperless/src/documents/index.py", line 93, in update_document
    writer.update_document(
  File "/usr/local/lib/python3.8/dist-packages/whoosh/writing.py", line 1024, in update_document
    self._record("update_document", args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/whoosh/writing.py", line 1001, in _record
    getattr(self.writer, method)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/whoosh/writing.py", line 490, in update_document
    self.add_document(**fields)
  File "/usr/local/lib/python3.8/dist-packages/whoosh/writing.py", line 750, in add_document
    for tbytes, freq, weight, vbytes in items:
  File "/usr/local/lib/python3.8/dist-packages/whoosh/fields.py", line 669, in index
    yield (self.to_bytes(num, shift), 1, 1.0, emptybytes)
  File "/usr/local/lib/python3.8/dist-packages/whoosh/fields.py", line 722, in to_bytes
    x = self.prepare_number(x)
  File "/usr/local/lib/python3.8/dist-packages/whoosh/fields.py", line 691, in prepare_number
    raise ValueError("Numeric field value %s out of range [%s, %s]"
ValueError: Numeric field value 9364061719 out of range [-2147483648, 2147483647]
```

### Browser logs

_No response_

### Paperless-ngx version

1.8.0 (but also occurs on latest)

### Host OS

Docker container (not sure)

### Installation method

Docker - official image

### Browser

_No response_

### Configuration changes

I am using Sqlite option due to having started with linuxserver.io images.

### Other

_No response_

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Figured I would also make it > 0. Again I feel like this shouldnt be needed according to Django docs https://docs.djangoproject.com/en/4.1/ref/models/fields#django.db.models.IntegerField but...

Fixes #2496

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- x ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] ~~I have made corresponding changes to the documentation as needed.~~
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
I think a PositiveIntegerField[¶](https://docs.djangoproject.com/en/4.1/ref/models/fields/#positiveintegerfield) would accomplish the same thing, right?

**Comment by shamoon** [comment]
Ha yea I thought about it but figured we’d still need the max validator so seemed ok to leave as this, but I can test to see

**Comment by shamoon** [comment]
Oddly enough if I try a PositiveIntegerField it makes no difference, still needs the max validator and even seems to need min (i.e. it still accepts < 0), but still for correctness sake Im happy to use it. LMK if you find differently, of course!

**Comment by shamoon** [comment]
Uh oh, I dont like rabbit holes. Yea I was just testing via API /documents/ID/
```
{
    "archive_serial_number": [
        "Ensure this value is less than or equal to 2147483647."
    ]
}
```

**Comment by stumpylog** [comment]
Yeah, I'd assumed this would end up as database level checks against the value of the field, which would have prevented me from creating a Document via the command line with an invalid value.  

At least it sounds like DRF validates against the model field.  I'll add a tweak to #2437 to validate the located barcode value, as that will be the only other source for an ASN

**Comment by stumpylog** [comment]
And as I keep digging into docs, the rabbit hole gets deeper.  But I think a true solution here is to limit the ASN value as a uint32.  So a range from 0 to 4,294,967,295, which had better be enough for anyone, hah!  It would need these changes:

- The validator would change to 0xFF_FF_FF_FF (I like the hex, it's obvious it's a 32 bit that way)
- An ASN from a barcode needs to check against this limit manually, as the DB schema doesn't protect against it
- the Whoosh schema for the ASN is a [NUMERIC](https://whoosh.readthedocs.io/en/latest/api/fields.html#whoosh.fields.NUMERIC). which should have the `signed` parameter set False.

Still not enough to support 9364061719, but I don't think going to a uint64 is truly necessary and might have implications in the performance of the index.

**Review by stumpylog — APPROVED** [review]
I pulled in the ASN from barcode from `dev` and fixed that range check + added a test case for covering it.

**Pull request merged**
