### PR TITLE
Add "Created" as additional (optional) parameter for post_documents 

### PR DESCRIPTION
**Pull request by eingemaischt**
## Proposed change

I need to import my ecodms-database and I spend much effort on manually tagging all the "created" dates on the documents. But now, while migrating to paperless with a self written import client, I had no option to migrate the "create" date as well.

So I added the possibility...

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [X] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [X] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

Some needed Checklist-Boxes are unchecked. My change is very minimal and I tested it with a docker-compose instance manually for my import. Would someone from the dev team do the tests and have a second look over the changes?

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks for re-basing.

Seems like a reasonable change. A general q: are we updating the API version for something like this? Its not a breaking change, so is it like a v2.1 ? Added to changelog?

**Comment by stumpylog** [comment]
I don't think APIs normally have point versions?  Since this is optional, probably just having it in the changelog is enough?

@eingemaischt Can you fix up the styling and add test coverage?

**Comment by eingemaischt** [comment]
> @eingemaischt Can you fix up the styling and add test coverage?

I reformatted the code using black - but I can't do unit tests or test coverage because I don't set up a dev environment. I changed the code and built it with docker-compose build ...

**Comment by stumpylog** [comment]
I think you need to add `required=False` to the new field to fix existing tests.

**Comment by shamoon** [comment]
> I think you need to add `required=False` to the new field to fix existing tests.

Yep, `allow_null` != `required` (that took me a second yesterday too =)

**Review by stumpylog — APPROVED** [review]
Ok, I added a quick test for posting a creation date, seems ok to me

**Pull request merged**
