### PR TITLE
Adding Dev container support for VSCode

### PR DESCRIPTION
**Pull request by Eckii24**
## Proposed change

The editor VSCode provides a way, to develop fully inside docker containers.
This feature is called "dev-containers" --> https://code.visualstudio.com/docs/remote/containers

This PR adds basic support for setting up a docker image and a setup script to configure a dev environment on the fly.
When the repository is then checked out with the vscode extension, it will automatically install all dependencies and sets up an redis service.

------

I don't know, if this is a feature you want to have checked in into the  repository.
If this information is relevant and will be merged in the future, I will add further documentation how to use it and fix the broken pipeline.

If this information will not be merged (e.g. because is only relevant for vscode) please close this PR.
 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

## Todos if this PR is relevant
- [ ] Add documentation
- [ ] Fix pipeline
- [ ] Use a docker-compose.override.yaml file
- [ ] Integrate the python and javascript dependencies into the image

### CODE REVIEW

**Comment by shamoon** [comment]
Thank you for this. I do use VS Code but frankly I've kinda got a working setup and dev containers in vscode isnt something Im very familiar with and so I dont have a lot of reason to migrate. I will say it was pretty easy to get working.

With anything that gets added to the core repository theres always the issue of maintenance and so if its not being used actively by at least a few people its debatable whether its a good idea to include it. 

I would love to hear from other folks if they do use / want to use this and if so of course we can integrate it. If not, we can consider creating its own repo or something like linking from the documentation to the config files to at least share with others.

Regardless, thanks again for contributing.

**Comment by stumpylog** [comment]
I can see this being useful.  From what I understand, it would be a lower bar to new contributors getting setup, while also allowing a development system to be more isolated (ie, I don't really need qpdf, etc installed on my computer).  I'm not sure it would require much, if any maintenance unless a new system dependency or image update is needed.

**Comment by qcasey** [comment]
I also think it's a valid usecase. Not sure if it's entirely related, but I wanted to link #210

**Comment by Eckii24** [comment]
> @Eckii24 et al. so we think this is ready to go? It did work for me in testing.

I have mentioned some open points in the description above. So if we decide we will merge this PR I will continue to work on this open points.

**Comment by stumpylog** [comment]
It looks like we're alright to include this, so when you have time to work on the open points, we can get this reviewed and merged.

**Comment by shamoon** [comment]
This sounds like a good idea but its been a while without any movement here. @Eckii24 if youre interested in completing this please do re-open, Im just closing to keep things tidy.

**Pull request closed without merging**
