### PR TITLE
Chore: Reduces webserver and task worker count to 1 by default

### LINKED ISSUE #1098: Reduce PAPERLESS_TASK_WORKERS and  PAPERLESS_WEBSERVER_WORKERS default values
### Description

# Problem with memory and CPU usage
In connection with #1084, reducing the `PAPERLESS_TASK_WORKERS` and  `PAPERLESS_WEBSERVER_WORKERS` default values to `1` helps not only with reducing the memory footprint (from approx. 400mb to approx. 200mb) but because the Django-Q's internals, the CPU usage goes downs as well (each worker checks in every second, which creates a Redis hit; the more workers, the more check-ins, the more Redis hits, the higher the idle CPU usage).

# Typical paperless use-case
I argue paperless is mostly used by hobbyists to store simple invoices, notes, etc. However, by and large, the instance is idling rather than running multicore, CPU heavy processes (see typical use-cases on [/r/selfhosted](https://www.reddit.com/r/selfhosted/search/?q=paperless))

# Change the defaults to match the typical use-case
If the instance is mostly idling and every once in a while processing a new document, it is more reasonable than not to limit the default number of workers to `1`. This is still configurable via env variables, so if anyone ever needs more workers, they can change it, but most users, simply starting the docker container, would benefit from the reduced memory and CPU usage.

Any thoughts, objections?

@stumpylog , I'm happy to create a PR to change the defaults and update the [documentation](https://paperless-ngx.readthedocs.io/en/latest/setup.html?highlight=PAPERLESS_TASK_WORKERS#considerations-for-less-powerful-devices) as well if we are happy with reducing the defaults to preserve memory and CPU.

# Affected code

On any modern CPU (including slow, Atom CPUs) paperless creates [unnecessary amount of task workers based on core-count](https://github.com/paperless-ngx/paperless-ngx/blob/9a1bd9637cbef0e7318a3c61cae14805c6510cea/src/paperless/settings.py#L438) and [exactly 2 web workers](https://github.com/paperless-ngx/paperless-ngx/blob/9a1bd9637cbef0e7318a3c61cae14805c6510cea/gunicorn.conf.py#L4) for historical (?) reasons

### Webserver logs

_No response_

### Paperless-ngx version

1.7.1

### Host OS

Ubuntu

### Installation method

Docker

### Browser

_No response_

### Configuration changes

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

This PR reduces the webserver and task worker count to 1, by default.  These can still be set as usual via environment variables.  The aim is to reduce overall memory and CPU usage, while allowing users with more demanding work to configure as needed.  

The built image loaded up for me and the frontend seemed responsive to me.  In totally unscientific testing, 1.7 sat at around 330MB and 0.5% CPU.  This image was about 250MB and 0.2% CPU.

Fixes #1098

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by qcasey** [comment]
I am seeing very similar changes on a Pi 4, halfing idle CPU usage from 1.2% to 0.5% and that same mem reduction from about 340mb to 250mb. No noticible drop in web performance

**Review by qcasey — APPROVED** [review]

**Comment by shamoon** [comment]
I’m happy to merge and try this out in the 1.8 beta, if there was to be a difference in web performance I think it would only be with multiple concurrent users? I have no idea how many users are doing that but my guess is not many since we don’t even fully support permissions etc

And the task workers doesn’t seem to affect things like ingesting multiple docs, agreed?

**Review by tribut — APPROVED** [review]

**Comment by shamoon** [comment]
Yea. I see the argument for the greater good here, I’m sure it won’t be too noticeable unless people are processing a big queue of docs but anyway, we can document the change.

I’m sure the blockchain devs burning entire countries-worth of energy every day are also obsessing over 1% vs 0.5% idle cpu 😉

**Comment by qcasey** [comment]
> Could this be done more dynamically? Like scheduled task spin up their own worker always? Or if there are x docs queued up, there is another one added temporarily?

Yep, definitely. See the discussion here, https://github.com/paperless-ngx/paperless-ngx/issues/1098, basically it's on the roadmap.

**Pull request merged**
