### PR TITLE
Feature: slim sidebar

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

This PR introduces a UI feature suggested in https://github.com/paperless-ngx/paperless-ngx/discussions/1221 that is an icon-only option for the sidebar. Video below to demonstrate. Other than the « this doesnt change things for folks who dont want to use it. Details:

- Icon-only sidebar which shows title on hover
- Adds an extra column to documents (best part imho)
- Setting is saved to db to persist across sessions (automatically when visually-toggling, also an option in settings)

https://user-images.githubusercontent.com/4887959/192602606-bf36ed2b-5777-4123-bce9-34cebae7c1b3.mov

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] ~~I have made corresponding changes to the documentation as needed.~~
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by sukisoft** [comment]
Looks great to me. Have you thought about leaving the failed tasks indicator bubble containing the amount of failed tasks visible in the slim-mode? Maybe just a smaller version of it, or just making the icon red to indicated something went wrong. 

Just a thought.

**Comment by shamoon** [comment]
> Have you thought about leaving the failed tasks indicator bubble containing the amount of failed tasks visible in the slim-mode? Maybe just a smaller version of it, or just making the icon red to indicated something went wrong.

I like that, also made the animation better =)

(video updated)

**Comment by stumpylog** [comment]
Very neat! Does it work for mobile pretty well too?  (Just in case someone accesses it via the phone)

**Comment by shamoon** [comment]
> Very neat! Does it work for mobile pretty well too? (Just in case someone accesses it via the phone)

The mobile menu is more of a dropdown thing so this doesnt really apply there, but they do play nice together =)

**Pull request merged**
