### PR TITLE
Chore: Improves manual Docker building

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

I'm probably about the only one using this, but improves the manual building of Docker images.

- Actually can pull cache from the registry
- Minimal version arguments passed to build
- Use buildx, just like the CI does

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
I dont have much to add here code-wise but happy to leave it with you stumpy, I think we all know you know what youre doing. I do think this sounds like a good idea as in the past people have had significant trouble building the image locally

**Comment by stumpylog** [comment]
I think 137 is memory related.  This does spawn a buildx container to use, so it might take more memory.

**Comment by shamoon** [comment]
I had that thought, didnt look like my machine ran out at the time but I think youre right (duh)! I found some stuff to try

**Review by shamoon — APPROVED** [review]
Works!

```
./build-docker-image.sh Dockerfile -t paperless-ngx:test
...
#48 writing image sha256:1303f231e8b107a6a545da57b00032b2411e8e7378d4d010fbf59bfb56d299ad done
#48 naming to docker.io/library/paperless-ngx:test done
#48 DONE 0.9s
```

Edit: and the image works of course =)

**Pull request merged**
