### PR TITLE
Increase length of SavedViewFilterRule

### LINKED ISSUE #601: [BUG] Can´t save filtered view - filter possible too long
**Describe the bug**
The save view dialog is not closing, not showing an error, not saving the view.

**To Reproduce**
I am filtering documents for the last month (03-2022). adding some advanced search filters to exclude some document types, then I want to save this view. The save button goes immedeately back to normal, dialog is not closing, view was not saved, no error message.
The advanced filter is:
```
NOT type:Anleitung AND NOT type:Lieferschein AND NOT type:Vertrag AND NOT type:Aufforderung AND NOT type:BWA AND NOT type:Bescheinigung
```

**Expected behavior**
Filtered view of the advanced search should be saved. Even with long advanced filters.

**Screenshots**
Advanced search filter:
image
Save view dialog after klicking on save:
image

**Webserver logs**
the following log message comes up in the container:
`[2022-04-01 21:09:56,695] [WARNING] [django.request] Bad Request: /api/saved_views/`

**Browser network analyse**
Payload:
```
{"name":"filtered 03-2022","show_on_dashboard":false,"show_in_sidebar":false,"filter_rules":[{"rule_type":20,"value":"NOT type:Anleitung AND NOT type:Lieferschein AND NOT type:Vertrag AND NOT type:Aufforderung AND NOT type:BWA AND NOT type:Bescheinigung"},{"rule_type":8,"value":"2022-03-31"},{"rule_type":9,"value":"2022-03-01"}],"sort_reverse":false,"sort_field":"created"}
```
Response:
```
{"filter_rules":[{"value":["Stelle sicher, dass dieses Feld nicht mehr als 128 Zeichen lang ist."]},{},{}]}
```
> translated it says "please make sure that the field does not contain more than 128 characters".

**Relevant information**
 - chrome, opera
 - Version 1.6.0
 - Installation method: docker-compose with postgres & tika & gotenberg
-

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

Increases the length of the SavedViewFilterRule to allow for quite complex filters to be saved

Fixes #601

@paperless-ngx/backend (Python / django, database, etc.)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Awesome thanks. One other thing I noticed in #601 is that the dialog doesnt show any error. Looking into it a bit the frontend is expecting an error like:
```
{
    error: {
        name: 'Something'
    }
}
```

but at the moment its returning:
```
{
    ...
    "error": {
        "filter_rules": [
            {
                "value": [
                    "Ensure this field has no more than 128 characters."
                ]
            }
        ]
    }
}
```

If you set the title to be more than 128 chars and try to save it it returns in the correct format. 

```
{
    ...
    "error": {
        "name": [
            "Ensure this field has no more than 128 characters."
        ],
        "filter_rules": [
            {
                "value": [
                    "Ensure this field has no more than 128 characters."
                ]
            }
        ]
    }
}
```

Of course I can change the front-end to handle this but I think the API code should be changed to handle that, what do you think?

**Comment by crazychatting** [comment]
@shamoon correct, there was no visual feedback or error message in the ui. as what I have seen in the browser network debug the response contained multiple result arrays - one for each field. I guess because one result/error message per field in the request. So the response could have contained more errors for multiple fields? Then "error": "name" should contain all of them?

**Comment by stumpylog** [comment]
Bear in mind I'm still learning Django on the fly, but I think that error response is what we're going to get.  Basically, the error is a layer down in this case.  Maybe a Django wizard could fix it, but I'm that yet

**Comment by shamoon** [comment]
No worries! I kinda guessed that this was being somewhat automatically generated by Django thus not so simple to “fix”.

So does anyone object to:
1. Handling this issue on the frontend
2. Including the above in this PR (nbd if not of course)

**Comment by shamoon** [comment]
Nvm I see this is your own fork (wanna work on this one in the future?), see #616

**Review by shamoon — APPROVED** [review]

**Pull request merged**
