### PR TITLE
Allow merging of non-pdf files

### PR DESCRIPTION
**Pull request by AlexKraus**
## Proposed change

The bulk edit merge function is enhanced to check if the document to merge is of type pdf.
If not, the archived file for that document is merged instead.

Closes #6341

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [X] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [X] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [X] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [X] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed. *(As far see, no documentation change needed)*
- [X] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
This is a draft PR.  You need at the very least to add testing as well as updating documentation.

Also `mime_type` is a much better check of what a Document is.

**Comment by shamoon** [comment]
I actually think this should be closed rather than left as a draft and could be opened as a new PR if/when ready. This does not include the vast majority of changes that would be required for such a feature.

**Comment by AlexKraus** [comment]
Thank you for your very fast replies!

Just so I understand correctly: It would be expected to fill the lack in testing and documentation for the base functionality of the merge feature to make an enhancement as suggested?

**Comment by stumpylog** [comment]
I would also argue this doesn't meet the feature request.  It does not attempt to merge images.  It merges the archive files of images.  I would find that surprising as a user

**Comment by shamoon** [comment]
> Just so I understand correctly: It would be expected to fill the lack in testing and documentation for the base functionality of the merge feature to make an enhancement as suggested?

The current merge feature certainly does have testing, both the frontend and backend portions. As noted above, the change here is a change from the current behavior without any real explanation, so it would need to be documented, somehow made apparent to the user and as I mentioned, the frontend currently would not allow this. And yes, any changes would need test coverage.

If youre interested in pursuing this we'd be happy to provide more guidance, I'd suggest you can open a discussion if so, but rather than keep this open, given how little is here so far I'm going to close this just for efficiency-sake. Thank you for your interest in contributing.

**Comment by AlexKraus** [comment]
Thank you for guidance!

**Pull request closed without merging**
