### PR TITLE
Chore: remove ignore translation branches from ci

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

As discussed, PRing to make sure

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by stumpylog — APPROVED** [review]
Not sure what's up with the checks on this branch either.  Would have expected it to run here.  Hmm

**Comment by shamoon** [comment]
Yea that is weird, lets see...

**Comment by shamoon** [comment]
I reverted this, it breaks things, my bad

**Comment by stumpylog** [comment]
What broke?

**Comment by shamoon** [comment]
ci wasn’t running at all, just like here. I thought it was because I removed the pull_request line but that didn’t fix it either. I assumed removing the branches filter lines would make it run on all pushes or pull requests, the docs make me think so but didn’t seem to be the case.

Feel free to fix obv, but lesson learned for me not to muck with this stuff :)

**Pull request merged**
