### PR TITLE
Documentation: Fix list indentation

### PR DESCRIPTION
**Pull request by marph91**
## Proposed change

mkdocs expects list to be indented with four spaces. Lists indented with two spaces only will be rendered incorrectly.

Before - After comparison (https://docs.paperless-ngx.com/api/#documents):

grafik

Before - After comparison (https://docs.paperless-ngx.com/configuration/):

grafik

## Type of change

- [x] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [x] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
I’ve hit this many times, so have others. There’s some issue with prettier vs mkdocs, it’s extremely annoying and it can’t be solved in all situations. Feel free to try to figure it out or abandon ship. 

Ps. Thats why we have the checklist above…

**Comment by marph91** [comment]
> Thats why we have the checklist above…

Sorry about that. I didn't read properly and thought the pre-commit hooks will be applied automatically.

> I’ve hit this many times, so have others. There’s some issue with prettier vs mkdocs, it’s extremely annoying and it can’t be solved in all situations. Feel free to try to figure it out or abandon ship.

I tried the mkdocs extension `mdx_truly_sane_lists` as recommended [here](https://github.com/mkdocs/mkdocs/issues/545#issuecomment-522196661), but that breaks some lists indented with four spaces and some admonitions. I will open a new PR if I figure out anything substantial.

**Comment by marph91** [comment]
Actually, there might be a way. I made three changes:

1. Apply the tab with of 4 to all Markdown files.
2. Don't format code blocks. Disable `embeddedLanguageFormatting`.
3. Remove some unneeded escaping. It was present before, but somehow is only rendered after the change. For example replace [`[\#305]`](https://github.com/paperless-ngx/paperless-ngx/blob/b2e9f3195a38d387f7fabd24744d092e7800964e/docs/changelog.md?plain=1#L5127) with `[#305]`.

**Review by shamoon — APPROVED** [review]
Heh, Github hide whitespace button helpful here. 
Screenshot 2024-10-27 at 4 57 22 PM

Thanks

**Pull request merged**
