### PR TITLE
replaced tag text color logic to match google's material design

### PR DESCRIPTION
**Pull request by BeneGrueter**
## Proposed change

Some tag names were a little bit hard to read because the text color logic yielded black for fairly dark background colors. This change introduces the logic used by googles material design, as described [here](https://api.flutter.dev/flutter/material/ThemeData/estimateBrightnessForColor.html). This will generally produce more white text color.

Example:
image
-> 
image

The implemented tests for the text color are still passing.

@paperless-ngx/backend (Python / django, database, etc.)
@paperless-ngx/test (General testing for larger PRs)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Cool idea. Tbh I’m not sure why this is done in the backend at all. I assume it’s not used anywhere besides the frontend…

Also, obv I trust that the Google folks have done/read the research on this but I think because I’m on dark mode (always) I found the change slightly harder to read! Darker surroundings I suppose

**Comment by BeneGrueter** [comment]
I think you are right, in the dark mode the "problem" pretty much disappears - it's very easy to read the black text color with a dark background:
image

I came across the idea in the first place when I noticed a discrepancy of the text color with the [paperless app](https://github.com/bauerj/paperless_app/pull/75/files#diff-a7b7a2e908548d039aeac3219b15e636a49a71984e7929693639de279edf9b01), which is using the material design. I suppose this context also gives the reason to why this code is part of the backend (tag text colors are provided by the api).

**Comment by shamoon** [comment]
Thanks for posting the screenshots, glad to know you agree.

So I think the questions becomes: do we just remove the text color from the backend entirely and let the front-end handle it? I can think of a bunch of potential ways to do this, frankly even just a bit of CSS might do it... I havent really looked at the backend codebase for this so I need to check if there are other ramifications of that but if not obviously it would require a database migration and API change. None of that is too onerous but obviously a lot of work so that we can add 1 css rule =)

**Comment by BeneGrueter** [comment]
Yes I don't think this would be worth the effort but actually, I think it makes sense to run this code as part of the backend in a sense of "run it once and use the result in every frontend (web interface, app, ...)".

My goal was to make the tags look identical in the web interface and in the paperless app (https://github.com/bauerj/paperless_app/pull/75) so I had to choose between the two implementations for the text color. I figured the google implementation used by @bauerj would be more common, but since the difference is very small I think both choices are good (and of course this is your choice anyways).

I think if we want to stick to the implementation from this repository, everything should be fine and we can just go ahead and close this PR.

**Comment by shamoon** [comment]
Yea, certainly appreciate the effort but I played with this for a bit and I think we ought to close the PR for now, given the cost/benefit we discussed. If you can re-work of course we'd be happy to look at that.

**Pull request closed without merging**
