### PR TITLE
Enhancement: rename comments to notes and improve notes UI

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

This PR renames "comments" to "notes" and makes them a bit more 'first-class citizens' in the UI. Screenshots below. Details:

- Shows note count on cards, table & on the tab in doc details
    - Was tricky to decide where to put on small cards, but Im happy with this idea and only downside is we display 1 fewer tag if many are assigned. The notes indicator is visually distinct-enough from tags, imho =)
    - I decided to keep the no. notes consistent with other data on the large cards (as opposed to mimic the 'pill' from small cards.)
 - Note counts are links to go to the tab directly. As a result all document detail tabs now get a url e.g. `/documents/7/notes`
 - Allows sorting by number of notes
 - Fixed an annoyance for me that notes should accept ⌘-enter / control-enter to submit

Screenshot 2023-03-17 at 12 04 06 AM
Screenshot 2023-03-17 at 4 33 22 PM
Screenshot 2023-03-17 at 4 32 51 PM
Screenshot 2023-03-17 at 8 00 56 AM

Fixes #1832
Closes https://github.com/paperless-ngx/paperless-ngx/discussions/2906

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by tooomm** [comment]
That's a lot of great improvements for comment users! 👍 

> 

My thoughts here:
- It looks quite crowded and the tag labels and new comment icon look a bit connected with the overhang count '+3'.
What do you think about using '...' instead and align it more to the tags than the comment icon to create a little gap for easier assignment? I don't think it's too important to show if there is 1 or 5 additional tags. 
- What would be more important than the exact count, would be to show the hidden tags on hover IMHO

**Comment by shamoon** [comment]
Yea I agree thats the trickiest case to get right. How about this, I increased the space between the + and the comments button just a smidge.

Screenshot 2023-03-17 at 7 51 34 AM

- I agree "+ 3" isn't a game-changer to know exactly how many more tags there are but it is useful info as opposed to '...'. Also in trying it out the '...' doesn't read very well (not so legible)
- Im not sure how show on hover would work, ultimately youre going to have to truncate the list eventually? Also a separate PR I think but I suppose you knew that.

**Comment by shamoon** [comment]
Pps. Am I the only person who wishes we named this feature "notes" from the start =/

**Comment by shamoon** [comment]
Im going to update this to change 'comments' to 'notes'. Happy to discuss that change more

**Comment by stumpylog** [comment]
For some reason, I'm seeing the note count about the middle of the document, instead of lower right corner:
image

**Comment by shamoon** [comment]
> For some reason, I'm seeing the note count about the middle of the document, instead of lower right corner:
> image

Hmm maybe something got messed up in a merge, I’ll double-check in a bit

**Comment by shamoon** [comment]
stumpy I can't recreate that screenshot above. Is that just a white document or is the thumbnail not loaded? Trying to think how / what might recreate that

Screenshot 2023-03-18 at 1 45 47 PM

**Comment by shamoon** [comment]
Also looking at your screenshot there really ought to be some color differentiation there between the card and the thumbnail in light mode, e.g. attached

Screenshot 2023-03-18 at 1 51 02 PM

**Comment by shamoon** [comment]
Oh I got it, thanks! I'll fix

**Comment by shamoon** [comment]
Ok please give it another shot

**Review by stumpylog — APPROVED** [review]
Can't comment on the frontend changes, but it looks good when I run it

**Pull request merged**
