### PR TITLE
Add "Created" as additional (optional) parameter for post_documents

### PR DESCRIPTION
**Pull request by eingemaischt**
## Proposed change

I need to import my ecodms-database and I spend much effort on manually tagging all the "created" dates on the documents. But now, while migrating to paperless with a self written import client, I had no option to migrate the "create" date as well.

So I added the possibility...

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [X] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [X] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

Some needed Checklist-Boxes are unchecked. My change is very minimal and I tested it with a docker-compose instance manually for my import. Would someone from the dev team do the tests and have a second look over the changes?

### CODE REVIEW

**Comment by stumpylog** [comment]
This isn't going to be mergeable or reviewable as it is.  

You'll either need to reset your `main` back to `dev` then apply 51d322e1835d24eb3ce62ef0482b35861a4d2e97 or apply 51d322e1835d24eb3ce62ef0482b35861a4d2e97 to `dev` and create a new pull request.

**Comment by shamoon** [comment]
Thanks for the PR. Please re-base to `dev`

**Comment by shamoon** [comment]
Oh sorry missed the previous comment!

**Comment by eingemaischt** [comment]
Sorry, I rebased to dev:  #965

**Pull request closed without merging**
