### PR TITLE
[Beta] Paperless-ngx v1.9.0 Release Candidate

### PR DESCRIPTION
**Pull request by stumpylog**
Hello and welcome to a new release!  We've fixed a number of things and added a few new features (see release notes for details), all thanks to the hard work of the team and all our contributors.  A big thank you to everyone who contributed, whether with code updates, reporting issues and answering discussions.

## Beta Testing

A new docker container has been built at `ghcr.io/paperless-ngx/paperless-ngx:beta`. A release zip can be found in the [github pre-release](https://github.com/paperless-ngx/paperless-ngx/releases/tag/v1.9.0-beta.rc1) or the [latest CI build](https://github.com/paperless-ngx/paperless-ngx/actions?query=branch%3Abeta).

Please test this beta as best you can and report any bugs by [opening a new issue here](https://github.com/paperless-ngx/paperless-ngx/issues/new?assignees=&labels=bug&milestone=v1.9.0&template=bug-report.yml&title=[BUG]+v1.9.0+RC1+Bug). See the [pre-release changelog](https://github.com/paperless-ngx/paperless-ngx/releases/tag/v1.9.0-beta.rc1) and [closed PRs](https://github.com/paperless-ngx/paperless-ngx/pulls?q=is%3Apr+milestone%3Av1.9.0+is%3Aclosed), especially ones labeled non-trival, to guide your tests.

Please remember to [make a backup](https://paperless-ngx.readthedocs.io/en/latest/administration.html#making-backups) if you will be running this over a production installation.

Once you have tested thoroughly for a few days and have not found any [more] issues please approve this PR. We generally aim for **about 5 tested approvals** before this is merged. This is not simply a code review, we prefer hands-on production experience with this beta. The beta will be open for at least 5 days.

Some additional notes:

* The `beta` container is updated as commits are made, see the [actions tab](https://github.com/paperless-ngx/paperless-ngx/actions?query=branch%3Abeta) for progress.
* If bugs are found release candidates will be pushed as necessary.

# Thank you

If you're reading this, **thank you** for being a part of paperless-ngx! While we are proud to continue to publish new releases, we are even prouder of the collaborative process that makes it possible. Thanks to each and every person who has contributed so far 🙏

### CODE REVIEW

**Comment by stumpylog** [comment]
When testing the new Redo OCR, I'm seeing the request to the `bulk_edit` endpoint go pending and never respond.  The request seems alright: 
image

So this may be in the backend.  I don't have more time to test it out tonight, but will when I can

**Comment by shamoon** [comment]
> When testing the new Redo OCR, I'm seeing the request to the `bulk_edit` endpoint go pending and never respond.

Actually working ok for me, using the new (old) `update_document_archive_file`:
```
HTTP POST /api/documents/bulk_edit/ 200 [0.04, 127.0.0.1:64124]
[2022-09-12 03:51:26,014] [INFO] [django.channels.server] HTTP POST /api/documents/bulk_edit/ 200 [0.04, 127.0.0.1:64124]
...
[2022-09-12 03:51:26,838] [INFO] [paperless.tasks] Starting update_document_archive_file
[2022-09-12 03:51:30,243] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /paperless-ngx/media/documents/originals/0000277.pdf
[2022-09-12 03:51:30,390] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/paperless-ngx/media/documents/originals/0000277.pdf', 'output_file': '/var/folders/50/p_n18fw96lj8y3jnd69gy2w40000gn/T/paperless/paperless-70tgrfd7/archive.pdf', 'use_threads': True, 'jobs': 8, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/var/folders/50/p_n18fw96lj8y3jnd69gy2w40000gn/T/paperless/paperless-70tgrfd7/sidecar.txt'}
[2022-09-12 03:51:31,677] [WARNING] [ocrmypdf._pipeline] Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
[2022-09-12 03:51:32,071] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.
[2022-09-12 03:51:35,267] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /var/folders/50/p_n18fw96lj8y3jnd69gy2w40000gn/T/paperless/paperless-70tgrfd7/archive.pdf
[2022-09-12 03:51:35,270] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /var/folders/50/p_n18fw96lj8y3jnd69gy2w40000gn/T/paperless/paperless-70tgrfd7/archive.pdf[0] /var/folders/50/p_n18fw96lj8y3jnd69gy2w40000gn/T/paperless/paperless-70tgrfd7/convert.webp
OMP: Warning #96: Cannot form a team with 8 threads, using 1 instead.
OMP: Hint Consider unsetting KMP_DEVICE_THREAD_LIMIT (KMP_ALL_THREADS), KMP_TEAMS_THREAD_LIMIT, and OMP_THREAD_LIMIT (if any are set).
[2022-09-12 03:51:36,980] [DEBUG] [paperless.parsing.tesseract] Deleting directory /var/folders/50/p_n18fw96lj8y3jnd69gy2w40000gn/T/paperless/paperless-70tgrfd7
03:51:36 [Q] INFO Process-1:9 stopped doing work
```

**Comment by stumpylog** [comment]
I guess we've never made a second release candidate before: https://github.com/paperless-ngx/paperless-ngx/actions/runs/3040356651/jobs/4896819877

**Comment by cutec-chris** [comment]
This happens to me:

[2022-09-15 23:08:12,634] [ERROR] [paperless.consumer] Error while consuming document Info Witten.odt: Could not parse /tmp/paperless/paperless-upload-2j4ej9jw with tika server at http://tika:9998: 'PosixPath' object has no attribute 'decode'

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 55, in parse

    parsed = parser.from_file(document_path, tika_server)

  File "/usr/local/lib/python3.9/site-packages/tika/parser.py", line 40, in from_file

    output = parse1(service, filename, serverEndpoint, headers=headers, config_path=config_path, requestOptions=requestOptions)

  File "/usr/local/lib/python3.9/site-packages/tika/tika.py", line 327, in parse1

    path, file_type = getRemoteFile(urlOrPath, TikaFilesPath)

  File "/usr/local/lib/python3.9/site-packages/tika/tika.py", line 762, in getRemoteFile

    urlp = urlparse(urlOrPath)

  File "/usr/local/lib/python3.9/urllib/parse.py", line 392, in urlparse

    url, scheme, _coerce_result = _coerce_args(url, scheme)

  File "/usr/local/lib/python3.9/urllib/parse.py", line 128, in _coerce_args

    return _decode_args(args) + (_encode_result,)

  File "/usr/local/lib/python3.9/urllib/parse.py", line 112, in _decode_args

    return tuple(x.decode(encoding, errors) if x else '' for x in args)

  File "/usr/local/lib/python3.9/urllib/parse.py", line 112, in <genexpr>

    return tuple(x.decode(encoding, errors) if x else '' for x in args)

AttributeError: 'PosixPath' object has no attribute 'decode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 320, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 57, in parse

    raise ParseError(

documents.parsers.ParseError: Could not parse /tmp/paperless/paperless-upload-2j4ej9jw with tika server at http://tika:9998: 'PosixPath' object has no attribute 'decode'

**Comment by stumpylog** [comment]
Please pull the latest image and make sure you're using it.  This was fixed by #1591

**Comment by stumpylog** [comment]
I can't approve my own pull, but I have test the beta, as built today at 355b3fc and haven't found any further issues.  So here is my stamp of approval: :heavy_check_mark:

**Review by shamoon — DISMISSED** [review]
Yea this has been great. Other than the few things that have come up I havent found any big issues. I plan to test a bit more this weekend too.

Onward and upward team! 👏👏

**Review by shamoon — DISMISSED** [review]

**Comment by cutec-chris** [comment]
> Please pull the latest image and make sure you're using it. This was fixed by https://github.com/paperless-ngx/paperless-ngx/pull/1591

nope, at least with newest beta docker image its today the same

**Review by gador — DISMISSED** [review]
I have tested the beta-rc3 docker image without any issues. Update from 1.7.1 to 1.9.0-beta.rc3 went smooth as well

**Comment by shamoon** [comment]
Thanks everyone! https://github.com/paperless-ngx/paperless-ngx/releases/tag/v1.9.0

**Pull request merged**
