### PR TITLE
Chore: Prevent forks from having failing CI runs by default

### PR DESCRIPTION
**Pull request by tooomm**
## Proposed change

Every fork ends up with regularly failing pipeline runs ~~from scheduled workflows~~ that require further setup or are very specific to the main repo to deploy stuff or interact with other services like GHCR.
I think those should not run by default on all forks.

Maybe worth configuring them even more restrictive to run only on the main repo out of the box:
```
if: github.repository == 'paperless-ngx/paperless-ngx'
```
The cleanup-tag workflow requires further setup to work on forks anyway (PAT setup). So maybe that's the way to go to prevent further unintentional failing runs on users forks?

What about the CodeQL workflow?

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain): CI

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
Thanks, generally good idea.

- I've actually removed the scheduled job [over here](https://github.com/paperless-ngx/paperless-ngx/compare/dev...chore-ci-cleanups) and will put it in shortly, so that won't need to be checked for.
- I think it would be better to check if the secret exists/is not empty, so a fork could configure a secret PAT if they want to.
- This should probably target dev for the moment.  It will reach `main`  next release then, but I don't want to deal with conflicts if possible.

**Comment by stumpylog** [comment]
That quick change has gone into `dev` now, if you want to base these checks against that version.  Thanks

**Comment by tooomm** [comment]
Thanks for letting me know stumpylog, I can come back to this in a few days.

**Comment by tooomm** [comment]
I made it now check for the repo_owner instead a specific repo and removed the scheduled check. @stumpylog 

<br>

>I've actually removed the scheduled job [over here](https://github.com/paperless-ngx/paperless-ngx/compare/dev...chore-ci-cleanups) and will put it in shortly, so that won't need to be checked for.

Without the schedule in place, it will still trigger a failing run in forks for every deletion of a branch (e.g. a successful merge in upstream).

>I think it would be better to check if the secret exists/is not empty, so a fork could configure a secret PAT if they want to.

I quick search tells me this is only possible on a "step" level. Here, we want to prevent all workflow run (job level).
See https://stackoverflow.com/questions/70249519/how-to-check-if-a-secret-variable-is-empty-in-if-conditional-github-actions
There, they suggest to have a PAT checking step first and then following steps can check the outcome. But that would still run the workflow in the first place and status reports of the workflow would not be clear anymore.

>This should probably target dev for the moment. It will reach main next release then, but I don't want to deal with conflicts if possible.

Done.

**Review by stumpylog — APPROVED** [review]

**Pull request merged**
