### PR TITLE
Feature: Add option to enable response compression

### LINKED ISSUE #2616: [BUG] Heavy correspondents set leads to slow application loading
### Description

At launch, with more than 100k correspondents, Paperless-ngx takes a fair amount of time to be 'ready to use'.

Here are my findings, until all correspondents are loaded we can't:
- In documents list, use correspondent filter
- In documents list, see any correspondents be bound to documents
- In document edit view, assign a correspondent
- In document edit view, save document

On my instance with approximatively 120k correspondents, it takes up to 16.60s to load:
image

### Steps to reproduce

1. Create an instance of Paperless
2. Import more than 100k correspondents
3. Import at least one document
4. Launch Paperless-ngx from private navigation

### Webserver logs

_Not necessary_

### Browser logs

_No response_

### Paperless-ngx version

1.12.2

### Host OS

Debian amd64

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

Adds an option, defaulting to False/off, to enable compression of responses from the webserver.  This can help with responsiveness of the UI when returning large document content, many tags or correspondents, etc.

I made it optional and defaulted to off as users with a proxy such as nginx or Traefik will probably find faster and more efficient compression using the compression of the proxy.  The Python libraries do use C for the actual compression, but it will still be better to use the proxy if a user already has it setup.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — APPROVED** [review]
Nice. If a user has compression enabled here and at RP level, is there any potential problem there? I guess the question is if there's a downside to enabling by default?

**Comment by stumpylog** [comment]
I checked with Traefik and it passed the response through as is.  I assume it's looking at the content encoding and not running through compression again.  This actually does a slightly better job at compression, since Traefik doesn't do Brotli yet

**Comment by shamoon** [comment]
Yea, I have no idea what percentage of our users do / don't use compression but my feeling is the overall benefit could be high while those users who aren't happy with this compression as opposed to somewhere else could disable it to take back that level of control. Welcome other opinions, of course

**Comment by shamoon** [comment]
Looks like I convinced you =)
Certainly welcome other opinions if there are any, Im definitely not an expert here!

**Comment by stumpylog** [comment]
Yeah, I think it's a minor slowdown at worst and most users probably wouldn't think to enable it.  And the users who might, are already using reverse proxy setups anyway and will use that instead.

**Review by kaybi-gh — APPROVED** [review]

**Pull request merged**
