### PR TITLE
[Beta] Paperless-ngx v1.8.0 Release Candidate 1

### PR DESCRIPTION
**Pull request by qcasey**
It's been a while! Our development has slowed to a sustainable pace now that many of the outstanding issues/PRs from [jonaswinkler/paperless-ng](https://github.com/jonaswinkler/paperless-ng) have been merged and our Actions workflow is stable.

Thank you to everyone who has contributed, and thank you to the [paperless-ngx team](https://github.com/orgs/paperless-ngx/people) who continues to make paperless one of the best community DMS.

## Beta Testing

A new docker container has been built at `ghcr.io/paperless-ngx/paperless-ngx:beta`. A release zip can be found in the [github pre-release](https://github.com/paperless-ngx/paperless-ngx/releases/tag/v1.8.0-beta.rc1) or the [latest CI build](https://github.com/paperless-ngx/paperless-ngx/actions?query=branch%3Abeta).

Please test this beta as best you can and report any bugs by [opening a new issue here](https://github.com/paperless-ngx/paperless-ngx/issues/new?assignees=&labels=bug&milestone=v1.8.0&template=bug-report.yml&title=[BUG]+v1.8.0+RC1+Bug). See the [pre-release changelog](https://github.com/paperless-ngx/paperless-ngx/releases/tag/v1.8.0-beta.rc1) and [closed PRs](https://github.com/paperless-ngx/paperless-ngx/pulls?q=is%3Apr+milestone%3Av1.8.0+is%3Aclosed), especially ones labeled non-trival, to guide your tests.

Please remember to [make a backup](https://paperless-ngx.readthedocs.io/en/latest/administration.html#making-backups) if you will be running this over a production installation.

Once you have tested thoroughly for a few days and have not found any [more] issues please approve this PR. We generally aim for **about 5 tested approvals** before this is merged. This is not simply a code review, we prefer hands-on production experience with this beta. The beta will be open for at least 5 days.

Some additional notes:

* The `beta` container is updated as commits are made, see the [actions tab](https://github.com/paperless-ngx/paperless-ngx/actions?query=branch%3Abeta) for progress.
* If bugs are found release candidates will be pushed as necessary.

# Thank you

If you're reading this, **thank you** for being a part of paperless-ngx! While we are proud to continue to publish new releases, we are even prouder of the collaborative process that makes it possible. Thanks to each and every person who has contributed so far 🙏

### CODE REVIEW

**Comment by shamoon** [comment]
Big release thanks to a mountain of collaboration, awesome work everyone!

**Comment by shamoon** [comment]
Beta feels good so far! I upgraded over my 'production' install and no issues. I forgot all the small "quality of life" stuff thats in this release in addition to bigger features, awesome.

One small thing I noted is we added "Redo OCR" as an option to the new "actions" dropdown from /documents view but when you actually go into a doc (edit) theres no option there. Thought would be to consolidate Download/More like this/Redo OCR into another actions dropdown (saves room + consistent with other place) but the counter-argument is when youre viewing 1 doc at a time its nice to just have those buttons immediately, but adding another button obviously takes up room. Im leaning towards a separate button. Thoughts? This would be trivial to add to this beta (and probably should have been added with the feature before).

We'll see if anything besides #1246 / #1261 crop up, I also updated the 1.8.0 milestone: https://github.com/paperless-ngx/paperless-ngx/milestone/5

**Comment by bauerj** [comment]
Hey,

sorry for responding so late. I'll be able to test this on Monday.

With regards to @shamoon's comment: Yes, we should probably add that to the next release. I'm not sure which option would be better. Do you have some screenshots to compare?

**Comment by stumpylog** [comment]
Once my two outstanding PRs are in, I'm good with this.  It looked good upgrading a copy of my "normal" data, imported that data just fine and processed new files without issues I could see.

**Comment by shamoon** [comment]
> With regards to @shamoon's comment: Yes, we should probably add that to the next release. I'm not sure which option would be better. Do you have some screenshots to compare?

The more I look at it, the more I think the separate button makes sense, I'll open a PR of course we can discuss/change if people feel otherwise.

**Review by bauerj — DISMISSED** [review]
Works great on my personal instance 😊

**Review by stumpylog — DISMISSED** [review]
I've tested the latest `:beta` and found no issues from upgrading my install in place nor importing a recent export.

**Comment by shamoon** [comment]
Yea Im happy with this, seems like no show-stopper issues. Bravo everyone!

**Review by shamoon — DISMISSED** [review]

**Review by nathanaelhoun — DISMISSED** [review]
Works great on my personal (200 docs, 2 users) instance since 9 days :smile:

**Review by stumpylog — APPROVED** [review]

**Review by shamoon — APPROVED** [review]
Frustrating how every merge dismisses all approvals (makes sense ofc)

**Review by bauerj — APPROVED** [review]

**Comment by qcasey** [comment]
I've been running latest beta and haven't had any issues. I can't approve my own PR, but this has my unofficial seal :seal:

**Comment by nathanaelhoun** [comment]
> Frustrating how every merge dismisses all approvals (makes sense ofc)

FYI, there is a [GitHub setting to disable this](https://stackoverflow.com/a/44747392/16242651)

**Review by nathanaelhoun — APPROVED** [review]
I still approve

**Comment by DarkoBG79** [comment]
I didn't have time to fix the Serbian translation earlier, it has been translated now. If not too late for 1.8.0? Thanks.

**Comment by shamoon** [comment]
> I didn't have time to fix the Serbian translation earlier, it has been translated now. If not too late for 1.8.0? Thanks.

@DarkoBG79 Yea any changes you made wont be in 1.8.0 but they will be in the next release. Thanks for all your translation work!

**Pull request merged**
