### PR TITLE
Feature: New management command for fuzzy matching document content

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

Something requested in the Matrix room, a quick and simple tool to compare the content of documents to all the other documents, reporting those which look very similar, according to either a default ratio or a given ratio.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — COMMENTED** [review]
Cool 😎

Im curious if there will be demand to have support for this on the frontend (doesnt sound easy).

One thing is I tested this out on a couple docker installs and got some weird behavior, similar on both. Both machines are well-resourced (one macOS, other Ubuntu). Both seem to return the initial set of matches quickly and then hang for a very long time (at least from shell it doesnt look like anything is happening e.g. screenshot below). They do eventually complete without error, but seems odd.
1. 65 docs: Time to full set of matches ~14s, then didnt return until 2:34.
2. 71 docs: Time to full set of matches ~9s, then didnt return until 5:14!

Screenshot 2023-09-10 at 8 02 09 PM

Regardless, cool feature.

**Comment by shamoon** [comment]
Ah, I dont have the time to dig more right now but I added some simple print statements just to see and I think its looping unnecessarily
e.g.
```python
        for first_doc in all_docs:
            print(f"first doc: {first_doc.pk}")
            for second_doc in all_docs:
                print(f"second doc: {second_doc.pk}")
                if first_doc.pk == second_doc.pk:
                    print('first_doc.pk == second_doc.pk continue')
                    continue
```
yields https://gist.github.com/shamoon/a8996c4b00f6fafa89df58b07045a196 (its done at line 972)

**Comment by shamoon** [comment]
Sorry for all the noise, I misunderstood and that output is fine, I guess it really does just take that long 🤷

**Comment by shamoon** [comment]
Took a crack at this mostly cause it was fun, feel free to ignore / change: #4161

**Review by shamoon — APPROVED** [review]

**Comment by stumpylog** [comment]
It does actually work, I have a 100% duplicate in text, but it must be generated, so it wasn't a bit for bit match

**Comment by shamoon** [comment]
Nice, way faster with multithreading

Screenshot 2023-09-11 at 4 42 34 PM

**Pull request merged**
