### PR TITLE
Enhancement: dashboard improvements, drag-n-drop reorder dashboard views

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Opening a pair of UI PRs (not dependent on each other) in honor of v2.  Appreciate any feedback. This PR gives the dashboard some love. Screenshots and video below.

- Allow for more legible & useful saved view widgets
- Support drag-and-drop reorder of dashboard views
- Make things nicer (remove clutter, tighten up spacing, resize some headers)
- For mobile, reduce the **noise**

The biggest challenge with updating the dashboard was that I pushed the upload widget down and made it smaller, the potential problems caused by this are mitigated with:

- Enable the 'global' dropzone on the dashboard, because really this makes more sense anyway
- Make the status alerts 'float' to the bottom right, i.e. they're no longer tied to this little widget

Edit: as pointed out by stumpylog the drag-n-drop package has a bad [bug](https://github.com/georgipeltekov/ngx-file-drop/issues/293), so attempted to apply https://github.com/georgipeltekov/ngx-file-drop/pull/294 via https://www.npmjs.com/package/patch-package...

Screenshot 2023-09-24 at 12 58 40 AM

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/1cca136a-92bf-4fe4-bc78-24ee41aeb4bc

Screenshot 2023-09-23 at 10 00 16 PM

Screenshot 2023-09-23 at 8 23 17 PM

Screenshot 2023-09-23 at 8 26 07 PM

I'll update screenshots in the docs once these PRs are done / merged.

Fixes #1818 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
I like the visual changes with this and re-ordering is something I know often asked for.  That looks to work great.  

One thing I'm seeing is the "global" drag and drop seems inconsistent.  I can't tell it's a particular location not working or just doing it too frequently?  No network activity when the drag and drop is released in these cases.  This was in the console:
image

I also managed to get the dashboard to freeze with the upload green box/text showing:
image

**Comment by shamoon** [comment]
Ah great, fail on the first try 😑

Hmm, I think there may have been an issue where the drag-and-drops were interacting in a weird way (I remembered to turn off global file drop if moving the widgets but forgot the other way around).

I still couldn't exactly reproduce the same error as above though, but let me know if youre still seeing it (and if so maybe a video or if there's a more specific set of steps?).

**Comment by LucaNerlich** [comment]
you are doing some nice stuff! Thanks for the work (loving the consumption template pr :) )

**Comment by shamoon** [comment]
Ok phew, hopefully better. I still find drag-n-drop on ubuntu chromium (even FF was better) more wonky than on macOS. The file picker widget should feel the same (but also was rewritten).

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/ba51a535-f64a-4b57-9fd8-ca0225045bde

**Comment by HOCHH4U5JUMP3R** [comment]
You, sir, are a legend! Awesome changes, really looking forward for the update!!

**Comment by shamoon** [comment]
Ok @stumpylog , humbly request another shot. It might not be perfect, I still see occasional ERR_FILE_NOT_FOUND etc. but at this point:

- Have reverted to the current package we're using, now with https://github.com/georgipeltekov/ngx-file-drop/pull/294 applied using https://www.npmjs.com/package/patch-package
- Simplified the overlay transitions which I think was part of the issue

Otherwise, im running out of ideas...

This is chromium ubuntu:

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/4fc80cd4-c05e-47c8-a1df-a2c2a811cf32

**Comment by stumpylog** [comment]
Haha, sorry to send you down a real rabbit hole.  I'll try to test it out this evening

**Comment by shamoon** [comment]
Ha, no worries. Im glad to catch (and hopefully mitigate) that bug, but ultimately pretty frustrated about how inconsistently file drop is implemented across browsers / OS. Actually the patch-package thing may be useful elsewhere too, its a cool little tool...

Appreciate your patience

**Comment by shamoon** [comment]
Weird the backend tests are repeatedly failing with `<class 'TimeoutError'>: <class 'httpcore.ReadTimeout'>, <class 'OSError'>: <class 'httpcore.ReadError'>`. Maybe a GHA issue, will try later but dont think PR is problem for that =)

**Comment by stumpylog** [comment]
it's not, trying to follow the link gives me:
image

**Comment by shamoon** [comment]
> it's not, trying to follow the link gives me:
> image

Ha, wow, never even noticed that

>  A public image is used in the html sample file. We have no control whether this image stays online forever, so here we check if we can detect if is not available anymore.

Actually Im getting a 502, I guess we'll see if wikimedia can fix things for us 😂

Screenshot 2023-09-26 at 9 24 50 AM

**Comment by shamoon** [comment]
Is there a hex on this PR?!? I really dont get codecov math here...

> The diff coverage is 100.00%.

Screenshot 2023-09-26 at 11 04 16 AM

**Comment by shamoon** [comment]
Nevermind, it's changed its mind...

Screenshot 2023-09-26 at 11 07 46 AM

Sorry for the noise, I'm gonna go on a walk now 😖

**Comment by shamoon** [comment]
O.K.

So I think I figured out how to replicate the flashing overlay issue, it had to do with HTML element ordering in the DOM, blah blah. But—and Im a bit afraid to say it out loud—I think I've got us to a better place.

At this point, we're using the _patched_ ngx-file-drop for all the voodoo file stuff and rolling our own component for the rest. I think the PR that we're patching in doesnt totally solve things so thats why we still get occasional failures (very browser / OS dependent, it seems), but not that JS error. Point is, even if we were to shrink it back down to the small widget, we'd have the same issues, so tbh I dont think that would help (assuming the flashing stuff is sorted).

### Some videos.

Reproducing the issue ubuntu Chromium:

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/3ff14bc0-1533-4f39-8383-d78dd11a07e4

With latest commit ubuntu chromium:

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/01e88b28-a2e2-47b4-b32d-214a31632ad9

FF Ubuntu seems better:

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/da74c59b-d06f-42ac-b0a4-1086acdc0ad2

And just for reference, here's macOS Chromium having absolutely 0 issues =)

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/69b48f3a-7db8-4b22-a63a-94be2be43ead

**Comment by stumpylog** [comment]
The flickering does look to be fixed.  Still those odd errors the patch was going to fix, but doesn't fully.  On FF Windows, it seems pretty solid

**Review by stumpylog — APPROVED** [review]
Seems pretty solid now.  Reordering works and d&d is solid on Windows especially.

**Pull request merged**
