### PR TITLE
Beta: 1.6.0 Release Candidate

### PR DESCRIPTION
**Pull request by qcasey**
Hello everyone, and welcome to our first `beta` release! :tada: 

We have just pushed a [release candidate](https://github.com/paperless-ngx/paperless-ngx/releases) for the upcoming 1.6.0 version. This is an all-call for beta testing. If you have the time, we would really appreciate your input :)

If your reaction to this email was annoyance - please read on! There will be minor updates to the team structure.

@paperless-ngx/backend @paperless-ngx/frontend  @paperless-ngx/ci-cd @paperless-ngx/issues @paperless-ngx/test @paperless-ngx/translation 

## Beta Testing

A new docker container has been built at `ghcr.io/paperless-ngx/paperless-ngx:beta`. A release zip can be found in the [github pre-release](https://github.com/paperless-ngx/paperless-ngx/releases) or the [latest CI build](https://github.com/paperless-ngx/paperless-ngx/actions?query=branch%3Abeta).

Please test this beta as best you can and report any bugs by [opening a new issue here](https://github.com/paperless-ngx/paperless-ngx/issues/new?assignees=&labels=bug&milestone=v1.6.0&template=bug_report.md&title=[BUG]+1.6.0+Beta+Bug). See the [changelog](https://github.com/paperless-ngx/paperless-ngx/blob/beta/docs/changelog.rst) and [closed PRs](https://github.com/paperless-ngx/paperless-ngx/pulls?q=is%3Apr+is%3Aclosed+label%3Abackend%2Cfrontend%2Cdeployment), especially ones labeled non-trival, to guide your tests.

Please remember to [make a quick backup](https://paperless-ngx.readthedocs.io/en/latest/administration.html#making-backups) before running this in production.

When you have tested thoroughly (2-3+ days) and did not find any regressions please Approve this PR. We're looking for **about 5 tested approvals** before this is merged. This is not simply a code review, we prefer hands-on production experience with this beta. The beta will be open for at least 5 days to ensure any critical bugs in normal use are found.

Some additional notes:

* The `beta` container is updated as commits are made, see the [actions tab](https://github.com/paperless-ngx/paperless-ngx/actions?query=branch%3Abeta) for progress.
* If bugs are found release candidates will be pushed as necessary.

## Paperless-ngx Teams

For many of us, this is our first time being in a GitHub Organization. You may have noticed the immense volume of direct pings and notifications this creates. Please be warned, when 1.6.0 is released and #98 completed this will only increase (exponentially).

* New issues (likely [10+ a week](https://github.com/jonaswinkler/paperless-ng/issues)) will be triaged and assigned to the relevant teams.
* Similarly, PRs will be assigned to teams for review.

The only purpose of being on a team is to be notified of relevant issues or PRs.

If you are **not** interested in being notified you are welcome to leave your team. Leaving a team does not mean leaving the organization, you can be in 0 teams and still commit to the repo and approve PRs.

With that in mind, I think it's best to remove the @paperless-ngx/translation team. I don't see it being directly pinged in to issues or PRs.

# Thanks

If you're reading this, **thank you** for being a part of paperless-ngx!

An incredible 50+ people have contributed to 1.6.0 which is wonderful to see. We will soon invite the public to switch to paperless-ngx, and everyone will enjoy Paperless for many more years thanks to your contributions.

### CODE REVIEW

**Comment by shamoon** [comment]
Obviously still testing but wow, its awesome to just drop in the new container URL and recreate the docker container and boom 💥, -ngx!

I've really enjoyed working with you all so far—let's keep up the momentum folks!

(again, I will properly test + review over the next few days, just wanted to say this now)

**Comment by apeltzer** [comment]
Couple of things I noticed, not necessarily complete (but will add these here once I'm done testing):

[ ] Changelog does only list V1.5.0 changes, nothing for 1.6.0 / Beta so far - is this intended?

**Comment by azapater** [comment]
Great job guys! I cloned my paperless-ng instalaltion and have been testing it for a few hours on -ngx. First of all: migration is a piece of cake! 

About the testing so far, apart from a few Spanish translation issues I already fixed in crowdin (hopefully they will make it for the final release), the only bug I've found so far is #215

The next couple of days I'll try to find some extra hours to keep the testing and I'll report anything I find.

**Comment by qcasey** [comment]
Thank you for testing!

> Changelog does only list V1.5.0 changes, nothing for 1.6.0 / Beta so far - is this intended?

I believe this will be updated once we merge, readthedocs pulls from the main branch. The 1.6.0 changelog about to be merged can be seen here: https://github.com/paperless-ngx/paperless-ngx/blob/beta/docs/changelog.rst

**Comment by benjaminfrank** [comment]
also installed ngx and migration went without major issues. will check the next coming days If I observe any issues in my normal workflows

When running `sudo -Hu paperless python3 manage.py migrate` I got the message I need to run `sudo -Hu paperless python3 manage.py makemigrations`. This worked without any issues but is not mentioned in the [Upgrade](https://paperless-ng.readthedocs.io/en/latest/administration.html#bare-metal-route) instructions. It is quite self-explanatory but a mention in the release notes/documents might be worthwhile

**Review by shamoon — CHANGES_REQUESTED** [review]
I havent found any issues beyond the minor ones already reported. Once #226 is merged, as they say, LGTM 🚀

**Review by shamoon — APPROVED** [review]

**Review by shamoon — DISMISSED** [review]
I suppose we should merge #235 before release, awaiting that

**Comment by qcasey** [comment]
> I suppose we should merge #235 before release, awaiting that

Merged those in, although I think dependabot will reopen since it was merged into beta

**Comment by qcasey** [comment]
It's day 5, and bug reports have seemingly slowed to 0. If you're also living a bug-free life with this beta, please consider approving this PR in the next few days and we'll get this merged.

**Review by bauerj — APPROVED** [review]

**Review by shamoon — APPROVED** [review]
Sorry forgot to re-approve, lets do this!

**Review by apeltzer — APPROVED** [review]

**Review by benjaminfrank — APPROVED** [review]
tested for 2 days, added PDFs via UI and via android app, no issues

**Comment by rickyagrawal** [comment]
> Please test this beta as best you can and report any bugs by [opening a new issue here](https://github.com/paperless-ngx/paperless-ngx/issues/new?assignees=&labels=bug&milestone=v1.6.0&template=bug_report.md&title=%5BBUG%5D+1.6.0+Beta+Bug). See the [changelog](https://github.com/paperless-ngx/paperless-ngx/blob/beta/docs/changelog.rst) and [closed PRs](https://github.com/paperless-ngx/paperless-ngx/pulls?q=is%3Apr+is%3Aclosed+label%3Abackend%2Cfrontend%2Cdeployment), especially ones labeled non-trival, to guide your tests.

The link to the changelog does not work

**Comment by qcasey** [comment]
Thanks, the beta branch was deleted. The changelog can be found here temporarily: https://github.com/paperless-ngx/paperless-ngx/blob/main/docs/changelog.rst

**Comment by shamoon** [comment]
Docs are fixed (and should be going forward)

**Pull request merged**
