### PR TITLE
[Documentation] Update docker-compose steps to support podman

### PR DESCRIPTION
**Pull request by white-gecko**
Update the documentation.

As also written in the docker-compose file it is necessary to do the steps in the order:

1. Run 'docker-compose pull'.
2. Run 'docker-compose run --rm webserver createsuperuser' to create a user.
3. Run 'docker-compose up -d'.

This is also the order of steps in the setup script:

https://github.com/paperless-ngx/paperless-ngx/blob/9564a9c28d3910fbca66f6a34bca221fd2e9129f/install-paperless-ngx.sh#L385-L389

## Proposed change

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
I don't actually think this change is needed though? Works fine as is

**Comment by white-gecko** [comment]
Actually it did not work for me at least on podman.
When I first pulled, then brought the compose up and subsequently tried to create the user I received the following error message:

```
$ docker-compose pull
Pulling broker    ... done
Pulling db        ... done
Pulling gotenberg ... done
Pulling tika      ... done
Pulling webserver ... done

$ docker-compose up -d
docker-compose up -d
Creating network "paperless_default" with the default driver
Creating volume "paperless_data" with default driver
Creating volume "paperless_media" with default driver
Creating volume "paperless_pgdata" with default driver
Creating volume "paperless_redisdata" with default driver
Creating paperless_broker_1    ... done
Creating paperless_gotenberg_1 ... done
Creating paperless_db_1        ... done
Creating paperless_tika_1      ... done
Starting paperless_webserver_1 ... done

$ docker-compose run --rm --no-deps webserver createsuperuser
Creating paperless_webserver_run ... error

ERROR: for paperless_webserver_run  Cannot create container for service webserver: bad parameter: link is not supported

ERROR: for webserver  Cannot create container for service webserver: bad parameter: link is not supported
ERROR: Encountered errors while bringing up the project.
```

So I had to switch the `run` and `up` commands

**Comment by shamoon** [comment]
Ah, well I do think that’s only true for podman.

googling the specific error re `link` suggests other solutions: https://github.com/containers/podman/issues/11717

I suppose if it works in both cases the change would be OK, especially if it’s written that way elsewhere.

**Comment by white-gecko** [comment]
I see, thank you for the research and clarification. But since I assume it works in the suggested way as well, as also shown in all of the other point in the project this would improve the podman support.

**Review by shamoon — APPROVED** [review]
Will leave merge pending others agree

**Review by stumpylog — APPROVED** [review]
Seems like it shouldn't cause an issue

**Pull request merged**
