### PR TITLE
Resolve `scikit-learn` warnings in unit tests

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

This resolves a few warnings in the test suite, when the new version of `scikit-learn` un-pickles the unit test pickled models.  It does this by manually un-pickling then re-pickling the file, without other changes, using the newest locked version of `scikit-learn`.

Just for fun, I also added a comment for tracking why the classifier format version was updated.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
@shamoon is there a configuration step I need to take for the project automations to succeed?

**Comment by shamoon** [comment]
> @shamoon is there a configuration step I need to take for the project automations to succeed?

Yea sorry didn’t want to bother y’all with that, I had tested it previously and it worked fine but now only sometimes. It’s really a pretty simple action, not sure if you guys can tell why it fails? Some runs it claims can’t get the token but obviously token exists because other runs work fine.

Eg 
https://github.com/paperless-ngx/paperless-ngx/actions/runs/2019776303
Vs
https://github.com/paperless-ngx/paperless-ngx/actions/runs/2019317597

I can try to dig more into it but dunno if it’s obvious to anyone else.

**Comment by shamoon** [comment]
> @shamoon is there a configuration step I need to take for the project automations to succeed?

Ah, figured it out, was because `pull_request` action doesnt have access to secrets when run from a fork e.g. `stumpylog/paperless-ngx/tree/resolve-sklearn-test-warnings` here as opposed to bauerj's PR. I switched it to `pull_request_target` and that should fix it.

( see https://docs.github.com/en/actions/security-guides/encrypted-secrets )

**Review by bauerj — APPROVED** [review]
It loads here, the tests pass so let's merge it 😊

**Pull request merged**
