### PR TITLE
Fix consumer ignore pattern for macOS .DS_Store

### PR DESCRIPTION
**Pull request by dcava**
## Proposed change

The current ignore patterns includes ".DS_STORE" which does not reflect the current MacOS filename ".DS_Store". While MacOS and Windows are generally "cicp" the glob patterns are case *sensitive* when run via Docker (=Linux=case sensitive). Whilst it is easy to add this pattern via an environment variable, as it represents an entire operating system, it seems reasonable to make the change.

I left ".DS_STORE" as it may be relevant for MacOS files transferred via other filesystems where case may not always be preserved.

Fixes # (issue)

Webserver logs an error when encountering ".DS_Store" files on MacOS via Docker.
```
[2023-04-16 21:04:32,191] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/.DS_Store: Unknown file extension.
```

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain)

Non-breaking change to modify current behaviour. Not really a bug.

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Sure thanks. Isn't it just a file though, not a dir?

**Comment by dcava** [comment]
You're right it is just a file, I presumed as the  exisiting ".DS_STORE" had that glob pattern that it was necessary for some reason! Do you want me to re-submit?

**Comment by stumpylog** [comment]
So this name used to be a folder, but on newer Macs, it is now a file?  Or was it always a file and accidentally set like a folder?

With the glob, it doesn't get ignored as a file, so a quick update to fix that would be good.  Then maybe a quick few lines added to `test_is_ignored` inside `test_management_consumer.py`

**Comment by shamoon** [comment]
It's always been a file, I think. @dcava let us know if you can take care of stumpylog's suggestions above

**Comment by dcava** [comment]
Have changed the settings.py file to reflect the changes above.

**Review by shamoon — APPROVED** [review]

**Review by stumpylog — APPROVED** [review]

**Pull request merged**
