### PR TITLE
Enhancement: disable / hide some UI buttons / elements if insufficient permissions, show errors

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Nothing new here, mostly about hiding / disabling UI elements based off permissions and also show the user an error if needed upon background loading of mail rules / accounts and users / groups. To be clear, all of these actions are already correctly denied by the backend but no reason to show something to the user if we already know they cant do it.

Screenshot 2023-08-17 at 8 37 29 PM
Screenshot 2023-08-17 at 1 46 10 PM

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain): Enhancement

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
Just looking at that screenshot, is it possible to do a little cleanup to it?  Maybe the "headers", "lazyUpdate", could be pruned out, leaving something like a URL, status code, details?

No idea if that's easy or not.  Or if those details are actually useful in some cases.  What do you think?

**Comment by shamoon** [comment]
I have had the same thought but I wasn’t really sure how predictable those errors are. Seems like a fun thing to play with, I’d prefer to do it in a different PR though actually as that will touch a bunch of different spots.

(and no worries if you want to hold this PR until after another bug fix release)

**Comment by stumpylog** [comment]
I'd hope they follow a pretty defined format, but I'm not positive.  If you want to include this in the next release, i'm good with that, it's kind of bug fixy/good QoL

**Comment by shamoon** [comment]
That sounds good, will save the spiffying-up of error messages for the one after.

**Review by stumpylog — APPROVED** [review]

**Pull request merged**
