### PR TITLE
Add Dockerfile arguments for language versions

### PR DESCRIPTION
**Pull request by adamantike**
## Proposed change

Simplify changes to Dockerfile regarding Node/Python versions. This also allows parameterizing build for different versions to test if they could be supported.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other: Parameterize builds.

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
I can't say I see the point behind this.  We have plans to upgrade Node soonish, before it goes EOL.  Python 3.9 is going to be around for quite some time and PiWheels only build 3.9 for ARMv7 right now.

If someone wants to build an image with something newer, they'd already be able to edit the file.

**Comment by stumpylog** [comment]
All the backend tests run again 3.8 through 3.10, so the code is known to be compatible with those versions, at least for x86_64. 
 That's the compatibility, there's no newer language features in use.

The Docker image is 3.9 and there's no expectation or plan to change that yet.  It will remain so long as ARMv7 is supported for the image and PiWheels isn't building anything for 3.10 or newer.

**Comment by shamoon** [comment]
Thanks for the efforts, sounds like we'll hold off on merging for now.

**Comment by adamantike** [comment]
@stumpylog, thanks for the context. My question was not about newer Python versions, but regarding if the Docker iamge should support being built with 3.8, as that should be supported by the project.

However, I found that https://github.com/paperless-ngx/builder only builds the wheels using 3.9.

**Pull request closed without merging**
