### PR TITLE
Chore: update frontend PDF viewer (including pdf-js)

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Happy to report the frontend PDF viewer [was updated](https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/10.0.0) to a [newer pdf-js version](https://github.com/VadimDez/ng2-pdf-viewer/commit/b8529897010d951b6b63ffbd4da5cc43bd06dd95), hoping this fixes some issues with it. I tested locally without any obvious problems, there's an image available for testing as well `feature-update-pdf-viewer`.

See #3732
See #3635
See #3743
See #3890

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain): dependencies

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
Is this pretty safe for maybe another point release?  I forgot to merge in the translations last time anyway

**Comment by shamoon** [comment]
Yes I think so. At worst this could have some new rendering issues but the only real change they made was updating pdf-js (the library that Mozilla maintains that native renders PDFs in Firefox). I’m not sure how many of these random things this will help, no one has tested,  but yea, low risk I think.

**Review by stumpylog — APPROVED** [review]
I didn't notice any rendering problems with some sample files.  The bundled version upside seems pretty minor

**Comment by shamoon** [comment]
Ignoring the codecov complaining here

**Comment by alexpovel** [comment]
Thanks for addressing that issue, had been a nasty couple weeks!

Unfortunately, I am still running into the issue (am on 1.17.4 by now, and was on 1.17.3 for a while with the issue still occurring). I deleted all site data in an attempt to remove old, cached JS libs/files and restarted Firefox. Neither helped.

Is there anything else I can try or provide for you to troubleshoot more?

**Pull request merged**
