### PR TITLE
Allow setting more than one tag in mail rules

### PR DESCRIPTION
**Pull request by jonasc**
For me it would be very useful to be able to set multiple tags for mail rules, e.g. set `inbox` and `purchase` for mails arriving in my purchases folder. Hence, I converted the `ForeignKey` to a `ManyToManyField` with suitable data migration:
1. Add the new many-to-many field assign_tags.
2. Copy existing data from the assign_tag field to the assign_tags.
3. Delete the existing assign_tag field.

### CODE REVIEW

**Comment by jonasc** [comment]
I just figured out that my change breaks some tests so I'll take care of that as well.

**Comment by jonasc** [comment]
All additionally failing test cases have been fixed by the last two commits.

**Comment by bauerj** [comment]
Sorry for the delay. The code looks good but I haven't tested it yet. I'll leave a review after that, hopefully next week.

**Review by bauerj — APPROVED** [review]
Thanks, seems to have worked fine!

**Review by stumpylog — APPROVED** [review]
Looks alright to me.  I'm assume the migrations won't conflict with the other mail related migrations which went in with a different pull request.

**Comment by shamoon** [comment]
@jonasc OP looks like this is approved but it needs a re-base to the current `dev` branch when you have a second.

**Comment by jonasc** [comment]
I did the rebase, but somehow there was a problem pushing, so I force-pushed to my repo. I hope that this doesn't brake the workflow here? Anyway, I merged the migrations ran all the tests, so it should be fine.

**Comment by shamoon** [comment]
Thank you. I will let the original reviewers take another look. Perhaps we could sneak this into 1.7.0 (dont think it will need a re-base 😬)

**Review by stumpylog — APPROVED** [review]
Looks alright to me.  The empty migration in `src/paperless_mail/migrations/0013_merge_20220412_1051.py` is presumably to bring the branching migrations back together, since another migration was also made to the models.

**Comment by jonasc** [comment]
> The empty migration in `src/paperless_mail/migrations/0013_merge_20220412_1051.py` is presumably to bring the branching migrations back together, since another migration was also made to the models.

Exactly, it was automatically created by django to merge the two independent migrations.

**Comment by shamoon** [comment]
cheers, thanks all

**Pull request merged**
