### PR TITLE
add instructions to install pytest-xdist and pytest-cov 

### PR DESCRIPTION
**Pull request by lippoliv**
(imported https://github.com/jonaswinkler/paperless-ng/pull/1681)

I needed to research this, so I think it could help others to have it in the documentation.

### CODE REVIEW

**Comment by lippoliv** [comment]
I will probably update or remove this PR since using `pipenv` looks to be the expected way to setup local environment. So the documentation should hold this information already, or this should be added instead of manual commands.

**Review by shamoon — CHANGES_REQUESTED** [review]
But this doc already links to the main documentation section on development, I don’t think we need to repeat things in two places. At most you could add a line at the start like “After getting your environment setup (link to documentation), …”. 

As is this is just like an overly-brief duplicate of those instructions.

**Review by qcasey — DISMISSED** [review]

**Comment by lippoliv** [comment]
@shamoon I think I miss something. I checked again today, and I do not find some docs in code about coding? Are you talking about [Initial setup and first start](https://paperless-ngx.readthedocs.io/en/latest/extending.html#initial-setup-and-first-start) / [Bare Metal Route](https://paperless-ngx.readthedocs.io/en/latest/setup.html#bare-metal-route)?

**Comment by shamoon** [comment]
Yes https://paperless-ngx.readthedocs.io/en/latest/extending.html#initial-setup-and-first-start

> 1. Install prerequisites + pipenv as mentioned in [Bare metal route](https://paperless-ngx.readthedocs.io/en/latest/setup.html#setup-bare-metal)

> 6. Install the python dependencies by performing in the src/ directory. .. code:: shell-session `pipenv install –dev`

My point is to just link there so if things change we don’t need to update two places. Anyway, it’s a small PR I don’t want to make a big deal of it but ya know, [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) …

**Comment by lippoliv** [comment]
OK now I broke something. Let me fix that.

**Comment by lippoliv** [comment]
@shamoon thanks for your feedback. I updated the PR, now it is linking to the docs.

**Comment by shamoon** [comment]
Great, thanks for your patience and for the effort!

**Pull request merged**
