### PR TITLE
[Readme] Fix typo

### PR DESCRIPTION
**Pull request by tooomm**
## Proposed change

Tiny typo fix in README.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (documentation in readme)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks

**Comment by qcasey** [comment]
I don't think this was a typo, it's trying to say the app works with:

1. paperless-ngx
2. paperless-ng
3. paperless

Although it's a little redundant/confusing. The line could probably just say "Also works with the original Paperless projects."

**Comment by tooomm** [comment]
>it's trying to say the app works with:
>
>    paperless-ngx
>    paperless-ng
>    paperless

Exactly. It used to say it works with **Paperles-ngx**, **Paperless** and **Paperles-ngx** (again).

I like your other suggestion as well, makes things even easier. :)

**Comment by qcasey** [comment]
Hah, my mistake. Good catch

**Pull request merged**
