### PR TITLE
Feature: Add additional caching support to suggestions and metadata

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

This uses already existing or easy and quick to compute data for setting an ETag and Last-Modified headers on the responses for some of the slower endpoint.  Notably this is suggestions, and metadata.  An attempt was made for the preview, but for yet unknown reasons, this is not ever shown as cached. 

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Oh wow this is really fantastic, I think this will make a really huge difference for literally all users. Nice!

Is it ready to test?

**Comment by stumpylog** [comment]
Mostly.  I was trying to get the preview caching actually working first.  Suggestions and metadata seem fine.  Not really sure if the response type for the preview can't be cached or something

**Review by shamoon — COMMENTED** [review]
Hmm, so I tested this out with a document in my dev install that seems to cause drama with checking suggestions ( https://link.testfile.org/PDF50MB ) and couldn't tell if it is doing what I hoped, but I think it helps! 

The second call to `metadata` is very speedy and looks like it's working but reloading the page still seemed to tax the server in a way that made me think suggestions is perhaps re-running. Then again maybe it's just that loading the classifier takes that long? I guess avoiding loading the classifier altogether is not so straightforward?

First time:
Screenshot 2024-01-15 at 2 41 56 PM


Second time:
Screenshot 2024-01-15 at 2 43 04 PM


Third time (after server recovers):
Screenshot 2024-01-15 at 2 52 35 PM


Fourth time:
Screenshot 2024-01-15 at 2 55 21 PM


Looking at the eTag certainly looks like its working:
Screenshot 2024-01-15 at 2 58 13 PM
Screenshot 2024-01-15 at 2 57 44 PM

Not making a totally coherent point here, just reporting in an end-user kinda way

**Comment by stumpylog** [comment]
In Firefox, the network tab will show it as `cached` if it didn't actually make the request again.  When exactly it decides to or not, I think is a little up to the browser.  At least what I see is:

image
then
image

I know Firefox has a button in the tools to disable caching, that may be checked?

**Review by shamoon — APPROVED** [review]
Oh boy thats embarrassing, I guess in dev I usually do want caching disabled 😅

Ok, then back to my original thought: this is totally awesome.

(confirmed, look how freaking zippy this is when I dont disable caching)
Screenshot 2024-01-15 at 3 32 37 PM


Nice one stumpy

**Comment by shamoon** [comment]
I guess a future potential idea would be to cache / store these on the server somehow

**Comment by stumpylog** [comment]
Eventually using Redis could be useful.  It could store the ETag and modified, as well as even the suggestions.  But future work.

I can't figure out the preview caching.  I'm inclined the leave the view decorated, since it doesn't seem to hurt anything, even if it doesn't help.

**Pull request merged**
