### PR TITLE
Link to "Share Links"

### PR DESCRIPTION
**Pull request by tmaier**
#share-links

## Proposed change

image

The section about "Share links" exists in the navigation, but cannot be clicked.
The reason is a missing anchor/id at that section.

Closes #(issue or discussion)

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [x] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks for the PR but I dont think this is broken? mkdocs defaults to hyphenating headings, so the default link is #share-links and I think thats what it is currently, see screenshot:

Screenshot 2023-12-26 at 4 57 04 PM

**Comment by tmaier** [comment]
@shamoon Then I don't understand what is broken here...

This is the screenshot of the documentation.

- In the navigation: Share Links cannot be clicked
- In the text itself: the Heading is missing

image

(Screenshot of v2.3.0)

**Comment by shamoon** [comment]
Clear your browser cache? See below in two browsers...

Screenshot 2024-01-06 at 8 19 40 PM
Screenshot 2024-01-06 at 8 20 45 PM

Or maybe some extension or something in your browser?

**Comment by tmaier** [comment]
So I checked also ob my smartphone. There I see the same issue.

the root cause is my ad blocker (AdGuard). I dont know which ad filter exactly… maybe a social sharing filter…

**Pull request closed without merging**
