### PR TITLE
docs: better language code help

### PR DESCRIPTION
**Pull request by tooomm**
## Proposed change

The [docs](https://docs.paperless-ngx.com/configuration/#ocr) currently link https://www.loc.gov/standards/iso639-2/php/code_list.php and ask to use ISO639-2 codes.
Turns out those are not always correct, and Tesseract sometimes has its own variant.
The issue appeared in https://github.com/paperless-ngx/paperless-ngx/issues/1106#issuecomment-1427057018 and https://github.com/paperless-ngx/paperless-ngx/issues/2824#issuecomment-1454892159 recently.

The Tesseract docs seems to not be very actively maintained and currently do not list languages for v5 in the table for example. But linking to the official docs still seems most reasonable and should provide a good help resource to users:
https://tesseract-ocr.github.io/tessdoc/Data-Files-in-different-versions.html

Alternative links if you think they are a better fit:
- https://packages.debian.org/source/bullseye/tesseract-lang (needs to be kept up to date with the debian base image)
- https://tesseract-ocr.github.io/tessdoc/Data-Files#data-files-for-version-400-november-29-2016
- https://github.com/tesseract-ocr/tessdata

The commit also includes a few tiny layout fixes in this section.
Also, the link is now clickable.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (docs)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — DISMISSED** [review]
Agree

**Comment by stumpylog** [comment]
Maybe the same link should be provided for `PAPERLESS_OCR_LANGUAGES`?  And perhaps an additional note for it being a space separated list?

**Comment by tooomm** [comment]
Yep, very good points. Will add it tomorrow.

**Review by stumpylog — DISMISSED** [review]
Thanks, hopefully this clears up some confusion

**Comment by tooomm** [comment]
Have the commits cleaned up now. Sorry for the back and forth 😄

**Review by shamoon — APPROVED** [review]

**Pull request merged**
