### PR TITLE
Feature: Add ahead of time compression of the static files for x86_64

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

This PR adds compression of the static files, using whitenoise.  The static files are compressed once, on x86_64, then used throughout.

I considered making it more configurable, but then I think it would be easy for a user to change this and not run `collectstatic`, leaving them with no or wrong static files in place.  Or a "release" vs "development" build, but that proved to become complicated quickly. 

Perhaps in the future GitHub will have native arm64 runners, which would allow this to be revisited and simplified.  Some improvements to whitenoise could be built in as well.

In some testing, this reduced main.js to about 50% size when using gzip and to about 40% size when using Brotli (requires HTTPs).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
This seems useful (and patching PRs into other OSS projects seems to be a theme lately...), but pardon my ignorance in trying to test this out:

- No issues running on either `x86_64` or `arm64` machines I have.
- On both e.g. main.js seems to be the same size, and seems to be served with brotli even when testing `dev` on localhost vs this branch either locally or via https, assuming that's what this `Content-Encoding: br` means? Am I missing something here? Again my understanding of this stuff fairly limited.

Also, just curious if this change requires the css map to be added or did you just not like seeing the error log =)? No problem with that obv, just curious

**Comment by stumpylog** [comment]
- The CSS map was required.  I'm not sure why, but `collectstatic` failed without it being there.
- Do you have [`PAPERLESS_ENABLE_COMPRESSION`](https://docs.paperless-ngx.com/configuration/#PAPERLESS_ENABLE_COMPRESSION) set to anything?  That would be doing some "on the fly" compression, though I still think Brotli should require an HTTPS connection

**Comment by shamoon** [comment]
I dont have `PAPERLESS_ENABLE_COMPRESSION` explicitly set, no.

So like here's `dev` with `PAPERLESS_ENABLE_COMPRESSION=0`:
Screenshot 2023-10-17 at 12 11 04 PM
Screenshot 2023-10-17 at 12 11 12 PM

`dev` with `PAPERLESS_ENABLE_COMPRESSION` left off:
Screenshot 2023-10-17 at 12 13 26 PM
Screenshot 2023-10-17 at 12 13 21 PM

and `feature-compressed-static-files`:
Screenshot 2023-10-17 at 12 14 23 PM
Screenshot 2023-10-17 at 12 14 30 PM

Obviously, I believe that this works =) just was trying to due diligence to test out. Sorry for the hassle.

**Comment by stumpylog** [comment]
Very curiously different than what I recall seeing.  I'll have to look again when I can.  I recall `main.js` coming in at around 1MB and never being compressed for me, when using localhost or a hostname connection.  Through my domain, Traefik is handling compression, so it doesn't count.

Now I'm curious about this.

**Comment by shamoon** [comment]
Yea my domain is behind CF and Traefik so at first I was like "oh duh, its those" but I dont understand who/what/how/why is doing it over localhost (not https either). This stuff is really opaque to me 🤔

**Comment by stumpylog** [comment]
With `dev`, when I set `PAPERLESS_ENABLE_COMPRESSION: 0`, I get no compression of `main.js` and a size of ~1.8 MB:
image

It does look like Brotli is allowed for `localhost`, so that's actually a good thing for this PR.  I'm not sure how your `dev` was still returning a compressed response when it was disabled.  Cache maybe?

When I have `feature-compressed-static-files` and `PAPERLESS_ENABLE_COMPRESSION: 0`, `main.js` is coming in Brotli encoded with ~379 kb:
image


As far as i can tell, this is working as intended, and it's doing the compression ahead of time, rather than per request, so I think it will be helpful (at least for x86_64 at the moment)

**Review by shamoon — APPROVED** [review]
Blah, sorry my bad, I think just user error on my part.

Thanks for the PR

**Comment by shamoon** [comment]
Appreciate the explanation. I do mostly understand the flow and overall goal but code is still mostly Greek to me. I think at this point you've earned trust with the project to do as you see fit. For my part, can confirm working from an end-user perspective. Thanks stumpy

**Comment by stumpylog** [comment]
Weird, not sure why this keeps getting stuck.  That's at least twice now, at different times in the build.  I may have to go back to the simpler method

**Comment by stumpylog** [comment]
Alright, I ended up going back to the simple method which doesn't add much time at all to the build.  Even with the attempts earlier, the ARM64 build seemed to be taking longer and getting stuck in weird ways.  The 1hr+ to compress the files under emulation just isn't worth it.  Our ARM64 users can still get the on-the-fly compression from the middleware.

Once this finishes building and I double check it on both platforms, I'll merge this one and be done

**Pull request merged**
