### PR TITLE
Fix #224: "Auto-detected date is day before receipt date"

### LINKED ISSUE #224: [BUG] Auto-detected date is day before receipt date
**Describe the bug**
When the system automatically detects the date on the receipt, the "Date Created" field is set to the day before.

**To Reproduce**

1. Have system timezone set to UTC-6
2. Scan document that has approved date type
3. See that date is day before date in receipt.

**Expected behavior**
Date should be exact date on receipt.

**Webserver logs**
N/A

**Relevant information**
 - Host OS of the machine running paperless: Docker/Ubuntu 18.04
 - Browser: Chrome
 - Version 1.5.0
 - Installation method: docker
 - Any configuration changes:
```
PAPERLESS_TIME_ZONE=America/Chicago
PAPERLESS_DATE_ORDER=MDY
```

### PR DESCRIPTION
**Pull request by a17t**
Fixing #224 by
1. Adding the timezone to the parsed date from the document
2. Adding corresponding assertion in consumption test

### CODE REVIEW

**Comment by a17t** [comment]
Just from fixing that issue I can say, most used time/date APIs include the timezone. So getting rid of it might require major changes and workarounds to ignore the timezone. 

But in general I agree, the topic of timezones is quite complex and we need to decide on whether we want to support timezones or just say "the date of a document is timezone-less". 

What do you think about creating an issue to discuss that proposed change, so the team can discuss and decide on that?

**Comment by bauerj** [comment]
> What do you think about creating an issue to discuss that proposed change, so the team can discuss and decide on that?

Yes, I think that's a good idea.

**Comment by MMauro94** [comment]
@bauerj I would like to say my 2 cents about this timezone issue. Where should I write? Here, on #224 or elsewhere?

**Comment by bauerj** [comment]
Probably here: https://github.com/paperless-ngx/paperless-ngx/discussions/350

**Review by bauerj — APPROVED** [review]
Apart from the high-level discussion about time-zones, this looks good and fixes the issue.

**Pull request merged**
