### PR TITLE
Fix custom theme color contrast

### LINKED ISSUE #708: [BUG] Bad visibility of logo and other icons when using lighter colors in dark mode
### Description

Bad visibility of logo and other icons when using lighter colors in dark mode. Color in picture is #e39296. Similar to #c9b3e6.
Text is in gray so the visibility is not so good. Same goes for Save button in settings. 

### Expected behavior

Text should maybe be a little darker for logo or some kind of background. Or maybe apply same rule for those items as for tags?

### Steps to reproduce

1. select lighter color in theme color

### Webserver logs

```bash
/
```

### Screenshots

image
image

### Paperless-ngx version

1.7.0-rc1

### Host OS

Linux/Unraid

### Installation method

Docker

### Browser

Chrome

### Configuration changes

/

### Other

/

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

This PR addresses potential poor contrast of elements when using the new custom "theme color". I initially used a simple brightness method but wasn't happy with the results so ended up using a luminance calculation (thanks @BeneGrueter from #544). Video below demonstrates this. As a side-effect this PR merges the two "theme" .scss files which probably didnt need to be separate anyway.

https://user-images.githubusercontent.com/4887959/163106440-b5077a31-742b-41d6-81ca-023ae169d6ff.mov

Closes #708 @miku323

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] ~~I have made corresponding changes to the documentation as needed.~~
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
> I get a couple of these
> 
> `src-ui/src/app/components/app-frame/app-frame.component.scss exceeded maximum budget. Budget 10.00 kB was not met by 1.39 kB with a total of 11.39 kB.`

Ah, because the theme file is slightly larger. I think I can sort that out easily, 1 sec.

**Comment by qcasey** [comment]
One last thing I noticed: in the settings if you change the color then press reset, the popup alert isn't readable (in light mode only)


Screenshot from 2022-04-13 09-29-05

**Comment by shamoon** [comment]
Cheers, appreciate testing, lots of little things can easily miss with these. That one should be sorted.

**Review by qcasey — APPROVED** [review]
Thank you! This UX is so much better.

**Comment by smseidl** [comment]
@shamoon - not sure if this is related to this PR or not, but in general Dark Mode some details are not visible/hard to see.  The best example is the close X in the notification box and the progress bars on the Dashboard.

While trying to get examples, I switched out of dark mode, and the progress bars on the Dashboard were worse (see 3rd image).

This is all out of the `beta` branch as of 4/15/22 USA Evening.

image
image
image

Please let me know if you want this here, or if I should open a new Beta issue.

**Comment by shamoon** [comment]
> @shamoon - not sure if this is related to this PR or not

No worries I'll take a look when I have a minute and fix. There's always css stuff like this when things get moved around (which there's a lot of in 1.7), thanks for pointing them out!

**Pull request merged**
