### PR TITLE
Change: tweaks to system status

### LINKED ISSUE #6007: System Status shows classifier error after update 2.6.0
### Description

In System Status, i get an Error on the Classifier Status.

### Steps to reproduce

1. Go to Settings
2. Click on System Status

### Webserver logs

```bash
[2024-03-05 06:55:47,456] [ERROR] [paperless.api] System status error loading classifier: Classifier not loaded
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/views.py", line 1625, in get
    raise Exception("Classifier not loaded")
Exception: Classifier not loaded
```

### Browser logs

_No response_

### Paperless-ngx version

2.6.0

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

Safari

### Configuration changes

_No response_

### Other

_No response_

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

1. If there are 0 documents and 0 auto matching items the classifier actually shouldn't exist, so show that as 'OK'
2. Change the logging language to better communicate whats happening.
3. Screenshot 2024-03-05 at 12 11 27 AM

Closes #6007

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [x] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by gothicVI** [comment]
I'm seeing the same issue as described here: https://github.com/paperless-ngx/paperless-ngx/issues/6007

Would it be possible to show the pending tasks maybe?

When I start using `docker compose up` after pulling the logs shows that the update is in the queue:
```bash
webserver-1  | [2024-03-05 15:24:32,830] [INFO] [celery.beat] beat: Starting...
webserver-1  |  
webserver-1  |  -------------- celery@7abc0b90fa2a v5.3.6 (emerald-rush)
webserver-1  | --- ***** ----- 
webserver-1  | -- ******* ---- Linux-6.7.4-2-MANJARO-x86_64-with-glibc2.36 2024-03-05 15:24:32
webserver-1  | - *** --- * --- 
webserver-1  | - ** ---------- [config]
webserver-1  | - ** ---------- .> app:         paperless:0x7ce196eca8d0
webserver-1  | - ** ---------- .> transport:   redis://broker:6379//
webserver-1  | - ** ---------- .> results:     
webserver-1  | - *** --- * --- .> concurrency: 1 (prefork)
webserver-1  | -- ******* ---- .> task events: ON
webserver-1  | --- ***** ----- 
webserver-1  |  -------------- [queues]
webserver-1  |                 .> celery           exchange=celery(direct) key=celery
webserver-1  |                 
webserver-1  | 
webserver-1  | [tasks]
webserver-1  |   . documents.tasks.bulk_update_documents
webserver-1  |   . documents.tasks.consume_file
webserver-1  |   . documents.tasks.index_optimize
webserver-1  |   . documents.tasks.sanity_check
webserver-1  |   . documents.tasks.train_classifier
webserver-1  |   . documents.tasks.update_document_archive_file
webserver-1  |   . paperless_mail.mail.apply_mail_action
webserver-1  |   . paperless_mail.mail.error_callback
webserver-1  |   . paperless_mail.tasks.process_mail_accounts
webserver-1  | 
webserver-1  | [2024-03-05 15:24:32,913] [INFO] [celery.worker.consumer.connection] Connected to redis://broker:6379//
webserver-1  | [2024-03-05 15:24:32,920] [INFO] [celery.apps.worker] celery@7abc0b90fa2a ready.
webserver-1  | [2024-03-05 15:24:51,250] [INFO] [paperless.classifier] Classifier version incompatible: sklearn version update, will re-train
webserver-1  | [2024-03-05 15:24:51,257] [ERROR] [paperless.api] System status error loading classifier: Classifier not loaded
webserver-1  | Traceback (most recent call last):
webserver-1  |   File "/usr/src/paperless/src/documents/views.py", line 1625, in get
webserver-1  |     raise Exception("Classifier not loaded")
webserver-1  | Exception: Classifier not loaded
webserver-1  | [2024-03-05 15:24:52,280] [ERROR] [paperless.api] System status error loading classifier: Classifier not loaded
webserver-1  | Traceback (most recent call last):
webserver-1  |   File "/usr/src/paperless/src/documents/views.py", line 1625, in get
webserver-1  |     raise Exception("Classifier not loaded")
webserver-1  | Exception: Classifier not loaded
db-1         | 2024-03-05 14:29:24.130 UTC [27] LOG:  checkpoint starting: time
db-1         | 2024-03-05 14:29:38.975 UTC [27] LOG:  checkpoint complete: wrote 150 buffers (0.9%); 0 WAL file(s) added, 0 removed, 0 recycled; write=14.809 s, sync=0.012 s, total=14.845 s; sync files=120, longest=0.003 s, average=0.001 s; distance=812 kB, estimate=812 kB
webserver-1  | [2024-03-05 15:29:57,814] [ERROR] [paperless.api] System status error loading classifier: Classifier not loaded
webserver-1  | Traceback (most recent call last):
webserver-1  |   File "/usr/src/paperless/src/documents/views.py", line 1625, in get
webserver-1  |     raise Exception("Classifier not loaded")
webserver-1  | Exception: Classifier not loaded
webserver-1  | [2024-03-05 15:29:58,840] [ERROR] [paperless.api] System status error loading classifier: Classifier not loaded
webserver-1  | Traceback (most recent call last):
webserver-1  |   File "/usr/src/paperless/src/documents/views.py", line 1625, in get
webserver-1  |     raise Exception("Classifier not loaded")
webserver-1  | Exception: Classifier not loaded
webserver-1  | [2024-03-05 15:30:00,002] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
webserver-1  | [2024-03-05 15:30:00,009] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[7e3ccdb6-9d77-4106-a3f9-44f031e7aeb1] received
webserver-1  | [2024-03-05 15:30:00,047] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[7e3ccdb6-9d77-4106-a3f9-44f031e7aeb1] succeeded in 0.03695438800014017s: 'No new documents were added.'
webserver-1  | [2024-03-05 15:31:16,309] [ERROR] [paperless.api] System status error loading classifier: Classifier not loaded
webserver-1  | Traceback (most recent call last):
webserver-1  |   File "/usr/src/paperless/src/documents/views.py", line 1625, in get
webserver-1  |     raise Exception("Classifier not loaded")
webserver-1  | Exception: Classifier not loaded
webserver-1  | [2024-03-05 15:31:17,335] [ERROR] [paperless.api] System status error loading classifier: Classifier not loaded
webserver-1  | Traceback (most recent call last):
webserver-1  |   File "/usr/src/paperless/src/documents/views.py", line 1625, in get
webserver-1  |     raise Exception("Classifier not loaded")
webserver-1  | Exception: Classifier not loaded
webserver-1  | [2024-03-05 15:32:30,860] [ERROR] [paperless.api] System status error loading classifier: Classifier not loaded
webserver-1  | Traceback (most recent call last):
webserver-1  |   File "/usr/src/paperless/src/documents/views.py", line 1625, in get
webserver-1  |     raise Exception("Classifier not loaded")
webserver-1  | Exception: Classifier not loaded
webserver-1  | [2024-03-05 15:32:31,883] [ERROR] [paperless.api] System status error loading classifier: Classifier not loaded
webserver-1  | Traceback (most recent call last):
webserver-1  |   File "/usr/src/paperless/src/documents/views.py", line 1625, in get
webserver-1  |     raise Exception("Classifier not loaded")
webserver-1  | Exception: Classifier not loaded
```

Having an overview not only for the pending file operations but for all tasks might be helpful.
Also, you could check if a retraining is pending or in progress and wouldn't need to use "may be pending".

**Comment by shamoon** [comment]
There’s already an entire separate place for viewing tasks. And no, you can’t.

**Comment by gothicVI** [comment]
> There’s already an entire separate place for viewing tasks. And no, you can’t.

Could you point me to it (or the docs) please?

Also, what can I not? I don't get the second part of your reply.

If you can - with this PR - query the queued tasks then you can inform more accurately. That's all I wanted to point out.

**Comment by shamoon** [comment]
It’s at /tasks

> Also, you could check if a retraining is pending or in progress and wouldn't need to use "may be pending".

You can’t do this

**Comment by gothicVI** [comment]
> It’s at /tasks

But that's only the file tasks that I mentioned initially.

I was talking about the other tasks like `train_classifier` that can be seen at startup
```bash
webserver-1  | [tasks]
webserver-1  |   . documents.tasks.bulk_update_documents
webserver-1  |   . documents.tasks.consume_file
webserver-1  |   . documents.tasks.index_optimize
webserver-1  |   . documents.tasks.sanity_check
webserver-1  |   . documents.tasks.train_classifier
webserver-1  |   . documents.tasks.update_document_archive_file
webserver-1  |   . paperless_mail.mail.apply_mail_action
webserver-1  |   . paperless_mail.mail.error_callback
webserver-1  |   . paperless_mail.tasks.process_mail_accounts
```
But I guess that's not possible as you mentioned for some reason. Thanks for the reply though.

**Review by stumpylog — APPROVED** [review]

**Pull request merged**
