### PR TITLE
Add LDAP auth support

### PR DESCRIPTION
**Pull request by bauerj**
This pull request has been imported from jonaswinkler/paperless-ng#1211 and was originally opened by dani on 2021-08-04 21:42:27.

---

I needed LDAP auth to use paperless (which I'm evaluating as a personal document management system), so, I've hacked it. It's pretty basic, only support users (not groups or fancy searches) but should fit most needs. Tested against a samba4 (AD style) directory only, but should work with most directories

### CODE REVIEW

**Comment by shamoon** [comment]
> Just a quick note, maybe a connection to OID / OAUTH provider would make more sense. Given that LDAP isn't state of the art anymore. I'll take a look into the PR the next days.

Yea its a great point. Im not sure how everyone feels, on the one hand LDAP is broadly used and I see a lot of projects supporting both LDAP directly and some form of OAuth (a lot of which connect to LDAP of course). I would say if this PR is good, i.e. works well and doesnt involve a lot of rewriting then we do this now and worry about OAuth whenever someone is ready to take a crack at it, they're not mutually exclusive of course. 

Just my thoughts.

**Comment by Timoms** [comment]
> > Just a quick note, maybe a connection to OID / OAUTH provider would make more sense. Given that LDAP isn't state of the art anymore. I'll take a look into the PR the next days.
> 
> Yea its a great point. Im not sure how everyone feels, on the one hand LDAP is broadly used and I see a lot of projects supporting both LDAP directly and some form of OAuth (a lot of which connect to LDAP of course). I would say if this PR is good, i.e. works well and doesnt involve a lot of rewriting then we do this now and worry about OAuth whenever someone is ready to take a crack at it, they're not mutually exclusive of course.
> 
> Just my thoughts.

Exactly, I'll check the PR with my local AD and review the PR later on.

**Comment by Timoms** [comment]
I can see some problems with the PR:

1. `libsasl2-dev` is missing from the env - needed to compile python-ldap.
2. Need `#PAPERLESS_LDAP_IGNORE_CERT=True` option in config to ignore certificate errors in non-ldaps or unconfigured ldaps scenarios
3. See (2) for another config with `#PAPERLESS_LDAP_CERT=<path>` to allow secure LDAP communication 
4. `django-auth-ldap = "~=3.0.0"` missing in Pipfile

Got the LDAP connection up and running with a local AD user.
Will append the missing parts to the PR later.

**Comment by Timoms** [comment]
#100 created a new branch with advanced features, documentation and group bindings. Closed - will continue working on new one.

**Pull request closed without merging**
