### PR TITLE
Feature: Allow setting backend configuration settings via the UI

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

This PR allows users the configure the settings used by the OCR parser via the UI instead of environment variables.  These will take affect the next time the parser runs, for either consumption or document archive updates (aka "Redo OCR").

As time allows, more settings can be added to the UI, instead of the environment (for example, some consumer settings).  However, any Django setting cannot be changed this way, as those are essentially immutable once `settings.py` is imported.

Still TBD is a cleaner way to let the frontend know what options are allowed for settings, type, that sort of thing.

Closes #3090, #1466, #3287

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
This maybe doesn't include some of the Angular 17 changes needed?  If you have time @shamoon could you try to rebase and resolve the conflicts?

**Comment by shamoon** [comment]
Ok `dev` merged in & resolved!

I think people will find this feature really useful.

**Comment by nimodius** [comment]
This seems very useful to me, thank you for your work! Does the users need to restart his container when changing these settings?

**Comment by bdr99** [comment]
This is a great feature! If a setting is set both in the UI as well as in an environment variable, which will take precedence?

**Comment by stumpylog** [comment]
- No restart is needed to apply the setting.  The next consume will use the updated settings
- The UI set value takes precedence, environment remains for compatibility.

**Review by shamoon — APPROVED** [review]
This is a big one stumpy, nice. Again, I think its a kind of platform we can build upon and bring even more (relevant) settings to the frontend.

I obviously already tested this out, but ya know, LGTM =)

**Comment by cdoepmann** [comment]
Thanks for the useful improvement! I am Thanks for the very useful improvement! I am having some trouble understanding the exact semantics, though. Maybe it’s some kind of unclear presentation, or entirely my own misunderstanding.

I am using paperless-ngx with only default configuration. Deskewing and page rotation are enabled by default according to https://docs.paperless-ngx.com/configuration/. Now, after upgrading, the new UI says that these features are disabled – actually, the same is true for the screenshots that were posted in this PR before. So, are these features active now?

I suspect that there is no change in behavior unless I explicitly reconfigure something through the UI. is this correct? Either way, I think the UI is a bit confusing in this regard. As far as the text input boxes are concerned, it is clear to me that if no text is entered, it doesn’t overwrite anything. For the boolean selectors, however, one cannot differentiate between “not configured” and “disabled”.

Intuitively, I would have expected the UI to either display the currently active setting (which would be “enabled” for deskewing and page rotation, as these are the defaults), or offer some kind of tri-state element so one can differentiate disabled and unconfigured values. Am I missing the point here or would that be a sensible enhancement?

**Comment by shamoon** [comment]
@cdoepmann This is something I realized along the way but never really resolved. The 'answer' is that if you've never changed that toggle its neither setting `false` nor `true`, its just `null`, in other words using the default or whatever other configuration you set. Please open a discussion for it, in general commenting on merged PRs isnt the best way to discuss / track something like that.

**Pull request merged**
