### PR TITLE
Add JPG-merge functionality

### PR DESCRIPTION
**Pull request by g3gg0**
## Proposed change

Having source files in JPEG format prevents later merging.
This change preprocesses JPEG files to PDF and thus makes them mergeable.

Closes #(issue or discussion)

## Type of change

- [x] Bug fix: non-breaking change which fixes an issue.
- [x] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
In an effort to prevent feature creep, we do ask there is an open and up-voted feature request for a feature.  Is there one?

**Comment by g3gg0** [comment]
I could not find a feature request here.
However I can file a bug report - the GUI shows the user he can merge two files, but when clicking merge nothing happens.
The error log reveals (in a cryptic manner) that JPGs cannot get processed.

So to me it looks, as if it was not fully implemented.

grafik

**Comment by stumpylog** [comment]
Feel free to fix that and open a pull request for it.  At this point in time, rotate and merge and PDF only actions, as described in the documentation: https://docs.paperless-ngx.com/usage/#pdf-actions

For merging image files or other operations, please open a feature request first or up vote an existing one.

**Comment by g3gg0** [comment]
"only PDFs" is indeed misleading, because the archive format is PDF anyway, regardless of the source file format.

no worries. i fixed it for myself and just wanted to offer a solution for that issue.

**Pull request closed without merging**
