### PR TITLE
Fix: replace drag drop & clipboard deps with angular cdk

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

While playing with some stuff I ran into a rather nasty bug with drag & drop (macOS Safari only but its kind of a killer): https://github.com/reppners/ngx-drag-drop/issues/155 if anyones curious. I could be wrong, but the fix doesnt seem obvious and I'm a little hesitant to keep the faith the dependency will fix it (doesnt seem very active), so I looked into replacing it which was pretty straightforward using the likely pretty-reliable [Angular CDK](https://material.angular.io/cdk/categories). By using it we get to replace a clipboard dependency too, which is the other commit in the PR.

I tested this on my Mac and ubuntu machine and found it to be really smooth, again it's an Angular-made package so I think it's pretty reliable / stable. A bonus is it works pretty well on mobile too, out of the box. Theres a feature branch if anyone wants to test.

Note, this doesnt change the functionality at all but I do think its a tiny bit nicer now with some animation etc, see video below vs #4252 

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/f5aaac28-9b48-457c-b350-eba5417498a1

Also, kind of amazing:

- https://bundlephobia.com/package/@angular/cdk@16.2.7
vs
- https://bundlephobia.com/package/ngx-drag-drop@16.1.0
- https://bundlephobia.com/package/ngx-clipboard@16.0.0

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by stumpylog — APPROVED** [review]

**Comment by stumpylog** [comment]
One thought about this one, do we still need the patching step and dependency?  Up to you if you have other thoughts about using it somewhere or it doesn't hurt to keep it

**Comment by shamoon** [comment]
Unfortunately we do still need the patch because thats for `ngx-file-drop` i.e. dragging-and-dropping files which is different than what the angular CDK has which is just drag-and-drop html elements. They're different events etc in HTML so I dont think CDK really helps there

**Comment by shamoon** [comment]
But I'll keep an eye on upstream and we can remove that once the change is merged

**Comment by stumpylog** [comment]
Oh, that drag and drop, not the other drag and drop.  This is why I don't do frontend things.

**Comment by shamoon** [comment]
Lol, yea, clear as mud

**Pull request merged**
