### PR TITLE
Chore: Fixing up some minor annoyances

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

Sort of a grab bag of some collected small fixes and improvements to code and styling.

- CI now prints just errors, failures and skips, instead of also printing everything which passed
- Trimmed some of Sphinx related items from the `dev-packages` of the Pipfile
- Trimmed some other tools that I couldn't find referenced or were superseded by `pre-commit`
- Improved determination if a document/mime type is supported
  - It send Django signals and parsed the responses every document
  - Now the support/no support is cached
  - Cache size is unbounded, but memory is minimal unless you're trying every mime type under the sun
  - Caching is OK because the support doesn't change dynamically, it would require a restart
- Removed `get_parser_class` which was only used in tests
- Improved + simplified the parser discover testing
- Moved files which are modified during testing into correct tmp folders instead
- Fixed some flake8 stuff in the tests

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain) - general code improvements

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — APPROVED** [review]
Nice thanks for all these

**Comment by stumpylog** [comment]
Wanted to be sure everything was good.  Tested out the grab bag of samples and everything I expected to was consumed still.

**Comment by shamoon** [comment]
Yea I didnt notice any issues running this locally

**Comment by shamoon** [comment]
Hey @stumpylog I can no longer run this on python 3.8, getting `cannot import name 'cache' from 'functools'`, [looking around a bit](https://stackoverflow.com/questions/66846743/importerror-cannot-import-name-cache-from-functools) looks like `cache` isnt in 3.8. 

I dont understand why the tests are passing, unless maybe its just me / Im missing something?

**Comment by stumpylog** [comment]
That's quite curious.  I'll look today

**Pull request merged**
