### PR TITLE
Feature use env vars in pre post scripts

### PR DESCRIPTION
**Pull request by ziprandom**
## Proposed change

This PR changes the pre- and post-consumption script invokation to not use positional script arguments but named environment variables. 

It also adds the documents relevant dates: `added`, `created` and `modified` to complete the available metadata provided to the post-consumption script 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

scripts that used the positional arguments will have to be changed, see the diff for the provided example script

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
I do see the advantages to using the environment. It allows more cars to be added without needing any script changes. But as is, this is very breaking.  My 2 cents would be keeping the args still, also using the environment and adding docs/warning of impending deprecation of arguments

**Comment by ziprandom** [comment]
Hello & thanks for your replies! 

I would call it best or better practices to use environment variables in scripts like this. One example are gitlab pipeline scripts that will be called with a big fleet of available variables. as it stands the two hooks get very little information, and my initial starting point was, that i needed the documents extracted date because I want to update the pdf files own metadata with it.. 

Also like I stated in the commit message, the python code becomes much more readable. Calling a function with 8+ arguments makes it easy to confuse their positions. 

I totally understand that breaking peoples workflow is a big drawback here and  maybe @tribut is right and we should keep positional arguments for backwards compatibility. 

I think the simplification this leads to in  example script shows clearly how this makes writing shell hooks more convenient. 

Anyways, as I use nix I have absolutely no problem with carrying this patch around manually for myself, I just thought I´d do the right thing and offer it to you, because this project is amazing!

**Comment by stumpylog** [comment]
What do we think of the following:

- Keep the args for now, so as to not break existing scripts
- Update docs/examples to use environment
- New and future args go into environment
- Maybe a warning to the effect "Using args to scripts is deprecated, please update to environment"
- At some point, remove the args, once people have probably changed over (technically as a v2 I guess)

**Review by stumpylog — APPROVED** [review]
I've re-added the arguments so existing scripts will continue to work and the changes look good to me.

**Pull request merged**
