### PR TITLE
Feature: Switches to a new client to handle communication with Gotenberg

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

I figured there was a better way to handle talking with Gotenberg for the PDF generation and reduce the amount of work handled here.  Plus, I got to make another simple client, with a pretty cool way to configure and run the generate or merge (if I do say so myself).

This also fixes a small bug where emails with HTML content might not have the right PDF/A format from the generation.  Weirdly, this changed the whitespacce of the resulting PDF, but it looks the same anyway.  Tabs became 4 spaces.

The resulting output PDFs look the same to me with the sample files.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
I'll have to have a look at the coverage.  That doesn't seem quite right, but...

**Comment by stumpylog** [comment]
I think coverage is just confused.  I don't see any extra lines not hit in Tika and the patch coverage in that file is 100% anyway

**Review by shamoon — APPROVED** [review]
Cant comment on the code changes much, testing this out though I didnt notice any problems.

The spacing thing is a bit odd, but seems inconsequential?

**Comment by stumpylog** [comment]
I did some double checking about the whitespace changes, just using cURL.  For whatever reason, though the text looks identical, the extracted text when PDF/A is requested differs from the non-PDF/A format.  So it's just something with Gotenberg's tools

**Pull request merged**
