### PR TITLE
Fix: give superuser full doc perms

### LINKED ISSUE #2812: [BUG] Unable to edit permissions as super user on documents owned by other users
Issue:

1. Create a super user
2. Create another user
3. Add docs while logged in as the super user (owner=super user)
4. Using bulk edit (or i assume just editing details works too), set owner to the other user.

Observed Behavior:

Currently logged in super user is no longer able to edit the document (and reset owner for example)

Expected behavior:

Super user should be able to edit all permissions (?)

Notes:

This is what I'd expect. My closest comparison is the super user on unix, who is also allowed to do almost anything, pretty much.

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Screenshot demonstrates a superuser (me) editing someone else's doc permissions

Screenshot 2023-03-03 at 7 50 02 PM

Fixes #2812

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by jonaswinkler** [comment]
Not sure if its related, but:

1. Open a document that doesn't belong to you
2. Go to permissions tab, assign yourself as the owner
3. Go to details tab, edit document title
4. Hit save
5. Observe popup dialog "You have unsaved changes, do you want to close this document?"

**Comment by shamoon** [comment]
Hmm, I can't reproduce that issue, let me know if you still can. See video (my account is superuser in the video)

https://user-images.githubusercontent.com/4887959/223175373-b7739211-d25d-4e33-96a2-b844a9c74f9c.mov

**Review by stumpylog — APPROVED** [review]
Test it out and it looks good to me.  Makes sense to have a super user have all the access.  Kind of in the name.

Couldn't reproduce the above saving scenario.

**Comment by shamoon** [comment]
Cool thanks. Yea this one is pretty straightforward. I don't think that saving thing would be related, if it's reproducible we can address separately of course.

**Pull request merged**
