### PR TITLE
Refector: Do the npm compile as a Build step in docker

### PR DESCRIPTION
**Pull request by bauerj**
This pull request has been imported from jonaswinkler/paperless-ng#1150 and was originally opened by toxix on 2021-07-03 22:18:57.

---

This removes the requirement of npm on the host system and removes an
additional manual step during the building of the docker image.

Updated the documentation accordingly and fixed a typo.

### CODE REVIEW

**Comment by qcasey** [comment]
This is very interesting. I was able to build and bring up the docker containers OK.

Unfortunately following the steps in [extending.rst](https://github.com/paperless-ngx/paperless-ngx/blob/ba30247933d529e24bdf71c3a6544455ffc5d44c/docs/extending.rst#initial-setup-and-first-start) no longer works because there isn't a `node_modules` directory.

@toxix, if you're still interested in this PR, could you please rebase on our current `dev` branch (to run against CI tests)?

I suspect `extending.rst` just needs an `npm install`.

**Review by sbrunner — APPROVED** [review]

**Comment by Tockra** [comment]
What is the current state here. I would love to see this fix.

**Comment by stumpylog** [comment]
I can't claim to be an expert with Ansible either, but it looks like `ansible/meta/main.yml` needs some editing.   See the Ansible docs [here](https://galaxy.ansible.com/docs/contributing/creating_role.html#role-metadata).

Specifically, I think setting `role_name: paperless-ngx` would at least get the process further.  Ending up with an Ansible FQN of `C0nsultant.paperless-ngx`.

 However, looking at the Ansible, there are a lot of references to `paperless-ng` links still.  That's a future clean up work though.

**Comment by qcasey** [comment]
Ansible was removed in #109 (and then moved to https://github.com/paperless-ngx/paperless-ngx-ansible). If anyone is wanting to maintain that it can be done over there.

I think rebasing on dev would fix the tests and merge conflicts :)

**Comment by stumpylog** [comment]
As I just discovered when I started looking deeper.  Correct me if I'm wrong, but I don't think this exact pull request will be re-baseable by any of us, right?  It would require toxix:multistep-build to rebase?

**Comment by qcasey** [comment]
Yes ideally that's what would happen, it's an important PR though so depending on the time frame we can look at other options.

**Comment by bauerj** [comment]
Closed in favour of #161 (thanks @stumpylog!)

**Pull request closed without merging**
