### PR TITLE
Fix dependency conflicts, broken frontend build

### PR DESCRIPTION
**Pull request by shamoon**
As discussed in chat, *hopefully* this fixes current issues on `dev`

Has been tested by @qcasey and myself , would be good to have others

### CODE REVIEW

**Comment by azapater** [comment]
Everything seems to work fine for me. 

Getting a warning if I use the compile-frontend.sh to generate a production version. That's not related with this PR, but the migration to Angular 13 I think. I will open an issue.

**Comment by shamoon** [comment]
Awesome @azapater , I added one more from dependabot, mind testing and if its still all good please "review" and I will merge, thanks!

**Comment by azapater** [comment]
Tests done. The bump to Angular 13.2.5 seems to work fine. I've noticed a couple UI/CSS issues (nothing concerning) but I'm pretty sure they are related with the the major migration to Angular 13. I will open a couple issues in more detail. 

About the review, I used to be part of the frontend team, but I just noticed that I've been removed, sorry. Not sure if @qcasey  could add me again as member or just simply review this PR :-)

**Review by qcasey — APPROVED** [review]

**Comment by qcasey** [comment]
> Not sure if @qcasey could add me again as member or just simply review this PR :-)

I will happily do both!

**Pull request merged**
