### PR TITLE
enhancement: Hide sort fields if the user does not have the right permissions

### PR DESCRIPTION
**Pull request by theomega**
## Proposed change
Idea is to hide the fields from the Sort Dropdown in the Document View if the user does not have the permissions to see the fields anyway. This also includes hiding the "Notes" sorting option if the Notes functionality is disabled.

Additionally, this PR also hides the "Owner" column in the document list if the user does not have the permissions to see Users. Previously, this column was "Shared" for all documents (independent of owner) which was not super helpful information.

Screenshot of the most extreme case where a user does not have any of the checked permissions:

Screenshot 2024-04-19 at 12 18 10

## Type of change
- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:
- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks for the PR. Im going to close this because it needs to be re-thought and it conflicts with #6439 (which isnt merged yet).

The biggest issue here is that youre re-generating the list every time (as opposed to before it was a const) which means that the object isnt immutable which means Angular change detection will run too often.

I'd be happy to put this idea into that PR or if you'd like to wait until thats in that'd be fine, dont want to 'steal your thunder'. Let me know your thoughts.

**Comment by shamoon** [comment]
Ps. It wouldn't much to change, by the way, all you would need to do would be instantiate the object upon first creation and not every time the method is called. Id prefer you use getters too.

**Comment by theomega** [comment]
Lets wait for your stuff to be merged, not urgent from my side.

**Comment by shamoon** [comment]
Would you mind if I just include it in there? Its a small change and would be logical to go in to that PR

**Comment by theomega** [comment]
Sure, go ahead, I don't think you need to ask for permission :-D

Let me know if the PR is ready to be tested, I'm happy to check out the branch and check what is working and what not....

**Comment by shamoon** [comment]
Ha, just trying not to be a jerk. Thanks. Yea all PRs are welcome for testing

**Pull request closed without merging**
