### PR TITLE
Fix: permissions display should not show users with inherited permissions & unable to change owner

### LINKED ISSUE #2809: [BUG] Changing of owner is inconsistent between document details and bulk edit
Issue:

* I've observed that my second user (who is not a super user but has all global permissions), can select other owners in the document details, but then cannot save the document. The save button is greyed out.
* If a user is not allowed to change the owner (this is what I assume is happening here), then the owner field should be read only.
* However, I am able to clear the owner field, and save the document.

However:

* Changing the owner as this second non-super user is possible via bulk edit.

Notes:

* I'm not sure what the expected behavior is.
* I'd assume that changing ownership should be reserved for super users. Normal users should not have this option?

### LINKED ISSUE #2810: [BUG] Display of View and Edit permissions problem
Issue:

I have a group, and two users in that group. Assigning just edit permissions to the group on a document, and then reopening results in the following:

Image

This is when logged in as "superuser".

* the tag of "superuser" seems messed up.
* Just entering work as the group in edit populates all this data. It is technically correct, when I give edit permissions to a group, then these are the implied permissions (edit for the users of the group, and view permissions for the group and its users). However I wouldn't expect them to show up here, since I did not explicitly configure anything expect editing for the group "work".

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

This PR now corrects a couple things (see linked issues). Most importantly it updates the api / permissions forms to (correctly, and what was expected) only show groups and not the users inheriting object permissions from that group. I think that was causing confusion / problems.

In other words if a user has access only via a group, they no longer show up under "users".

Not being able to change the owner was just because document owner was being used from the current value in the form i.e. the user 'lost' permissions, the location of owner changed in the form.

Fixes #2809 
Fixes #2810

Screenshot 2023-03-17 at 8 55 19 PM

https://user-images.githubusercontent.com/4887959/222873409-b2d47271-8e1f-4b3b-b2b3-c9016ea1bc00.mov

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by jonaswinkler** [comment]
Well yes, saving now works, but still has some kinks,

* Be a user "normaluser" without superuser rights, who owns a document.
* Edit that document and assign it to someone else, so that "normaluser" looses view and edit permissions on this document.
* Save the document
* Observe red error popup with 404 error:

image

**Review by jonaswinkler — DISMISSED** [review]
Well yes, saving now works, but still has some kinks,

* Be a user "normaluser" without superuser rights, who owns a document.
* Edit that document and assign it to someone else, so that "normaluser" looses view and edit permissions on this document.
* Save the document
* Observe red error popup with 404 error:

image

**Comment by shamoon** [comment]
Ah, yes. This can be handled by checking to see if they no longer have edit perms, see video. Let me know if e.g. you think the message should be more explicit?


https://user-images.githubusercontent.com/4887959/223193976-c82441ed-bb4e-48e5-8b37-d4082d0e281b.mov

**Comment by jonaswinkler** [comment]
I'll check on sunday, I'm not home at the moment.

**Review by stumpylog — APPROVED** [review]
Looks correct.  I only see the group visible when added, not the user in the group or the owner in the user section

**Pull request merged**
