### PR TITLE
Fix: Generate secret key with C locale and increase allowed characters

### LINKED ISSUE #4272: [BUG] Install script fails on macOS because of empty `PAPERLESS_SECRET_KEY`
### Description

I think https://github.com/paperless-ngx/paperless-ngx/discussions/4267 is the same as https://github.com/paperless-ngx/paperless-ngx/discussions/2560 and #4267 (sorry for converting what was correctly a bug report) and the issue is the secret key generation in the install script. 

There's a change in https://github.com/paperless-ngx/paperless-ngx/discussions/3821 but it doesnt fix it for me.

1. Running `LC_CTYPE=C tr -dc 'a-zA-Z0-9' < /dev/urandom 2>/dev/null | head --bytes 64` just gives some weird ouput e.g.:
`��Jz�0���Bc�i�RZ�Y�vl�B��1�r����l4n�B�8e�B��X���TY78�W��6��bs��D%` and I think that leaves PAPERLESS_SECRET_KEY empty ( https://github.com/paperless-ngx/paperless-ngx/discussions/2560#discussioncomment-4821925 https://github.com/paperless-ngx/paperless-ngx/discussions/4267#discussioncomment-7108885 ).
2. Then there's the fact that when the webserver starts with an empty key python does seem to throw `django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.` but nothing is shown in the logs, so its really not obvious.

I tried a hack-y little thing that just falls back if the key is empty:
```
SECRET_KEY = os.getenv(
    "PAPERLESS_SECRET_KEY" if os.getenv("PAPERLESS_SECRET_KEY") is not None else "PAPERLESS_SECRET_KEY_IS_EMPTY",
    "e11fl1oa-*ytql8p)(06fbj4ukrlo+n7k&q5+$1md7i+mge=ee",
)
```
which works but perhaps a better solution exists. Im happy to help test (have an intel Mac I can test with too) but this stuff not in my wheelhouse, or I can PR that little change above.

### Steps to reproduce

1. Run install script on macOS

### Webserver logs

```bash
Look normal, which is confusing
```

### Browser logs

```bash
generic Internal Server Error, which is confusing =)
```

### Paperless-ngx version

1.17.4

### Host OS

macOS (seems to affect at least Apple Silicon 13.5.2 & Intel 12.6.2)

### Installation method

Docker - official image

### Browser

_No response_

### Configuration changes

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

Fixes #4272

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — APPROVED** [review]
No surprise, works great!

`PAPERLESS_SECRET_KEY=5ebf387562b30bfdc98c83453f3ff0da0471b08d22dcdd5255252c53b847bc12`

```
[+] Running 4/4
 ✔ Container paperless-gotenberg-1  Running                                                                                                                                                                                                0.0s
 ✔ Container paperless-broker-1     Running                                                                                                                                                                                                0.0s
 ✔ Container paperless-tika-1       Running                                                                                                                                                                                                0.0s
 ✔ Container paperless-webserver-1  Started
```

😎

**Comment by stumpylog** [comment]
Do we want to enforce a length on the secret key when prompting?

**Comment by shamoon** [comment]
I guess if a long-enough string will break things?

**Comment by stumpylog** [comment]
This new version seemed to work on Macs right?  With the LC_ALL setting vs the old version without?

**Comment by shamoon** [comment]
Actually in this version I get `tr: illegal option -- -`, changing it to `LC_ALL=C tr -dc 'a-zA-Z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' < /dev/urandom | head --bytes 64` (the one you sent me) does work for me

**Comment by stumpylog** [comment]
Other than long options vs short, I think that's equivalent.  `-d` for `--delete` and `-c` for `--complement`.  Does `tr` not recognize those on a mac?

**Comment by jsonn** [comment]
Why not just use Python to do this, e.g.
```
python3 -c 'import os; print(os.urandom(64).hex())'
```
This gives about 512bit of entropy, without any guess work.

**Comment by stumpylog** [comment]
We can't assume a user has Python installed.

**Comment by shamoon** [comment]
Yea it's weird, but seems to be the case. On both my machines:

```sh
% LC_ALL=C tr -dc 'a-zA-Z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' < /dev/urandom | head --bytes 64
[9^U9?:fF|6IH4^F$A"%Fr"<qY(3gX?e?-+9IaOoYt]XI{#&aIicYm=&H1jRI~_e%

% LC_ALL=C tr --delete --complement 'a-zA-Z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' < /dev/urandom | head --bytes 64
tr: illegal option -- -
usage: tr [-Ccsu] string1 string2
       tr [-Ccu] -d string1
       tr [-Ccu] -s string1
       tr [-Ccu] -ds string1 string2
```

**Comment by jsonn** [comment]
Well, if you want to restrict it to POSIX: `od -t x1 -A n -N 32 /dev/urandom | tr -d ' '`

**Comment by stumpylog** [comment]
Alright, lets try this version this.

**Comment by shamoon** [comment]
Yep! This one works for me:
```sh
% LC_ALL=C tr -dc 'a-zA-Z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' < /dev/urandom | head --bytes 64
H";#pWhVRf7J[UqEQs?AH6ZFh8C+}`sg[WM%2`&yM*.oh'fyCkz^|0Z}yu50jFk2%
```

**Pull request merged**
