### PR TITLE
Chore: Updates dependabot to group more dependencies

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

Ideally will reduce the number of PRs it will open in a few days.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain):

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — APPROVED** [review]
nice. yea im loving the group updates (though frontend stuff is still a. lot.)

**Comment by stumpylog** [comment]
Oops, guess changing that made it run

**Comment by shamoon** [comment]
Yea I knew that =)

**Comment by stumpylog** [comment]
Looks like dependabot still can't handle our backend updates anyway.  Different error than when it was failing on scipy.  Ugh

**Pull request merged**
