### PR TITLE
Enhancement: improve validation of custom field values

### LINKED ISSUE #5151: [BUG] Non-http/https URLs erroneously considered invalid
### Description

When entering the value for a custom field of type "link", URLs using a protocol other than http or https do not pass validation. Any URL that conforms to RFC 3986 should be considered valid, whether or not Paperless-ngx recognizes the protocol.

Examples:

      ftp://ftp.is.co.za/rfc/rfc1808.txt
      http://www.ietf.org/rfc/rfc2396.txt
      obsidian://open?vault=Vault&file=fields%2Fai%2Fai
      ldap://[2001:db8::7]/c=GB?objectClass?one
      mailto:John.Doe@example.com
      news:comp.infosystems.www.servers.unix
      tel:+1-816-555-1212
      telnet://192.0.2.16:80/
      urn:oasis:names:specification:docbook:dtd:xml:4.1.2

See https://datatracker.ietf.org/doc/html/rfc3986

### Steps to reproduce

1. Log into the Web UI of a Paperless-ngx instance containing a custom field of type "link" and at least one document.
2. Add the link custom field to the document.
3. In the custom field input, enter any URL using a protocol other than http or https.
4. Observe the entry is rejected with the error "Enter a valid URL"

### Webserver logs

```bash
n/a
```

### Browser logs

_No response_

### Paperless-ngx version

2.2.1

### Host OS

macOS

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

_No response_

### Other

_No response_

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

This is... a little absurd. I welcome any other thoughts, of course. Basically https://docs.djangoproject.com/en/5.0/ref/validators/#urlvalidator seems pretty annoying in that it doesnt allow arbitrary schemes (https://consideratecode.com/2021/03/08/django-urlvalidator-with-scheme-deny-list/ doesnt work either, apparently), so I just used https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

Closes #5151 

## Type of change

- [x] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
What about not attempting to validate the URI/URL at all?  The field becomes a CharField in the backend (with decent length), but is displayed as a link (as it is now) for a user to click?  Or even remains a URLField, which maybe doesn't validate anyway (we added the special handling)?

So if they click and it doesn't go anywhere, it's not valid, but they probably typed/copied it wrong, otherwise the browser probably handles the URI with any registered handler/application.

**Comment by shamoon** [comment]
I obviously don’t feel strongly here, the whole thing is a bit esoteric to me. But I guess it feels weird that we’d allow “$xyz “ with no validation, but yea I also don’t want to obsess. What about something like https://stackoverflow.com/questions/7160737/how-to-validate-a-url-in-python-malformed-or-not ? 

In JavaScript this is way easier (I’m tempted to do it on the frontend only but again I don’t love the no validation)

**Comment by stumpylog** [comment]
I think we could use [urlparse](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlparse) and require a scheme and at least one of netloc or path.  That seems to support most, if not all of the values mentioned in #5151.  It also mentions following [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986.html), which we want.

I can create a custom one for that, probably later today if you want.

**Comment by shamoon** [comment]
Sounds good mate. Want to close this or you can just take it over? Up to you!

**Comment by stumpylog** [comment]
Alright, I went a little bit further than just URL validation

- The short text field now validates length
- The decimal field validates digits and places
- Integer field validates it's getting an integer
- URL field accepts more possible options

Hopefully I covered all these.  See what we think.

**Comment by shamoon** [comment]
You know stumpy, I never know when you're gonna get 'stuck in' on a thing like this but the end result usually pretty great. Appreciate the tests and these work well in testing via frontend too. Awesome work, thanks.

Screenshot 2023-12-29 at 1 47 08 PM
Screenshot 2023-12-29 at 1 47 24 PM

**Review by stumpylog — APPROVED** [review]
Thanks for testing it out in the UI, I'd only done the code testing.  Looks like a much nicer error message now

**Comment by pm64** [comment]
@stumpylog and @shamoon, sincerest thanks for your time and effort, this looks phenomenal. Very excited to explore the new interoperability doors this opens. Greatly appreciate all you guys do.

**Pull request merged**
