### PR TITLE
Fix: Delay consumption after MODIFY inotify events

### PR DESCRIPTION
**Pull request by frozenbrain**
## Proposed change

Fujitsu recently released a firmware update for their iX1600 scanner allowing you to scan directly to a network folder without the need for a PC. Currently Paperless delays consumption after CLOSE_WRITE and MOVED_TO inotify events, however Fujitsu's implementation of network scanning seems to open and close the PDF file multiple times (with a longer open-write-close phase at the end) which causes Paperless to try to consume the file prematurely.

This PR proposes to add the MODIFY event to the list of delaying inotify events.

To better visualize the issue, I've attached two logs of inotifywait during a scan of the same (physical) document. I have PAPERLESS_CONSUMER_INOTIFY_DELAY set to 3 seconds in my Paperless installation. In [before.txt](https://github.com/paperless-ngx/paperless-ngx/files/13400703/before.txt) you can see Paperless trying to read the file (L122) 3 seconds after the last CLOSE_WRITE event (L76) while the scanner is still writing data. In [after.txt](https://github.com/paperless-ngx/paperless-ngx/files/13400702/after.txt) you can see Paperless correctly waiting until the file has been fully written.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [X] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [X] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [X] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [X] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [X] I have made corresponding changes to the documentation as needed.
- [X] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks for the PR. Makes sense to me but I’ll leave this one for the backend folks

**Comment by shamoon** [comment]
Ps. I’d be fine with this going into beta

**Comment by stumpylog** [comment]
Based on the test results, this is adding the file multiple times to the task queue, not just once.

**Comment by frozenbrain** [comment]
I just realized that I ran my local tests in the wrong branch, sorry about that.

Anyways you're right @stumpylog, MODIFY events now add the files to the consumption queue before the file is actually closed which isn't much better (or arguably even worse).

I've modified the PR so that now files waiting to be consumed are removed from the notified_files dict after MODIFY events. This should delay consumption until after the next CLOSE_WRITE event.

**Review by stumpylog — APPROVED** [review]
Looks fine to me now.  I've targeted this to beta instead

**Pull request merged**
