### PR TITLE
Update Angular to version 13

### LINKED ISSUE #60: [Other] Bump Angular from 11 to 13
There are a bunch of improvements and changes from the Angular team. https://github.com/angular/angular/blob/master/CHANGELOG.md

We should keep it up to date. Otherwise, it will be hard in some point of time to update.

### LINKED ISSUE #81: [Other] Get rid of ngx-bootstrap
We have two libraries for using Bootstrap with Angular: `@ng-bootstrap/ng-bootstrap` and `ngx-boostrap`. We should remove `ngx-bootstrap` in favor of the other library.

### PR DESCRIPTION
**Pull request by yschroeder**
As discussed in #60 this PR updates Angular from version 11 to version 13.

This is still WIP. Right now it is at version 12 which seems workable (just clicked a few buttons in the UI, no obvious bugs, no errors in browser console.

Update to Angular 13 will be added. When that is done, this is ready for review.

### CODE REVIEW

**Comment by yschroeder** [comment]
Update to Angular 13 is done. While I was at it I also updated all dependencies. Many of them required an update to work with newer Angular versions. As these were updates to new major versions, we need to check if all of their functionality is still working.

One thing I already noticed: The grey background in modal dialogs renders in front of the actual dialog making it impossible to click anything at all.

If someone is willing to search more such bugs, please add them here.

**Comment by shamoon** [comment]
Cool, thanks. Yes with all these updates there will surely be issues. I would like to be careful about this one, should be tested thoroughly.

**Comment by yschroeder** [comment]
Yes, we need to be very careful.

I made separate commits for everything so it should be easier to bisect when searching for the cause of a bug.

**Comment by shamoon** [comment]
Great thanks. Once a couple other things are sorted out I will circle back to this to get a sense for how challenging it’ll be. Maybe it won’t be too bad! 😅 And yea, worst case it’s put off to future release.

**Comment by FrankStrieter** [comment]
@yschroeder I checked the changed dependencies. Maybe the background issue comes from the bootstrap version that has not been changed. You updated `ngx-bootstrap` but `bootstrap` itself is on `4.5.0`. can you please check this?

**Comment by yschroeder** [comment]
You are right, I missed that `ng-bootstrap@12` requires `bootstrap@5`. And this indeed fixes the background in the modal dialogs.

But we now got other issues:

grafik

I guess the new major version of (ng-)bootstrap changed up a few widgets and we need to update our usage of them.

Regarding `ngx-bootstrap`: I noticed that as well and find it odd. I guess I open an issue to get rid of `ngx-bootstrap` in favor of `ng-boostrap`.

**Comment by shamoon** [comment]
OK should you rebase this to dev and we can test and fix from there?

**Comment by yschroeder** [comment]
Yes, going to rebase. However, this cannot be merged anytime soon. So it would be best to updated crowdin based on the current `dev` branch.

**Comment by shamoon** [comment]
Wow, ok lots of CSS bugs etc but it doesnt look totally broken! I'll start working through this...

**Comment by yschroeder** [comment]
There are more things to fix. Dialogs look a bit broken, here and there stuff it not pixel perfect aligned.

PDF preview is not working.

But we're on the way.

This will need extensive testing and we should be somewhat quick as it will will be a pain to keep up if other frontend stuff is merged in the meantime.

**Comment by shamoon** [comment]
I have a lot done, just hang on

**Comment by yschroeder** [comment]
Wow good job 👍

I'll do some testing later today.

**Comment by shamoon** [comment]
Thanks, I love the pixel-perfect kinda stuff =)

Not done tho, also the pdf viewer 😡

**Comment by shamoon** [comment]
Oh nice, got the pdf viewer sorted. Also funny they released angular-13 compatible version 2 days ago

Ok Im just hunting for things I missed but this should actually be pretty close!

**Comment by yschroeder** [comment]
I clicked around in the interface a bit (hopefully I have seen everything). I didn't notice anything odd.

LGTM.

However, we should have this reviewed by people not involved with the PR :-)

**Comment by yschroeder** [comment]
@Nicarim do you have time to test this? You did a good job on finding the quirks in the new tag filter feature 😀

**Comment by Nicarim** [comment]
If I only find time, but can't promise its today.

**Comment by shamoon** [comment]
Honestly I’m pretty confident in this at this point, we can still hunt the odd bug on `dev` but I think it’s GTG

**Review by shamoon — APPROVED** [review]

**Comment by shamoon** [comment]
Only thing I’m worried about is Crowdin 😅

**Comment by yschroeder** [comment]
You just click that update button again. It will certainly go postal on the id changes...

**Comment by qcasey** [comment]
I imagine we'll be testing dev pretty heavily before release anyway.

**Review by Timoms — APPROVED** [review]

**Pull request merged**
