### PR TITLE
[Beta] Paperless-ngx v1.14.0 Release Candidate 1

### PR DESCRIPTION
**Pull request by shamoon**
Welcome to our latest beta release of Paperless-ngx! This version is one of our biggest yet and includes some new features we've been working hard on including multi-user permissions, barcode scanning improvements, an overhaul to email processing and more. All-told this release contains almost 300 commits from many various contributors.

Thank you to everyone who has contributed, and thank you to the [paperless-ngx team](https://github.com/orgs/paperless-ngx/people) who continue to make Paperless-ngx one of the best community DMS.

## Beta Testing

A new docker container has been built at `ghcr.io/paperless-ngx/paperless-ngx:beta`. A release zip can be found in the [github pre-release](https://github.com/paperless-ngx/paperless-ngx/releases/tag/v1.14.0-beta.rc1) or the [latest CI build](https://github.com/paperless-ngx/paperless-ngx/actions?query=branch%3Abeta).

Please test this beta as best you can and report any bugs by [opening a new issue here](https://github.com/paperless-ngx/paperless-ngx/issues/new?assignees=&labels=bug&milestone=v1.14.0&template=bug-report.yml&title=[BUG]+v1.14.0+RC1+Bug). See the [pre-release changelog](https://github.com/paperless-ngx/paperless-ngx/releases/tag/v1.14.0-beta.rc1) and [closed PRs](https://github.com/paperless-ngx/paperless-ngx/pulls?q=is%3Apr+milestone%3Av1.14+is%3Aclosed), especially ones labeled `non-trival`, to guide your tests.

Please remember to [make a backup](https://docs.paperless-ngx.com/administration/#backup) if you will be running this over a production installation.

Once you have tested thoroughly for a few days and have not found any [more] issues please approve this PR. This is not simply a code review, we prefer hands-on production experience with this beta. The beta will be open for at least 5 days.

Some additional notes:

* The `beta` container is updated as commits are made, see the [actions tab](https://github.com/paperless-ngx/paperless-ngx/actions?query=branch%3Abeta) for progress.
* If bugs are found release candidates will be pushed as necessary.

# Thank you

Finally, if you're reading this, **thank you** for being a part of paperless-ngx! While we are proud to continue to publish new releases, we are even prouder of the collaborative process that makes it possible. Thanks to each and every person who has contributed so far 🙏

### Changes Since Opened
- #3013
- #3020
- #3060
- #3061
- #3062
- #3068 
- #3071
- #3108
- #3109
- #3103
- [Fix multi-select with private items](https://github.com/paperless-ngx/paperless-ngx/commit/87479c32debb64a6ee5281392284a4371e0c5d63)
- #3015
- #3134
- #3135
- #3146

#### Pending:
- #3123

### CODE REVIEW

**Comment by thegodfatherrelish** [comment]
@shamoon First of all, thank you so much for your work, managing my documents with Paperless has made everything so much easier, and multi-user support was what was missing for me to make it work for everyone at home.

But now a technical question about the practical implementation regarding the ASN: Will there be a separate ASN counter for each user? That would make it much easier to divide up the documents and file them separately by person.

**Comment by JigSawFr** [comment]
> @shamoon First of all, thank you so much for your work, managing my documents with Paperless has made everything so much easier, and multi-user support was what was missing for me to make it work for everyone at home.
> 
> But now a technical question about the practical implementation about the ASN: Will there be a separate ASN counter for each user? That would make it much easier to divide up the documents and file them separately by person.

How will you deal for a document assigned for multiple user? For e.g. a bank loan, it is for the two persons, so I assume one will be primary. And ASN will be assigned to this person? Today, I am managing it with tags, and refer to associated ASN if needed, it is working for a document associated with two persons.

**Comment by thegodfatherrelish** [comment]
> How will you deal for a document assigned for multiple user? For e.g. a bank loan, it is for the two persons, so I assume one will be primary. And ASN will be assigned to this person? Today, I am managing it with tags, and refer to associated ASN if needed, it is working for a document associated with two persons.

Yes in that case I have to decide when I pick it up where I want to file it. But if each user has separate ASN counters, then I file user A's documents from 1-100 in the folder for user A and user B's documents from 1-90 in the other folder and I can label that accordingly.

If I only have one counter, then I can only staple all the documents into one folder or I have to guess that user A now has documents 1-22, 24, 27-38 and so on. For shared documents, it would even make sense to have an extra counter, for example based on a group. I have no idea whether and how this can be implemented, hence my question.

**Comment by JigSawFr** [comment]
Like the idea to have multiple counters. Something like:
- Bills (owner: user A, shared: no, ASN: B-0000)
- Home (owner: user A, shared: yes with user B, ASN: H-0000)
Etc.

**Comment by shamoon** [comment]
There is no current implementation of ASN per user, see #1841 or open a new feature request.

**Review by stumpylog — DISMISSED** [review]
Tested with my server and I don't see any problems.  The upgrade went smoothly and consumption worked normally for me.

**Comment by shamoon** [comment]
Funny, I was just going to say the same but then I noticed one tiny frontend regression, its driving me a little bonkers but I'll sort it out and otherwise I do think this is g2g 🤞

**Comment by shamoon** [comment]
Bug squashed, translations merged, PR approved from me 🚀

**Review by stumpylog — DISMISSED** [review]

**Review by stumpylog — DISMISSED** [review]

**Pull request merged**
