### PR TITLE
Provide UTF-8 encoded content-disposition field to address the issues in the firefox when downloading files

### LINKED ISSUE #56: [BUG] Unicode characters are not formatted properly in Content-Disposition field, causes issues in firefox
**Describe the bug**
When the filename of the file that you try to download from paperless contains UTF-8 characters after formatting, firefox will not able to properly format the resulting filename, causing issues when saving and trying to preview it. 

Related issue in original repository https://github.com/jonaswinkler/paperless-ng/issues/838

**To Reproduce**
0. Use Firefox
1. Create a new document in paperless
2. Create correspondent with UTF-8 characters like "Urząd Gorzów Document"
3. Assign the correspondent to the newly created document
4. Attempt to download the file
5. File will be saved as `.pdf` instead of proper name

**Expected behavior**
File should save as `Urząd Gorzów Document.pd`

**Screenshots**
image

**Webserver logs**
There is no error in logs.

**Relevant information**
 - Linux - Manjaro
 - Firefox
 - 96.0.3 (64-bit)
 - Installation method: docker
 - Default configuration

### PR DESCRIPTION
**Pull request by Nicarim**
See the issue [#56](https://github.com/paperless-ngx/paperless-ngx/issues/56) for extensive description of the issue.

What I did was I used a field specified in [RFC 5987](https://datatracker.ietf.org/doc/html/rfc5987#section-4.2) as a guideline on how to encode the fields properly. I used `filename` field and provided ASCII only filename, for any browser that don't support the UTF-8 encoding, and UTF-8 encoded filename (using urlencode) is put into `filename*=utf-8''` field. 

This fixes the issue in the firefox, and retains the same functionality on chromium. Tested under linux on both browsers. 

Requires confirmation on Safari/MacOS, and Edge/Windows.

### CODE REVIEW

**Comment by Nicarim** [comment]
Force-pushed amended commit fix for code style issue.

**Comment by isigmund** [comment]
I did test this fix on Ubuntu/Firefox, Ubuntu/Chromium, Windows/Edge, MacOS/Safari and it worked fine on all platforms/browsres. The correction looks good to me.

**Review by isigmund — APPROVED** [review]
I did test this fix on Ubuntu/Firefox, Ubuntu/Chromium, Windows/Edge, MacOS/Safari and it worked fine on all platforms/browsers. The correction looks good to me

**Comment by Nicarim** [comment]
Ok, fixed, now it's just this change, based on latest `dev` branch

**Comment by qcasey** [comment]
TYVM!

**Pull request merged**
