### PR TITLE
Chore: Exclude dependabot PRs from Project, set status to "Needs Review"

### PR DESCRIPTION
**Pull request by qcasey**
## Proposed change

I expect this change will exclude dependabot PRs from the [Project Board](https://github.com/orgs/paperless-ngx/projects/2). They pollute the "No Priority" section and we never promote them up the board, so those PRs need to be removed by hand each time.

If a dependabot PR needs to be on the board for whatever reason it can still be added from the sidebar. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by qcasey** [comment]
> exclude dependabot PRs from the [Project Board](https://github.com/orgs/paperless-ngx/projects/2)

I just realized that's not exactly what this does. My mistake

**Comment by qcasey** [comment]
Well, it's not super clear. The step's title is `Set PR status to ${{ env.in_progress }}` but the [Action intro](https://github.com/leonsteinhaeuser/project-beta-automations) describes itself as:

> If the issue or pull request is not attached to a project, it is automatically added to the project and its desired column.

So I have circled back to believing this PR does indeed exclude dependabot from ever being added to the Project. If so, updating the step name is in order

**Comment by stumpylog** [comment]
I also think this should exclude dependabot from the project boards.  The step name doesn't encompass all it does, roughly both adding to the project board and setting the status to "In Progress".

Maybe new PRs should be set to "Needs Review" anyway?

**Comment by qcasey** [comment]
> Maybe new PRs should be set to "Needs Review" anyway?

Agreed, I'll make both changes here I suppose

**Comment by qcasey** [comment]
Okay I'm 70% sure that will work

**Review by stumpylog — APPROVED** [review]
Ship it!

**Review by shamoon — APPROVED** [review]

**Comment by stumpylog** [comment]
Whoops, I guess this didn't quiet work: https://github.com/paperless-ngx/paperless-ngx/actions/runs/2853350259/workflow

Probably needs single quotes?  Can it really be that restrictive?

**Pull request merged**
