### PR TITLE
Fix: Make all document related objects soft delete, fix filepath when deleted

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Phew, I think this should do it!

Part of closing #8063

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
The failure seems tricky to solve...

**Comment by shamoon** [comment]
The failure seems tricky to solve...

basically when the document is updated with custom_fields: [] it deletes all the instances, but now they 'soft delete'. gotta figure out where / how that deletion happens and see if it can be overridden to be a hard delete.

I think?

**Comment by stumpylog** [comment]
That may happen in the database  I think at least with some, a cascade is done with triggers.

**Comment by shamoon** [comment]
Aha! LMK thoughts =)

**Review by stumpylog — APPROVED** [review]

**Pull request merged**
