### PR TITLE
Documentation: Add copy-paste list of Python build dependencies

### PR DESCRIPTION
**Pull request by madduck**
## Proposed change

To be consistent, let's provide an easily copy-pastable list of packages even for the final set of build dependencies for the bare-metal route

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [x] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by stumpylog — CHANGES_REQUESTED** [review]
The list isn't really accurate.  It would be better to install setuptools and wheel via `pip`, especially as distributions are often quite behind in versions.

**Comment by madduck** [comment]
I only reflowed the existing content, @shamoon, but I am happy to extend this PR accordingly, if that's alright. It'd have to grow a small section on `virtualenvs`, or do you want to propagate installing those with `pip` system-wide?

For the record, it works with Debian stable ("bookworm") and current `dev`. But I see your point.

**Comment by madduck** [comment]
@stumpylog do you want me to pursue this?

**Comment by stumpylog** [comment]
You're right, this is just the existing.  We can keep it as is, though the section probably needs to be re-visited.

**Comment by stumpylog** [comment]
If you could rebase this, I'll merge it in

**Comment by madduck** [comment]
@stumpylog done. Ready.

**Review by stumpylog — APPROVED** [review]

**Pull request merged**
