### PR TITLE
Update `install-paperless-ngx.sh`

### PR DESCRIPTION
**Pull request by kpj**
This PR updates the quick-install script to use files from this repository.

While doing so I noticed that running
```bash
curl -L https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/master/install-paperless-ng.sh | bash
```
(which is recommended in the docs) leads to all `read` instructions being skipped and the script breaking.
I tried this on Archlinux.

The alternative
```bash
bash -c "$(curl -L https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/master/install-paperless-ng.sh)"
```
works just fine.

Can anyone reproduce this issue or have an idea what the cause might be?

### CODE REVIEW

**Review by qcasey — DISMISSED** [review]

**Comment by qcasey** [comment]
The curl pipe to bash did not work for me either. Tried on both arch and ubuntu with the same breaking result. I think [this is the reason:](https://stackoverflow.com/a/16854263)

> With the pipe, the read reads from standard input (the pipe), but the shell already read all the standard input so there isn't anything for the read to read.

`bash -c` works great instead.

**Comment by qcasey** [comment]
Could you please rebase this onto `dev`? It was my understanding that even doc updates are going there until the first release.

**Comment by isigmund** [comment]
I recently merged #33 into dev wich already takes care of removing the pipe and replaces it with an input redirection. But #33 did not refer to the nix repo yet. So after rebasing this to dev you will probably run into a manual merge situation

**Comment by kpj** [comment]
Thanks for the information!

Once the rebased PR is approved I'll merge it into dev and resolve all conflicts.

**Review by qcasey — APPROVED** [review]

**Comment by kpj** [comment]
Closed by #77

**Pull request closed without merging**
