### PR TITLE
Feature: Bake NLTK into Docker image

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

This changes the downloading on the NLTK data at startup into a downloading at image build time.  Initially, I didn't do this as I wasn't sure about how much it adds to the size.  It's actually around 60mb to the compressed image, so fairly small in the end.  NLTK usage can still be enabled or disabled if a user doesn't want to use it.

This will also resolve user's being unable to download the files at startup, either due to (so many) DNS issues or working in a completely offline environment.

Finally, it fixes the missing documentation on the enable/disable as well as location of data.

See #2061

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Nice this is a good idea, I agree seems like a small increase and well worth it after learning how many folks keep their installs in a faraday cage :)

**Review by shamoon — APPROVED** [review]
It works =)
```
/usr/src/paperless/src# ls /usr/local/share/nltk_data
corpora  stemmers  tokenizers
```

I guess this orphans anything at `/usr/src/paperless/data/nltk`, but nbd

**Comment by stumpylog** [comment]
Hm, that's a good point, but I wouldn't want to remove it, as someone could choose to use it.  I'll document it I think.

**Comment by panther-sh** [comment]
I think NTLK data integration into the image is a good way to go. I spent two hours trying to resolve my web server container startup issue after updating from 1.9.2 > 1.10.2 (the container is isolated from the internet).

**Pull request merged**
