### PR TITLE
extend the backup mechanism during updates

### PR DESCRIPTION
**Pull request by bauerj**
This pull request has been imported from jonaswinkler/paperless-ng#1058 and was originally opened by muued on 2021-05-24 20:15:35.

---

make it optional (enabled by default).
only include relevant application parts.
exclude docs, consumption, media.
compress the backup.

### CODE REVIEW

**Comment by qcasey** [comment]
Ansible was removed in #109, this can be reconsidered in https://github.com/paperless-ngx/paperless-ngx-ansible/issues/1

**Comment by muued** [comment]
Hi there, thanks for your great work continuing the paperless-ng project.
The [link provided above](https://github.com/paperless-ngx/paperless-ngx-ansible/issues/1) does not lead me anywhere.
Is that a permission issue or has the repo been deleted since you posted?

**Comment by shamoon** [comment]
Od
d, your link is to -ng but link posted was for ngx, e.g. should be https://github.com/paperless-ngx/paperless-ngx-ansible/

**Comment by muued** [comment]
That link doesn't work for me either, so I guess it is a permission thing - I assume the repo is only visible to the paperless-ngx organisation.

**Comment by qcasey** [comment]
> That link doesn't work for me either, so I guess it is a permission thing - I assume the repo is only visible to the paperless-ngx organisation.

Oops, that's exactly why. I just made it public. Sorry about that.

**Pull request closed without merging**
