### PR TITLE
Update .env

### LINKED ISSUE #97: [Other] Add prompt to env file for better visibility of pipenv
Just a quick QoL change for developing - and an issue to reference a PR.

If we append `export PROMPT="(pipenv-projectname)$P$G"` to the .env file we can get an indicator that we are in the pipenv. 

image

### PR DESCRIPTION
**Pull request by Timoms**
Added visual indicator that pipenv is active as mentioned in #97

### CODE REVIEW

**Comment by yschroeder** [comment]
This does not work for me. If I do `pipenv shell` my prompt looks like before. I am using zsh with [GRML config](https://grml.org/zsh/) which already heavily mods my prompt.

It works in a plain bash though.

So I guess LGTM.

**Comment by Timoms** [comment]
> 

So it doesn't mess up your current config but improves the "normal" bash one, right? 
Don't want this PR to mess with other configs but improve default ones.

I am a WSL2/Ubuntu user with some minimal mods to the bashrc - and it makes quite the difference.

**Comment by tribut** [comment]
This looks harmless enough, but is feels like this belongs to pipenv, not every project using it.

Indeed, pipenv includes code that should be doing exactly the same thing: https://github.com/pypa/pipenv/blob/main/pipenv/shells.py#L91-L94

Just found this upstream issue - apparently it's a pipenv/powershell bug? https://github.com/pypa/pipenv/issues/3505

**Comment by Timoms** [comment]
> This looks harmless enough, but is feels like this belongs to pipenv, not every project using it.
> 
> Indeed, pipenv includes code that should be doing exactly the same thing: https://github.com/pypa/pipenv/blob/main/pipenv/shells.py#L91-L94
> 
> Just found this upstream issue - apparently it's a pipenv/powershell bug? [pypa/pipenv#3505](https://github.com/pypa/pipenv/issues/3505)

Seems like the issue is around since 2018 and got only fixed for cmd recently.
I am not sure if pipenv fixes this in the near future (since the mentioned issue is around like 2 years now).

**Comment by tribut** [comment]
If you change doesn't duplicate the prompt for systems where it currently works (if any), sure. We can remove it later once it works.

**Review by bauerj — APPROVED** [review]

**Pull request merged**
