### PR TITLE
Feature: app branding

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Uses the new app config

Screenshot 2024-01-11 at 10 51 58 PM
Screenshot 2024-01-12 at 2 32 36 AM
Screenshot 2024-01-12 at 8 48 10 AM

Closes #1428

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Just made a couple teaks:

- ability to remove a logo if set (not just replace)
- make changing the title also change the window title

**Review by stumpylog — APPROVED** [review]
Didn't notice any issues.  Fancy how the title pops up right away

**Comment by tmaier** [comment]
Thank you! ❤️

**Comment by shamoon** [comment]
> Thank you! ❤️

Welcome ☺️

**Pull request merged**
