### PR TITLE
Feature: add redis sentinel support

### PR DESCRIPTION
**Pull request by ajgon**
## Proposed change

This PR adds support for Redis Sentinel, which enables paperless to be deployed in High-Availability environments (like kubernetes). It should be backwards compatible with current redis uri schemas.

P.S. I'm not a python developer, so I couldn't set up working environment to run tests ~~and pre-commit hooks~~, I'm relying on github actions, that PR is fine. Is it possible to build dev env via docker somehow?

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by sbrunner** [comment]
Doesn't it only use the master?
I don't see where the slaves are used...

**Comment by stumpylog** [comment]
I'll need to do some research on what a Redis Sentinel is to really review.  

One major thing though, for our next release (hopefully), there is some in progress work to switch from `django-q` to `celery`, as `django-q` is sadly no longer maintained (and the team doesn't always have the time or understanding to take it over fully and fix issues in it).  So it might be very benefical to read on how celery handles Sentinel configuration/setup.

**Comment by ajgon** [comment]
> Doesn't it only use the master? I don't see where the slaves are used...

Actually I was relying on the fact, that in kubernetes all sentinels are hidden behind load balancer, so at the end of the day, there is one URL to point to. But I agree, specifying multiple sentinels should also be possible. Question is - how to properly pass them in `PAPERLESS_REDIS`. From what I understand, in celery, they solve this, by coma separated list of sentinels:
```python
app.conf.broker_url = 'sentinel://localhost:26379;sentinel://localhost:26380;sentinel://localhost:26381'
```
so maybe that's the path which I should follow... It won't require the changes in future, when django-q gets dropped.

**Comment by ajgon** [comment]
I adapted `PAPERLESS_REDIS` to support semicolon-separated sentinel uris, and introduce new `PAPERLESS_REDIS_SENTINEL` variable, to configure extra connection/sentinel kwargs.

Currently I'm running the changes in my cluster, and they seem to be working :)

**Comment by ajgon** [comment]
Drat, tested it some more, and unfortunatelly it won't work... yet. Turns out, sentinel authentication is not supported in `channels_redis` at the moment. I was basing my code on [these docs](https://github.com/django/channels_redis#hosts), which are for upcoming `4.0` version. 

So this is blocked until they release proper sentinel support :/

**Comment by ajgon** [comment]
I've spend whole day on this, getting deeper, and deeper in the rabbit hole... and it looks like, it may need multiple python libs to be updated. I filed issue on [channels_redis](https://github.com/django/channels_redis/issues/331) and [redis-py](https://github.com/redis/redis-py/issues/2406), to see if this can be resolved, but at the moment this can be labeled as blocked :(

**Comment by shamoon** [comment]
Its been a while without any movement here. @ajgon if youre interested in completing this please do re-open, Im just closing to keep things tidy. Thanks for your contribution

**Pull request closed without merging**
