### PR TITLE
Improved webmanifest to make better use of theming capabilites in modern (mobile) browsers

### PR DESCRIPTION
**Pull request by LeoKlaus**
## Proposed change

This applies the theme color to the address/status bar on mobile browsers and when using Paperless as a PWA. 
safari-pinned-tab.svg is used in Safari on Mac as that browser doesn't use favicons.

Fixes # (I didn't create an issue for this)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks, except the app now lets you change the theme color, so what happens for users who have changed it if its hardcoded here?

**Comment by LeoKlaus** [comment]
Good call, didn't see that. I'd have to implement dynamic generation of the manifest. The current version also has a static reference to the theme color in index.html. Should I open an issue?

**Comment by shamoon** [comment]
I mean sure, suppose its kind of a feature request. This doesnt even support dark mode at the moment either. Up to you if you want to update this PR or what, its pretty lame none of these support variables. The meta tag is straightforward and I would probably just leave out the manifest one for now.

**Comment by LeoKlaus** [comment]
> its pretty lame none of these support variables.

Yeah, it's weird. The manifest doesn't have to be a file though, it could also be an api or something like a blob.
I'll see what I can do to make it happen. I'll close this PR and open a new one if need be.

**Pull request closed without merging**
