### PR TITLE
Fix: frontend handle "private" tags, doctypes, correspondents

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

_Draft for now:_ This didn't come up in the original PR so this is a possible way to handle viewing a document where the current user doesn't have access to all the attached objects e.g. tags etc. This implementation is handled by the frontend, retaining the object by ID but displaying "Private" ("Hidden", "Not Shared"?) for the name. Screenshot below. I could also imagine this being handled in the backend such that the private objects are returned but with their name replaced or something like that.

Of course alternatives include changing how this works overall but this makes sense to me. Im not sure how frequent this will come up in real-world use especially on a newly-setup install where objects are owned from the start.

Screenshot 2023-03-06 at 4 29 13 PM

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
I know it's probably more work, but I feel like a "private" tag/type/etc shouldn't leave the backend.  It feels leaky otherwise.

**Comment by shamoon** [comment]
> I know it's probably more work, but I feel like a "private" tag/type/etc shouldn't leave the backend. It feels leaky otherwise.

At the moment all that's returned from the backend is the ID of the object, even that you mean?

**Comment by stumpylog** [comment]
Ah, so the frontend only gets the id, and would need to query the backend for the name?  The id only seems ok.  I was thinking the name shouldn't be visible in the response from the backend anywhere

**Comment by shamoon** [comment]
Yea exactly, currently the frontend gets the id, that way you don't remove a private tag / correspondent / whatev but if it's not shared the frontend doesn't get anything else e.g. name, color etc. That's what this PR does, it handles that situation by just using the word "Private" instead of the tag name, correspondent, etc

E.g. a document would return
```
...
tags: [1 ,2, 3]
...
```

but if tag 3 isn't shared with the current user their calls to /api/tags/ don't return tag id 3 _at all_

**Comment by stumpylog** [comment]
Ok, cool.  I'm in agreement with the `Private` value displaying.

**Pull request merged**
