### PR TITLE
Add option to merge multiple files into single PDF when bulk downloading

### PR DESCRIPTION
**Pull request by czyzlukasz**
## Proposed change
I'm using paperless-ngx for document sorting and periodic reports generation. Currently, the workflow requires from the user to select documents, download them as zipped collection, unpacking them and manually merging them in external file. I propose adding an option to automatically create single PDF when downloading multiple documents.

Changes in the front-end:

- Following checkbox in bulk download component: image
- Document IDs passed to **BulkDownloadView** are now passed in the same order as displayed to the user (useful when user wants the documents in a specific order)

Changes in the back-end:

- **BulkDownloadView**: Selection between **ZipFile** and new **MergedPdfFile** as writer
- Parsers: Added **merge_pdfs** method that uses already available ghostscript binary
 
Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Thank you for the PR.

I have to ask, respectfully, does anyone want this besides you? That’s why we usually use feature requests as the basis for new features. I understand the purpose but I wonder if the use case is a little narrow

**Comment by czyzlukasz** [comment]
I agree that this feature may not be used by everyone, but I found that this topic was mentioned in some issues (#367, #502, paperless-ng [335](https://github.com/jonaswinkler/paperless-ng/issues/335), [426](https://github.com/jonaswinkler/paperless-ng/issues/426) and [789](https://github.com/jonaswinkler/paperless-ng/pull/789)). I'm aware that document processing isn't something that paperless-ngx promises to deliver but I hope some users would find that useful.
They are other features that were mentioned in these issues, like rotate or document split. Let me know if that's something worth creating pull requests - I'd love to see these options in paperless-ngx ;)

**Comment by shamoon** [comment]
Yes I’m familiar with those ones but I think those requests are talking about the document in paperless, not just at download time? In other words, I’m not sure this would really satisfy those FRs

**Comment by stumpylog** [comment]
I have to agree that this PR doesn't seem to fit the feature requests.  From what I see, those are requesting to be able to split and merge _within_ paperless, not during the download process.  I would make a feature request and see if there is support for the feature.  This PR can always be revisited.

**Pull request closed without merging**
