### PR TITLE
Extent upload widget to merge input files

### PR DESCRIPTION
**Pull request by mpflanzer**
## Proposed change

This extends the upload functionality to merge multiple input files into a single PDF before it's being processed as new document.

On the front end the upload file widget is extend with a second file drop field. Instead of uploading document directly this one waits so that multiple files can be selected (staged), reordered, removed again (unstaged) before the upload is triggered. Optionally a filename can be provided as well.

The backend checks if multiple documents have been provided in the `post_document` POST request. If that is the case the files are fed into `img2pdf` to merge them into a single PDF which is then treated as the document and processed as usual.

image

Except for checking that both kinds of file uploads are still working I haven't performed any tests. If this feature is something considered to be merged I would be happy if someone else could take care of all the validation steps below. As I'm not really a web developer and not too familiar with paperless it would cost me quite some effort to do all of this.

Potentially an improvement with respect to https://github.com/paperless-ngx/paperless-ngx/discussions/367

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [X] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks for the PR. This is an interesting idea but as you note this is not ready to be merged so Im going to mark it as a draft.

A few things:

- [ ] Instead of two completely separate boxes, I would prefer a toggle or something like that to use merge upload mode.
- [ ] The backend changes do need testing. (frontend testing is coming soon too...) 
- [ ] There are some code issues but I think I'll hold off on full review for now

Also, we do not use Angular CDK at all and Im not sure how I feel about mixing it in now. We use bootstrap for most components, others are implemented natively. I did note these components have minimal styling and obviously its pretty nice to just get the features out-of-the-box.

**Comment by mpflanzer** [comment]
> Thanks for the PR. This is an interesting idea but as you note this is not ready to be merged so Im going to mark it as a draft.

Thanks for the quick feedback.

> A few things:
> 
> * [ ]  Instead of two completely separate boxes, I would prefer a toggle or something like that to use merge upload mode.
> * [ ]  The backend changes do need testing. (frontend testing is coming soon too...)
> * [ ]  There are some code issues but I think I'll hold off on full review for now

Using a switch or similar to toggle the behaviour should not be a problem. I just thought I keep the original behaviour as it is to avoid an additional button press etc. If you have improvement suggestions for the code I'd be happy to hear even if it's not a full review. I haven't worked with neither Angular nor Django before so I'm not surprised there might be a few things that can be improved.

> Also, we do not use Angular CDK at all and Im not sure how I feel about mixing it in now. We use bootstrap for most components, others are implemented natively. I did note these components have minimal styling and obviously its pretty nice to just get the features out-of-the-box.

The drag and drop was a last minute addition when I spotted that Angular offers it practically for free. Not a must have if you prefer not add the dependency to CDK.

> Is there a reason you are using img2pdf and not qpdf?

No, particular reason. OCRmyPDF suggests to use it [1] so I picked it up. If qpdf can do the same and you prefer that I don't mind switching.

[1] https://ocrmypdf.readthedocs.io/en/latest/cookbook.html#option-use-img2pdf

**Comment by shamoon** [comment]
Please reopen if/when you are able to address the above. Thanks for the PR

**Comment by mpflanzer** [comment]
I found a bit of time over the last days and reworked the first draft to have a toggle switch instead of two boxes. The upload without merging is now also not immediately happening on drag and drop or file selection but also requires the user to press the upload button. The "merge" switch can only be toggled if there is more than one file and only if the button is toggle the filename input field appears.

image
image

The Angular "UploadFileWidgetComponent › should support drop files" test obviously fails at the moment since I changed the behaviour. Also I get the following failure but have no idea what's wrong. I followed all the steps in the development guide to set up my environment:

```
 FAIL  src/app/services/consumer-status.service.spec.ts
  ● Test suite failed to run

    src/app/services/consumer-status.service.spec.ts:14:16 - error TS2307: Cannot find module 'jest-websocket-mock' or its corresponding type declarations.

    14 import WS from 'jest-websocket-mock'
```

All of the playwright tests are passing. FYI, the instructions are missing the `npx playwright install` command. But npx is giving that information if you just run the test command. ;-)

`pytest` fails all over the place with this error. Did I forget to set up something?

```
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

Another problem I currently have is that the connection to the websocket is failing and because of the this the consumer status is not working. Any idea what could be wrong? If build a docker image from the branch and run it everything is ok. But if I just follow the development instructions (with debug mode enabled) it's not working.

image

Is there a way to reopen the PR? Or do I need to create a new one?

**Comment by shamoon** [comment]
Sorry I don’t have the time right this second to answer all the questions in full detail:

- it does look like you would need to open a new PR, it won’t let me reopen this one
- I think “immediately upload on drop” should be preserved. If the merge toggle is flipped, only then things can work differently with the queue, upload button etc
- You may need to modify some of the existing tests, yes
- Not sure why the WS import is failing, have you made sure it installed with npm etc?
- pytest should work except for a few tests which need to run on ci. Not sure about that error but yea sounds like installed incorrectly
- Getting web sockets to work locally has always been a pain, that’s why I used that testing package :)

**Comment by mpflanzer** [comment]
The old upload behaviour is now preserved unless the button is toggled. Except for a Tika parser test all tests are now passing. The failed is not related to anything I touched.

```
FAILED paperless_tika/tests/test_tika_parser.py::TestTikaParser::test_parse - AssertionError: datetime.datetime(2020, 11, 21, 0, 0) != datetime.datetime(2020, 11, 21...
```

**Comment by mpflanzer** [comment]
Currently only multiple image files are supported. But extending this to PDF documents for example should not be an issue.

@thmo, do I understand correctly that you would have two documents, one with the front and one with the back pages. The two files would then need to be interleaved and pages from the second document would need to be taken from last to first?

That would be possible for sure but adding quite some additional complexity. Would be good to hear from the maintainers how if they would be willing to accept such a feature as a pre-processing step in paperless.

**Comment by thmo** [comment]
Exactly. They would have to be merged as in `qpdf --collate even.pdf --pages . odd.pdf z-1 -- out.pdf`.

In an ideal world, this would work via e-mail (because then, no other device than the scanner and the paperless server would be needed!), however I must admit I am not sure how matching the two documents could be achieved in that case.

**Comment by alexgrahamuk** [comment]
I was toying with the idea of a separator page or maybe a stamp . Basically anything unique you can manually apply to paper which triggers a split. I imagine something similar in a digital to digital conversation would still be true depending on how you want to handle it. Multiple stamps could work well. "Starts dipping potatoes in paint."

**Comment by thmo** [comment]
With the non-duplex scanner, the issue still is that you cannot send a single document with that separator page somewhere in, because you have to take the document stack out, turn it over an feed it again.
There could be two marker pages though, one for the 'even' pages, one for the 'odd' pages, not sure. Maybe there's prior art somewhere?

**Comment by alexgrahamuk** [comment]
I know my printer (while it does page by page two sided) can drop the scans
to your choice of preset folder. Odd, even folders maybe. Still annoyingly
manual though.

**Pull request closed without merging**
