### PR TITLE
Don't submit owner via API on document upload

### PR DESCRIPTION
**Pull request by jonaswinkler**
## Proposed change

Don't allow owner to be submitted via API, instead use currently logged in user for the new document.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by stumpylog — APPROVED** [review]
Makes sense to me

**Comment by shamoon** [comment]
Hmm, but wouldn’t we want to sometimes be able to set the owner to the post documents view?

Currently this does the same thing (uses the logged in user) just that it comes from the frontend.

Sorry if I’m misunderstanding

**Comment by jonaswinkler** [comment]
It's more about user separation. You could use the API to add documents for another user, and I'd say that's a big no no.

**Comment by shamoon** [comment]
Fair enough, it doesn’t feel that “dangerous” to give a doc to someone else but I can see how separation is cleaner

**Review by shamoon — APPROVED** [review]

**Pull request merged**
