### PR TITLE
Enhancement: Allow setting 'X_FRAME_OPTIONS' via environment variable

### PR DESCRIPTION
**Pull request by MaxWinterstein**
## Proposed change

Allow setting of `X_FRAME_OPTIONS` via environment variable, as discussed / requested within #2415 or #1837 

Closes #2415 

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by ronindesign** [comment]
I've noticed X-Frame-Options is now ignored in modern browsers. Maybe the ENV variable should be to set CSP `frame-ancestors` instead...

Refs:
https://stackoverflow.com/questions/40373771/how-does-content-security-policy-work-with-x-frame-options
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
Obsoleted by: https://w3c.github.io/webappsec-csp/#frame-ancestors-and-frame-options
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

**Comment by MaxWinterstein** [comment]
@ronindesign that (sadly) sounds correct to me, at least from what I read after a few minutes of Googling.

This should be solvable with https://github.com/mozilla/django-csp. Sadly, my missing django knowledge and the missing/undocumented development support for Mac OS is a little bummer.

**Comment by ronindesign** [comment]
> @ronindesign that (sadly) sounds correct to me, at least from what I read after a few minutes of Googling.
> 
> This should be solvable with https://github.com/mozilla/django-csp. Sadly, my missing django knowledge and the missing/undocumented development support for Mac OS is a little bummer.

Yes, it is unfortunate. I also tried different method of specifying allowed origins/hosts, but no combination allowed for iframe/embedding. I resolved to just setting the two headers (one to invalidate, and one to set CSP `frame-ancestors`) via reverse proxy (traefik, middleware)
```python
def _parse_paperless_url():
    global CSRF_TRUSTED_ORIGINS, CORS_ALLOWED_ORIGINS, ALLOWED_HOSTS
    url = os.getenv("PAPERLESS_URL")
    if url:
        CSRF_TRUSTED_ORIGINS.append(url)
        CORS_ALLOWED_ORIGINS.append(url)
        ALLOWED_HOSTS.append(urlparse(url).hostname)

    return url
```

I resolved

**Comment by shamoon** [comment]
Thanks, but it sounds like this PR will not really achieve the desired result so I’ll plan to close this out for now unless I’ve misunderstood. As noted, a RP can solve this for those that use one. Personally I have always found the embedded iframe approach of things like organizr weird (and problematic) but that’s just me.

**Comment by ronindesign** [comment]
> Thanks, but it sounds like this PR will not really achieve the desired result so I’ll plan to close this out for now unless I’ve misunderstood. As noted, a RP can solve this for those that use one. Personally I have always found the embedded iframe approach of things like organizr weird (and problematic) but that’s just me.

Agreed, I would think this PR doesn't fix the underlying issue/need. Organizr tab was precisely my use case. It can be problematic until it's configured correctly. However, the demand is real for users that are not technically inclined or cannot be bothered to learn your network config.

Granted, a dashboard with external links works just fine, but in my opinion/preference, it adds extra cognitive load for the user to remember they have to go back to the dashboard to get to another app (vs. simply clicking the other app icon in the sidebar of Organizr.) Just my thought on the matter in case a related feature is considered in the future.

**Comment by shamoon** [comment]
im for sure biased :) as my own dashboard project takes a different approach but I think embedded iframes are an outdated web tech that everyone is forced to support but no one likes (one of many :) but anyway, off-topic.

thanks for the effort

**Pull request closed without merging**
