### PR TITLE
Enhancement: confirm buttons

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Small UI thing that came up in #5190 (and this PR is dependent on that just so the changes there are included). This adds a little confirmation to certain buttons in the UI. Eg:
Screenshot 2024-02-06 at 4 57 09 PM

Edit: I've narrowed down the scope of this PR, the button is used for:

- Profile regenerate API key and disconnect social account
- Workflow editing delete action and trigger (currently has no confirm)
- Saved view delete (this actually had no confirm before, which seems inconsistent)

Screenshot 2024-02-06 at 8 52 53 PM
Screenshot 2024-02-06 at 8 52 57 PM
Screenshot 2024-02-06 at 10 23 48 PM
Screenshot 2024-02-06 at 9 35 21 PM

Closes #(issue or discussion)

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by hendrik1120** [comment]
From a user perspective, I don't think that displaying such a generic message like "Are you sure?" is a good idea.
Yes, ofc I am sure, I clicked the red button that says delete. The message doesn't add any extra value.

I think that the user should be informed of non-obvious consequences he didn't think about before.
For example, when deleting tags, the user should be informed that this tag will be removed from **all documents** and maybe that the documents themselves are not being removed.
Tags and views can easily be recreated, deleting files, tokens or credentials can only be undone when restoring from a backup.
There needs to be a difference.

**Comment by shamoon** [comment]
I agree the popup confirm dialogs are better at showing a little more info about consequences.

I’d be fine reverting this change for all of the management lists (delete tags, delete workflow etc), though without any A/B testing or something like that we are talking about one persons opinion so far...  But I don’t agree in every situation, like removing a workflow trigger or regenerating an API key. Those are situations where I think it really is useful just to confirm the user wanted to perform the action before doing it.

**Comment by shamoon** [comment]
I've narrowed down the scope here.

**Comment by stumpylog** [comment]
Maybe just to be cleaner, you could drop the extra commits?

**Comment by shamoon** [comment]
I dont know if I can now that theres a merge commit, but when this is merged in it'll get squashed cleanly to the one commit, right?

**Comment by stumpylog** [comment]
It probably will.  I guess just make sure the co-authored isn't set?

**Comment by shamoon** [comment]
Or I can open a new PR if you prefer

**Comment by shamoon** [comment]
Yea, should be clean I think?

Screenshot 2024-02-08 at 9 59 29 AM

**Review by stumpylog — APPROVED** [review]

**Comment by shamoon** [comment]
I'm just gonna open a new PR...

**Comment by shamoon** [comment]
Ok sorted, sorry for the noise

**Pull request merged**
