### PR TITLE
Feature: Add explanations to relative dates

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Small tweak which adds 'explanations' to the relative dates, see screenshot. My only question with this is whether it will make people think the date is 'static' i.e. last 7 days will always be May 20–May 27 2023. In the end, I dont think this makes that any less apparent than currently and it does clear up "last month" = "within the last month", so I think change makes sense. Welcome any thoughts, of course.

Fixes #773

New:
Screenshot 2023-05-27 at 10 24 00 AM

Old:
Screenshot 2023-05-27 at 10 19 23 AM

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by clemensrieder** [comment]
One interesting thing to mention is semantics here and I want to make sure I am alone with this:

"Last year" for me is 2022. So I would expect a "last year" filter to show everything between 01.01.2022 and 31.12.2022, not relative to the current day. The same holds true for the "last month" and the "last 3 months". This is directly in contrast to "last 7 days" where I would expect everything from "today" to "7 days in the past". 🤣

**Comment by shamoon** [comment]
Yea I mentioned that in the thread. And if you stick “within the” in front they all make sense. I don’t natively speak any other languages but I wonder if that is a quirk of English

**Comment by shamoon** [comment]
(Hit enter too soon)

but either way these little labels should hopefully help clarify

**Review by stumpylog — APPROVED** [review]
I think this makes sense.  Having the dates to "now" will help prevent thinking it is static

**Pull request merged**
