### PR TITLE
Chore: Remove duplicated `static` folder

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

As noticed in the Matrix chat, the release archive included 2 copies of the `static` folder, one at the root, and one at `src/documents/static/` which also contained the files.  After looking into it, it's probably best to leave these in the release archive.  `src/documents/static/` is where the `collectstatic` command will look for files, and removing it might cause problems if the user moves the STATIC_ROOT. 

This problem also extended to the Docker image including the duplicate files.  This was a simpler fix, `collectstatic` was modified to use symlinks instead of copying where possible.  This saves a number of files being duplicated.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain) - fixing up the frontend packaging

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — APPROVED** [review]
> Resulting image still displays the frontend, etc, so the change should be fine. The only question I have is if a bare metal user changes STATIC_ROOT and runs `collectstatic` will it fail? Or can they just move the existing files to the new location?

I find this a little confusing so not certain but `PAPERLESS_STATICDIR` (`STATIC_ROOT`) is where the files get copied to so yea if `src/documents/static/` is empty that command won't work e.g. `0 static files copied to...`. Moving them would work. If / when the user [re-generates the frontend it'll put them in `src/documents/static/frontend`](https://github.com/paperless-ngx/paperless-ngx/blob/main/src-ui/angular.json#L86) and `collectstatic` will work but only overwriting the [new] frontend files

Again, I think! Would love a double-check on this

**Comment by stumpylog** [comment]
Actually, I think using the `--link` option could work.  Instead of copying, it's a link to them.  I'm going to give that a try later.

**Comment by stumpylog** [comment]
I still need to test the resulting image, but I think we can save a little space there at least.

For the release archive though, `collectstatic` copies more than just the frontend files to STATIC_ROOT.  It's also some admin page stuff, and some items from DRF.  Using the `--link` there creates absolute symlinks, not relative.  It's not really a huge deal, it's just some extra files and space in the release archive.

**Comment by shamoon** [comment]
Yea its the css and some other stuff. I agree this isn't a major thing if you think its going to cause problems than its worth

**Comment by stumpylog** [comment]
Test out the image, it's working as normal, frontend files loaded, etc.  So the `--link` works no problem.

**Comment by stumpylog** [comment]
Holy moly, this shaved over 100 MB off the image size.  From 523 MB to 420 MB!  Glad that person noticed

**Comment by shamoon** [comment]
Awesome!

**Pull request merged**
