### PR TITLE
Docs: More fixes and improvements

### PR DESCRIPTION
**Pull request by tooomm**
## Proposed change

As mentioned in an earlier PR, the changelog.md file had many conversion issues which I tried to address here.
Also some small other fixes and improvements.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain): Docs

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — CHANGES_REQUESTED** [review]
Thanks but some of these seem unnecessary like all the changes in index, and why bother removing dependabot links? Those are auto-generated and so the next time we have a release it’ll include them making things inconsistent (though of course I agree they’re pointless). If you wouldn’t mind limiting these PRs to things that are actually broken.

Quality over quantity! 👍

**Comment by tooomm** [comment]
>why bother removing dependabot links? Those are auto-generated and so the next time we have a release it’ll include them making things inconsistent (though of course I agree they’re pointless)

Please check https://docs.paperless-ngx.com/changelog, dependabot is no longer linked. It's automatically linked in GH release descriptions still, because of how GitHub threatens @.
I made the changelog uniform and removed old links to the dependabot profile as well.

**Comment by shamoon** [comment]
Thanks again tooomm, I pared it back to be just the errors, I think the other stuff can be left alone

**Comment by tooomm** [comment]
Thanks for bringing this forward and providing feedback @shamoon.

But you need to help me now to better understand how to proceed from here and prevent misalignment in potential future PR's.
I was planning to improve the docs further. Obviously, I prefer to not invest time and effort if I'm missing a point here.

After your change, there are now several errors still live in the changelog page of the documentation, e.g.:
- false links
- broken mkdocs formatting
- many leftover layout/styling issues from the conversion

<br>

I know that squashing my pile of small commits locally was not perfect and reduced overview while it was actually supposed to achieve the opposite.

**Comment by shamoon** [comment]
Ah, sorry if things got lost. Feel free to fix things that are broken like links and generally things that have actual effects on the docs / people's ability to use them. It looked to me like some of those things were just for "correctness" sake which made it hard to pick out the useful changes, so again sorry if some useful ones were lost 👍

**Pull request merged**
