### PR TITLE
[Beta] Paperless-ngx v2.13.0 Beta Release

### PR DESCRIPTION
**Pull request by shamoon**
Welcome to our latest beta release of Paperless-ngx! This release includes some cool new features we've been working hard on including a new system for file naming, advanced custom field queries, OAuth2 support for Gmail and Outlook and much more.

Thank you to everyone who has contributed, and thank you to the [Paperless-ngx team](https://github.com/orgs/paperless-ngx/people) who continue to make Paperless-ngx the best community-supported DMS out there.

## Beta Testing

A new docker container has been built at `ghcr.io/paperless-ngx/paperless-ngx:beta`. A release zip can be found in the [github pre-release](https://github.com/paperless-ngx/paperless-ngx/releases/tag/v2.13.0-beta.rc1) or the [latest CI build](https://github.com/paperless-ngx/paperless-ngx/actions?query=branch%3Abeta).

Please test this beta as best you can and report any bugs by [opening an issue](https://github.com/paperless-ngx/paperless-ngx/issues/new?assignees=&labels=bug&milestone=v2.13.0&template=bug-report.yml&title=[BUG]+v2.13.0+RC1+Bug) or leaving a comment below. See the [pre-release changelog](https://github.com/paperless-ngx/paperless-ngx/releases/tag/v2.13.0-beta.rc1) and [closed PRs](https://github.com/paperless-ngx/paperless-ngx/pulls?q=is%3Apr+milestone%3Av2.13.0+is%3Aclosed), especially ones labeled `non-trival`, to guide your tests.

We generally recommend testing this in a separate instance as things like database migrations can change. If you will be running this over a production installation, be careful to [make a backup](https://docs.paperless-ngx.com/administration/#backup).

Some additional notes:

* The `beta` container is updated as commits are made, see the [actions tab](https://github.com/paperless-ngx/paperless-ngx/actions?query=branch%3Abeta) for progress.
* If bugs are found release candidates will be pushed as necessary.

# Thank you

Finally, if you're reading this, **thank you** for being a part of Paperless-ngx! While we are proud to continue to publish new releases, we are even prouder of the collaborative process that makes it possible. Thanks to each and every person who has contributed so far 🙏

### Changes Since Opened

- #7908
- #7912
- #7916
- #7927
- #7933
- #7953
- #7961
- #7963
- #7967

### CODE REVIEW

**Comment by shamoon** [comment]
Not so much Codecov 😒

Screenshot 2024-10-14 at 8 19 29 AM

(we can safely ignore, its just because there are no previous beta bundle uploads)

**Comment by stumpylog** [comment]
I suppose it could be increased, but that seems to getting quite large.  Maybe you need more storage paths instead?

**Comment by vamagnus** [comment]
@stumpylog I just need extra 500 or so... 2048 is just by slightly not enough. The limit can be 2500 or 3000, wasn't sure it needs to follow the logic of x2 from 512 > 1024 > 2048. Thanks!

**Comment by marcelbrueckner** [comment]
> I suppose it could be increased, but that seems to getting quite large. Maybe you need more storage paths instead?

Why not simply using a `TextField` instead of an arbitrarily limited `CharField`?

**Comment by nhardgrove** [comment]
I'm not seeing the option to add an OAuth2 account in the mail config? Am I dumb or blind? That's TOTALLY possible.

**Comment by nhardgrove** [comment]
> I'm not seeing the option to add an OAuth2 account in the mail config? Am I dumb or blind? That's TOTALLY possible.

image

**Comment by shamoon** [comment]
> > I'm not seeing the option to add an OAuth2 account in the mail config? Am I dumb or blind? That's TOTALLY possible.

did you review the documentation for using the feature?

**Comment by nhardgrove** [comment]
After digging in the new docs, yep, dumb AND blind! LOL

I see what I needed to do, thank you.

From: shamoon ***@***.***>
Date: Sunday, October 20, 2024 at 7:53 PM
To: paperless-ngx/paperless-ngx ***@***.***>
Cc: nhardgrove ***@***.***>, Comment ***@***.***>
Subject: Re: [paperless-ngx/paperless-ngx] [Beta] Paperless-ngx v2.13.0 Beta Release (PR #7902)

I'm not seeing the option to add an OAuth2 account in the mail config? Am I dumb or blind? That's TOTALLY possible.

did you review the documentation for using the feature?

**Comment by paradizelost** [comment]
Running the beta and successfully pulling in imap gmail with oauth!

**Pull request merged**
