### PR TITLE
Chore: Backend bulk updates

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

Bulk updates all our Python dependencies and the locked pipenv version.  Takes the moment to do a little sorting of the Pipfile, clean up and format setup.cfg.

Also builds the latest qpdf and includes that in the Dockerfile.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain): maintenance

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
https://github.com/celery/celery/releases/tag/v5.3.5 😎

**Comment by stumpylog** [comment]
Oh good.  I'll get it when I'm fully back.  If you want to merge the docs changes first, I can de-conflict the lock file

**Comment by shamoon** [comment]
Yea might as well there’s another tiny docs PR that’s waiting on that bigger one

**Review by shamoon — APPROVED** [review]
Thanks!

**Pull request merged**
