### PR TITLE
Feature: quick filters from document detail

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

This PR adds a "quick filter" button next to the fields on the doc details page, see video. Basically this allows you to quickly find docs with the same date / correspondent / doc type / storage path / tags. I debated where to put the buttons but in the end this seemed the best option (imho).

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/c7702acd-cef9-49e5-a087-fdb9f5dc684a

Fixes # (theres a FR somewhere)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
I'm assuming the tags quick filter looks for that exact set of tags?  Or is it more of an OR type search?

**Comment by shamoon** [comment]
Yea at the moment it's an AND, so yea, contains all. I debated e.g. OR but I thought that seemed too 'loose' when actually using this.

Like, look at a yearly insurance thing with tags "Insurance", "Auto", "VW Bus" and I can click the button to quickly show me all the other invoices (or the correspondent etc) whereas OR would show me all of my (non-auto) insurance docs, etc.

https://github.com/paperless-ngx/paperless-ngx/blob/74c965d21d1f5a92b1b9fb0ebc23f51340a48368/src-ui/src/app/components/document-detail/document-detail.component.ts#L820

**Review by stumpylog — APPROVED** [review]
An AND type makes sense for tags.  I'll trust you on the code portions!

**Comment by shamoon** [comment]
> I'll trust you on the code portions!

Thanks! I'm working on something to mitigate this =)

**Pull request merged**
