### PR TITLE
Chore: better bootstrap icons

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Sorry, this is a bit of an absurd PR (in terms of diff size) but all it's really doing is replacing the way we use the bootstrap icons. Currently we reference an external svg file which:

1. Causes some unsightly visual things, like [this](https://github.com/paperless-ngx/paperless-ngx/assets/4887959/0fa75577-fe50-422d-b1a3-3c4eab6a3080) (and just watch the browser network when on e.g. tasks page and auto-refresh)
2. Makes the releases unnecessarily larger.

This replaces them with an angular package, only loading in the ones we actually use and ultimately embeds the svg in the page so no loading delay.

Hopefully I caught all the little tweaks, I'll keep an eye out for more =)

Closes #(issue or discussion)

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [x] Other. Please explain: chore dependencies

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
Something I notice is the open documents has a scroll bar in this image:
image

**Comment by shamoon** [comment]
Great catch thanks!

**Review by shamoon — COMMENTED** [review]
Went through again line-by-line, a little annoying but hoping I've caught all the little things

**Review by stumpylog — APPROVED** [review]
I haven't noticed any other missing or odd icons

**Pull request merged**
