### PR TITLE
Feature: Fork django-q to update dependencies

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

I'm opening this up as a discussion point around `django-q`, which is the library used for running the time consuming tasks in the background.  At least as of this time, the library hasn't been updated in around 11 months.  The author also hasn't had anything activity [in their profile](https://github.com/Koed00) since then.

I propose forking the repo into paperless-ngx, not to fully maintain (bug fixing, etc), but to allow its dependencies to be updated to more recent versions.  I've done a prototype of this work [here](https://github.com/stumpylog/django-q/compare/master...stumpylog:relock-deps).

### Advantages

- `redis-py` updates from version 3 to version 4
  - many bug fixes and improvements ([changelog](https://github.com/redis/redis-py/blob/master/CHANGES))
- Confirms `hiredis` 2.0.0 support
- resolves numerous warnings in our test suite
- Minor modernization of the library code
- In the future, could allow adding new features or fixing issues with the library

### Disadvantages

- More code to maintain

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Cool! Funny timing as I have never experimented with Q until the last few days ( https://github.com/paperless-ngx/paperless-ngx/discussions/1015 ).

I cant really speak to the technical side of this (again, I dabble but thats about it) but this does make sense to me, and I suppose if the original repo comes back to life it wouldn't be too hard to switch back?

**Comment by stumpylog** [comment]
> I suppose if the original repo comes back to life it wouldn't be too hard to switch back?

That's the idea behind only keeping the dependencies a little more up to date, with the most minor code updates to resolve obvious things (like a django deprecation warning).  

Now that I have a pyproject.toml file which works, that's really all to do for the moment.  It will allow us to include newer versions.

**Comment by qcasey** [comment]
> That's the idea behind only keeping the dependencies a little more up to date, with the most minor code updates to resolve obvious things (like a django deprecation warning).

I think this is a great idea!

**Comment by stumpylog** [comment]
I've forked `django-q` into [the organization](https://github.com/paperless-ngx/django-q) and replicated the changes I made, keeping the code changes actually even a little lighter this time (for now).

So in my opinion, this is now ready for review.  Everything in the image looks to work just fine (and all `django-q` tests pass on the fork).

**Review by shamoon — APPROVED** [review]

**Comment by shamoon** [comment]
I think just needs a re-base / merge with `dev` and then lets get this in, no?

**Comment by stumpylog** [comment]
Yeah, it's easy to fix those conflicts.  

I was kind of waiting for more feedback, but it's been around long enough to probably just go for it.

**Comment by shamoon** [comment]
Yea it’s dev after all and I think next release will need beta testing anyway

**Pull request merged**
