### PR TITLE
Fix: Ensure the scratch directory exists before consuming via the folder

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

Only an issue on baremetal or Docker if they change the undocumented setting

Closes #5567

## Type of change

- [x] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — APPROVED** [review]
Thanks stumpy! I didn’t realize the part about that setting needing to be set to see this, that explains why it’s a rather isolated issue. 

There’s something satisfying about a one-line fix 😎

**Comment by stumpylog** [comment]
I can do a point release later today

**Comment by shamoon** [comment]
Cool thanks!

**Comment by shamoon** [comment]
Do you also have settings.SCRATCH_DIR set?

**Comment by eliasp** [comment]
I didn't have it set, but now with it being set to `/tmp/paperless/scratch`, I still end up with this:
```
Jan 30 17:37:01 homeserver celery[573475]: [2024-01-30 17:37:01,232] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[2385a7c4-605a-4dfc-ac43-db15e9104d5c] raised unexpected: FileNotFoundError(2, 'No such file or directory')
Jan 30 17:37:01 homeserver celery[573475]: Traceback (most recent call last):                                                                                                                                                               
Jan 30 17:37:01 homeserver celery[573475]:   File "/nix/store/rz33dk0cmkwwpiar45z06qvfy86jcgfr-python3.11-celery-5.3.6/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task                                           
Jan 30 17:37:01 homeserver celery[573475]:     R = retval = fun(*args, **kwargs)                                                                                                                                                            
Jan 30 17:37:01 homeserver celery[573475]:                  ^^^^^^^^^^^^^^^^^^^^                                                                                                                                                            
Jan 30 17:37:01 homeserver celery[573475]:   File "/nix/store/rz33dk0cmkwwpiar45z06qvfy86jcgfr-python3.11-celery-5.3.6/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__                                   
Jan 30 17:37:01 homeserver celery[573475]:     return self.run(*args, **kwargs)                                                                                                                                                             
Jan 30 17:37:01 homeserver celery[573475]:            ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                             
Jan 30 17:37:01 homeserver celery[573475]:   File "/nix/store/cwlcf9zm93zwasxbax1bi30hdmfjc8c3-paperless-ngx-2.4.3/lib/paperless-ngx/src/documents/tasks.py", line 122, in consume_file                                                     
Jan 30 17:37:01 homeserver celery[573475]:     ) as status_mgr, TemporaryDirectory(dir=settings.SCRATCH_DIR) as tmp_dir:                                                                                                                    
Jan 30 17:37:01 homeserver celery[573475]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                
Jan 30 17:37:01 homeserver celery[573475]:   File "/nix/store/w4fvvhkzb0ssv0fw5j34pw09f0qw84w8-python3-3.11.7/lib/python3.11/tempfile.py", line 854, in __init__                                                                            
Jan 30 17:37:01 homeserver celery[573475]:     self.name = mkdtemp(suffix, prefix, dir)                                                                                                                                                     
Jan 30 17:37:01 homeserver celery[573475]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                     
Jan 30 17:37:01 homeserver celery[573475]:   File "/nix/store/w4fvvhkzb0ssv0fw5j34pw09f0qw84w8-python3-3.11.7/lib/python3.11/tempfile.py", line 368, in mkdtemp                                                                             
Jan 30 17:37:01 homeserver celery[573475]:     _os.mkdir(file, 0o700)                                                                                                                                                                       
Jan 30 17:37:01 homeserver celery[573475]: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/paperless/scratch/tmporhhhg1_'
```

**Comment by stumpylog** [comment]
A closed pull request isn't the best location to post a possible issue.  Lets move to a new support discussion.

**Comment by oddlama** [comment]
For any future visitors having the same issue, the new discussion is in #5606 .

**Pull request merged**
