### PR TITLE
Feature: Use semver for release process

### LINKED ISSUE #824: [BUG] Docker image tag not semver compliant
### Description

The new docker image tag (`ngx-1.7.0`) format is not compatible with semantic versioning, and can therefore break automated updating tools (such as Renovate) that by default rely on a semantic versioning-style tag.

I would have expected the latest versioned tag to be `1.7.0`.

### Steps to reproduce

Open https://github.com/paperless-ngx/paperless-ngx/pkgs/container/paperless-ngx/20580039?tag=ngx-1.7.0

### Webserver logs

_No response_

### Screenshots

_No response_

### Paperless-ngx version

1.7.0

### Host OS

n/a

### Installation method

Docker

### Browser

_No response_

### Configuration changes

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

This PR updates the various files for starting using semver for our release process.  As before, we would create the `beta` branch, tag it with various RC numbers.  The larger change is for the release tag, matching to a `vX.Y.Z` format (minus the `ngx-` of previous releases).  This allows using the Docker [metadata-action semver type](https://github.com/docker/metadata-action#typesemver), which manages creating  `:latest`, `X.Y.Z` and `X.Y` image tags.

I've run these changes through a faux release cycle on my fork and they appeared to work.  

- The [`beta-1.7.1-rc1`](https://github.com/stumpylog/paperless-ngx/tree/beta-1.7.1-rc1) tag was properly set as a pre-release
- The beta tag also didn't update the Docker image `:latest`
- The tag of `v1.7.1` created a "real" release
- [The packages](https://github.com/stumpylog/paperless-ngx/pkgs/container/paperless-ngx/versions) tagging also looked correct for the release tag
- There's an org-docs pull request open to describe the fairly minor update to the release process

Fixes #824

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Also need to update #591 right? (I can do)

**Comment by stumpylog** [comment]
I made changes in `src/documents/views.py` for the new format, is there something I missed there?

**Comment by shamoon** [comment]
> I made changes in `src/documents/views.py` for the new format, is there something I missed there?

Oh so sorry I missed that, awesome!

**Comment by qcasey** [comment]
Overall \*chef's kiss\* as usual. But..

> [The packages](https://github.com/stumpylog/paperless-ngx/pkgs/container/paperless-ngx/versions) tagging also looked correct for the release tag

I'm seeing [beta-1.7.2-rc0](https://github.com/users/stumpylog/packages/container/paperless-ngx/21031255?tag=beta-1.7.2-rc0) tagged as `latest`, is that intentional?

**Comment by stumpylog** [comment]
Argh, no, it's not intentional. I'll look into it.

**Comment by stumpylog** [comment]
Ok, fixed it.  

- Any tags made in the beta will need to follow a slightly different format: `beta-1.7.1-rc0` -> `v1.7.1-beta.rc0`.  Turns out the semver standard is pre-release info after the version.
  - Org docs still todo
- Or if it looks better `v1.7.1-rc0`, but I'll need to update some conditions for that format.  It is less to type though?
- Release tags still look the same `v1.7.1` creates `1.7` and `1.7.1` image tags.

But the the beta or release candidate tags won't update latest now and will create pre-release releases and actual release version correctly with the drafter.

**Comment by shamoon** [comment]
Awesome! Will be glad to make this change, the old tagging was a bit rando. For betas I think going with the standard semver conventions is best (that’s the point of this after all!) so `v1.7.1-beta.1` or `v1.7.1-beta.rc0` are good with me

**Review by qcasey — APPROVED** [review]
Thanks stumpylog! I agree, `1.7.0-beta.rc0` is perfectly fine.

**Pull request merged**
