### PR TITLE
Feature: Add an option to disable matching

### PR DESCRIPTION
**Pull request by bdr99**
## Proposed change
Add an option to completely disable matching for a particular correspondent, tag, document type, or storage path. This has been requested a couple of times, and I think it would be pretty useful.

This is my first PR to this project so please let me know if I did anything wrong.

Fixes https://github.com/paperless-ngx/paperless-ngx/discussions/2461
Fixes https://github.com/paperless-ngx/paperless-ngx/discussions/2662

image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — CHANGES_REQUESTED** [review]
Thanks for the PR.

I re-ordered the options in the list, to me this should be last, and updated the frontend strings. I also made an unrelated change (MatchingModel should extend just `ObjectWithId`) that I noticed looking at this.

Im OK with the feature itself even if it seems a little niche I can imagine use-cases.

One other thing in terms of the backend code would be to please include this option in the python tests, but I will defer to backend team if they have any other concerns.

**Review by henrywintif — APPROVED** [review]
Code looks good, and very happy to see this feature implemented! For the time being I've just been setting matching to exactly "this string Will never come up!?xyz!!!" (with case sensitivity enabled) 😄

**Comment by jonaswinkler** [comment]
Just as a side note, when you leave the matching algorithm as default "Any word" and don't enter any words in the pattern field, the tag/correspondent/etc will never be assigned automatically.

**Review by jonaswinkler — APPROVED** [review]
If you could add a small test case that verifies that MATCH_NONE works as expected in test_matchables.py -> class TestMatching, that would be great.

**Review by stumpylog — APPROVED** [review]

**Review by shamoon — APPROVED** [review]

**Pull request merged**
