### PR TITLE
Added support for specifying multiple languages in the installer

### PR DESCRIPTION
**Pull request by bauerj**
This pull request has been imported from jonaswinkler/paperless-ng#1167 and was originally opened by mweimerskirch on 2021-07-13 20:01:49.

---

I tried specifying multiple languages in the installer but ran into issues. The issues were caused because "PAPERLESS_OCR_LANGUAGE" expects a list of items separated by a "+" (e.g. "eng+deu+fra+ltz", which is also the way tesseract expects it), while "PAPERLESS_OCR_LANGUAGES" expects a list separated by a whitespace (e.g. "eng deu fra ltz").

With this change, you can now specify multiple languages separated by a "+" when asked (I added a note explaining this). Then, the script loops through the languages and checks if there are any languages not in the "default" list. It will then only add those to "PAPERLESS_OCR_LANGUAGES" that are not in the default list. If all of the languages are in the default list, "PAPERLESS_OCR_LANGUAGES" is not added.

Also checked to work with single languages.

### CODE REVIEW

**Comment by mweimerskirch** [comment]
I saw that my pull request was imported to this new project and I rebased the code on paperless-ngx/dev in order to eliminate the merge conflict.

**Comment by mweimerskirch** [comment]
Unfortunately, I can't modify the original description, but here's a bit more on why this is needed:
The Docker image comes with a few OCR languages preinstalled (see https://github.com/paperless-ngx/paperless-ngx/blob/ec5416abfdfd41b70a85c5f93b111a53fa6935a6/Dockerfile#L44). You can add any of those in the OCR_LANGUAGE environment variable, separated by a "+". Example: "eng+deu"

But when you add a language that's not in the default list, it needs to be installed. Example: "eng+deu+ltz"
Those languages have to be specified in the "PAPERLESS_OCR_LANGUAGES" environment variable, but separated with a space. See https://github.com/paperless-ngx/paperless-ngx/blob/ec5416abfdfd41b70a85c5f93b111a53fa6935a6/docker/compose/docker-compose.env#L15 and https://github.com/paperless-ngx/paperless-ngx/blob/ec5416abfdfd41b70a85c5f93b111a53fa6935a6/docker/docker-entrypoint.sh#L79

The unpatched code only works for a single language. After the patch, the process also works for multiple languages.

**Comment by bauerj** [comment]
Thanks for the explaination!

I wonder why we even need two variables. Couldn't we change this: 

https://github.com/paperless-ngx/paperless-ngx/blob/ec5416abfdfd41b70a85c5f93b111a53fa6935a6/docker/docker-entrypoint.sh#L81

to use `PAPERLESS_OCR_LANGUAGE` as well?

**Comment by mweimerskirch** [comment]
Good question. I see two reasons to keep them separate:

- PAPERLESS_OCR_LANGUAGE is used by Docker Compose, while OCR_LANGUAGE is used at runtime.
- It doesn't make sense to call the installer for a language that's already included in the base image. If you only use eng or deu for example, you don't need the PAPERLESS_OCR_LANGUAGES variable and can instead use the ones included with the base image.

But your idea isn't bad: Using only one variable would simplify the installation a bit. At the same time, the defaults (eng, deu, fra, etc) could all be removed entirely to make the base Docker image smaller and then let the user install only the languages they need. However, somebody else will have to do that, as I don't have that much free time on my hands.

**Comment by bauerj** [comment]
Sorry, I kind of forgot about this issue.

Indeed, we could remove the default languages from the image and then just install the needed ones on startup.

Maybe we can even cache this somehow by installing the language into paperless_data? Then only the first start would be slower.

**Comment by mweimerskirch** [comment]
> Maybe we can even cache this somehow by installing the language into paperless_data? Then only the first start would be slower.

I don't think there is a need to cache anything. The languages are installed as debian packages through "apt-get install": https://github.com/paperless-ngx/paperless-ngx/blob/19ff8339bed01f2030fda73e0021a603ab5b90cb/docker/docker-entrypoint.sh#L70
So once your docker container is up, you can restart it without OCR languages being redownloaded. Until you recreate your container of course.

**Comment by bauerj** [comment]
Sure, but wouldn't this slow down startup by a few seconds?

**Comment by stumpylog** [comment]
I think this has been OBE by #777?

**Comment by qcasey** [comment]
> I think this has been OBE by #777?

Sure seems that way.

**Pull request closed without merging**
