### PR TITLE
Chore: close unsupported FRs

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Final bit of keeping things tidy.

5 votes by 180 days
10 votes by 365 days

Closes #(issue or discussion)

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [x] Other. Please explain: repo maintenance

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by noseshimself** [comment]
> 5 votes by 180 days
> 10 votes by 365 days

Even if it is a nearly trivial change (see https://github.com/paperless-ngx/paperless-ngx/discussions/5703)?

**Comment by shamoon** [comment]
I misunderstood the comment, thought it was totally off topic.

> Even if it is a nearly trivial change?

6 months (and then 12 months) seems like a generous amount of time to garner some community support. Realistically we need a way to prioritize and prune FRs and it’s not realistic to do it manually.

We can always tweak the thresholds.

**Comment by stumpylog** [comment]
It does seem reasonable to me as well.  I do make an effort to at least glance through new feature requests once, in case it really is easy and makes such good sense.  But there's a lot of FRs and limited time/resources here.

Correct me if I'm wrong, but it could always be reopened too.  It's not locking them permanently?

**Comment by shamoon** [comment]
> Correct me if I'm wrong, but it could always be reopened too. It's not locking them permanently?

Yea correct. There’s still the same 30 (or 60, I forget) delay between closing and locking for all discussion types, in case they need to be reopened for whatever reason.

**Comment by noseshimself** [comment]
> I misunderstood the comment, thought it was totally off topic.
> 
> > Even if it is a nearly trivial change?

That one was connected to my request for an alternative representation for an ISO date without any dashes or other additional characters (it's  popular for a lot of reasons, one of them being its use for comparisons if interpreted as integer number). I assumed the change to be less time consuming than discussing it.

> 6 months (and then 12 months) seems like a generous amount of time to garner some community support. Realistically we need a way to prioritize and prune FRs and it’s not realistic to do it manually.

I've seen a number of interesting (but badly written) feature requests that could solve much more problems than they seem to address but they just vanish in the night without being read by anyone because people tend to have a rather narrow view on other peoples problems (and solutions).

[See the feature request for throwing documents at OpenAI or other services -- there is n extremely large number of other things you would have to add like having a way to specify document classes that may not leave the DMS due to legal restrictions so you will have to add something tag-like with the semantics "NDA on this -- do not hand over to the potential kraken. The plumbing for that seems like a complex nightmare to me.]

Example (sorry, but I don't even find it anymore): Someone asked PAPERLESS_FILENAME_FORMAT to be applied to generate the download filename for document downloads. This specific question is not well thought about because you can't use a path name for this (and PAPERLESS_FILENAME_FORMAT could contain directory separator characters) and even if you could use it it would be an "intended side effect"which would be somewhere between stupid and dangerous. But reshaped into asking for another variable PAPERLESS_EXPORT_FILENAME_FORMAT solely for this purpose and independent from internal representation would be a great idea (even solving my problem -- internally I could always use {created_year/month/day} as a workaround for my problem and the only place where it was important to me I could make it do what I need.

So if you really use upvotes as the only deciding factor for doing something (or not doing it) without reshaping feature requests into a more useful/applicable and maybe easier to implement form you might lose some things that would indeed be useful. The same applies to things where the author tried to be as vague as possible to give you as many options to implement it as you want like my idea for a "workflow-integrated 
export mechanism". I don't care how you want to implement it in the end and the transport mechanism will be my problem. But I would like to be able to tag a document "wrong DMS - send on to private stuff" and it falls out into an appropriate bin (and gets deleted) and something else will pick it up and throw into the input bin of the next DMS or "tax thing -- send to accountant" and  a copy will be put in the "mail it to the accountant" export bin. How do I write that in a way that will give you free reign of however you want to do it and get people to think about it and vote? Most won't even know what they are getting there before they have it.
(And if I really really really want it -- why not make a few more github accounts and upvote the hell out of it -- on the internet nobody knows if your a dog or just one of its tails?)

There are things where you have to make the decision yourselves and voting will just not cut it. Or where you have to write "your description sucks, I don't even see an advantage or a solution to a problem in this request".

> We can always tweak the thresholds.

I thought "closed" means "no way, never, and do not ask that same question ever again" in the area of Feature Requests.

**Comment by shamoon** [comment]
Honestly, I’m not going to respond to every point there other than to say that:

1. We, the folks who do 99% of the work in maintaining this project, need a way to keep the repository manageable. Of course it would be better to have a dedicated army of people combing the comments and discussions every day but I think if you look at the history of any open source project you’ll see that most team members don’t stick around that long, this project included unfortunately.
2. I don’t particularly care if a closed FR gets re-created, especially if it is more clearly written or whatever.
3. Reality check: there are currently just shy of 1000 open feature requests. **1000**. That number increases every day. The vast majority will never be implemented. Whether it’s because they’re poorly worded or overly-specific or in the wrong language I don’t know but frankly it doesn’t matter. The ones people care about rise to the top, even then it’s not really a guarantee they will be implemented but at least we have some idea of what matters to people.

**Pull request merged**
