### PR TITLE
Fix: install script fails on alpine linux

### LINKED ISSUE #5411: [BUG] install-paperless-ngx.sh -> line 318: head --bytes 64 failing on alpine linux due to lack of coreutils
### Description

When installing paperless-ngx in alpine linux with docker it seems the installation script which is curled is failing on line 318 due to the lack of coreutils and the minimal implementation of "head".

### Steps to reproduce

1. Install Alpine Linux (in my case 3.18)
2. Install docker and docker-compose
3. Run bash -c "$(curl --location --silent --show-error https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/install-paperless-ngx.sh)"

### Webserver logs

```bash
-
```

### Browser logs

_No response_

### Paperless-ngx version

latest

### Host OS

Alpine Linux

### Installation method

Docker - official image

### Browser

_No response_

### Configuration changes

_No response_

### Other

_No response_

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Big disclaimer is I'm just going off what the OP in the issue said, I totally defer to others (stumpylog) on this, bash isnt my thing. I tested it on my macOS and Ubuntu machines, OP of the issue confirmed, but Im not sure if there are other ramifications of this.

Closes #5411 

## Type of change

- [x] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by stumpylog — APPROVED** [review]
Works for me too.  This one line has had so much work

**Comment by shamoon** [comment]
Haha its true, kinda wild

**Comment by mquade** [comment]
I believe, the argument of `head` may also be changeable from `--bytes` to `-c` which is supported under GNU Linux and also busy box (what Alpine uses). I'm just curios why you did solve it this way.

**Comment by scherddel** [comment]
> I believe, the argument of `head` may also be changeable from `--bytes` to `-c` which is supported under GNU Linux and also busy box (what Alpine uses). I'm just curios why you did solve it this way.

I just wanted to keep it as down compatible as possible. dd works even on older UNIX based distros and I thought it reduces the risk of dependencies to other libraries. (maybe others than just alpine)

**Pull request merged**
