### PR TITLE
Feature: Even better re-do of OCR

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

When first creating the redo OCR functionality, I didn't realize the `document_archiver` command already existed to re-parse AND remake the archive file.  My attempt only updated the new OCR content in the database.

So with that knowledge, this improves the functionality so it not only will redo OCR, but will also make a new archive file, all accessible from the frontend as before.  The functionality is moved out of the management command, and into the tasks, from where an async task or the command can call it.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by ocelotsloth** [comment]
Oh hey this fixes some confusion I had yesterday with this feature.

I was trying to manually fix the page orientation of some originals that had already been parsed and the redo ocr didn't seem to be doing anything at all.

If the redo ocr button will now regenerate all the documents shown in the web interface that would be super!

**Review by qcasey — APPROVED** [review]
Nice, as advertised.

> If the redo ocr button will now regenerate all the previews shown in the web interface that would be super!

It does exactly that from what I can tell in testing.

**Comment by stumpylog** [comment]
The best way I could tell something was happening was with the archive file checksum displayed in the metadata.  Content never seemed to change, which makes sense if the OCR was good the first time.

**Comment by qcasey** [comment]
The checksum works too, I didn't think of that.

I uploaded an upside down image, noticed the garbled ocr and upside down preview, rotated it upright in the filesystem `media/originals`, redid ocr, noticed correct ocr and correct preview orientation.

**Comment by shamoon** [comment]
Yea this worked well for me too and updated the thumbnail etc.

**Pull request merged**
