### PR TITLE
Enhancement: improve date parsing with accented characters

### LINKED ISSUE #7099: [BUG] Paperless doesn’t detect day number in case of accented month name in french language
### Description

When french language is set, some dates are not detected correctly in uploaded documents. They are detected as the first of the month, regardless of the day number written in the document.
I notice this happens when dates are in "j F Y" format, like "13 décembre 2023" or "15 août 1967", and only with dates in February, August an December, which are the only months with accented characters in french language.

### Steps to reproduce

1. Install paperless-ngx via docker compose
2. Set language to french in parameters
3. Upload a pdf that contains a date with accented month name in , e.g. "13 décembre 2023"
4. Observe that the suggested date is "01/12/2023" instead of "13/12/2023". 

### Webserver logs

```bash
I don’t know where to find them. I have a local installation on my computer, not a remote server.
```

### Browser logs

_No response_

### Paperless-ngx version

2.10.1

### Host OS

Solus OS x86_64

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.10.1",
    "server_os": "Linux-6.8.12-293.current-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 983358451712,
        "available": 110041489408
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-06-25T17:14:39.434258+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-06-25T15:07:53.686776Z",
        "classifier_error": null
    }
}
```

### Browser

Firefox

### Configuration changes

_No response_

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

### PR DESCRIPTION
**Pull request by fdubuy**
## Proposed change

Proposed solution for this issue #7099. Simply by adding accented characters to the date parsing regex.
This is useful for better date suggestions in other languages with such characters.

Closes #7099

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by stumpylog — CHANGES_REQUESTED** [review]
Generally fine, but:
- Lets make the updates more targeted, ie d9e694cccbd6d0595a95490dd817b5471f0b07d0.  Not every character appears in month names.  Starting with at least `éûä` covers French and German
- Needs to be testing.  Again see d9e694cccbd6d0595a95490dd817b5471f0b07d0

**Comment by fdubuy** [comment]
> Generally fine, but:
> 
>     * Lets make the updates more targeted, ie [d9e694c](https://github.com/paperless-ngx/paperless-ngx/commit/d9e694cccbd6d0595a95490dd817b5471f0b07d0).  Not every character appears in month names.  Starting with at least `éûä` covers French and German
> 
>     * Needs to be testing.  Again see [d9e694c](https://github.com/paperless-ngx/paperless-ngx/commit/d9e694cccbd6d0595a95490dd817b5471f0b07d0)

Thank you for working on this issue !

We could add these characters for wider support : ë č ž ú ř ě á í ó ń ź ç Ş ı ğ ü
These should cover Albanian, Croatian, Czech, Hungarian, Polish, Portuguese, Slovak and Turkish.

Not sure what I should do to help now that you created a branch…

**Comment by stumpylog** [comment]
Feel free to borrow the tests and update with those characters.  That seems like a decent set to support for starters

**Comment by stumpylog** [comment]
It looks like `dateparser` doesn't handle some of the cases well.

**Comment by fdubuy** [comment]
As this appears to be an issue with a dependency, and affects only Albanian language, I will remove the support for this character : ë.

**Comment by stumpylog** [comment]
Leave it in the regex, in case dateparser ever updates again with a fix.

**Comment by stumpylog** [comment]
Looks good to me.  We're holding off on features, just in case anything comes up, but it will merge soon.  Thanks for the enhancement.

**Review by stumpylog — APPROVED** [review]

**Pull request merged**
