### PR TITLE
Fix: Miscellaneous visual fixes in v2.0.0-beta.rc1 2

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

I dont think theres any issue with the favicon (no changes there) and I cant reproduce the dashboard one, dunno if anyone else can.

https://github.com/paperless-ngx/paperless-ngx/discussions/4579#discussioncomment-7607353 (great catch, wasnt intentional but rather from bootstrap update):
Screenshot 2023-11-18 at 11 49 40 PM

https://github.com/paperless-ngx/paperless-ngx/discussions/4579#discussioncomment-7608138:
Screenshot 2023-11-18 at 11 20 56 PM

https://github.com/paperless-ngx/paperless-ngx/discussions/4579#discussioncomment-7607222:
Screenshot 2023-11-18 at 11 16 51 PM

And I cant reproduce https://github.com/paperless-ngx/paperless-ngx/discussions/4579#discussioncomment-7608270: 
Screenshot 2023-11-18 at 11 51 18 PM
Screenshot 2023-11-18 at 6 55 10 PM

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by stumpylog — APPROVED** [review]
favicon looks alright to me as well

**Comment by lagset** [comment]
Regarding the moveable tiles in the dashboard not taking the available space:

I have encountered the issue on Firefox for Android (Android 12) and Firefox on Windows 11.

Chrome/Edge seems fine.

**Comment by shamoon** [comment]
Appreciate that bit of info, unfortunately I cant repro in Win 11/FF:

Screenshot 2023-11-22 at 11 21 57 AM
Screenshot 2023-11-22 at 11 21 19 AM
Screenshot 2023-11-22 at 11 21 05 AM
Screenshot 2023-11-22 at 11 33 03 AM


Nor Android FF:
Screenshot 2023-11-22 at 11 25 24 AM
Screenshot 2023-11-22 at 11 25 08 AM

**Comment by shamoon** [comment]
Aha! Needs to be with an empty saved view. And yes, FF only it seems. OK I'll sort it out

**Pull request merged**
