### PR TITLE
Fix / Enhancement: restrict status messages by owner if set & improve 404 page

### LINKED ISSUE #3945: [BUG] upload status messages are visible by all users
### Description

Upload process of a new document by user A is visible by user B in the dashboard and by a notification. 
If user B tries to open such document, he has no access to that and lands on the 404-page. 
Browser back-button from 404-page navigates again to the document, that can't be accessed by user B, so he lands again on the 404-page. The only solution here is to close paperless and open it again in a new tab.

I see here two issues:
1. upload process from user A shouldn't be seen by user B
2. 404-page back-button navigation issue.

### Steps to reproduce

1. create two users: A and B
2. login with user A in one browser
3. login with user B in another browser
4. upload a document with user A
5. see the uploading process on the dashboard of user B
6. user B should try to open the uploaded document

### Webserver logs

```bash
no logs
```

### Browser logs

_No response_

### Paperless-ngx version

1.17.0

### Host OS

Debian x86_64

### Installation method

Docker - official image

### Browser

Chrome, Safari

### Configuration changes

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Edit 2: backend updated, see [below](https://github.com/paperless-ngx/paperless-ngx/pull/3959#issuecomment-1672329075)

Edit: also see 404 improvements [below](https://github.com/paperless-ngx/paperless-ngx/pull/3959#issuecomment-1670782475)

- Pass the owner id (if set) with status messages. This only happens when docs are uploaded via UI or an email rule with an owner. This really requires little change since we already [potentially] have the owner in `override_owner_id`
- Backend checks if `owner_id` is set in the data, if it is message is only set if logged in user is same (or superuser)
- The frontend compares this to the current user and ignores the message if needed.

I made a feature branch at `feature-fix-3945` to test

I included a frontend unit test for this and video below, logged in with 2 users to the same instance.

After (basically, nothing happens on the left 😅):

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/059545b1-8ff9-47db-9a76-e8851348e1c4

Before:

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/1f1249c8-35ba-4212-88be-160e1fe83e7f

New 404:

Screenshot 2023-08-09 at 12 02 25 AM

Fixes #3945

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] ~~I have made corresponding changes to the documentation as needed.~~
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
I almost forgot, 404 page improvements:

- replace the URL upon navigation, meaning you can use the back button
- add a "go to dashboard" button
- make it less fugly

Screenshot 2023-08-09 at 12 02 25 AM

**Comment by shamoon** [comment]
Ok I added logic to the backend for this, appreciate any feedback. Arguably the frontend portion could now be removed but feels OK as a backup (?). In the video you can see messages aren't even being sent to the other user (previously they were sent, just ignored).

Screenshot demonstrates other scenario, admin user is getting messages because they are superuser.


https://github.com/paperless-ngx/paperless-ngx/assets/4887959/534f8bc5-2972-4baa-936d-e48e566dd452

Screenshot 2023-08-09 at 4 41 50 PM

**Review by stumpylog — APPROVED** [review]
Thanks for tackling this!

**Review by stumpylog — APPROVED** [review]
Thanks for tackling this!

**Pull request merged**
