### PR TITLE
Read ASN from barcode on page

### PR DESCRIPTION
**Pull request by peterkappelt**
## Proposed change

A new feature is introduced, which allows the document ASN to be set by a bar code on the document. This feature has been requested [here](https://github.com/paperless-ngx/paperless-ngx/discussions/648) for instance - and is fairly useful for my workflow, too.

For parsing the ASN in a barcode, I've made some changes to `barcodes.py`, in order to separate the barcode-parsing and page-separator-detection logic.

Please consider this PR just a draft and a request for comments, there is definitely some additional work left (tests, docs, ...). 

I'm not really sure how a duplicate ASN (a document with a ASN code is scanned & ASN already exists) should be handled. For now, I only print a warning in the log and don't set the ASN. This is not a good UX - the user probably wants to know when there's a possible duplicate.

If someone's keen to try it out: set `PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE=true`, the first detected barcode in the document that starts with `ASN` (for instance `ASN0000001`) will be used. The prefix can be configured via `PAPERLESS_CONSUMER_ASN_BARCODE_PREFIX`. I've attached a sample document: [barcodetest_asn1.pdf](https://github.com/paperless-ngx/paperless-ngx/files/10420522/barcodetest_asn1.pdf)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by stumpylog — CHANGES_REQUESTED** [review]
Seems like a useful feature for some users.  Just a couple small suggestions

**Comment by peterkappelt** [comment]
Cool, thanks for your comments, will do! (Though probably not before friday or the weekend). Cheers!

**Comment by gador** [comment]
I have tested it with a `CODE128` barcode and in combination with barcode splitting. It works flawlessly. (Tested with the most recent commit 8385357b)

**Review by stumpylog — APPROVED** [review]
I went ahead and added the commenting + one extra test to verify the read ASN value is provided to the consumer.  Thanks for the feature!

**Comment by mtettke123** [comment]
just tested the new feature - works great - but my first consume failed, as there was already this ASN - erroneously - assigned to a document. 
It would be great if there was a way to restart comsumption without having to scan the document again - I'm a little bit afraid I could miss documents...

**Comment by peterkappelt** [comment]
Thanks @stumpylog for implementing the changes to my code yourself, my week unexpectedly became way more busy...

**Comment by stumpylog** [comment]
1. If you want to use barcodes to assign the ASN, there should only be a single one per the document.  If there are multiple, it's treated as a new document (or will be in the next release).  The integer portion of the code is used to assign the ASN
2. There were no changes to the error handling here.  If something fails, there will be logs, etc, just as before

**Pull request merged**
