### PR TITLE
Add more ItemsPerPage options

### PR DESCRIPTION
**Pull request by jwalzer**
## Proposed change

Add more options for the ListItemsPerPage property, to allow showing more items then 100 before paging.

See: https://github.com/paperless-ngx/paperless-ngx/discussions/8426

Solves #8426 

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks but:

- there is one other vote on your FR, and in general I do not suspect there is a great need for this.
- There are implications from trying to load 10k docs at once, so perhaps hastily updating the paging option is not the best solution

In general, with all of the search and filtering options this feels like an odd need.

As such, I’ll close this for now. Thanks for your interest

**Comment by jwalzer** [comment]
Thank you for taking the time to review my PR. I want to start by saying that I really appreciate this project and the effort that goes into maintaining it. That said, I found the way this PR was handled somewhat disheartening, and I’d like to provide some constructive feedback.

I understand the concerns raised about the potential implications of loading a large number of documents and that there might not currently appear to be significant demand for this feature. However, it feels like the decision to close the PR was made rather quickly, without much opportunity for discussion or exploration of possible solutions.

For example, in discussions like #3563 and #7695, there seems to have been limited engagement and no clear way to gauge ongoing community interest, especially since closed discussions can no longer be upvoted. This creates a bit of a Catch-22: community feedback is expected, but the mechanisms to gather it aren’t always open or accessible. My PR was intended to provide a concrete starting point for solving a specific user story, even if adjustments (e.g., limiting the number of items) might be necessary after further consideration.

From a user’s perspective, the swift rejection without any dialogue does come across as discouraging. While I understand the need to prioritize development efforts, I believe a more collaborative approach—where ideas can be refined and middle grounds explored—would better reflect the welcoming and community-driven spirit that the project seems to aim for.

Lastly, while the comment mentioned only one other vote on the feature request, even a small number of interested users can signal a need worth discussing. Offering options for different use cases (such as displaying up to 1000 items) might not only address specific user needs but also avoid alienating contributors who are eager to help.

Thank you again for considering my feedback. My goal is not to criticize but to help improve the collaborative process so the project continues to thrive as a community-driven effort.

**Comment by stumpylog** [comment]
#3563 got zero votes in roughly six months, a clear demonstration of no community interest.  #7695 is still open, with 2 total votes, so not showing community interest there either.  Waiting 6 months is not a "swift rejection", it's cleaning up things the community has not shown an interest in.

**Comment by shamoon** [comment]
Yea, I appreciate your thoughts but I would suggest that opening a PR against a feature request with 2 votes and 0 comments is not really adhering to the guidelines of the project.

Also, with all due respect, this PR isn't exactly something you have pored over for a long time, I imagine it took you about as long as it took me to review it. Apologies if that is untrue.

I agree I dont want to stifle contribution, but I also think as maintainers of the project we are allowed, in fact expected, to have an opinionated view of the project direction.

If you'd like to discuss the idea further, the discussion seems much more the appropriate place than here.

**Comment by jwalzer** [comment]
Thank you for your reply and for clarifying the guidelines and expectations. I understand and respect the need for maintainers to have a clear, opinionated direction for the project—it's what keeps things focused and manageable. However, I’d like to offer a different perspective on the points raised.

First, while it’s true that the original feature request may not have garnered overwhelming support, part of the reason for that could be that discussions like #3563 are closed and cannot be further upvoted or engaged with. This limits the community's ability to express interest and contribute to the conversation. Perhaps revisiting how community feedback is gathered and reflected might help in such cases.

Second, while the PR might not have been overly complex or time-intensive, I approached it as a starting point to spark discussion and refine the idea. Code is sometimes the best way to illustrate a potential solution, even if it's not perfect or final. To dismiss it on the basis of its simplicity, without delving into the underlying user story or use case, feels a bit counterproductive, especially when contributions—big or small—can foster collaboration.

I’d suggest continuing this discussion in #8426, where the feature request is still open, and the code in the PR can serve as a basis for understanding and exploring the idea further. It would be valuable to dive deeper into the potential drawbacks or risks of the "simple" solution I’ve proposed to ensure we’re aligned in our understanding. Even if this approach isn't the right one, it could help inform a more robust solution.

Finally, I appreciate the suggestion to take the discussion back to the appropriate place, and I’m happy to do so. However, I believe rejecting contributions outright without deeper engagement can create a perception that community input, especially from smaller voices, is less valued. I know this is not the intent, but it's something to consider.

I’m still eager to contribute and collaborate, and I hope we can use this as an opportunity to ensure the process is as inclusive and constructive as possible.

**Pull request closed without merging**
