### PR TITLE
Feature: Preserve original filename in metadata

### PR DESCRIPTION
**Pull request by GwynHannay**
## Proposed change

This change adds a metadata field to capture the original filename of the document being uploaded. For some, there can be important information in the original filename not captured within the document, so it is important to preserve this information.

Right now this field will only be displayed in the admin UI.

Screen Shot 2022-08-21 at 4 03 38 am

Fixes #874 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
If you don't mind, I'd like to cherry pick your commits a bit to clean up the history.  It will mean you'll need to do a fetch and reset to instead of pull though.  Let me know if that's a problem.

**Comment by GwynHannay** [comment]
> If you don't mind, I'd like to cherry pick your commits a bit to clean up the history. It will mean you'll need to do a fetch and reset to instead of pull though. Let me know if that's a problem.

Please feel free! :-)

**Comment by stumpylog** [comment]
The changes look good to me.  I think it would be nice to extend this just a touch more for people though:

- Visible on the document details page (src-ui/src/app/components/document-detail/document-detail.component.html I think)
- Provided to the post consume script: https://github.com/paperless-ngx/paperless-ngx/blob/main/src/documents/consumer.py#L175 and https://github.com/paperless-ngx/paperless-ngx/blob/main/docs/advanced_usage.rst#post-consumption-script

**Comment by shamoon** [comment]
Agree its less useful if its not visible, I will add the frontend part

**Comment by shamoon** [comment]
Screen Shot 2022-08-21 at 8 04 18 AM

All set for doc detail part =)

**Comment by GwynHannay** [comment]
Awesome!! Thank you so much - I couldn't, for the life of me, work out how to add it to the front end, haha.

**Review by stumpylog — APPROVED** [review]
I added the value to the post consume data as well.  Looks good, thanks for the contribution

**Review by qcasey — APPROVED** [review]
Thanks to all three of you

**Pull request merged**
