### PR TITLE
Enhancement: Support custom path for the classification file

### PR DESCRIPTION
**Pull request by lino-b**
## Proposed change

Allow to set a custom path for the classification file. Some users have already reported having [very large](https://github.com/paperless-ngx/paperless-ngx/discussions/1883#discussioncomment-4022669) classification files and I ran into an issue where I'd need that file to be somewhere else. So here's some little bit more flexibility. 

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development). Manually testet setting and unsetting it.
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks for the PR. This is of course a small change and I will defer to our backend dev but there is a message in the PR template for a reason but you didn’t really address it so I can’t help but wonder if this is just for you. Again I defer on this one.

> ⚠️ Important: Pull requests that implement a new feature or enhancement *should almost always target an existing feature request* with evidence of community interest and discussion. This is in order to balance the work of implementing and maintaining new features / enhancements. If that is not currently the case, please open a feature request instead of this PR to gather feedback from both users and the project maintainers.

**Comment by lino-b** [comment]
Thank you for the feedback.
I didn't address it any further because I linked to a discussion with other users mentioning their large classification files and the change is so small that I don't think it would increase any maintenance work.

**Comment by stumpylog** [comment]
It doesn't increase maintenance, but it is something that feels specific to your own system.  I will accept it (after you rebase please), but just something to keep in mind for anything in the future.

How large is your classification model file?  How small is your data storage?

**Comment by lino-b** [comment]
Thank you.
The classification model grew to 350mb while the storage space is currently only 200mb. That is the issue I'd like to solve with this.

**Review by stumpylog — APPROVED** [review]

**Pull request merged**
