### PR TITLE
Fix: default order of documents gets lost in QuerySet pipeline

### PR DESCRIPTION
**Pull request by madduck**
Currently, when pages of documents are requested from the API, the webserver logs a warning:

```
gunicorn[1550]: /home/madduck/code/paperless-ngx/.direnv/python-3.11.2/lib/python3.11/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'documents.models.Document'> QuerySet.
```

This can yield unexpected and problematic results, including duplicate and missing IDs in the enumeration, as demonstrated in https://github.com/paperless-ngx/paperless-ngx/discussions/6859

## Proposed change

The patch is simple: turn the unordered Documents QuerySet into one that's ordered by ID.

Closes: https://github.com/paperless-ngx/paperless-ngx/discussions/6859

## Type of change

- [X] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [X] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [X] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [X] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [X] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
In this example is it happening from the web UI, if so do you know where? If you’re using the API you’d just pass an ordering field

**Comment by madduck** [comment]
> In this example is it happening from the web UI, if so do you know where? If you’re using the API you’d just pass an ordering field

I think I see your point. I am using the API. However, I don't really think it should be a requirement to pass an ordering field to avoid getting duplicates or missing items in the output.

Maybe my patch is too invasive. Would you rather have it apply the ordering only if it's not already ordered?

Thanks,
martin

**Comment by shamoon** [comment]
If it has no other effects I suppose it’s fine but I will defer to @paperless-ngx/backend on that

**Comment by stumpylog** [comment]
The Document model already defines [`ordering`](https://github.com/paperless-ngx/paperless-ngx/blob/9e8b96cd34b063c1aa144a65e2df5e29c26b7428/src/documents/models.py#L278) in its `Meta` class.  A very quick `Document.objects.all().query` shows it properly includes the clause `ORDER BY "documents_document"."created"`.  If DRF is ignoring this default or stripping it, that would be a problem they should fix.

**Comment by madduck** [comment]
> The Document model already defines [`ordering`](https://github.com/paperless-ngx/paperless-ngx/blob/9e8b96cd34b063c1aa144a65e2df5e29c26b7428/src/documents/models.py#L278) in its `Meta` class. A very quick `Document.objects.all().query` shows it properly includes the clause `ORDER BY "documents_document"."created"`. If DRF is ignoring this default or stripping it, that would be a problem they should fix.

I am not an expert in Django, but I dived into the code a bit. Here is what I found, first making the code more debuggable:

```
        ret = Document.objects.distinct()
        import ipdb; ipdb.set_trace()  # noqa:E402,E702
        ret = ret.annotate(num_notes=Count("notes"))
        ret = ret.select_related("correspondent", "storage_path", "document_type", "owner")
        ret = ret.prefetch_related("tags", "custom_fields", "notes")
        return ret
```

The QuerySet instance `ret` has an attribute `ordered`, and `ret.ordered` in the above will be `True` only after the call to `distinct()`. Following `annotate()`, `ret.ordered` is `False`.

If, however, I insert `ret.order_by('-created')` before `annotate()`, then `ret.ordered` will remain `True` until the `return` statement.

**Comment by stumpylog** [comment]
Ok, sounds like this is https://code.djangoproject.com/ticket/32811 which leads to https://docs.djangoproject.com/en/4.2/topics/db/aggregation/#interaction-with-order-by

We'll need to resolve the test failures, if any come up after the re-run is completed

**Comment by madduck** [comment]
> We'll need to resolve the test failures, if any come up after the re-run is completed

I'll gladly help. I followed your [dev setup](https://docs.paperless-ngx.com/development/) instructions to the letter, but running `pytest` results in an absolute flood of errors around permission errors creating databases, improperly configured SETTINGS, and many others, thus resulting in:

```
Results (92.93s (0:01:32)):
      15 passed
       1 failed
         - paperless/tests/test_settings.py:300 TestDBSettings.test_db_timeout_with_sqlite
     950 error
      14 skipped
```

**Comment by stumpylog** [comment]
1. `pipenv sync --dev`
2. cd `src/`
3. `pytest`

You do need the same items as a bare metal install, such as Ghostscript, Poppler, etc.  That's linked in step 1

**Comment by madduck** [comment]
@stumpylog I fixed the test that was failing presumably due to the proposed change. The other failing test doesn't seem to be related, and it's weird anyway:

```
self = <documents.tests.test_api_status.TestSystemStatus testMethod=test_system_status>
[…]
>       self.assertEqual(response.data["tasks"]["redis_status"], "ERROR")
E       AssertionError: 'OK' != 'ERROR'
E       - OK
E       + ERROR

documents/tests/test_api_status.py:50: AssertionError
```

so my Redis is OK, but the test expects an ERROR?

**Comment by madduck** [comment]
> Ok, sounds like this is https://code.djangoproject.com/ticket/32811 which leads to https://docs.djangoproject.com/en/4.2/topics/db/aggregation/#interaction-with-order-by

So the fix I propose is actually the recommended way to handle it…

**Review by stumpylog — APPROVED** [review]

**Pull request merged**
