### PR TITLE
Bugfix: Fallback to pdf2image if pikepdf fails

### LINKED ISSUE #1743: [BUG] some PDFs raise a NotImplementedError
### Description

Since 1.9.2 (I skipped 1.9 and 1.9.1) account statements of german dkb bank (also ones previously working fine) get stuck in processing.
There are some statements about barcode separation, maybe something broken there, as there is no barcode visible in the PDF.
Unfortunately also "reprinting" the PDF with a tool usually fixing issues for files which cannot be processed in papaerless is not working here.
Unfortunately I cannot share samples as its bank data....

Have barcode separation enabled:
PAPERLESS_CONSUMER_ENABLE_BARCODES=true
PAPERLESS_CONSUMER_BARCODE_STRING=PATCHT

### Steps to reproduce

1. get the document consumed
2. process gets stuck in frontend
image
3. shows up as queued for quite some time
image
4. ends up as failed task

### Webserver logs

```bash
Kontoauszug_1023735317_Nr_2022_003_per_2022_08_01.pdf
HISTORY

Id:
79423d05e71d4a10b2457bf23f91cd60
Name:
Kontoauszug_1023735317_Nr_2022_003_per_2022_08_01.pdf
Func:
documents.tasks.consume_file
Hook:
-
Args:
/tmp/paperless/paperless-upload-0n2e8jty
Kwargs:
{'override_filename': 'Kontoauszug_1023735317_Nr_2022_003_per_2022_08_01.pdf', 'override_title': None, 'override_correspondent_id': None, 'override_document_type_id': None, 'override_tag_ids': None, 'task_id': 'dc8d5b5b-5eec-4395-b29a-22f4ee8df01a', 'override_created': None}
Result:
Not sure how to handle PDF image of this type : Traceback (most recent call last):
File "/usr/src/paperless/src/src/django-q/django_q/cluster.py", line 454, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 99, in consume_file
pdf_filepath, separators = barcodes.scan_file_for_separating_barcodes(path)
File "/usr/src/paperless/src/documents/barcodes.py", line 126, in scan_file_for_separating_barcodes
pillow_img = pdfimage.as_pil_image()
File "/usr/local/lib/python3.9/site-packages/pikepdf/models/image.py", line 742, in as_pil_image
im = self._extract_transcoded()
File "/usr/local/lib/python3.9/site-packages/pikepdf/models/image.py", line 606, in _extract_transcoded
if self.mode in {'DeviceN', 'Separation'}:
File "/usr/local/lib/python3.9/site-packages/pikepdf/models/image.py", line 301, in mode
raise NotImplementedError(
NotImplementedError: Not sure how to handle PDF image of this type
Group:
-
Started:
Oct. 4, 2022, 5:52 p.m.
Stopped:
Oct. 4, 2022, 5:56 p.m.
```

### Paperless-ngx version

1.9.2

### Host OS

Synology with Docker

### Installation method

Docker - ghcr.io image
webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest

### Browser

Chrome

### Configuration changes

barcodes for page separation was enabled, problem is resolved after commenting it out in compose file:
#PAPERLESS_CONSUMER_ENABLE_BARCODES=true
#PAPERLESS_CONSUMER_BARCODE_STRING=PATCHT

### Other

_No response_

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

If `pikepdf` isn't able to provide a PIL image and raises an exception, fall back to using `pdf2image`, which converts page by page to an image.

Fixes #1743 

I suspect this is the resolution for #1699 as well, since `pikepdf` isn't handling the transcode correctly in that case either.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
Based on my research for pikepdf/pikepdf/issues/401 I have added specific handling for an image encoding which I believe pikepdf should be rejecting, but currently isn't.

**Comment by smseidl** [comment]
I'm hoping to have a dev system working this weekend to try out 1.9.2 and if I can reproduce the problem with my PATCHT scans, I will then switch to this and see if it resolves.

**Comment by shamoon** [comment]
> I'm hoping to have a dev system working this weekend to try out 1.9.2 and if I can reproduce the problem with my PATCHT scans, I will then switch to this and see if it resolves.

Awesome thanks

**Comment by smseidl** [comment]
Did the git workflow change since April to not create docker images for PRs like this?  Looking it doesn't seem like any actions ran for creating an image that I can easily Pull.  Do I need to rebuild it myself?

**Comment by shamoon** [comment]
> Did the git workflow change since April to not create docker images for PRs like this?  Looking it doesn't seem like any actions ran for creating an image that I can easily Pull.  Do I need to rebuild it myself?

I think it only runs for branches `feature-...` (someone correct me if I'm wrong)

**Comment by stumpylog** [comment]
Yes, only `feature-` get made into images.  I created `feature-pdf2image-fallback` to make it easier.

**Comment by smseidl** [comment]
@stumpylog  Thanks for creating the feature branch for me.
@stumpylog  and @shamoon - I only have 1 document saved off for testing with and my scanner is out of commission for a few days.  This test file does fail in 1.9.2, and **works in both 1.8.0 and this PR.**  

One item I did notice with this PR, the split out documents (#_originaldocname.pdf) do not show up in the Queued Task list.  As they process they do show up in the Started and Completed lists.

**Comment by stumpylog** [comment]
They're likely to only be in Queued for a brief moment before a worker starts on them.  If there's not other tasks going, that should be almost immediate.

**Comment by smseidl** [comment]
My file had a total of 4 docs in it... in 1.8.0 I would see one started and 3 queued.  In this PR I only ever saw the 1 started.  As soon as that finished another would come in.  I'm running on a Chromebox converted to Ubuntu with only 2 CPU Cores so there is not much happening in parallel for this dev instance.  

Obviously this Queue list is much less important than the actual splitting of the documents :-).  I look forward to seeing the next release with this PR in it.

**Comment by shamoon** [comment]
I wonder if that's a difference with celery (assuming this was rebased to a recent `dev` I'm on my phone so not easy to check), I'll have to look at that.

Anyway, thanks for the fix as always stumpy and for verifying smseidl!

**Review by shamoon — APPROVED** [review]

**Pull request merged**
