### PR TITLE
Fix: Adds better handling for files with invalid utf8 content

### LINKED ISSUE #3338: issue UnicodeEncodeError: 'utf-8' codec can't encode character '\udcb7' in position 18: surrogates not allowed
### Description

My Docker-compose file is:
```
root@rene:~# cat paperless-compose.yml
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /mnt/paperless_smb:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1000
      USERMAP_GID: 100
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_SECRET_KEY: "a-secret-key"
      PAPERLESS_URL: http://localhost:8010
      PAPERLESS_CSRF_TRUSTED_ORIGINS: http://localhost:8010
      PAPERLESS_CORS_ALLOWED_HOSTS: http://localhost:8010
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: admin
      PAPERLESS_ADMIN_MAIL: my-mail@domain.de
volumes:
  data:
  media:
  pgdata:
  redisdata:
```

on  - /mnt/paperless_smb is my nas content mountebd about fstab:
# UNCONFIGURED FSTAB FOR BASE SYSTEM
//192.168.178.146/home/Drive/Dokumente /mnt/paperless_smb cifs credentials=/etc/smb_credentials,uid=100

paperless didt search recursive, cant activate it

### Steps to reproduce

after each restart the issue on log

### Webserver logs

```bash
[2023-05-07 11:45:08,428] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/Scan 07 Apr. 23 083731.pdf to the task queue.

[2023-05-07 11:45:08,567] [ERROR] [paperless.handlers] Creating PaperlessTask failed

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 535, in before_task_publish_handler

    PaperlessTask.objects.create(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 671, in create

    obj.save(force_insert=True, using=self.db)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save

    self.save_base(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 863, in save_base

    updated = self._save_table(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1006, in _save_table

    results = self._do_insert(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1047, in _do_insert

    return manager._insert(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1791, in _insert

    return query.get_compiler(using=using).execute_sql(returning_fields)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

UnicodeEncodeError: 'utf-8' codec can't encode character '\udcb7' in position 18: surrogates not allowed

[2023-05-07 11:45:08,575] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/ER.xlsx: Unknown file extension.

[2023-05-07 11:45:08,575] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/Mappe.xlsx: Unknown file extension.

[2023-05-07 11:45:08,576] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/Dokument (1).docx: Unknown file extension.

[2023-05-07 11:45:08,576] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/Dokument.docx: Unknown file extension.

[2023-05-07 11:45:08,576] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/Kndigung.docx: Unknown file extension.

[2023-05-07 11:45:08,581] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
```

### Browser logs

_No response_

### Paperless-ngx version

lastest

### Host OS

Ubuntu WSL2

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

see above docker compose

### Other

_No response_

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

Adds some better handling for files which aren't fully valid unicode.  In case of an error decoding the content, the bytes are read instead, decoded and errors with decoding ignored.  This removes content, so it is logged as a warning if encountered.

Fixes #3338

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — APPROVED** [review]
Thanks for the fix, test seems pretty straightforward 

I’m still sort of amazed how esoteric things like this come up (and haven’t already after all this time…)

**Comment by stumpylog** [comment]
I tweaked the error handling a bit, instead of ignore, which removes invalid, now it keeps it as a ? or the equivalent in unicode.  It seems more like what browsers and other editor are also doing when I open the same file

**Comment by shamoon** [comment]
Makes sense, yea that’s what it looks like when viewing for me

**Comment by BoBBer446** [comment]
Awesome!! Thx

**Pull request merged**
