### PR TITLE
Enhancement: custom field sorting

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

(This is last thing from me for the next release, wanted to get a bunch of these improvements to custom fields in together) 

This was actually pretty tough for me to figure out (the backend part), appreciate any thoughts about the approach. I spent a bunch of time digging into Django Queryset stuff. I think this works in the end but there may be a smarter way, or of course maybe Im missing something. I left the commit history so you can see what I tried (aka all the fumbling around I did 😅)

Screenshot 2024-12-15 at 3 42 35 PM
Screenshot 2024-12-15 at 3 43 25 PM
Screenshot 2024-12-15 at 3 43 13 PM
Screenshot 2024-12-15 at 3 42 04 PM

Closes #5434

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
Sorry, with holidays and some personal stuff, going to be a whole before I can look if you want

**Comment by shamoon** [comment]
All good, I wouldn’t be that excited about dropping a release without you being available anyway

**Review by stumpylog — APPROVED** [review]
Quite positive I couldn't test everything.  And I'm really no better on the complicated queries, they seem fine to me

**Comment by johnsturgeon** [comment]
Thank you @shamoon !  This is a game changer for me.

I'm now adding an 'expiration' date on all documents that are no longer needed after a certain date.

**Pull request merged**
