### PR TITLE
v1.7.1

### PR DESCRIPTION
**Pull request by qcasey**
## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Awesome! I've been running `dev` as changes have gone in without issue. Will double-check once the image builds but I think no issues from my end!

**Comment by stumpylog** [comment]
To get an image building from this, the branch would need to be `beta`

**Comment by shamoon** [comment]
Yea my bad, its built already aka `dev`, this is just a patch release.

**Review by shamoon — DISMISSED** [review]

**Comment by shamoon** [comment]
I think Crowdin wasn't merged before this. Can we still do that now?

**Comment by qcasey** [comment]
> I think Crowdin wasn't merged before this. Can we still do that now?

Yep, I'll merge that in

**Review by stumpylog — APPROVED** [review]
The image runs and consumed all the documents I have stored, so seems alright to me.

**Review by shamoon — APPROVED** [review]

**Pull request merged**
