### PR TITLE
Chore: limit unnecessary ci testing

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

This separates the changes from #3597 into its own PR

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other: ci improvement

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
Just to make sure, did you check a `feature-` branch will run the image build step still?  I think it would, but for a double check on what I think

**Comment by shamoon** [comment]
Sure, this is running: https://github.com/paperless-ngx/paperless-ngx/actions/runs/5301518694

**Comment by shamoon** [comment]
Hmm, good point, it didnt, not sure why?

```
if: github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/feature-') || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/beta' || contains(github.ref, 'beta.rc') || startsWith(github.ref, 'refs/tags/v'))
    ...
    needs:
      - ci-optional
```

seems like both conditions are met, ci-optional did run successfully

**Comment by stumpylog** [comment]
Hm, that's odd indeed.  It did look correct and still does...

**Comment by shamoon** [comment]
Got it! Looks like a weird GHA thing, if not quite a bug (https://github.com/actions/runner/issues/2205 & many others)

See https://github.com/paperless-ngx/paperless-ngx/actions/runs/5301674067

**Comment by shamoon** [comment]
Actually, question is if we need to put a similar condition on all subsequent steps, I think so based on that thread...

**Comment by shamoon** [comment]
updated with some logic to run build documentation when needed, added some comments too for clarity.

Defer to you, stumpy, but I think this should work as expected now

**Comment by stumpylog** [comment]
I think overall for this, though I like the idea, it adds an amount of complexity I don't like so much.  Ideally, this is something Github would build in

**Pull request closed without merging**
