### PR TITLE
Color theming

### PR DESCRIPTION
**Pull request by shamoon**
I was inspired by #241 and set about converting the CSS to use variables, that way we can derive all colors from a single variable and it lets you do cool stuff like the video below. It also significantly reduces redundant css.

My idea is to implement a new setting that allows the user to set the color of their install. I think this should be saved to the database. What do folks think?

(this is a draft for now)

https://user-images.githubusercontent.com/4887959/157351187-a83042df-72d8-41e5-b966-f9b6886ba60b.mov

### CODE REVIEW

**Comment by sense4t** [comment]
As i have some instances of paperless running simultanously, this feature would definitely be helpfull for me to separate them.

**Comment by go-ten** [comment]
Yes, that's exactly what I was thinking.

I think we shouldn't propose more changes, just the choice of the main color

**Comment by alexthamm** [comment]
I like the option to change the color. 
Except, shouldn't the logo (and other Paperless identifying characteristics) perhaps be left untouched?

**Comment by qcasey** [comment]
This is fun!

>  Except, shouldn't the logo (and other Paperless identifying characteristics) perhaps be left untouched?

I'm just impressed the logo can be changed at all. 

Nextcloud / Home Assistant lets you completely rebrand, I don't see why Paperless shouldn't if people want it.

**Comment by go-ten** [comment]
Hi,
I am ready to test on one of May test instances.

**Comment by shamoon** [comment]
Yea this is def fun (new video).

I also implemented 'live' previewing of appearance changes e.g. dark mode. Respects save (or not)

Some day we should convert (some) settings to saving to the database not just local storage.

This is pretty much ready for testing, @qcasey it shouldn't have to wait for 1.6.0 to be released (and merged back into dev), right? Not a rush ofc

https://user-images.githubusercontent.com/4887959/157558326-03e08175-070d-46ad-a7fe-da813ff5f4db.mov

**Comment by qcasey** [comment]
Super cool.

> This is pretty much ready for testing, @qcasey it shouldn't have to wait for 1.6.0 to be released (and merged back into dev), right? Not a rush ofc

Yes this can (and should) go straight into `dev`, and would be included in the next release (1.6.1 or whatever).

**Comment by shamoon** [comment]
Not sure if people got a proper notification when was changed from draft but please test away!

**Comment by qcasey** [comment]
Small bug, when you have a system wide (or browser --prefers-dark-mode) set, changing the theme color does the cool preview effect but switches to light mode. This is fixed upon save.

Another issue unrelated to this PR the "randomize" dice icon when focused disappears on light mode. (similar to #189 perhaps).

This SR demos both:

https://user-images.githubusercontent.com/1429672/157740689-201cc83d-4ef5-4c72-ab83-54e91526a185.mp4

**Comment by shamoon** [comment]
> This SR demos both:

Ah, typo—good catch thanks! Fixed the button bug too.

Anything else folks?

**Review by qcasey — APPROVED** [review]
Not from me! Looks great

**Comment by go-ten** [comment]
Great work it works perfectly !

Thks Guys

**Pull request merged**
