### PR TITLE
SSO admin group support

### PR DESCRIPTION
**Pull request by cyberb**
## Proposed change

Adds admin group support to SSO.

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

Config example:
```
    SOCIALACCOUNT_PROVIDERS = {
        "openid_connect": {
            "SCOPE": ["openid", "profile", "email", "groups"],
            "APPS": [
                {
                    "provider_id": "authelia",
                    "name": "Authelia SSO",
                    "client_id": "<insert-id>",
                    "secret": "<insert-secret>",
                    "settings": {
                        "server_url": "https://auth.example.com/.well-known/openid-configuration",
                        "scope": [...NEW...],  # <-- NEW
                    }
                }
            ]
        }
    }
```

### CODE REVIEW

**Comment by stumpylog** [comment]
Please use the template. It's provided for a reason

**Comment by shamoon** [comment]
Thanks, but:

1. I do not believe this actually adds support for groups as your title suggests, it looks like just allows you to designate superuser status.
2. Superuser != "admin"
3. This needs documentation and test coverage

Im going to mark this as draft for now as given the above it does not actually seem ready to be merged, we're happy to review once above is addressed.

**Comment by shamoon** [comment]
Also, as the template (again, please use) suggests we require that features / enhancements target an up-voted feature-request. Im not sure if there is one for this or not, if not it should be closed pending that.

**Comment by cyberb** [comment]
Sorry I needed this for Syncloud project where I want bootstrap superuser(s) from SSO.
Users do not want to touch command line.
Is there any better way to get superusers or admins from SSO?
I can add superuser group and admin group mapping if you want (I do not really need it).
In terms of test do you want a unit test for this method or you have more complex tests to look at?
I have tested this on my end of course (e2e syncloud tests) to be sure I am suggesting a working thing. Just want to have it upstream in some form.

If you do not want this it is ok.

**Comment by shamoon** [comment]
Yes, the reason we ask that PRs target a feature request is so that we're not just adding something highly-specific that one person wants for their own purposes, which is what it sounds like this really is so we will politely decline for now. Again, if you open a FR we can see what the discussion is like. Youre free to maintain your own fork, of course.

You are correct there is no automated way to do this otherwise but I think a PR for this should properly include actual groups support (I think there may be a feature request for that, but I don't totally recall).

**Pull request closed without merging**
