### PR TITLE
feat: Extend Correspondents with Category #1216

### PR DESCRIPTION
**Pull request by whvneo**
## Proposed change

Fixes #1216 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

correspondent
correspondent_2
correspondent_3
correspondent_4
correspondent_5
correspondent_6
correspondent_7
correspondent_8
correspondent_9
correspondent_10

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks for the PR!

I can imagine your personal use case but I’m not totally sure this makes sense to bring into the core. It seems like Tags anlready achieve a pretty similar effect to what this does and I’m worried about adding too many layers of seemingly-overlapping metadata. I also don’t think it will be obvious that categories are only for correspondents (and why?) and especially with the new storage paths feature the UI is starting to get rather full.

Again, certainly appreciate your hard work. I’d love to hear others opinions.

Ps. Code PRs should target `dev` not `main`

**Comment by qcasey** [comment]
I agree with shamoon - thank you putting this together with the screenshots but in its current form Categories fill the same role as Tags, but perhaps weaker. 

Your file name format could be achieved without this PR using `{tag_list}`.

Could we imagine some tweaks that would give Categories a broad, compelling use case over Tags?

**Comment by whvneo** [comment]
Hi,

thanks for reviewing and the comments and sorry for the wrong target of the PR.

I had a look "tag_list" and it is a quite "old" feature and it says it will add a comma separated list in the filename. I really don't like commas in the filename, same like other special characters. Plain old 7-bit ascii without space :-).
Also the order of the tag list is in alphabetical order and it doesn't split the documents in to separate directories.

I connected Paperless and Nextcloud to use the same directories, on nextcloud the documents folder is readonly of course. That way I can easily find my documents I'm looking for and it makes the filename shorter.

The advantage of categories linked to correspondents makes it a bit easier in the UI instead of having another field in the UI per document. 

The main target of my implementation is the target filename because using "insurance/company" as correspondents will be "insurance_company" as the directory name. 

Disadvantage of the tags are that they will be put over the thumbnails in the UI and hide some information.

Thanks for your comments

**Comment by Grmlrckr** [comment]
Hi,
sorry for "jumping in" here. I'm not a GitHub pro, so I might mix things a bit up. I hope this is the right place to give my opinion? Or is it only for the author and the "internal staff"? If so, I'm sorry!

Anyway: In my opinion that field "Category" would make absolutely sense! Maybe don't call/see it as 'Category' but maybe as "Recipient" etc. 
Something that can be used as a top level field to distinguish on a larger scale. With just one field (and level when exporting to the file system!) we would have a much better overview e.g. for different members of a family.

The problem with tags is, that you can't use them in a useful way when exporting/storing data in the file system. Because tags can't be used for the path as single parts, only all tags [for a document] together.

An (maybe stupid) example: 
File "Carbonara.pdf", Tags are: John, Recipe, Pasta

Using PAPERLESS_FILENAME_FORMAT to have tags in the file system, today it could look something like 
\MyCorrespondent\Recipe\John, Pasta\Carbonara.pdf
(\{correspondent}\{document_type}\{tag_list}\{title})

But, if we would have an additional field like 'Category' (or whatever it might be called) we could use the "John" as category and that way create it in the file system like
Category\MyCorrespondent\Recipe\Pasta\Carbonara.pdf
({category}\{correspondent}\{document_type}\{tag_list}\{title})

Of course, recipes might not be the best example, but I think you get the point.


So, if it was wrong to post that here, please take my excuse. Otherwise it might help to get a different view on that request.

**Comment by qcasey** [comment]
Thank you both for your comments! @Grmlrckr we love having extra opinions and appreciate your detailed input, and I believe most other repos on Github operate similarly. 

It sounds like the biggest issue you both have with Tags is the way they're handled in `PAPERLESS_FILENAME_FORMAT`. I agree the scenarios you bring up can't be easily done with Tags, but I'm still not sure a new field is the best way to solve this.

In my opinion a new user to Paperless might be confused seeing "Category" (or even "Recipient"); it wouldn't be immediately clear how this new field is different from "Tags" (or "Correspondent", respectively). Perhaps a rework of how tags are rendered with `PAPERLESS_FILENAME_FORMAT` can get us there.

Regardless, I'm not qualified to review the code. I'd recommend waiting on a few more opinions on this or in the discussion #1216.

**Comment by Grmlrckr** [comment]
That's right, I struggle mostly with the tags being rendered to the file path "as one part". 
At least for me it also would be sufficient to have more options here when rendering tags.

Only the path structure on the hard drive is my only issue that stops me from switching from an old Paperport (which lets me create a folder structure just like I want) to Paperless.

**Comment by whvneo** [comment]
Hi, 

that's also my concern. The filename and the directory structure.

Extending the tags with some additional information to use them as part of the filename would make it more complex than using category for the correspondents.

It would be interesting how many use the filenaming feature of paperless to find documents in a different app (for me it is nextcloud, may be a CIFS-Share for different users).
When paperless is used only, the filenaming feature would be used very seldom I guess

**Pull request closed without merging**
