### PR TITLE
Mention paperless providers for non-techy user

### PR DESCRIPTION
**Pull request by lino-b**
## Proposed change

Hey, I'm a long time user and big fan of paperless, actually using it since the beginning of -ng and I love how you people continued -ngx as a community project. After a while of using it, I came to love it so much that I wanted everybody to know about it. But there is one problem:
People who come here and wish to install paperless for themselves need to have a lot of knowlege to be able to do so: docker? What even is a server to begin with? I can imagine a lot of people who would benefit from having their paperless, but who feel overwhelmed by the thought of deploying and maintaining their instance by themselves. Also, there might be people who are perfectly able to do that but who simply prefer not to (e.g. lack of time).

This, and two friends of mine who actually asked me for a paperless setup, made me start working on a hosting solution for easy but private and secure paperless deployments. It is still in an early phase but technically already well developed and stable. Now, I'd like to share it and I thought I'd start a list of hosting providers here on the readme just [like nextcloud did](https://github.com/nextcloud/providers/tree/7ce54772fdee748adcbafa2f6fcf46f6c1ac2479) for their providers. For now, there is only my hosting platform, but other providers can join the list or can be added by their users.

Happy to read what you think of the project and to discuss the pull request.

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [x] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by Citrus0299** [comment]
Checked out your website and there are so many red flags I don't even know where to begin.
Which hosting provider are you using?
Where is my data being stored?
There are very questionable sections in your TOS which are probably superseded by us law.
Do you even plan on complying with the GDPR?
Are you using Fly.io for hosting like the IP suggests?
If you are using Fly.io, claiming "Full processing power of 1 CPU" is completely misleading, as these cpus are shared.
... and much more ...

Not disclosing your company on the site and using a 3-day old gh account to submit this pr makes it super easy to get out if things do go sideways. Is that an AI profile pick btw? Jia Tan is that you?

**Comment by shamoon** [comment]
You can add this to the wiki, but we are not going to make your commercial product the first thing mentioned in our installation instructions.

Also, good on you for finding a low-overhead business model, but I’d like to add that I find your marketing website to be fairly misleading. Not once on the site do you mention that you do not produce and are in no way affiliated with this project, effectively this surely intentionally implies to users that you are. The same is true for the apps you link to. Nor does it mention that users can install our free software on their own at absolutely no cost (not your 'free' option). There is even an FAQ question “Are you affiliated with the paperless-ngx project?” And yet somehow, your answer is vague and misleading. Even the title of this PR is misleading in its true intent, I think.

While all of this may not technically violate our rather permissive software license (I’m no lawyer), I dont find it to be in line with the spirit of the self-hosted open source community, so no, we’re not going to promote it top-of-bill here.

The decision not to merge this is a shared one, the rest is my own opinion only.

**Comment by shamoon** [comment]
Ha, funny timing. Seems our community agrees 👍

**Comment by shamoon** [comment]
Ps. This is why I love this community: high standards, sharp as a whip. All great points citrus

**Comment by lino-b** [comment]
Oh wow. I always thought that my intentions are good. But reading your comments makes me feel like I am the personified evil.

Well, since to came to a decision before even giving discussion a chance, I won't put any hope into answering. But I still feel the need to defend against the aggresive attacks that seem very unfair to me.

So,
1. Yes, AI was involved in the profile pic. What's wrong with that? (Don't know any Jia Tan though)
2. Yes, this is a freshly created github account. I have been somewhat active in the repository and contributed a few PRs with another account. I created this new one to keep things apart and tidy. Again: What's wrong with that?
3. I am very sorry about the red flags on the website I created. Really. None of them are in the intention to mislead of deceive. You just successfully found out that my strengths are not with building a landing page. I am definitely open for suggestions on how to improve.
4. You are no lawyer, and neither am I. I needed to put some ToS on the website to begin with, so that is what I did. Again, with the little knowledge I have and with no bad intention. As soon as I have the budget for professional advice, I'll rework them. If you have suggestions on how to improve the questionable parts, I'd be very thankful to hear. 
5. As for any new web service, GDPR is not the easiest thing to understand and implement and therefore not the first item on the roadmap. But I have tried to understand the requirements and yes, I try to fulfill them as far as I can. This is a work in progress and I am thankful for any advice on this.
6. Same goes for the misleading parts of the website. I thought that the answer to the "affiliated with paperless-ngx project" FAQ was clear enough but apparently it's not. What wording would you prefer?
7. Yes, Fly.io is the infrastructure provider that I use. I guess you are right about the wording being misleading. Thank you for the feedback. It's noted and I will rework that. It was written while doing many things in parallel. Creating a project like that from scratch and making it stable for productive use is not just two days of work and it's not a single-talent task.
8. Don't I have a point with open-source self-hostable software being free only as long as you are a tech-person? My mother would read words like "docker", "deploy" and immediately give up. How "free" is paperless for her?
9. Aren't we confusing free as in free software with free as in free beer?

I genuinely want to help the non-tech people to use paperless. Am I really the bad guy just because I won't pay for the infrastructure costs so that everybody else can use it for free?

-------------------

Now, thinking productive and pragmatic feedback:
In your opinion, what would I need to do to achieve the goal I set for myself (paperless for non-tech people) in a way that would not upset you? Maybe even in a way that you could endorse? Is that possible?

**Comment by shamoon** [comment]
I mean, I’m no copywriter either but I think if I was endeavoring to do what you did I would be much more up-front, that paperless is free open source software but hosting it can be challenging, and  what you provide. And again, clarifying that you are separate.

I am not suggesting you have ill-intent or that none of what you said is true, but as an AI-generated mystery person all we have to go off of is what you have made available, and you have done so far seems intentionally misleading and in some ways, skimpy on details in other ways etc.

I have no desire for you to feel persecuted, this is not meant to be unkind or personal somehow. Remember that this discussion started with you asking for us to make your commercial service the sole promoted hosting service for this project. Generally speaking that’s not something I’m all that interested in but at the very least our standards should be pretty darn high for something like that, don’t you think?

**Comment by lino-b** [comment]
Thank you, I'm glad that we can have a discussion on this. And sorry for the confusion.

I totally agree about the high standards. Technically, I thought it all through quite a few times, exactly because I aim for high standards. As for copywriting, it's the first time I do that. I think that the audience for a hosting service (instead of DIY) might not know or care about free software and open-source. I do care - I even strongly advocate for the idea behind GDPR, despite its poor implementation in Europe. But my site is probably not the right place to teach about free software. I'll do my best to try and clarify that my hosting service is not to be confused with the hosted software and will come back to ask if you find it acceptable. 

As for the commercial part of my service, I hear you. The spirit of free-and-open-source is my ground zero and I'm a long time Linux and LineageOS user for that reason. I have a normal job so I don't depend on the commercial success of my hosting project in any way. It all started as a mere hobby project for myself and two friends of mine who wanted their paperless. While it evolved, I wanted to find out how far I can take it: how reliable, how performant, how secure can I actually make it? And only now that I am satisfied with most of it, did I open it up. Instead of yet another 14-day trial period, I opted for an unlimited-time free plan with enough storage for more than a year of document imports (at least that's the time I needed to fill up 200mb of documents). I'm happy if the paid plans can pay for the infrastructure and hopefully also for legal advice, insurance, etc. so that some people can actually use their own paperless for free.

**Comment by shamoon** [comment]
I do think it's cool that you offer a free hosting option, and I appreciate that you have addressed / are planning to address the points raised so far. I am confident that doing those things would go a long way in winning the trust of the Paperless community, although of course I do not speak for anyone but myself.

**Comment by Citrus0299** [comment]
I think shamoons response is very kind and probably reflects the community best.

The things I listed in my initial response are stuff I noticed within a few minutes and without even signing up. There is a lot more I just didn't mention or overlooked. From your response, I don't think you understood what the implications are in running this project as a business. You can't just ignore regulations and international law to deal with later while actively charging customers.
There is a lot of commercial competition in this space already, but I wish you the best of luck.

**Comment by lino-b** [comment]
Ok, so I pushed some changes to the copy and added a few more backlinks to the ngx repo:
- Added "Hosting service for paperless-ngx" with a link to this repo very promimently in the header
- clarified the vCPUs
- explicitly wrote that ngx is free and open-source and can be self-hosted in the FAQ answer
- clarified that the mobile apps are community-made

I attempted to address the points you've raised and I'd appreciate any feedback on these changes. 

------

As for "affiliated" question: You consider the mobile & desktops apps, the api-clients and the prometheus exporter to be [affiliated projects](https://github.com/paperless-ngx/paperless-ngx/wiki/Affiliated-Projects). For my hosting service though, you asked that I clarify that I am separate. Since the beginning of ng I thought of myself as part of the paperless community and now I am not sure what to think: Is my project affiliated of not? I am no main contributor to this repo, but neither are the authors of the mobile apps listed as affiliated projects, of which two offer in-app-purchases and could therefore be considered commercial too. 
I am okay with both a yes or a no. I'd just like to know what you think about this.

**Comment by shamoon** [comment]
Good on you for making those changes, I think they’re overall a lot clearer. As I said, you can feel free to add a section to that page in the wiki that links to your project. I added a little clarification to the top of it.

**Comment by lino-b** [comment]
Thank you. I guess that also clarifies things for me.
I'll prepare and open a new PR.
Since my site is mainly for folks who'd struggle with the installation or the self-hosting, I think a mention of it in [Getting Started](https://github.com/paperless-ngx/paperless-ngx#getting-started) and the [setup docs](https://docs.paperless-ngx.com/setup/#installation) would be appropriate. Would you oppose it? What form could you find acceptable? One sentence with a link? A table for other potential providers to join or be added to? Merely a link back to the wiki?

**Comment by lino-b** [comment]
Well,
I answered the questions you asked and clarified what I was asked to clarify. Now let me in turn also ask for clarification:
- Of course you don't know me. What would that mean anyway? With how many other community members have you gone for a coffee yet? Your Github profile is even younger than mine. Who are you?
- Whom would I even sell data to? I mean, I am not Google. Who do you imagine being interested in random people's documents? And for what price do you imagine they would buy random documents? Then please estimate just very roughly the time I had to put into getting all this to work? (Hint: It was more than a year since this is now the third iteration of building it from scratch and guess what, it was the security aspect which made me start again from scratch) Then put the working time in relation to the money you think I could get out of selling your data. Could that be worth it in any way?
- What are the "critical security and data integrity" issues you are talking about? (You seem to assume that I know, but I don't, which is why I need to ask)
- What are the "mountains of information" missing from my site? (You seem to assume that I know, but I don't, which is why I need to ask)
- What is misleading in the headline? Is it that I used the plural form? My idea was that I'd start a list for others to join. Anyway, I don't know of any other hosting provider for paperless.

**Comment by github-Jan** [comment]
What i am missing completly is : who am i dealing with.
Not a single "address" not a single name is given. An anonymous support@email.

At least in my country (germany) you are elegally required to include basic data for "who is responsibile, who is the person / company behind that (impressumspflicht) 

That said: I like the idea and i have the same impression that a "hosted paperless" is something of a great Idea.

I love paperless
I tell everyone how great it is and i "converted" some tech savy friend of mine.
My brother is a PhD (medicine) and would love to use it. but once i told him start with a Rasperry PI, but this on the SD Card, run the docker installation script he is was out.
My parents: same, or even worse.

So a hosted Paperless would be something that i believe people would like

**Pull request closed without merging**
