### PR TITLE
Fix: preview content remains hidden on mobile

### LINKED ISSUE #2344: [BUG] PDF-Preview not visible on mobile / small screens
### Description

the mobile-view does not show the PDF-Preview. See following Screenshots for further description.

If the mobile-view is exited, it is shown (though not useable). Would assume, some JS / CSS rendering problems here. Would be nice if this could be fixed.

### Steps to reproduce

1. Visit app on mobile / small screens
2. navigate to document edit
3. view preview tab
4. no preview is shown

### Webserver logs

```bash
not relevant
```

### Browser logs

```bash
no logs occur
```

### Paperless-ngx version

1.11.3

### Host OS

Synology DSM 6.2.X

### Installation method

Docker - official image

### Browser

Chrome Version 108.0.5359.94

### Configuration changes

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Man I wish the frontend had like 300% more tests.

Screen Shot 2023-01-04 at 6 59 44 AM

Fixes #2344

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by sukisoft** [comment]
Thanks! Is there a Chance of releasing this within e.g. in 1.11.4?

**Comment by shamoon** [comment]
> Thanks! Is there a Chance of releasing this within e.g. in 1.11.4?

Yes I think so

**Review by stumpylog — APPROVED** [review]

**Comment by stumpylog** [comment]
Be the change you want to see?  🧪++

**Comment by shamoon** [comment]
> Be the change you want to see? 🧪++

Haha yes, when I have the occasional fit of patience!

**Pull request merged**
