### PR TITLE
[Beta] Paperless-ngx v2.0.0 Beta

### PR DESCRIPTION
**Pull request by shamoon**
Welcome to our latest beta release of Paperless-ngx! This version is **by far** our biggest release yet and includes some awesome new features we've been working hard on including custom fields, consumption templates and loads more. All-told this release contains hundreds commits from various contributors.

Thank you to everyone who has contributed, and thank you to the [paperless-ngx team](https://github.com/orgs/paperless-ngx/people) who continue to make Paperless-ngx the best community DMS.

## Beta Testing

A new docker container has been built at `ghcr.io/paperless-ngx/paperless-ngx:beta`. A release zip can be found in the [github pre-release](https://github.com/paperless-ngx/paperless-ngx/releases/tag/v2.0.0-beta.rc1) or the [latest CI build](https://github.com/paperless-ngx/paperless-ngx/actions?query=branch%3Abeta).

Please test this beta as best you can and report any bugs by [opening a new issue here](https://github.com/paperless-ngx/paperless-ngx/issues/new?assignees=&labels=bug&milestone=v2.0.0&template=bug-report.yml&title=[BUG]+v2.0.0+BETA-RC1+Bug). See the [pre-release changelog](https://github.com/paperless-ngx/paperless-ngx/releases/tag/v2.0.0-beta.rc1) and [closed PRs](https://github.com/paperless-ngx/paperless-ngx/pulls?q=is%3Apr+milestone%3Av2.0.0+is%3Aclosed), especially ones labeled `notable` and `non-trival`, to guide your tests.

Please remember to [make a backup](https://docs.paperless-ngx.com/administration/#backup) if you will be running this over a production installation.

⚠️ This release also contains breaking changes that may be relevant for some users, see the [pull requests](https://github.com/paperless-ngx/paperless-ngx/pulls?q=is%3Apr+label%3Abreaking-change+milestone%3Av2.0.0)

Once you have tested thoroughly for a few days and have not found any [more] issues please approve this PR. This is not simply a code review, we prefer hands-on production experience with this beta.

Some additional notes:

* The `beta` container is updated as commits are made, see the [actions tab](https://github.com/paperless-ngx/paperless-ngx/actions?query=branch%3Abeta) for progress.
* If bugs are found release candidates will be pushed as necessary.

# Thank you

Finally, if you're reading this, **thank you** for being a part of paperless-ngx! While we are proud to continue to publish new releases, we are even prouder of the collaborative process that makes it possible. Thanks to each and every person who has contributed so far 🙏

### Changes Since Opened
- Added missing translation strings (https://github.com/paperless-ngx/paperless-ngx/commit/e79015d8779ddeab54a7b12540aeb5635aa52012, https://github.com/paperless-ngx/paperless-ngx/commit/07c38d63533eec2fc872abd138cc7f40c502b6c1)
- #4598
- https://github.com/paperless-ngx/paperless-ngx/pull/4602
- Increase xxxl sidebar breakpoint for large screens bedd4dafc4bf890040da15d0489eab4698ef45f4
- https://github.com/paperless-ngx/paperless-ngx/pull/4612
- https://github.com/paperless-ngx/paperless-ngx/pull/4616
- #4623
- https://github.com/paperless-ngx/paperless-ngx/pull/4626
- #4635
- https://github.com/paperless-ngx/paperless-ngx/pull/4650
- Fix: inconsistent border colors in input groups (https://github.com/paperless-ngx/paperless-ngx/commit/1f32e4a642429afd1a12d1378c9587c8506ba8e9)
- #4660
- #4668
- #4669
- #4674

### CODE REVIEW

**Comment by LucaNerlich** [comment]
Love it! Thanks for the hard work. Will you at some point set up github sponsors?

**Comment by astubenbord** [comment]
@LucaNerlich 
> Love it! Thanks for the hard work. Will you at some point set up github sponsors?

I think they decided not to accept donations, see #2769 where some ideas are referenced.

**Comment by thegodfatherrelish** [comment]
I have installed the beta and will let you know at the weekend if I notice anything in operation; unfortunately, I can't really help you find any bugs that may still exist in the code...

**Comment by iph0nege3k** [comment]
I just wanna say I'm so hyped for this release. I cannot wait for consumption templates. I've been checking the milestones page for weeks everyday! Thanks for your hard work!

**Comment by thegodfatherrelish** [comment]
> I have installed the beta and will let you know at the weekend if I notice anything in operation; unfortunately, I can't really help you find any bugs that may still exist in the code...

Short feedback from me, so far everything is running smoothly and without error messages (Container Manager on Synology DS920+ with DSM 7.2.1). I've just used the template for the first time and think it's a great idea.

However, I have one comment. My scanner simply gives the documents the timestamp as the file name, would it be possible to trigger the use of these templates in a later version based on the text found?

Please keep up the great work!

**Comment by shamoon** [comment]
would it be possible to trigger the use of these templates in a later version based on the text found?
> 
> Please keep up the great work!

Thanks for the kind words. Yes we had that thought, turned out to not be as straightforward as we hoped so wasn't included in this. Agree it would be useful but would likely require some re-working of things.

**Comment by shamoon** [comment]
Thanks everyone for your contributions!

**Pull request merged**
