### PR TITLE
Feature: pngx PDF viewer with updated pdfjs

### LINKED ISSUE #3732: [BUG] Text is shown as garbled characters
### Description

Since the update from 1.15.x to 1.16.x along with the entire Docker Compose stack, there are difficulties with various documents. Two error patterns occur, which are also reported in the "[paperless-ngx D/A/CH Group](https://www.facebook.com/groups/1354076788492948/)" Facebook group:

1) The text of the document is properly recognised, but the document is not correctly displayed in the edit view. You only see garbled characters. I have attached an example document for this.

grafik

```
[2023-07-02 19:03:14,109] [INFO] [paperless.consumer] Consuming 0004814539_20230531.pdf
[2023-07-02 19:03:14,188] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2023-07-02 19:03:14,226] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2023-07-02 19:03:14,237] [DEBUG] [paperless.consumer] Parsing 0004814539_20230531.pdf...
[2023-07-02 19:03:17,299] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngx1jncb5dr/0004814539_20230531.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-r644_570/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-r644_570/sidecar.txt')}
[2023-07-02 19:03:23,020] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.
[2023-07-02 19:03:23,108] [DEBUG] [paperless.consumer] Generating thumbnail for 0004814539_20230531.pdf...
[2023-07-02 19:03:23,121] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-r644_570/archive.pdf[0] /tmp/paperless/paperless-r644_570/convert.webp
[2023-07-02 19:03:49,936] [DEBUG] [paperless.consumer] Saving record to database
[2023-07-02 19:03:49,957] [DEBUG] [paperless.consumer] Creation date from parse_date: 2023-05-31 00:00:00+02:00
[2023-07-02 19:03:51,627] [DEBUG] [paperless.matching] Correspondent Bank of Scotland matched on document 2023-05-31 0004814539_20230531 because it contains this string: "Bank of Scotland"
[2023-07-02 19:03:51,648] [INFO] [paperless.handlers] Assigning correspondent Bank of Scotland to 2023-05-31 0004814539_20230531
[2023-07-02 19:03:52,495] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngx1jncb5dr/0004814539_20230531.pdf
[2023-07-02 19:03:52,545] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-r644_570
[2023-07-02 19:03:52,547] [INFO] [paperless.consumer] Document 2023-05-31 Bank of Scotland 0004814539_20230531 consumption finished
```
[0004814539_20230531.pdf](https://github.com/paperless-ngx/paperless-ngx/files/11930153/0004814539_20230531.pdf)

2) The text of the document is not properly recognised and the document is not correctly displayed in the editing view. The content and the document only show confused characters. Unfortunately, I cannot make an example document publicly available because it contains personal data.

```
[2023-07-02 19:16:33,341] [INFO] [paperless.consumer] Consuming EGNW_20230623_2023-06-23_1508281.pdf
[2023-07-02 19:16:33,423] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2023-07-02 19:16:33,452] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2023-07-02 19:16:33,461] [DEBUG] [paperless.consumer] Parsing EGNW_20230623_2023-06-23_1508281.pdf...
[2023-07-02 19:16:34,958] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngx1ksbcka8/EGNW_20230623_2023-06-23_1508281.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-kmkr_v3a/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-kmkr_v3a/sidecar.txt')}
[2023-07-02 19:16:39,668] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.
[2023-07-02 19:16:39,760] [DEBUG] [paperless.consumer] Generating thumbnail for EGNW_20230623_2023-06-23_1508281.pdf...
[2023-07-02 19:16:39,771] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-kmkr_v3a/archive.pdf[0] /tmp/paperless/paperless-kmkr_v3a/convert.webp
[2023-07-02 19:16:46,726] [DEBUG] [paperless.consumer] Saving record to database
[2023-07-02 19:16:46,728] [DEBUG] [paperless.consumer] Creation date from parse_date: 2023-06-23 00:00:00+02:00
[2023-07-02 19:16:48,331] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngx1ksbcka8/EGNW_20230623_2023-06-23_1508281.pdf
[2023-07-02 19:16:48,426] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-kmkr_v3a
[2023-07-02 19:16:48,428] [INFO] [paperless.consumer] Document 2023-06-23 EGNW_20230623_2023-06-23_1508281 consumption finished
```
grafik

I suspect the error is not in Paperless itself, but in the dependencies, but I have no idea where to start to fix it. Both documents seem to have a text layer.

```
version: '3.6'

networks:
  internal:
    external: false

services:
  broker:
    container_name: paperless-redis
    image: redis:7
    networks:
      - internal
    volumes:
      # Hier den richtigen Pfad eintragen
      - /volume1/paperless/redis:/redis
    #  - /volume2/paperless/redis:/redis
    restart: unless-stopped

  db:
    container_name: paperless-db
    image: postgres:14
    # Wenn man lieber die 13 Version von PostgreSQL möchte
    # image: postgres:13
    # Nicht einfach up- oder downgraden, die Datenbank wird dann nicht mehr laden.
    networks:
      - internal
    restart: unless-stopped
    volumes:
      # Hier den richtigen Pfad eintragen
      - /volume1/paperless/db:/var/lib/postgresql/data
    #  - /volume2/paperless/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: XXX
      POSTGRES_USER: XXX
      # Hier ein anderes Passwort verwenden
      POSTGRES_PASSWORD: XXX

  webserver:
    container_name: paperless
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    networks:
      # Wenn sich der Proxy Manager auf der Synology befindet, sollte hier zusätzlich das Netzwerk davon eingetragen werden, statt einen Port freizugeben.
      - internal
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      # Diesen Teil löschen, wenn der Proxy Manager auf der Synology ist.
      # Ansonsten hier einen Port auswählen, der frei ist.
      - 8010:8000
    # - 8011:8000
    # - 8012:8000
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000']
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      # Hier die richtigen Pfade eintragen
      - /volume1/paperless/data:/usr/src/paperless/data
      - /volume1/paperless/media:/usr/src/paperless/media
      - /volume1/paperless/export:/usr/src/paperless/export
      - /volume1/homes/jbr/Paperless-Inbox:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBPASS: XXX # Das ist das Passwort von oben
      USERMAP_UID: 1032 # UserID für den docker Benutzer
      USERMAP_GID: 65537 # GruppenID für den docker Benutzer
      PAPERLESS_OCR_LANGUAGES: eng deu
      # Hier einen zufälligen Key eintragen, wenn man Paperless von Außen erreichbar machen möchte.
      PAPERLESS_SECRET_KEY: XXX
      # Hier die eigene Domain hinter localhost eintragen, wenn man einen Proxy Host benutzt, ansonsten diese Umgebungsvariable löschen.
#      PAPERLESS_ALLOWED_HOSTS: 'XXX'
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu
      # Hier anpassen, wenn man eine andere Ordnerstruktur haben möchte
      PAPERLESS_FILENAME_FORMAT: '{created_year}/{correspondent}/{title}'
      # Die nächsten drei Zeilen weglassen, wenn man Tika/Gotenberg nicht einsetzen möchte.
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000/forms/libreoffice/convert#
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      # Die nächste Zeile setzen, wenn man einen Proxy Server benutzt.
      #PAPERLESS_URL: 'https://paperless.domain.de'
      # JBR
      PAPERLESS_FILENAME_DATE_ORDER: YMD
      PAPERLESS_NUMBER_OF_SUGGESTED_DATES: 5
      PAPERLESS_IGNORE_DATES: XXX
      PAPERLESS_ENABLE_UPDATE_CHECK: 1

  db-backup:
    container_name: paperless-db-backup
    # Das Image ggf. an das obere anpassen
    image: postgres:14
    volumes:
      # Hier den richtigen Pfad eintragen
      - /volume1/paperless/db-backup:/dump
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGHOST: db
      PGDATABASE: XXX
      PGUSER: XXX
      PGPASSWORD: XXX # Das ist das Passwort von oben
      BACKUP_NUM_KEEP: 10
      BACKUP_FREQUENCY: 7d # Alle 7 Tage, kann man anpassen
    entrypoint: |
      bash -c 'bash -s <<EOF 
      trap "break;exit" SIGHUP SIGINT SIGTERM 
      sleep 2m 
      while /bin/true; do
        pg_dump -Fc > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.psql 
        (ls -t /dump/dump*.psql|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.psql)|sort|uniq -u|xargs rm -- {} 
        sleep $$BACKUP_FREQUENCY 
      done 
      EOF'
    networks:
      - internal

  # Diesen Part weglassen, wenn man keine Umwandlung von Office-Dokumenten haben möchte.
  gotenberg:
    container_name: paperless-gotenberg
    image: gotenberg/gotenberg:7.6
    restart: unless-stopped
    networks:
      - internal
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
      
  tika:
    container_name: paperless-tika
    image: apache/tika:latest
    restart: unless-stopped
    networks:
      - internal
```

### Steps to reproduce

For 1), try the attached document. 
For 2) I can make a document available privately, but it must not become public.

### Webserver logs

```bash
n/a
```

### Browser logs

_No response_

### Paperless-ngx version

1.16.5

### Host OS

Synology DSM

### Installation method

Docker - official image

### Browser

Firefox 114.0.2

### Configuration changes

_No response_

### Other

_No response_

### LINKED ISSUE #4071: Invisible text in Edit mode
### Description

When viewing a document in Edit mode, the background of the document is visible, i.e. logos layout elements, but the text is not. The text is there and can be selected and copied and pasted, but it's white-on-white. This only seems to happen on generated PDFs, not scanned PDFs.

### Steps to reproduce

Click Edit on any file. Edit and normal screenshots attached. The normal view is from within Paperless.

### Webserver logs

```bash
[2023-08-25 20:59:59,910] [INFO] [paperless.consumer] Consuming 2023-03-01 CIX (2023-05-08).pdf

[2023-08-25 20:59:59,912] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2023-08-25 20:59:59,914] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2023-08-25 20:59:59,917] [DEBUG] [paperless.consumer] Parsing 2023-03-01 CIX (2023-05-08).pdf...

[2023-08-25 21:00:00,041] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxp_b0xf8n/2023-03-01 CIX (2023-05-08).pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-dgpokpnn/archive.pdf'), 'use_threads': True, 'jobs': 12, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-dgpokpnn/sidecar.txt')}

[2023-08-25 21:00:00,503] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.

[2023-08-25 21:00:00,561] [DEBUG] [paperless.consumer] Generating thumbnail for 2023-03-01 CIX (2023-05-08).pdf...

[2023-08-25 21:00:00,565] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-dgpokpnn/archive.pdf[0] /tmp/paperless/paperless-dgpokpnn/convert.webp

[2023-08-25 21:00:08,858] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2023-08-25 21:00:08,862] [DEBUG] [paperless.consumer] Saving record to database

[2023-08-25 21:00:08,863] [DEBUG] [paperless.consumer] Creation date from st_mtime: 2023-08-25 20:59:37+00:00

[2023-08-25 21:00:08,946] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngxp_b0xf8n/2023-03-01 CIX (2023-05-08).pdf

[2023-08-25 21:00:09,007] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-dgpokpnn

[2023-08-25 21:00:09,263] [INFO] [paperless.consumer] Document 2023-08-25 2023-03-01 CIX (2023-05-08) consumption finished
```

### Browser logs

_No response_

### Paperless-ngx version

1.17.2

### Host OS

Docker on Ubuntu 22.04

### Installation method

Docker - official image

### Browser

Firefox, Chrome

### Configuration changes

Just volume mounts

### Other

_No response_

### LINKED ISSUE #4475: [BUG] Issue parsing fonts on Firefox
### Description

I have put in some documents and have big issues with a couple of them.
The issue only appears on Firefox. On Edge working fine.

The whole font is messed up. only before edited text is readable.
attached is a screenshot. 
screenshot_paperless-ngx

### Steps to reproduce

All documents from the same magazine

### Webserver logs

```bash
-
```

### Browser logs

_No response_

### Paperless-ngx version

1.17.4

### Host OS

Docker on Synology

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

_No response_

### Other

_No response_

### LINKED ISSUE #4495: [BUG] PDF preview missing some lines.
### Description

The PDF preview is not complete. When opening the pdf in a regular pdf viewer
Paperless-NGX Preview
image
Original:
image

### Steps to reproduce

Upload a pdf file
Open the edting mode.
View the preivew

### Webserver logs

```bash
-
```

### Browser logs

```bash
-
```

### Paperless-ngx version

1.17.4

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

Microsoft Edge, Chrome, Firefox

### Configuration changes

-

### Other

-

### LINKED ISSUE #4637: [BUG] Missing Text in PDF
### Description

I uploaded this PDF via consume Folder:
image

Preview: 
image

If I open it in paperless: (some Text is missing)

image

Sams Issue, if I upload the File via Browser (Web). 
If I open the PDF from the installation, text is visible, so Text is "only" missing in Web View. (\paperless\media\documents\originals\....)
It happens with all these invoices from this supplier

### Steps to reproduce

see Discription

### Webserver logs

```bash
[2023-11-19 18:33:34,012] [DEBUG] [paperless.handlers] Deleted file /usr/src/paperless/media/documents/originals/none/2023-01-16-RG-16689678.pdf.

[2023-11-19 18:33:34,012] [DEBUG] [paperless.handlers] Deleted file /usr/src/paperless/media/documents/archive/none/2023-01-16-RG-16689678.pdf.

[2023-11-19 18:33:34,012] [DEBUG] [paperless.handlers] Deleted file /usr/src/paperless/media/documents/thumbnails/0000390.webp.

[2023-11-19 18:33:42,724] [INFO] [paperless.consumer] Consuming RG-16689678.pdf

[2023-11-19 18:33:42,726] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2023-11-19 18:33:42,727] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2023-11-19 18:33:42,729] [DEBUG] [paperless.consumer] Parsing RG-16689678.pdf...

[2023-11-19 18:33:42,803] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxh9i18nge/RG-16689678.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-y_al6ygw/archive.pdf'), 'use_threads': True, 'jobs': 8, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-y_al6ygw/sidecar.txt')}

[2023-11-19 18:33:43,375] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.

[2023-11-19 18:33:43,416] [DEBUG] [paperless.consumer] Generating thumbnail for RG-16689678.pdf...

[2023-11-19 18:33:43,419] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-y_al6ygw/archive.pdf[0] /tmp/paperless/paperless-y_al6ygw/convert.webp

[2023-11-19 18:33:47,001] [DEBUG] [paperless.consumer] Saving record to database

[2023-11-19 18:33:47,002] [DEBUG] [paperless.consumer] Creation date from parse_date: 2023-01-16 00:00:00+01:00

[2023-11-19 18:33:47,203] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngxh9i18nge/RG-16689678.pdf

[2023-11-19 18:33:47,209] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-y_al6ygw

[2023-11-19 18:33:47,210] [INFO] [paperless.consumer] Document 2023-01-16 RG-16689678 consumption finished
```

### Browser logs

_No response_

### Paperless-ngx version

1.17.4

### Host OS

debian 12.2-1

### Installation method

Docker - official image

### Browser

Edge

### Configuration changes

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Feature image available at `feature-new-viewer`

~~The big issue with our current embedded viewer is that it uses an outdated version of pdfjs, Im a little reticent to drop it because it is really small but this one seems so much more actively developed and way more timely about updating pdfjs versions. The downside is https://bundlephobia.com/package/ng2-pdf-viewer@10.0.0 vs https://bundlephobia.com/package/ngx-extended-pdf-viewer@18.1.9~~

Edit: [see below](https://github.com/paperless-ngx/paperless-ngx/pull/4679#issuecomment-1834677733)

I left the commit history in case I need it some day...

I've also added a 'native' zoom control with this

Screenshot 2023-11-30 at 2 33 21 PM
Screenshot 2023-11-30 at 2 33 29 PM
Screenshot 2023-11-30 at 2 32 49 PM

Im not 100% certain it solves all of these but since almost all browser PDF viewers use pdfjs (which seem to not have the linked problems) and this would update it, I assume it would fix many / most.

Fixes #4637
Fixes #4495
Fixes #4475
Fixes #3732
Fixes #4071
and more...

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain):

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
It's a basic question, but not knowing the history, why do we embed a PDF reader instead of always relying on the browser implementation?

**Comment by shamoon** [comment]
> It's a basic question, but not knowing the history, why do we embed a PDF reader instead of always relying on the browser implementation?

Very fair question, and I ask myself that approximately every single day.

There are 'soft' benefits:
- native pages, zoom controls (which I had planned to add anyway)
- looks nicer

The only real 'hard' benefit, I think:
- some browsers actually dont support inline PDFs, the biggest offenders are mobile browsers or situations where its explicitly disabled for security reasons (apparently thats a thing)

Im not totally opposed to dropping it, but on balance between leaving it as it is currently vs dropping it I think I'd leave it since it probably is very important to the users in that latter category and the only real downside is some occasional user frustration and us having to triage GH issues =)

Yea, this is still a draft cause Im still chewing on it. I've also discovered it increases the size of our releases. I considered forking the dep we currently use, but not sure I want to open that can of worms...

Open to feedback on the change itself or the larger question.

**Comment by shamoon** [comment]
Ok, taking a totally different approach here, I've basically pulled the pdf viewer dependency into our project (with light modification). The big thing is this still updates pdfjs to 3.11 (unfortunately, in the interim they've released [v4](https://github.com/mozilla/pdf.js/releases/tag/v4.0.189) which seems like one big breaking change 😑, but this should still have some improvements for users).

Its a little ugly, if Im honest, but the good news is if / when the dependency does get updated it won't be such a big deal to swap it back in.

Would love to get some testing of this, obviously I did myself and fundamentally it shouldn't be so different from our current one, but still.

**Comment by stumpylog** [comment]
I try with a new PDFs, one from a linked issue.  It looked good to me in both versions, so kind of hard to test it extensively.  I didn't notice anything not working though, so that's good too.  It does seem like getting a more updated pdf-js is good.  How much more recent does this bring us to?

**Comment by shamoon** [comment]
Thats precisely my aim, to not really be noticeable.

This gets us from 2.16.105 to 3.11.174, big leap for that. And v4 literally came out a couple weeks ago, at some point we can look to v4

**Comment by shamoon** [comment]
I'll mark this as ready, but not enabling auto-merge yet

**Comment by shamoon** [comment]
Yea sure:
Screenshot 2023-12-03 at 11 34 55 PM

**Comment by stumpylog** [comment]
I checked this out with the file from #4495 and it does fix the display issues.  I haven't noticed any new issues with PDFs either.

**Comment by shamoon** [comment]
Alright cool, I'll keep an eye on it too, something tells me if there are problems we'll hear about it... 😜

**Pull request merged**
