### PR TITLE
chore: remove ansible playbooks and documentation

### PR DESCRIPTION
**Pull request by slankes**
Remove the ansible support from the main repo.

Rationale:

- lower overall complexity
- if somebody shows up who wants to maintain the roles they could be moved to a seperate repository inside the organisation

### CODE REVIEW

**Comment by bauerj** [comment]
Looks like something went wrong in the README. Some changes regarding the translation have been reverted.

**Comment by torwag** [comment]
Wouldn't the same be true for the docker files and scripts?
Removing them from the main repo and adding them in a docker-paperless-ngx would make maintenance of both projects side by side, easier and makes the main repro less complex (less files and folders to take care of).

**Comment by tribut** [comment]
Docker is our main mode of deployment and needed for CI. Don't think it's equally a "bonus feature" as ansible.

**Comment by Timoms** [comment]
> Wouldn't the same be true for the docker files and scripts? Removing them from the main repo and adding them in a docker-paperless-ngx would make maintenance of both projects side by side, easier and makes the main repro less complex (less files and folders to take care of).

I do feel like we should offload the project into multiple repos too, but someone mentioned that CI will get more complex with multiple repos (like pushing to the main and testing the subrepo with changes on the main repo).

Maybe splitting in different repos (or the actual roadmap) should get another discussion...?

**Comment by yschroeder** [comment]
Things like docker configuration might only work with a specific version of the code. Thus having them side by side in one repo ensures that you always have the correct version of both.

We had the discussion in matrix for the UI but the argument is valid for many parts of the project.

**Comment by jovandeginste** [comment]
Docker can (and IMHO should) be used for "building the code". I'm not a Python programmer, and Paperless uses other components.

It's easier to have a "docker build" command ready, which is supposed to work regardless of your personal environment, and is supposed to not pollute your personal environment. And then the CI-setup should be easy, because that also uses that Dockerfile.

**Comment by slankes** [comment]
> Looks like something went wrong in the README. Some changes regarding the translation have been reverted.

Fixed

**Comment by morremeyer** [comment]
I agree here that the Dockerfile and others belong in the main repository as means of building the software in its standardized way.

Ansible as one of many possible deployment solutions however does not.

**Comment by bauerj** [comment]
I would accept these changes as they do what they should.

However, it seems like there is no consensus on whether Ansible should be removed or not. I have created a poll in our matrix channel, so please vote on whether or not you want to remove it.

**Review by bauerj — APPROVED** [review]
LGTM.

**Pull request merged**
