### PR TITLE
fix: exclude cypress from build in Dockerfile

### PR DESCRIPTION
**Pull request by FrankStrieter**
## Proposed change

- Fix building the fronend app an armv7. 
  - skip installation of cypress in the Dockerfile. It is not needed in production and causes errors an armv7  

Fixes # (issue)
#524 
@paperless-ngx/ci-cd (GitHub Actions, deployment)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

### CODE REVIEW

**Comment by FrankStrieter** [comment]
@paperless-ngx/ci-cd I have no idea to test this, can anyone help, please?

**Comment by shamoon** [comment]
Stupid question, why not `npm ci --production`?

**Comment by shamoon** [comment]
Ok, now that I've gotten past my momentary lapse of brainpower, I see no reason this would fail, we can just merge it and try? =)

**Comment by qcasey** [comment]
We don't have a sufficient process for testing yet, we have some ideas to explore in the coming months. 

For now I'll fork this to a feature branch, it'll run there

**Review by qcasey — APPROVED** [review]

**Review by shamoon — APPROVED** [review]

**Comment by shamoon** [comment]
Seems all good, bravo!
https://github.com/paperless-ngx/paperless-ngx/runs/5688098382?check_suite_focus=true#step:7:7182

**Pull request merged**
