### PR TITLE
Removes Coveralls from Dependabot

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

This pull request removes the coveralls coverage data gathering from any branch which includes "dependabot".  It would be probably easier for this to go in after #324 since that once changes the workflow file a lot more.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/contributing.html#pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Awesome thanks! one more thought: should we also change it to only run if changes are made inside `src` since that’s the only place it runs? :)

**Comment by stumpylog** [comment]
Ok, I think that latest will only run `coveralls` if `src/*` changed.  It looked to work [over here on my fork](https://github.com/stumpylog/paperless-ngx/runs/5558612233?check_suite_focus=true).  I'm not 100% sure about pull request vs just pushes, but I think it will be ok.

**Review by bauerj — APPROVED** [review]

**Comment by bauerj** [comment]
Thanks, let's see if this works as intended 😊

**Comment by shamoon** [comment]
So far so good! 😎 e.g. 462

**Pull request merged**
