### PR TITLE
Feature: Rename documents when storage path format changes

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

Feature request from #2695.  When a storage path changes, the document is renamed if needed and it's possible.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
That was fast! Good change, this has always seemed odd. Will check it out later

**Review by shamoon — APPROVED** [review]
Awesome, seems to work great! I removed the obsolete UI warning. 

IIRC bulk editing is sort of a separate issue but now it feels even weirder that bulk edit doesn't change the location. A fun test for example was I bulk edited 2 docs to have a SP (so they didn't move), then edited a third directly (it did move), then I updated the SP and all 3 ended up in the right place =)

If we don't want to deal with bulk editing at the moment that's cool, again this does as-intended, just noting.

**Comment by stumpylog** [comment]
Bulk editing of storage paths should already work (and did for me).  It sends the `post_save` signal out for each affected document, but may take a few, since it's delegated to a celery task.

**Comment by shamoon** [comment]
> Bulk editing of storage paths should already work

Well that's very good news, and indeed I can't recreate the situation described above. Fantastic, I think makes this feature significantly more approachable

Just out of curiosity, the last commit making it a bulk edit operation is to prevent things being done out of order? Or why? (again, just curious)

**Comment by stumpylog** [comment]
The code in the signal runs in the same process as the request to the API.  So if you have x documents with the path applied, it would have waited for all documents to be renamed/moved.

**Comment by stumpylog** [comment]
Sorry, a little churn while I thought through the change more.  It felt more correct doing this at the API when the StoragePath is begin updated, more like how other bulk updates are done.

**Comment by shamoon** [comment]
Yes I noticed that, make sense to me. Still works great in my testing, I did notice a completely unrelated bug =)

**Pull request merged**
