### PR TITLE
Documentation style

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

(screenshots below)

And so I continue my quest to make everything about this project beautfiul-ish. This [entirely superflous] PR updates the visual style of the documentation. The current theme is not great in many ways, imho. This PR does not in any way change the structure, content or code (still uses the same theme with additional css).

- Biggest goal here was to improve the typography. This opts for system fonts, increases line heights, etc. I find it to be much more legible.
- I didnt touch every color etc but tried to make things less jarring color-wise.
- Didnt go crazy with branding or anything.
- Most of styling stuff is cribbed from other popular online documentation styles.
- Hopefully I didnt miss anything big!
- All changes contained in one 5kb css file

Edit: I removed the single content change, its cleaner this way.

Screen Shot 2022-04-05 at 3 30 39 PM
Screen Shot 2022-04-05 at 3 32 29 PM
Screen Shot 2022-04-05 at 3 32 13 PM

Mobile:
<p float="left">
Screen Shot 2022-04-05 at 7 58 20 PM
Screen Shot 2022-04-05 at 7 58 30 PM
</p>

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by crazychatting** [comment]
looks pretty neat! do you think a dark-mode could be applied easily on this theme/style too?

**Comment by shamoon** [comment]
> looks pretty neat! do you think a dark-mode could be applied easily on this theme/style too?

Thanks :)

My goal with this was just to update the style not add any functionality or modify the theme. Dark mode would need a button or something to turn it off (at least that seems to be convention) so would at least need to add some JS. I wanted to keep this one “clean” but yea that would be pretty straightforward to implement in another PR.

**Comment by qcasey** [comment]
This looks so much cleaner, definitely a big improvement!

The purple #7253ed seems random, why was that color picked? 

> Dark mode would need a button or something to turn it off (at least that seems to be convention) so would at least need to add some JS.

Couldn't this just use the css prefers-color-scheme?

I'll dig deeper a little later for other notes.

**Comment by qcasey** [comment]
Cool. I tested this locally and it looks great. However there's an empty scroll channel on the sidebar, are you seeing this?

It shows up on Firefox and Chrome for me:

Screenshot from 2022-04-07 08-35-55
Screenshot from 2022-04-07 08-36-07

**Comment by shamoon** [comment]
> Cool. I tested this locally and it looks great. However there's an empty scroll channel on the sidebar, are you seeing this?
> 
> It shows up on Firefox and Chrome for me:

Oddly, no. What os / versions? Youre on 'nix or pc?

**Comment by shamoon** [comment]
Ok should be sorted, please re-check, LMK if anything else

**Review by qcasey — DISMISSED** [review]
Nice, thank you!

**Comment by shamoon** [comment]
sorry fixed one more tiny thing, g2g

**Review by qcasey — APPROVED** [review]

**Review by stumpylog — APPROVED** [review]
Looks nice!  Can't say I know the CSS portion, but the outcome looks good.

**Comment by shamoon** [comment]
> Looks nice! Can't say I know the CSS portion, but the outcome looks good.

Ha fair enough, honestly this is pretty 'low stakes', its just css for the documentation, very easy to change / fix, etc in the future.

And yes, I'll get around to dark mode...

Huzzah!

**Pull request merged**
