### PR TITLE
Development: frontend unit testing

### PR DESCRIPTION
**Pull request by shamoon**
> Be the change you want to see?  🧪++

_Originally posted by @stumpylog in https://github.com/paperless-ngx/paperless-ngx/issues/2346#issuecomment-1371523281_
            
```bash
File                   | % Stmts | % Branch | % Funcs | % Lines |               
-----------------------|---------|----------|---------|---------|
All files              |   97.01 |    88.35 |   95.75 |   97.11 |

Test Suites: 106 passed, 106 total
Tests:       577 passed, 577 total
```

This PR is a full implementation of frontend unit (component) testing. Glad to be done 😮‍💨

- [x] ~~I suppose we should include coverage reports in codecov? Think I'd need a hand with setting that up.~~ Edit: done
- This PR also contains ci changes to only run tests (back + frontend) if changes detected, certainly saved lots of time in working on this, but welcome any thoughts / feedback.
- This probably means we can remove some of the e2e tests, but no real urgency to do that, the time they take on ci is 75% installation so reducing the n won't do much, I think
- I realize it's a ridiculously-large diff. Changes to the codebase are very minimal, like basically syntax things, so Im not expecting any issues there. As for the tests, Im sure there are some tests that have issues but my feeling is that we can start to refine things from here. Of course I welcome any specific feedback, just dont know how realistic that is...

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other: tests

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Ironically it's the playwright tests that are failing, for reasons I do not understand, but not due to this PR (it doesn't change them at all)

```
Chromium 115.0.5790.24 (playwright build v1067) downloaded to /home/runner/.cache/ms-playwright/chromium-1067
...
Error: browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium-1064/chrome-linux/chrome
```

**Comment by stumpylog** [comment]
- For the CI improvements, what about pulling those out to a different PR so they can get reviewed a little easier?
- I think adding a codecov upload step, like the backend tests, will probably work as is.  I'd add the flag for frontend, just to allow differentiation a little bit in the UI.  If that doesn't just work, maybe something here: https://about.codecov.io/tool/jest/

**Comment by shamoon** [comment]
Cool, I separated the PRs and added uploading to codecov
Screenshot 2023-06-16 at 8 09 00 PM

**Comment by tribut** [comment]
Very impressive, thanks so much!

**Review by stumpylog — APPROVED** [review]
I can't really comment on the actual changes or tests, but CI seems good.  It'll be neat to see this in codecov too

**Pull request merged**
