### PR TITLE
Fix: Prioritize TokenAuthentication before others

### PR DESCRIPTION
**Pull request by Pizmovc**
## Proposed change

When calling the API, an Authorization header with token should be enough to authenticate the user, but since it has the lowest priority amongst all the authentication classes the call fails since there is no CSRF cookie set.

Moving the TokenAuthentication class higher in the array solves this issue.

Inspiration:
- https://stackoverflow.com/questions/49388349/django-rest-asks-for-csrf-token-even-with-tokenauthentication

NOTE: **Please take over this PR if more changes then this oneline change is needed.** I'm not a Django or a Python developer, but it seemed simple enough fix to open a PR.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — DISMISSED** [review]
This makes sense to me, but Im inlined to let the backend team weigh in before merging.

Thanks for the fix!

**Comment by stumpylog** [comment]
Perhaps it's my testing, but I still require a CSRF cookie when posting to an API endpoint (except `/api/token/`) with this change.

**Comment by shamoon** [comment]
Well, or its my testing that's off =)
I'll check again

**Comment by Pizmovc** [comment]
I'll be frank and say that I did not test this change before opening this PR.

But looking at the [Authentication documentation](https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication), `manage.py migrate` has to be run when changing any settings. 

Perhaps that could be the issue?

**Comment by shamoon** [comment]
No that's not the case I don't think.

What is the specific setup + scenario you run into the problem? Im having trouble recreating the issue and I regularly make POST requests directly against my install with only token auth.

**Comment by Pizmovc** [comment]
I have a script for scanning and uploading documents to paperless which at some point calls `httpie`.


<details>
<summary>API returns with `CSRF Failed: Referer checking failed - no Referer`</summary>

```
$ http -f POST https://MY_DOMAIN/api/documents/post_document/ "Authorization: Token MY_TOKEN" document@"~/doc.pdf" --ignore-stdin
HTTP/1.1 403 Forbidden
Allow: POST, OPTIONS
Alt-Svc: h3=":443"; ma=2592000
Content-Language: en-us
Content-Length: 63
Content-Type: application/json
Cross-Origin-Opener-Policy: same-origin
Date: Fri, 10 Mar 2023 18:14:29 GMT
Referrer-Policy: same-origin
Server: Caddy, uvicorn
Set-Cookie: csrftoken=IrJHaTtw8xkBbDcfuwF1E4xmHB8CXyT2; expires=Fri, 08 Mar 2024 18:14:30 GMT; Max-Age=31449600; Path=/; SameSite=Lax
Set-Cookie: sessionid=go79ye3ub4auw2tywkflxfz2cf80r4ii; expires=Fri, 24 Mar 2023 18:14:30 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax
Vary: Accept, Cookie, Accept-Language, Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN

{
    "detail": "CSRF Failed: Referer checking failed - no Referer."
}
```

</details>

Paperless is running behind Caddy reverse proxy.

What might be related is that it also uses Authelia as authentication source. Paperless is configured to use the remote user header set by Authelia and copied over by Caddy (and that part works), but I have bypassed the need for authentication for any paths starting with `/api/` on the Paperless domain, because it makes no sense to use it there. The API should handle authentication on its own.

<details>
<summary> I can query the API with no issue </summary>

```
$ http https://MY_DOMAIN/api/documents/145/ "Authorization: Token MY_TOKEN"
HTTP/1.1 200 OK
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Alt-Svc: h3=":443"; ma=2592000
Content-Encoding: br
Content-Language: en-us
Content-Length: 982
Content-Type: application/json
Cross-Origin-Opener-Policy: same-origin
Date: Fri, 10 Mar 2023 18:23:35 GMT
Referrer-Policy: same-origin
Server: Caddy, uvicorn
Set-Cookie: csrftoken=eMpXBHsn5QT1av5Cc5TWMOHUdRDwwSwq; expires=Fri, 08 Mar 2024 18:23:36 GMT; Max-Age=31449600; Path=/; SameSite=Lax
Set-Cookie: sessionid=dg8xqquj2hwpriso2v36w09je290euxz; expires=Fri, 24 Mar 2023 18:23:36 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax
Vary: Accept, Cookie, Accept-Language, Origin, Accept-Encoding
X-Api-Version: 2
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Version: 1.13.0

{
    ...document details are here
}
```

</details>

**Comment by Pizmovc** [comment]
As I was digging into this issue just now, I noticed something strange.

<details>
<summary>I can query the API with no Authorization header set</summary>

```
$ http https://MY_DOMAIN/api/documents/145/
HTTP/1.1 200 OK
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Alt-Svc: h3=":443"; ma=2592000
Content-Encoding: br
Content-Language: en-us
Content-Length: 982
Content-Type: application/json
Cross-Origin-Opener-Policy: same-origin
Date: Fri, 10 Mar 2023 18:30:13 GMT
Referrer-Policy: same-origin
Server: Caddy, uvicorn
Set-Cookie: csrftoken=5mY78mE1aWI2l0JHtfWCK0TyiyWk0kIa; expires=Fri, 08 Mar 2024 18:30:13 GMT; Max-Age=31449600; Path=/; SameSite=Lax
Set-Cookie: sessionid=ev6wezm8jw79bhnx9tixyckpqp95udg2; expires=Fri, 24 Mar 2023 18:30:13 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax
Vary: Accept, Cookie, Accept-Language, Origin, Accept-Encoding
X-Api-Version: 2
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Version: 1.13.0

{
   ...document details
}
```
</details>
<details>
<summary>I found an extra user!</summary>

Username is `{http.reverse_proxy.header.Remote-User}`.


image

</details>

It gets recreated with every `curl` or `http` call, so it looks to me like since I'm not adding any Authentication tokens to my request, it creates a blank user and uses that as allowed access?

Might be related to this issue, or it might be a red-herring, but I can open a separate issue for this.

**Comment by stumpylog** [comment]
The remote user authorization is 100% Django's implementation, so I would be doubtful there's a problem with it.  As expected, I am not able to query the API without authorizing in some fashion, domain or localhost.

To me, all this is pointing to a misconfigured proxy or settings for the remote user header.

**Comment by shamoon** [comment]
I’m inclined to agree this is a setup issue and looking back through issues on this, it has been generally in the past. Also it sounds like youve found that your PR doesn’t change anything here so Im gonna close the PR for now (of course we can reevaluate)

I have a very similar setup with traefik instead of caddy and I’m able to use the API with token auth only without issues.

I noticed in your API query above you are passing the session cookie, so that’s how it’s authenticating. Also, in reading about this I believe that’s what would trigger the csrf requirement

Clearly this stuff can be a bit tricky

**Comment by Pizmovc** [comment]
I agree with both of you. It does look like I should first make sure that this is not an issue on my side.

> Perhaps it's my testing, but I still require a CSRF cookie when posting to an API endpoint (except `/api/token/`) with this change.

That is unexpected to me. Shouldn't an API with an token header skip any CSRF checks?

Thanks for your time!

**Comment by shamoon** [comment]
> Shouldn't an API call with an token header skip any CSRF checks?

Yes that’s kind of the crux of the issue here :) In our private discussions we can’t reproduce the problem (either of us), as I said it’s a bit tricky!

Again, for sure if you gain some more insight and we can identify a clear issue we’re happy to re-assess

**Comment by shamoon** [comment]
For example the iOS shortcut and I have to imagine many of the apps that use the api don’t have this issue.

**Pull request closed without merging**
