### PR TITLE
[Beta] Paperless-ngx v1.10.0 Release Candidate 

### PR DESCRIPTION
**Pull request by stumpylog**
Hello and welcome to a new release!  We've fixed a number of things and added a few new features (see release notes for details), all thanks to the hard work of the team and all our contributors.  A big thank you to everyone who contributed, whether with code updates, reporting issues and answering discussions.

## Release Highlights

- This release sees the backend switch away from `djano-q` to `celery` for task processing.  We've made every effort to make this as seamless as possible.  For our Docker users, the additional services are included.  For those installing via bare metal, please review the installation instructions; there are some additional services needed
- For users who like metrics, the Docker image can optionally start [flower](https://flower.readthedocs.io/en/latest/) which provides deep details into the performance of tasks.  Please review the [advanced setup documentation](https://paperless-ngx.readthedocs.io/en/beta/advanced_usage.html#celery-monitoring) for more info
- We're happy to include [qpdf 11](https://qpdf.readthedocs.io/en/stable/release-notes.html) in the Docker image, which brings with it performance enhancements and many other improvements and fixes

As always, the release changelog contains all the fixes and improvements the team has been working hard on and we encourage you to review it in detail.

## Beta Testing

A new docker container has been built at `ghcr.io/paperless-ngx/paperless-ngx:beta`. A release zip can be found in the [github pre-release](https://github.com/paperless-ngx/paperless-ngx/releases/tag/v1.10.0-beta.rc1) or the [latest CI build](https://github.com/paperless-ngx/paperless-ngx/actions?query=branch%3Abeta).

Please test this beta as best you can and report any bugs by [opening a new issue here](https://github.com/paperless-ngx/paperless-ngx/issues/new?assignees=&labels=bug&milestone=v1.10.0&template=bug-report.yml&title=[BUG]+v1.9.0+RC1+Bug). See the [pre-release changelog](https://github.com/paperless-ngx/paperless-ngx/releases/tag/v1.10.0-beta.rc1) and [closed PRs](https://github.com/paperless-ngx/paperless-ngx/pulls?q=is%3Apr+milestone%3Av1.10.0+is%3Aclosed), especially ones labeled non-trival, to guide your tests.

Please remember to [make a backup](https://paperless-ngx.readthedocs.io/en/latest/administration.html#making-backups) if you will be running this over a production installation.

Once you have tested thoroughly for a few days and have not found any [more] issues please approve this PR. We generally aim for **about 5 tested approvals** before this is merged. This is not simply a code review, we prefer hands-on production experience with this beta. The beta will be open for at least 5 days.

Some additional notes:

* The `beta` container is updated as commits are made, see the [actions tab](https://github.com/paperless-ngx/paperless-ngx/actions?query=branch%3Abeta) for progress.
* If bugs are found release candidates will be pushed as necessary.

# Thank you

If you're reading this, **thank you** for being a part of paperless-ngx! While we are proud to continue to publish new releases, we are even prouder of the collaborative process that makes it possible. Thanks to each and every person who has contributed so far 🙏

## Changes Since Opened

- #1967 
- #1998
- 023c931401db7236d2d1f10def76c1855f465917 Fix top search not working due to missing button type
- 0ae8200593e6c92f92004c2bf13f1e19d930775e Fix link to flake8 linter
- #2016 
- #2017 
- #2023
- #2025

### CODE REVIEW

**Comment by shamoon** [comment]
So much work goes into every one of these, bravo everyone! So far so good for me, upgraded production install with just a change to `:beta`—off on the right foot 😎

**Comment by stumpylog** [comment]
I've upgrade my own instance to the `:beta` tag.  The migrations went off without a hitch and consumption with automatic tagging worked great.  :heavy_check_mark:

**Comment by darkobg79** [comment]
Thank you guys. Amazing job is done.

**Comment by shamoon** [comment]
Good catch in https://github.com/paperless-ngx/paperless-ngx/pull/1644#issuecomment-1312473477 I merged into here so maybe a few translations for those buttons will get done on Crowdin before we release this. We'll also need to merge #1971 here at the last possible second, of course.

**Comment by sarakha63** [comment]
Hello just tried the beta on my production.

No issue found so far

I have a question, how can we change the planification as now since the change to celery we only have access to the results and i didnt seem to find the tasks

**Comment by stumpylog** [comment]
I'm not following what you mean by"planification".  The consume tasks and status are still visible in the frontend, with more details visible in the admin pages.

**Comment by sarakha63** [comment]
I mean previously

we were able to change the train classifier  planning

the mail searcher planning also and so on


All this was visible on the admin page on the django list tasks and were editable


Now it seems on the celery section we only have "group results"  "tasks results"

we can not edit the tasks anymore (or i didnt find them)

**Comment by stumpylog** [comment]
Currently, it isn't possible to edit the timing of scheduled tasks with celery.  Allowing more control over that is something I'd like to implement, but it won't make it into this release.

**Comment by sarakha63** [comment]
@stumpylog  it would be great. As it is sometimes usefull when we have hundred of same new documents. generally i scan 5 of them tag them. Train the classifier. And then scan the others and generally it performs well and the manual check is faster to do.


I think i found a bug on this beta. The search box (the one on the top header of paperless (in the green part) doesn't seem to work anymore

Regards

**Comment by shamoon** [comment]
> I think i found a bug on this beta. The search box (the one on the top header of paperless (in the green part) doesn't seem to work anymore

Whoops, that was a silly one 😅, should be fixed now, thanks for reporting!

**Comment by sarakha63** [comment]
> > I think i found a bug on this beta. The search box (the one on the top header of paperless (in the green part) doesn't seem to work anymore
> 
> Whoops, that was a silly one 😅, should be fixed now, thanks for reporting!

confirmed working now ;) THX

**Review by shamoon — DISMISSED** [review]
Happy with this, havent seen anything in my day-to-day other than the small issue reported so far. There are some small PRs just merged but dont think that prevents my approval here.

LGTM!

**Comment by slankes** [comment]
I've updated my production instance today and everything still works. Good work!

**Comment by amo13** [comment]
A switch to celery sounds great! I have 3 instances of paperless running in parallel on my server. Will it be possible for them to share a single celery and redis instance?

**Comment by kprnks** [comment]
Hi all,

I like using paperless; it is a quite fine web application.

I recently updated to paperless-ngx 1.10.0-beta running in a docker container on a Raspi 4B (4 GB).

Besides uploading new files via the browser (works fine), I also use the REST API to provide new documents. Since the upgrade to 1.10.0-beta the REST API upload does not work anymore. The upload itself is successful, but when paperless tries to set the provided creation date, it fails:

```
[2022-11-22 12:20:32,436] [ERROR] [paperless.handlers] Creating PaperlessTask failed: malformed node or string: <ast.Call object at 0xb4ee8610>
[2022-11-22 12:20:32,573] [INFO] [paperless.consumer] Consuming PDFTest.pdf
[2022-11-22 12:20:32,577] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2022-11-22 12:20:32,579] [INFO] [paperless.consumer] Executing pre-consume script /usr/src/paperless/script/preconsume-preconsumedoc.sh
[2022-11-22 12:20:32,607] [INFO] [paperless.consumer] /usr/src/paperless/script/preconsume-preconsumedoc.sh exited 0
[2022-11-22 12:20:32,612] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2022-11-22 12:20:32,635] [DEBUG] [paperless.consumer] Parsing PDFTest.pdf...
[2022-11-22 12:20:33,603] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-upload-gbq4ehve
[2022-11-22 12:20:33,846] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-upload-gbq4ehve'), 'output_file': '/tmp/paperless/paperless-acb916vd/archive.pdf', 'use_threads': True, 'jobs': 4, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-acb916vd/sidecar.txt'}
[2022-11-22 12:20:35,609] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.
[2022-11-22 12:20:36,337] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-acb916vd/archive.pdf
[2022-11-22 12:20:36,338] [DEBUG] [paperless.consumer] Generating thumbnail for PDFTest.pdf...
[2022-11-22 12:20:36,353] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-acb916vd/archive.pdf[0] /tmp/paperless/paperless-acb916vd/convert.webp
[2022-11-22 12:20:43,706] [DEBUG] [paperless.consumer] Saving record to database
[2022-11-22 12:20:43,707] [DEBUG] [paperless.consumer] Creation date from post_documents parameter: 2022-10-01T01:00:00+02:00
[2022-11-22 12:20:44,506] [ERROR] [paperless.consumer] The following error occurred while consuming PDFTest.pdf: 'str' object has no attribute 'utcoffset'
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 383, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 122, in set_document_type
    potential_document_type = matching.match_document_types(document, classifier)
  File "/usr/src/paperless/src/documents/matching.py", line 43, in match_document_types
    return list(
  File "/usr/src/paperless/src/documents/matching.py", line 44, in <lambda>
    filter(lambda o: matches(o, document) or o.pk == pred_id, document_types),
  File "/usr/src/paperless/src/documents/matching.py", line 104, in matches
    log_reason(matching_model, document, f"it contains this word: {word}")
  File "/usr/src/paperless/src/documents/matching.py", line 17, in log_reason
    f"{class_name} {matching_model.name} matched on document "
  File "/usr/src/paperless/src/documents/models.py", line 249, in __str__
    created = datetime.date.isoformat(timezone.localdate(self.created))
  File "/usr/local/lib/python3.9/site-packages/django/utils/timezone.py", line 232, in localdate
    return localtime(value, timezone).date()
  File "/usr/local/lib/python3.9/site-packages/django/utils/timezone.py", line 217, in localtime
    if is_naive(value):
  File "/usr/local/lib/python3.9/site-packages/django/utils/timezone.py", line 269, in is_naive
    return value.utcoffset() is None
AttributeError: 'str' object has no attribute 'utcoffset'
[2022-11-22 12:20:44,510] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-acb916vd
```

The upload is done via this (simplified) code:

```
#!/usr/bin/env python
import requests
import json

url = "http://<paperless-url>:<port>"
doc = "/path/to/a/pdf/file.pdf"

credentials = {"username": "<paperless-user>",
               "password": "<password>"}

sess = requests.Session ()

# ############## login
response = sess.get (url)
csrfToken = response.cookies ['csrftoken']
response = sess.post (url + "/api/token/",
                      data=credentials,
                      headers={'X-CSRFToken': csrfToken}
                     )

if response.status_code == 200:
  responseJSON = json.loads (response.text)
  authToken = responseJSON["token"]

  # ############## doc upload
  f = open (doc, "rb")
  filesPayload = {"document": f}
  otherPayload = {"correspondent": 20,
                  "title": "MyDocument",
                  "created": ("2022-10-01T00:00:00+01:00")
                  }
                  # also tried "created": ("2022-10-01 00:00Z")
  response = sess.post (url + "/api/documents/post_document/",
                        data=otherPayload,
                        files=filesPayload,
                        headers={"Authorization": f"Token {authToken}",
                                 f"X-CSRFToken": csrfToken}
                       )
  
  if response.status_code == 200:
    print ("successfully uploaded")
  else:
    print ("error while uploading")
    print (response.status_code)
    print (response.text)
```

When removing the "created" line from the "otherPayload" dictionary, everything works fine.

Is anyone able to reproduce this failure or is it just an error within my setup?

Regards,
Michael

**Comment by stumpylog** [comment]
> Will it be possible for them to share a single celery and redis instance?

Possible, probably, with what I expect to be a lot of manual configuration.  It's not something I'm planning to work on, but if you can get it working and document it, we'd be happy to include it as advanced setup.

**Comment by kprnks** [comment]
Hi all,

I am still testing the version "1.10.0-beta.rc2". An upload via the REST API throws the error

```[ERROR] [paperless.handlers] Creating PaperlessTask failed: malformed node or string: <ast.Call object at ...>```

I have used the same test script as from https://github.com/paperless-ngx/paperless-ngx/pull/1960#issuecomment-1323551285. The error hinders the frontend from showing the consume task within the "File Tasks" entry. Everything other works fine. The upload via the browser also works as expected.

I am not an experienced python developer but it seems that the exception is thrown within

```
/documents/signals/handlers.py
  ...
  def before_task_publish_handler (sender=None, headers=None, body=None, **kwargs):
    ...
```

The error messages seems to point to one of both calls to "literal_eval (...)" ([ast.literal_eval ()](https://docs.python.org/3/library/ast.html?highlight=ast%20literal_eval#ast.literal_eval)).

Could anyone reproduce this error?

Regards,
Michael


```
Complete log output

[2022-11-24 11:35:22,243] [ERROR] [paperless.handlers] Creating PaperlessTask failed: malformed node or string: <ast.Call object at 0xa1038bb0>

[2022-11-24 11:35:22,379] [INFO] [paperless.consumer] Consuming PDFTest.pdf
[2022-11-24 11:35:22,384] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2022-11-24 11:35:22,385] [INFO] [paperless.consumer] Executing pre-consume script /usr/src/paperless/script/preconsume-preconsumedoc.sh
[2022-11-24 11:35:22,413] [INFO] [paperless.consumer] /usr/src/paperless/script/preconsume-preconsumedoc.sh exited 0
[2022-11-24 11:35:22,419] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2022-11-24 11:35:22,434] [DEBUG] [paperless.consumer] Parsing PDFTest.pdf...
[2022-11-24 11:35:23,405] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-upload-51bhz9vk
[2022-11-24 11:35:23,657] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-upload-51bhz9vk'), 'output_file': '/tmp/paperless/paperless-j31j4n45/archive.pdf', 'use_threads': True, 'jobs': 4, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-j31j4n45/sidecar.txt'}
[2022-11-24 11:35:25,429] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.
[2022-11-24 11:35:26,163] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-j31j4n45/archive.pdf
[2022-11-24 11:35:26,164] [DEBUG] [paperless.consumer] Generating thumbnail for PDFTest.pdf...
[2022-11-24 11:35:26,178] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-j31j4n45/archive.pdf[0] /tmp/paperless/paperless-j31j4n45/convert.webp
[2022-11-24 11:35:33,751] [DEBUG] [paperless.consumer] Saving record to database
[2022-11-24 11:35:33,752] [DEBUG] [paperless.consumer] Creation date from post_documents parameter: 2022-10-01 01:00:00+02:00
[2022-11-24 11:35:34,543] [DEBUG] [paperless.matching] DocumentType Invoice matched on document 2022-10-01 IKEA MyDocument because it contains this word: Invoice
[2022-11-24 11:35:34,563] [INFO] [paperless.handlers] Assigning document type Invoice to 2022-10-01 IKEA MyDocument
[2022-11-24 11:35:34,760] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-upload-51bhz9vk
[2022-11-24 11:35:34,769] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-j31j4n45
[2022-11-24 11:35:34,770] [INFO] [paperless.consumer] Executing post-consume script /usr/src/paperless/script/postconsume-updatedoc.sh
[2022-11-24 11:35:34,877] [INFO] [paperless.consumer] /usr/src/paperless/script/postconsume-updatedoc.sh exited 0
[2022-11-24 11:35:34,880] [INFO] [paperless.consumer] Document 2022-10-01 IKEA MyDocument consumption finished
```

**Comment by stumpylog** [comment]
Yes. It's a bit more of an involved fix and the only result is the task won't be visible in the frontend (it will be in the admin pages).  So I'm not planning to make that fix and require more testing at this moment or destabilizing something unintentionally.

Please do make an issue for tracking it.

**Comment by shamoon** [comment]
> Could anyone reproduce this error?

I thought that #2023 fixed this (and that you confirmed this in your previous comment)? I believe beta rc2 should have that fix in it

**Comment by kprnks** [comment]
> Yes. It's a bit more of an involved fix and the only result is the task won't be visible in the frontend (it will be in the admin pages). So I'm not planning to make that fix and require more testing at this moment or destabilizing something unintentionally.
> 
> Please do make an issue for tracking it.

I will file that issue.

**Comment by kprnks** [comment]
There were two issues in regards to the REST API: "setting the creation
date" and "showing entries within the file tasks". While writing my
first post, I was only aware of the first. That was fixed with #2023
<https://github.com/paperless-ngx/paperless-ngx/pull/2023>. Today I
observed the second one.

Sorry for that confusion.

Am 24.11.22 um 16:51 schrieb shamoon:

**Review by shamoon — APPROVED** [review]
Lets go for it =)

**Pull request merged**
