### PR TITLE
README: Use Markdown alerts and fix DigitalOcean logo

### PR DESCRIPTION
**Pull request by Alexander-Wilms**
## Proposed change

* Use [Markdown alerts](https://github.com/orgs/community/discussions/16925) to highlight important points
* Replace the DigitalOcean logo SVG with PNG, since the SVGs linked [here](https://opensource.nyc3.cdn.digitaloceanspaces.com/attribution/index.html) no longer work

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [x] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [x] I have made corresponding changes to the documentation as needed.
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks but we’ll politely decline. And the SVGs do work, I think:
DigitalOcean Open Source Sponsorship Attribution Guide jpeg

**Comment by sbrunner** [comment]
@shamoon +1 for the SVG, but I think that the usage of Markdown alerts is nice, especially for the last note, see:
https://github.com/Alexander-Wilms/paperless-ngx/blob/4aab5c685e2c85b955a26204bb5151c92883a933/README.md

What do you think?

**Comment by Alexander-Wilms** [comment]
This is how it looks for me:

image

When I click on one of the links, e.g. [https://opensource.nyc3.cdn.digitaloceanspaces.com/attribution/assets/SVG/DO_Logo_horizontal_black.svg](https://opensource.nyc3.cdn.digitaloceanspaces.com/attribution/assets/SVG/DO_Logo_horizontal_black.svg), I get a blank page.

**Comment by sbrunner** [comment]
@Alexander-Wilms on my computer it's working:
image
didn't you have a temporary network issue?

**Comment by Alexander-Wilms** [comment]
It seems there are two issues:

* The SVG in the README shows the broken graphic icon for me
* The black SVG URL actually links to a white SVG.

**Comment by shamoon** [comment]
Oh I see the black logo URL might be messed up

**Pull request closed without merging**
