### PR TITLE
Fix: Don't require the JSON user arguments field, interpret empty string as `null`

### LINKED ISSUE #5313: Configuration: User-Arguments are mandatory
### Description

See the following Screenshot. 

image

I don't think, user args should be mandatory, since the documentation says "additionally specify arguments".

### Steps to reproduce

1. Click on "Configuration"
2. Fill in some Values
3. Click "Save"
4. User-Args are mandatory

In order to save a Configuration, the user now has to enter an empty json which is not very user-friendly.

### Webserver logs

```bash
not applicable
```

### Browser logs

_No response_

### Paperless-ngx version

2.3.2

### Host OS

Synology DSM 6.2.X

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

none of interest

### Other

_No response_

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

Closes #5313 

## Type of change

- [x] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by stumpylog** [comment]
I can't reproduce that from the image.  The standard `{"invalidate_digital_signatures": true}` in the field works, and an empty field works now as well.

**Comment by shamoon** [comment]
Ah, I think if you set it, then delete the contents of the field the frontend will pass `""` which is what fails. I suppose we can handle it in either place, I think this came up with https://github.com/paperless-ngx/paperless-ngx/pull/4762/ where we handled it in the backend

**Comment by stumpylog** [comment]
Ah, the change without saving thing.  I can add that fix in a bit

**Comment by stumpylog** [comment]
Really hating DRF here.  It's not calling `validate` or `update` reliably for me when changing settings.  Any idea what the heck it's doing?

**Comment by shamoon** [comment]
Sometimes it's so weird. I can look a bit later, alternatively would it be easier to make the frontend pass `null` for this field? It might be a bit of a pain but vs. fighting with DRF =)

Maybe I'll have some beginners luck

**Comment by shamoon** [comment]
Dont ask me why, but `run_validation` seems to do it, lmk if you notice any issues with it:

Screenshot 2024-01-08 at 10 20 45 AM

**Comment by stumpylog** [comment]
That seems fine to me.  I'm going to ignore the coverage, it's an odd ball case to me.

**Comment by shamoon** [comment]
Dont mean to overstep but I took the liberty of adding a little coverage, happy to revert it if you dont want it

**Review by shamoon — APPROVED** [review]

**Pull request merged**
