### PR TITLE
Feature / fix saved view & sort field query params

### LINKED ISSUE #877: [BUG] Views on dashboard not working
### Description

After clicking on "Show all" button, of a custom view (e.g. Tag: Todo) at the dashboard, the link leads to http://xxxx:8000/documents and not to http://xxxx:8000/view/2.

That only happens, if the view is only shown on the dashboard. If the custom view is also shown at the side panel, everything is working as expected.

image

Tag: ToDo --> working
Tag: ToDo2 --> not working

### Steps to reproduce

1. Create a new custom view. (Save as ...)
2. Only add to the dashboard, not to the side panel
3. Click "Show all" at the dashboard. "Show all" does not lead to the correct view.

### Webserver logs

```bash
no relevant logs
```

### Paperless-ngx version

1.7.0

### Host OS

Debian x86_64

### Installation method

Docker

### Browser

Firefox

### Configuration changes

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

This PR adds a query parameter (`view`) for saved views on the Documents page & supports the sort fields (this should probably have been in #540). This fixes the linked issue where currently "Show all" doesnt work for saved views that aren't in the sidebar and also makes it possible to use browser navigation when choosing saved views from the **Views** dropdown on the Documents page as well as changing sort parameters. Note this doesnt affect the `/view/X` url which is used for views in the sidebar. Videos below if youre curious.

https://user-images.githubusercontent.com/4887959/166868467-59b22843-7e24-46a7-8882-7426bc2523ee.mov

https://user-images.githubusercontent.com/4887959/166962476-9d952600-5ec6-4691-a2c6-d9dcbba3aeeb.mov

Fixes #877 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://paperless-ngx.readthedocs.io/en/latest/extending.html#code-formatting-with-pre-commit-hooks).
- [ ] ~~I have made corresponding changes to the documentation as needed.~~
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
I realized sort field query params also weren't implemented so this is now updated to include that.

**Comment by shamoon** [comment]
> Brilliant, some good QoL stuff here. I noticed a small regression where selecting a Saved View and then selecting a new Sort order resets the saved view. Video attached

Thanks for testing! Yea this stuff is surprisingly complicated and hard to test every nook and cranny. For some reason I can never see your videos, can you? Anyway, I think I get what you mean, I’ll take a look

**Comment by qcasey** [comment]
Yeah definitely, it's easier with multiple people testing. Thanks for letting me know about the vids, I replaced it with one that might work.

**Comment by shamoon** [comment]
Video works, and this should be updated with a fix for that, thanks!

**Review by qcasey — APPROVED** [review]
Excellent, this is great :+1:

**Pull request merged**
