### PR TITLE
 Managenment command manage_superuser implemented KISS

### LINKED ISSUE #140: [BUG] Password reset after docker container restarted
*Copy from old repository*: https://github.com/jonaswinkler/paperless-ng/issues/1511

**Describe the bug**
I deployed Paperless-NG in TrueNAS via the TrueCharts integration. TrueCharts uses the official docker container and passes environment variables to configure the superuser.

I changed the admin password in the Django admin interface. However, after redeploying the application (for example due to an update) the password gets overridden by the initial password passed via environment variable.

**To Reproduce**
1. Deploy Paperless with credentials admin//secret
2. Open Paperless
3. Navigate to admin interface
4. Change password to "mysupersecretpassword"
5. Restart/update the docker container
6. Navigate to Paperless and try to login with admin/mysupersecretpassword
7. You can't login.

**Expected behavior**
The admin password should not be overridden by the initial password.

**Relevant information**
 - Version 
 - Installation method: **docker**
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`. -

I think this is related to the admin user password reset when the docker container is started:
docker-entrypoint.sh calls docker-prepare.sh calls the manage_superuser mgmt command and there the password is updated:
https://github.com/jonaswinkler/paperless-ng/blob/master/src/documents/management/commands/manage_superuser.py#L29

Am I missing something?

### PR DESCRIPTION
**Pull request by schnuffle**
- The implementation got tricky, when I realized, that I can't use the user count as reference, as there's the user "consumer" being created during migration. So now the reference is if there exists a super user
- I added some tests that check some more behaviour
-- Check what should happen when there's already a super user with a different name then "admin"
-- Check what should happen, when the super user "admin" already exists
-- Check what should happen, when there exists a normal user with username "admin"

### CODE REVIEW

**Comment by stumpylog** [comment]
@schnuffle except for the conflicts (because of the pre-commit changes) is this ready to have a look at?

I think the easy way to resolve the conflicts would be a rebase or merge with the `-Xours` option, then running pre-commit again should get all the formatting applied to your changes.

**Comment by shamoon** [comment]
@schnuffle are you available any more to circle back to this?

**Comment by m3nu** [comment]
This PR may try to accomplish too much at the same time. Some parts are still pretty useful. Like the missing Tesseract languages and the admin password being overwritten on restart. We stumbled over both today.

**Comment by qcasey** [comment]
I believe this was superseded in #903, if there's anything else to be done here it should be in a new PR. Thanks @schnuffle and @stumpylog :)

**Pull request closed without merging**
