### PR TITLE
Make paperless-ng able to be run as a rootless container (support for podman)

### PR DESCRIPTION
**Pull request by bauerj**
This pull request has been imported from jonaswinkler/paperless-ng#900 and was originally opened by gillesgagniard on 2021-04-12 12:36:51.

---

When using `podman` instead of Docker, it is possible to run containers in a rootless mode, ie. containers are directly created by the user and not by `root` through the Docker daemon.

A key difference of rootless containers is that they run in a different user namespace, where the `root` user inside the container (uid 1) is mapped to the user creating the container outside on the host, and other users inside the container get alternative user id in a different namespace than the host user namespace.

As a consequence, running paperless-ng webserver as `root` inside the rootless container is actually what we want: the paperless processes are then run by the user from the host point-of-view, and thus are able to read/write to the consume and export directories.

The current trick of forcing the paperless uid/gid to match the host user doesn't easily work for rootless containers, as uid/gid are remapped.

This proposed patch adds a new build argument `ROOTLESS` in Dockerfile for creating a rootless container image:
- No creation of paperless user and file ownership changes
- Different supervisord configuration file to run everything as root
- Export a `PAPERLESS_ROOTLESS` environment variable so that docker-entry.sh runs everything as root at container start time

It can be invoked like this:

    docker build . -t docker.io/jonaswinkler/paperless-ng:rootless --build-arg ROOTLESS=1

### CODE REVIEW

**Comment by shamoon** [comment]
@gillesgagniard your issue was imported to paperless-ngx, a community-supported successor to paperless-ng. If you are still interested in contributing please do so, we'd love to have you!

**Comment by gillesgagniard** [comment]
Sure, I believe this pull request is still useful (at least that's how I have deployed paperless on my server).

**Comment by slynn1324** [comment]
I would also find this option very helpful!

**Comment by qcasey** [comment]
@gillesgagniard, could you resubmit this PR to paperless-ngx after rebasing on our `dev` branch? I'd also be willing to reimplement or help test this. 

Regardless this PR should be closed and reopened anew so we can make edits.

**Comment by slynn1324** [comment]
In further looking, I did find another workaround that I think effectively achieves the same thing - and is already merged in the dev branch.  The addition of the '-o' option for the usermod command in docker-entrypoint.sh allows for overriding the uid to an existing value -- in this case '0'.  

I was able to quickly produce a patched docker image from the latest release with this Dockerfile:
```
FROM ghcr.io/paperless-ngx/paperless-ngx:latest

RUN sed -i 's/usermod -u "${USERMAP_NEW_UID}" paperless/usermod -o -u "${USERMAP_NEW_UID}" paperless/g' /sbin/docker-entrypoint.sh
```

And after running with `-e USERMAP_UID=0 -e USERMAP_GID=0`, everything seems to start and it pulls up my files with no issues.

I haven't dug much further to understand the merits of one direction vs. the other here -- but wanted to update with what I found.   If the USERMAP_UID=0 pattern is appropriate and doesn't have other issues, then these changes would be unnecessary (although they may provide a more obvious option).

**Comment by anthr76** [comment]
Any updates on this?

**Comment by bauerj** [comment]
Please refer to #1212 for the current work on this.

**Pull request closed without merging**
