### PR TITLE
Chore(deps): Use psycopg as recommended

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

Since Django 4.2, Django supports and recommends psycopg (aka psycopg 3) over psycopg2.  So this updates us to use the psycopg[c] version, which is the one built with C based speedups against the libpq-dev.

This does seem to add a decent amount to the Docker build, something I'll have to look at seeing if anything can be done.

Testing should be easy, just use Postgres and make sure everything is fine.  I didn't see any problems in basic testing.

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [ ] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [x] Other. Please explain: Maint

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Comment by shamoon** [comment]
Thanks stumpy, I’ll definitely test this out later but sounds safe and 3 looks like it’s been around for a while. I’m curious, so there’s no obvious improvement (for us) between the two, more just staying up-to-date? Yea docker build on this PR looks more than double the typical time, you think that’s from this change or other stuff like caching and other docker build voodoo that you’ve implemented?

**Comment by stumpylog** [comment]
> more just staying up-to-date

Up to date and moving to a library that looks to be active, supported and recommended.  But there's nothing user or us facing here, it's all in the background

The build time culprit is the aarch64 still, that emulated compiling is just really slow.  It took  8.5 minutes to build for that arch vs 1.7 minutes for the old library.  I wish we had native builders, but oh well.  I'll probably build it ahead of time and install it, similar to qpdf, etc

**Comment by stumpylog** [comment]
A quick change that still seems fine, the wheel is pre-built now, similar to how we have some updates to important packages.  I doubt it would be much to keep it updated and saving ~8 minutes seems worth it.

Later, I may build and install zxing in our image for aarch64 this way.  It is much better for barcodes.

**Review by shamoon — APPROVED** [review]
> [Build Docker image for feature-use-pyscopg3](https://github.com/paperless-ngx/paperless-ngx/pull/6811#logs)
succeeded 1 hour ago in 11m 11s

Nice! Thanks for sorting out the prebuild. I tested this out too and didnt run into any issues including filtering, searching, uploading etc

Screenshot 2024-05-22 at 7 53 39 PM

**Pull request merged**
