### PR TITLE
Feature: Upgrade Gotenberg to v8

### PR DESCRIPTION
**Pull request by stumpylog**
## Proposed change

A few minor tweaks in our own code to account, but everything should be straightforward.

As noted in the new log, Gotenberg v8 does not support producing PDF A/1 anymore (I believe LibreOffice dropped it), so there is now a warning and a default to PDf A/2b instead

## Type of change

- [ ] Bug fix: non-breaking change which fixes an issue.
- [x] New feature / Enhancement: non-breaking change which adds functionality. _Please read the important note above._
- [x] Breaking change: fix or feature that would cause existing functionality to not work as expected.
- [ ] Documentation only.
- [ ] Other. Please explain:

## Checklist:

- [ ] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [ ] If applicable, I have included testing coverage for new code in this PR, for [backend](https://docs.paperless-ngx.com/development/#testing) and / or [front-end](https://docs.paperless-ngx.com/development/#testing-and-code-style) changes.
- [ ] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [ ] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] I have made corresponding changes to the documentation as needed.
- [ ] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by shamoon — APPROVED** [review]
Thanks stumpy, LGTM, can merge or wait until we see if there'll be another bug fix release

**Comment by stumpylog** [comment]
Yeah, I'll leave it hanging for a bit.  Then let dependabot handle any conflicts

**Comment by compgeniuses** [comment]
what evrsion of version 8 gotenberg is supproted..  Highest version?

**Comment by shamoon** [comment]
The compose in this PR has version 8.7, my guess is 8.8 would be fine but of course ymmv

**Pull request merged**
